### ISSUE TITLE
Function has() in file /src/util.js contains a bug

### ISSUE THREAD

**Issue by tmcdos** [vuejs/vue-devtools#1020]
### Version
5.1.0

### Browser and OS info
Chromium Version 76.0.3773.0 (Official Build) (64-bit) / Windows 7 x64 SP1

### Steps to reproduce
Define the following data section:
```javascript
data ()
{
  return {
    requests:
    [
      {
        actions:
        {
          update: 0
        }
      }
    ]
  }
}
```
Now try to increment the value of **update** field through Vue DevTools.

### What is expected?
The `update` field should change its value to 1/2/3/4 ....

### What is actually happening?
You get the following error in the console:
```
TypeError: Cannot read property '0' of undefined
    at has (backend.js:680)
    at setStateValue (backend.js:2395)
    at Bridge.backend_bridge.on.args (backend.js:1550)
    at Bridge.emit (backend.js:5472)
    at Bridge._emit (backend.js:5172)
    at messages.forEach.message (backend.js:5097)
    at Array.forEach (<anonymous>)
    at Bridge.wall.listen.messages (backend.js:5097)
    at listener (backend.js:2568)
```

---
The issue is with function **has()** in file **/src/util.js** - it fails when **instance._props** is an empty object `{}` on line **968** in function **setStateValue()** (file **/src/backend/index.js**).

The code should be changed like this:
```javascript
export function has (object, path, parent = false) {
  if (typeof object === 'undefined') {
    return false
  }

  const sections = Array.isArray(path) ? path : path.split('.')
  const size = !parent ? 1 : 2
  while (sections.length > size && object) { // <--- additional check
    object = object[sections.shift()]
  }
  return object != null && object.hasOwnProperty(sections[0])
}
```

**Comment by omarmfs98** [comment]
This is happening to me too, every time I try to update a piece of information, that error is answered.

PS: I'm using vue-router

**Comment by Akryum** [comment]
Fixed
