### ISSUE TITLE
安装vue-devtools时，要下载cypress，可下载不下来呀

### ISSUE THREAD

**Issue by ztg-zlu** [vuejs/vue-devtools#1021]
![image](https://user-images.githubusercontent.com/26703048/59970688-6d716f00-959f-11e9-93dc-9445db5229e7.png)
 到这里，就不动了

**Comment by gavinsama** [comment]
请问如何安装呀？

**Comment by sodatea** [comment]
Cypress 下载地址最近在国内被墙了，用 Yarn 的话得设置环境变量后再安装：

- macOS: `CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/3.4.1/darwin-x64/cypress.zip yarn install`
- Windows 64 位系统 `CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/3.4.1/win32-x64/cypress.zip yarn install`
- Windows 32 位系统 `CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/3.4.1/win32-ia32/cypress.zip yarn install`

或者用 cnpm 客户端，他们的 install 命令有对这个做特殊处理绕开。
