### ISSUE TITLE
Editable props are disabled after reload

### ISSUE THREAD

**Issue by sh7dm** [vuejs/vue-devtools#1028]
### Version
5.1.1

### Browser and OS info
Chrome 76-78 / Ubuntu 19.04

### Steps to reproduce
1. Enable editable props
2. Update the page
3. Try to use editable props
4. Disable it
5. Enable it
6. Use it as before!

### What is expected?
Editable props will stay active.

### What is actually happening?
They're becoming inactive due to reload.

**Comment by talbs** [comment]
I can confirm that this is happening for me in 5.1.1 in the following browsers/versions:

* Chrome Version 77 (Mac OSX 10.14.5)
* Firefox 69 (Mac OSX 10.14.5)

P.S. - Thanks for the awesome set of tools, we use them every day at Font Awesome.
