### ISSUE TITLE
Selected component is not being highlighted enough

### ISSUE THREAD

**Issue by spaceemotion** [vuejs/vue-devtools#1049]
### What problem does this feature solve?
I am having trouble finding my currently selected component in certain hierarchies that have lots of child components. The subtle " = $vm0" hint does not pop out enough when scrolling though the list using the scroll bar.

![image](https://user-images.githubusercontent.com/429147/63004592-0d9a9480-be7b-11e9-8859-ed1c6b26d047.png)

### What does the proposed API look like?
Maybe inverting the color would help. White text on a green background. Or just a transparent green background to underline the selection.

**Comment by Akryum** [comment]
The selected component should have an inverted background 🤔

**Comment by spaceemotion** [comment]
Hm, this was in August. I just checked again, and $vm0 was now properly selected…

![image](https://user-images.githubusercontent.com/429147/67685025-957d3e80-f994-11e9-9d85-96fc55c01d56.png)
