### ISSUE TITLE
Enhancement: open console panel when sending vm to console

### ISSUE THREAD

**Issue by simplesmiler** [vuejs/vue-devtools#106]
The "Inspect DOM" button opens the "Elements" panel, but "Send to console" does not open the "Console" panel.

I believe opening the "Console" panel manually after clicking "Send to console" makes up for 90% of use cases of this buttons.

**Comment by bartlomieju** [comment]
Why don't we take React's devtools approach? Selecting component in devtools binds it to `$r` in console automatically. Number of clicks stays the same, no need to fight with Chrome to switch the tab (if it is even possible).

**Comment by simplesmiler** [comment]
Good point, I believe Chrome itself does it similarly.
Clicking on the element in the inspector binds it to `$0`. It actually goes further, and maintains a list of 5 last elements as `$0 .. $4`. Maybe we can do the same with `$vm0 .. $vm5`.

**Comment by simplesmiler** [comment]
This would solve https://github.com/vuejs/vue-devtools/issues/97

**Comment by bartlomieju** [comment]
Yep. Not bad either, but to be honest for me it's a little confusing that it moves item to next position. But I'll be happy to make a PR that does that :)

**Comment by yyx990803** [comment]
@simplesmiler sounds good! (autobinding on click)

**Comment by bartlomieju** [comment]
Ok, I'm on it

**Comment by simplesmiler** [comment]
Cool. I think for compatibility reasons it should still bind `$vm` too, along with `$vm0`.

**Comment by simplesmiler** [comment]
Another thing. Chrome gives developer a hint, that element is available as `$0`, by showing `== $0` after the element name:

![chrome-hint](https://cloud.githubusercontent.com/assets/550229/15680235/916f3706-275d-11e6-9d5a-f133c4a62460.png)

I guess we can do the same, something like this:

![vue-hint](https://cloud.githubusercontent.com/assets/550229/15680674/4283fe0e-275f-11e6-8208-22019fb50190.png)

**Comment by bartlomieju** [comment]
So I pushed some changes. Please let me know what you guys think, any feedback is welcome. @simplesmiler @yyx990803

**Comment by simplesmiler** [comment]
Kudos to @bartlomieju!
