### ISSUE TITLE
Setting: Checkbox that says "Don't randomly expand half of the Vuex state because it's extremely annoying"

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-devtools#1063]
### What problem does this feature solve?

My sanity? I have to go through and collapse about 30 different things every time I refresh the page and then expand the one thing that is always collapsed for some reason.

I think the current approach is:

* If a section is small, it is probably rarely used and doesn't need to be expanded, so make sure to [expand it by default](https://user-images.githubusercontent.com/4629794/64645757-8f7ece80-d3e3-11e9-8c2c-dc76d4d3f86e.jpg)
* If a section is large, it's probably the most complex and commonly edited part of the app and will need to be expanded most often, so [collapse it by default](https://user-images.githubusercontent.com/4629794/64645781-9c032700-d3e3-11e9-969b-649f3efc27a8.png).

### What does the proposed API look like?

**Best possible scenario:** "Remember what was expanded previously". Yes this means keeping track of some local storage or something of what was opened or closed before, and yes that means your preferences may get lost if you switch between apps, or add/remove/rename things in the state. But who cares, at least it would kinda work, most of the time.

**Next best option:** Have a "Collapse all items in Vuex state" checkbox so at the very least I don't need to do it manually a million times a day.

**Next best option:** Invert the current process. Literally do the exact opposite of what it is doing now. If it is small, collapse it by default, if it is large, expand it by default. It's so much more logical than the current approach which is the worst possible approach.

**Comment by MarcelloTheArcane** [comment]
Not sure I'm getting the relevance of the pictures, to be honest.

**Comment by Akryum** [comment]
I'm not sure the tone used by OP is respectful nor appropriate.

**Comment by TheJaredWilcurt** [comment]
The tone is driven by a frustrating, illogical, and bad user experience.

Rather than even acknowledge this, you close the issue. If you have a problem with the wording, then edit it. Not liking the way the message is delivered does not invalidate the message.

**Comment by Akryum** [comment]
Being toxic won't help you getting support nor help.
