### ISSUE TITLE
Plugin not opening when Vue is loaded async

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-devtools#1064]
### Version
5.1.1

### Browser and OS info
Chrome 76.0.3809.132, Mac OS 10.14.6

### Steps to reproduce
Consider the following code:

```
document.querySelector('button').addEventListener('click', (event) => {
  event.preventDefault()
  import(/* webpackChunkName: "vue" */ 'vue').then(Vue => {
    const vm = new Vue.default({
      el: '#app',
      components: {
        'thing': () => import(/* webpackChunkName: "thing" */ '../vue/Thing.vue'),
      },
      mounted: () => {
        console.log('I mounted!')
      },
    })
  })
})
```

### What is expected?
The plugin to detect Vue when loaded async

### What is actually happening?
Plugin is not picking up that Vue has been loaded and a component has mounted

**Comment by anlek** [comment]
I am interested in how to make this happen as well. I tried setting 
```
window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = vm
```
however, that did not re-render the Vue devtools UI.

I'm using pjax to load Vue, and I know when my loaded Vue comes in, but don't know how to wire it into the Vue Devtool.

**Comment by TheDutchCoder** [comment]
This was an issue on my end.

I was building webpack with `mode: 'production'`, which disables all hooks for Vue and the plugin. Works fine in development mode!
