### ISSUE TITLE
Open Devtool directly when Vue icon clicked in Tool Bar when Vue.js is detected.

### ISSUE THREAD

**Issue by Kidcredo** [vuejs/vue-devtools#1068]
### What problem does this feature solve?
It would be nice, if browser extension icon when clicked would open the DevTools right into the Vue tab instead of  "Vue is detected" message when Vue is detected. I believe this will help users to open the devtools directly rather then searching for it.

### What does the proposed API look like?

```
if (Vue = detected){
  if (Vue = production) {
    Message = "Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author. "
  }
  else  {
    toolbar.onclick = Open devtools to Vue Tab);
  }
}
else { 
  Message = Vue.js not Detected 
}
```

**Comment by Akryum** [comment]
I don't think it will be useful, as the pane is closed as soon as you click outside of it.
