### ISSUE TITLE
Vuex modules don't load with 'Autoload Vuex state'

### ISSUE THREAD

**Issue by mikaelhadler** [vuejs/vue-devtools#1098]
### Version
5.3.1

### Browser and OS info
Chrome 78.0.3904.70

### Steps to reproduce
1 - Open a chrome
2 - Navigate to app
3 - Open Chrome Devtools
4 - Enable 'Autoload state vuex'
5 - Refresh to force reload modules

### What is expected?
All modules loaded automatic

### What is actually happening?
No modules loaded in listing

---
https://drive.google.com/file/d/1zz1MDxu3bKo4DfuF2oja8LxeuIAQkdbB/view?usp=sharing

**Comment by Akryum** [comment]
Do you have a minimal runnable reproduction of the issue?

**Comment by wilf312** [comment]
hi @Akryum . Thank you great extension!

I have same error.
If you implement using https://github.com/vuex-orm/vuex-orm,
foo/bar/query and module are cut under module.

background page error message
> parent[parts.pop()] = res.getters[key]

https://github.com/vuejs/vue-devtools/blob/dev/packages/app-frontend/src/views/vuex/module.js#L224

<img width="958" alt="sc" src="https://user-images.githubusercontent.com/2202197/67887512-c0cb7d80-fb8e-11e9-9cf9-ce7991ecf35f.png">


sample code
https://codesandbox.io/s/vue-template-ci6qb

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/67893740-7084f900-fb57-11e9-9687-ac38d5c19cbf.png)

**Comment by Akryum** [comment]
The devtools now supports a getters which has the same name as a child module:

![image](https://user-images.githubusercontent.com/2798204/67894028-09b40f80-fb58-11e9-805d-66703d6f2f14.png)
