### ISSUE TITLE
5.3.2: Property or method "then" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by nicooprat** [vuejs/vue-devtools#1099]
### Version
5.3.2

### Browser and OS info
Mac OS 10.13.6 / Version 0.69.135 Chromium: 77.0.3865.120 (Build officiel) (64 bits)

### Steps to reproduce
Just load any vue app in dev mode.

### What is expected?
The console should be empty.

### What is actually happening?
The console is full of this kind of errors `Property or method "then" is not defined on the instance but referenced during render` for every component.

---
This wasn't occurring with 5.3.1. 

![image](https://user-images.githubusercontent.com/645641/67940014-145fba80-fbd3-11e9-89c5-3a3264474c2f.png)

**Comment by riedelkai** [comment]
I also get this error, but only when i enable "New Vuex backend" in settings.
When i disable this setting, the error does not appear.

**Comment by Akryum** [comment]
Please provide a runnable minimal reproduction.

**Comment by andreasvirkus** [comment]
Just wanted to say I've been debugging my app for 2 hours so thank you @nicooprat for this issue! 😞 🙌

**Comment by CalebKester** [comment]
Glad it's not just me. I was going crazy this morning with it. I'm going to have to restore old dev tools between this and consuming all of my CPU the latest version seems a bit buggy.

**Comment by VinceG** [comment]
Just came across this as well today. Turning off Vuex backend removed all those warnings.

**Comment by camaulay** [comment]
I noticed it this morning after I updated to Chrome 78.  

Toggling off "New Vuex Backend" in the Vue Dev Tools settings has prevented these warnings as others have suggested.

**Comment by emahuni** [comment]
AAAAAAAAgggggh I just spent 30 minutes debugging my app and turning off things! I was about to open this issue too. Definitely a bug

**Comment by mcmimik** [comment]
#metoo
FYI, exception in console refers to this line in backend.js:
https://github.com/vuejs/vue-devtools/blob/30f15164aabf216b4fcd4b147c2377e598380912/packages/app-backend/src/clone.js#L379
Vue.js devtools 5.3.2

**Comment by c-zenker** [comment]
I can reproduce the error, if "new vuex backend" and recording on the vuex tab are enabled.
disabling any of them stops the error from happening

**Comment by benjaminprojas** [comment]
I am also experiencing this exact same issue. Turning off "new vuex backend" fixes it for me as well.

**Comment by pdanpdan** [comment]
I think this might be related to using import to load components. I'll try to add a minimal example.

**Comment by dovyden** [comment]
Hello!

My case for reproduce

You need app that uses following packages:
1. Vue Router
2. Vuex
3. `vuex-router-sync`

App should have minimum two routes =)

Steps:
1. Open your app in browser
2. Open Vue developer tools
4. Navigate to other app page (route)
5. `vuex-router-sync` runs mutation `route/ROUTE_CHANGED` with payload `{from, to}` where will have references to components and their instances
6. Vue developer runs cloning of mutation payload and instances of Vue components
7. When devtools try to clone `payload.to.matched.0.instances.default._renderProxy` Proxy checks the availability of method `then` and shows warning

**Comment by iamsean007** [comment]
Spend an Hour to fix this. Thank again for posting this on the forum!!!

**Comment by 13802882756** [comment]
it,s was there being two different version of vur-devtools on my chrome

**Comment by 13802882756** [comment]
同时存在两个不同版本的vue-devtools，禁用调其中一个就OK了

**Comment by joelpro2** [comment]
Getting this error in version 6.0.0 beta 19
