### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by agentphoenix** [vuejs/vue-devtools#110]
I'm running a copy of Chrome installed by the company and they've locked down access to the Chrome store, so I can't install the vue-devtools from there. I cloned the repo, ran `npm install` and then ran `npm run build`. At first I couldn't get past the lint script because of a missing space in the ComponentInspector.vue file (line 52 in case anyone is running into a similar issue on Win7). Once I fixed that, I was able to run the lint script fine, but now I'm running into "module build failed" errors for every component.

![vue-devtools-error](https://cloud.githubusercontent.com/assets/14422/15675478/3278e424-2710-11e6-98f8-a5c6cfe4b9ce.PNG)

Am I doing something wrong here? Am I missing a dependency? Just trying to get this to build properly so I can install the extension in Chrome.

**Comment by yyx990803** [comment]
This is a bug in `stylus-loader` in Node 6.x (where `path.extname` no longer works on `undefined`). If you use Node 5 for now it should work properly.

**Comment by agentphoenix** [comment]
Thanks for the heads up @yyx990803! I'll keep an eye on that repo for when they patch the issue.
