### ISSUE TITLE
Cannot be ran locally for development or custom builds (Breaks nw-vue-devtools)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-devtools#1106]
### Version
5.3.2

### Browser and OS info
N/A

### Steps to reproduce

1. Clone the latest tag (or `dev` branch)
1. `npm install`
1. `npm run build`
   * **Fails**

There are many Webpack alias's that do not resolve properly. I was able to hack around them and found the code relies on the following dependencies that are not in this repo's `package.json`:

* webpack
* webpack-cli
* webpack-merge
* vue-loader
* friendly-errors-webpack-plugin
* uglifyjs-webpack-plugin
* buble
* buble-loader
* vue-template-compiler
* css-loader
* postcss-loader
* stylus-loader
* style-resources-loader
* @vue/ui
* d3
* url-loader
* vue-router
* vue-virtual-scroller
* vuex
* stylus
* file-loader

On top of that, with the dependencies in place, and the aliases manually resolved, there seems to still be some configuration missing around `buble`, as it does not process the source code to ES5, leading Uglify to throw errors. If we remove the uglify step entirely, then the project "builds" but the resulting extension does not work properly (displays the "loading" animation of the Vue logo, but never actually loads).

### What is expected?

This repo should follow the same best practice as most npm modules:

1. All required dependencies are denoted in the `package.json`
1. All that is required to run the project is `npm install && npm start`, or in this case `npm install && npm run build`

### What is actually happening?

---

I created the `nw-vue-devtools` repo/dependency. It's goal is to allow developers to have access to the latest version of Vue-DevTools inside of NW.js while working on their Desktop Apps. The approach taken for this was to automate pulling down the latest code and doing a custom build of the extension. This currently works on the `master` branch, but I recently realized that no code has been merged to `master` in a long time. Meaning the `nw-vue-devtools` downloads and installs a very old version of Vue-DevTools, rather than the latest. In my process to switch it over to be built based on the latest tag, I found that it is no longer possible to build from this repo.

**Possible solutions:**

* This repo could provide downloads for the built chrome-extension files. Preferably hosted on GitHub as part of the releases API, similar to how [LibSass bindings are made available](https://github.com/sass/node-sass/releases).
  * Then `nw-vue-devtools` could be updated to automate downloading/unzipping/installing of the latest release without the need to do a custom build.
* This repo could be updated to function normally and perform builds via `npm install && npm run build`
  * Then `nw-vue-devtools` could be updated to automate cloning the latest tag, installing dependencies, modifying whatever files need modified, then do a custom build, like it is currently doing against the `master` branch.
* A new `/packages/shell-nw` folder could be created and maintained in this repo to serve as an official support for NW.js, negating the need for the `nw-vue-devtools` project. (I'm willing to help if this is deemed the easiest or best route by the current maintainers).

**Comment by Akryum** [comment]
I guess you [didn't read the Readme](https://github.com/vuejs/vue-devtools#manual-installation).

**Comment by TheJaredWilcurt** [comment]
You linked to instructions which I mentioned in this detailed explanation do not work.

With your very dismissive comment, I cannot infer additional detail from what you are trying to convey.

**Comment by Akryum** [comment]
Your steps don't match the documented steps in the readme :cat2:
