### ISSUE TITLE
Tab crash! crash! crash!

### ISSUE THREAD

**Issue by lizy0329** [vuejs/vue-devtools#1116]
### Version
5.3.2

### Browser and OS info
Chrome 77

### Steps to reproduce
1. install Vue devTools
2. tools icon is show: Vue.js is detected on this page.
3. Find nothing in  inspect tab

### What is expected?
 Find Vue panel in  inspect tab

### What is actually happening?
Find nothing in  inspect tab

**Comment by Akryum** [comment]
Duplicate of #1072
