### ISSUE TITLE
run build ，Error occurred

### ISSUE THREAD

**Issue by ydwang1** [vuejs/vue-devtools#1134]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-devtools@5.3.3 build: `cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-devtools@5.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leqee\AppData\Roaming\npm-cache\_logs\2019-12-27T07_37_30_645Z-debug.log

please give a Solution, thanks

**Comment by QJune** [comment]
how do you resolve the issue?

**Comment by hua1995116** [comment]
https://github.com/vuejs/vue-devtools/issues/1141#issuecomment-574979267
