### ISSUE TITLE
 Cannot find module '@vue-devtools/build-tools' 

### ISSUE THREAD

**Issue by chaixiao1995** [vuejs/vue-devtools#1141]
Cannot find module '@vue-devtools/build-tools'

**Comment by hua1995116** [comment]
please use `yarn` replace `npm`.

**Comment by feedao** [comment]
go to https://github.com/vuejs/vue-devtools/tree/master
code -> download zip 
unzip the zip file
npm install
npm run build

**Comment by hua1995116** [comment]
Because vue-devtools use yarn workspace, so you should use `yarn` instead of `npm`. @feedao
