### ISSUE TITLE
npm run build error!

### ISSUE THREAD

**Issue by AndrewFrank-zxy** [vuejs/vue-devtools#1148]
I clone the repo, and npm i. But run npm run build will occur an error.
```bash
> cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-devtools@5.3.3 build: `cd packages/shell-chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-devtools@5.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
I tried branches (5.*.*). Is there something wrong?

**Comment by 1067831145** [comment]
请问这个问题解决了吗

**Comment by li-car-fei** [comment]
我遇到了同样的问题，求大神！！！

**Comment by li-car-fei** [comment]
我遇到了同样的问题，求大神！！！

**Comment by 1067831145** [comment]
我是重新找插件的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小灰灰"<notifications@github.com&gt;; 
发送时间: 2020年2月15日(星期六) 晚上11:28
收件人: "vuejs/vue-devtools"<vue-devtools@noreply.github.com&gt;; 
抄送: "1"<1067831145@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vuejs/vue-devtools] npm run build error! (#1148)




我遇到了同样的问题，求大神！！！

**Comment by li-car-fei** [comment]
请问在哪里重新找的插件？可以说下具体做法？

**Comment by 1067831145** [comment]
我是通过这个网站（https://chrome.zzzmh.cn/info?token=nhdogjmejiglipccpnnnanhbledajbpd）下载的插件，也有安装教程，希望能帮助到你们



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小灰灰"<notifications@github.com&gt;; 
发送时间: 2020年2月17日(星期一) 晚上8:04
收件人: "vuejs/vue-devtools"<vue-devtools@noreply.github.com&gt;; 
抄送: "1"<1067831145@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vuejs/vue-devtools] npm run build error! (#1148)




请问在哪里重新找的插件？可以说下具体做法？

**Comment by 1067831145** [comment]
我提供的下载插件的网站一直【正在投递中】，不能成功提交，我是在极简插件上找到的，希望能帮助到你们




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小灰灰"<notifications@github.com&gt;; 
发送时间: 2020年2月17日(星期一) 晚上8:04
收件人: "vuejs/vue-devtools"<vue-devtools@noreply.github.com&gt;; 
抄送: "1"<1067831145@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vuejs/vue-devtools] npm run build error! (#1148)




请问在哪里重新找的插件？可以说下具体做法？
