### ISSUE TITLE
How can I use devtools in jsfiddle

### ISSUE THREAD

**Issue by Nandiin** [vuejs/vue-devtools#115]
I've installed vue-devtools chrome extension and it works fine when using locally.
But when I want to write some code snippet on jsfiddle it doesn't work, I've checked that I linked to a non-min version of vue.js and explicitly enabled debug and devtools as 
```
Vue.config.debug = true
Vue.config.devtools = true
```
I also checked the console log and it says 
>Download the Vue Devtools for a better development experience:https://github.com/vuejs/vue-devtools

so i'm thinking devtools may be failed to detected when vue code is attached to a iframe.

**Comment by probil** [comment]
When you use jsfiddle code actually runs in `<iframe></iframe>`. As I know, vue-devtools couldn't detect and manage vue inside iframes.

**Comment by probil** [comment]
Possible workaround => open iframe url in new tab 
![Screenshot](http://i.imgur.com/wcSAeAr.png)

**Comment by blake-newman** [comment]
@probil this is a valid solution... Unfortunately vue devtools can't work through iframes, feel free to open a PR if you manage to find a solution.

**Comment by Akryum** [comment]
This solution isn't valid anymore since the result is still put inside an iframe.

**Comment by Akryum** [comment]
This solution isn't valid anymore since the result is still put inside an iframe.

Some ideas:

1: Change iframe to same origin:

```javascript
document.querySelector('iframe[name=result]').src = document.location.href + 'show'
```

2: Access iframe content:

```javascript
window.frames.result.document
```

**Comment by Akryum** [comment]
It works! :)

First, I had to change [this line](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L96) to `walk(hook.document, function (node) {`.

1 - I've put the following code in the jsfiddle script:

```javascript
const hook = top.__VUE_DEVTOOLS_GLOBAL_HOOK__
hook.document = document
hook.emit('init', Vue)
```

2 - Click 'Save'

3 - Execute this in the chrome console:

```javascript
document.querySelector('iframe[name=result]').src = document.location.href + 'show'
```

4 - You should have the vue devtools open and running!

**Comment by Yatima-Kagurazaka** [comment]
I can't understand why @Akryum's comment bring no reaction.
It's slightly complicated but very useful.

**Comment by jpgilchrist** [comment]
My team could really benefit from this. We have an older style (non SPA) where the parent frame basically contains the masthead and an child iframe which contains the content. In this manner, the masthead doesn't re-render on navigation, but the child frame does. It's a bit legacy at this point, but it works well and we don't have the resources to fix it at the moment. 

So, we really could use the chrome extension to work on child frames.

**Comment by khullah** [comment]
Maybe I'm far off, but wouldn't vue-devtools+iframes be achievable by:

_vue-devtools/shells/chrome/src/detector.js line 9_
```
   //const all = document.querySelectorAll('*')
   let all = Array.prototype.slice.call(document.querySelectorAll('*'))
   let iframes = Array.prototype.slice.call(document.querySelector('iframe')) && [document.querySelector('iframe')]
   iframes.forEach(function(i){
      all = all.concat(Array.prototype.slice.call(i.contentDocument.querySelectorAll('*')))
   })
```

where `Array.prototype.slice.call`, `concat` and `forEach` could be anything else for performance/back compatibility. This would work for every iframe that is in the same domain than `document.location`, right? (it would solve for you I guess, @jpgilchrist). Alternatively, to call the `detect` function passing `document` variable.

Similarly, the `scan` function (_vue-devtools/src/backend/index.js line 136_) could receive a `document` reference or have a loop to get each `contentDocument` from every iframe. (not sure why not to simply use `contentWindow.Vue`?)

As for jsfiddle itself, we have that domain problem ('https://fiddle.jshell.net' vs 'https://jsfiddle.net'), and I think there isn't a universal solution for this, without adding custom users situations or at least having the option to set it in some user settings. It would look something like this:

```
   ...
   iframes.forEach(function(i){
      i.onload = function(){
         all = all.concat(Array.prototype.slice.call(i.contentDocument.querySelectorAll('*')))
      }
      i.src = document.location.href + 'show' //specifically for jsfiddle, otherwise won't access it's content
      //or some setting like 'from'->'to' format with regex available...
   })
```

PS: @Akryum solutions didn't worked for me, don't know why, so the above didn't worked as well. Please check if its ok after all. Hope this helps.
