### ISSUE TITLE
Right click -> Copy object

### ISSUE THREAD

**Issue by b44rd** [vuejs/vue-devtools#118]
Hi, and thanks for a fantastic development tool. 

While working with objects in console, I find it very useful to right click the object, and then "Store as global variable". The object typically becomes available as temp1. Pretty much as you do when sending the vue model you´re inspecting to console as $vm. 

Some even more useful thing, is that running copy(temp1) allow me to copy the object. Copying an object and then pasting it somewhere is often so much faster than using the expand arrows etc., and typically makes me save quite a bit of time when working with data structures. 

What would be totally awesome in vue devtools, is if it was possible to simply right click on a object and then copy it directly to the clipboard. Thanks in advance for considering to make this a feature.

**Comment by JivanRoquet** [comment]
I was browsing the feature requests in order in order to post this exact same one, if it wasn't already there.

So here it is. It would be awesome, indeed.
