### ISSUE TITLE
I hope to download and use vue-devtools directly in the Microsoft Edge browser app store,

### ISSUE THREAD

**Issue by wodesj33** [vuejs/vue-devtools#1188]
### What problem does this feature solve?
Vue-devtools not found in the Microsoft Edge browser app store

### What does the proposed API look like?
Can be downloaded and used in the store

**Comment by GuoDapeng** [comment]
[https://github.com/vuejs/vue-devtools/issues/1155](url)

看样子还没安排，我也不会build，build直接报错了。要是着急用，可以找一个 谷歌访问助手 的 Chrome 浏览器插件，然后访问谷歌 Chrome网上应用商店 下载

**Comment by transtone** [comment]
https://github.com/vuejs/vue-devtools/issues/1202

**Comment by lpreterite** [comment]
> #1155
> 
> 看样子还没安排，我也不会build，build直接报错了。要是着急用，可以找一个 谷歌访问助手 的 Chrome 浏览器插件，然后访问谷歌 Chrome网上应用商店 下载

edge迁移过去直接损坏了，想用都用不了🙄

**Comment by transtone** [comment]
https://github.com/vuejs/vue-devtools/issues/1214

https://pictureknow.com/extension?id=d50143a5f53d406dbe992277bfc90521

**Comment by transtone** [comment]
https://github.com/vuejs/vue-devtools/issues/1245

**Comment by transtone** [comment]
https://github.com/vuejs/vue-devtools/issues/1173
