### ISSUE TITLE
Enable DevTools to work with JSFiddle, etc

### ISSUE THREAD

**Issue by davestewart** [vuejs/vue-devtools#119]
A lot of people use online tools like JSFiddle or CodePen to test and share Vue problems.

It would be a real aid to debugging to enable Vue Devtools to look at frames other than the main window, or even have it to this automatically, per site.

**Comment by davestewart** [comment]
I see there is also issue #115

**Comment by Mach12** [comment]
> I see there is also issue #115

Which means you just posted a duplicate.

Also, the problem has been identified. `vue-devtools` does not support `iframe`s.
See [this issue on jsfiddle's tracker](https://github.com/jsfiddle/jsfiddle-issues/issues/836) if you wish.

**Comment by blake-newman** [comment]
Closing as duplicate
