### ISSUE TITLE
vue 3/ vue next

### ISSUE THREAD

**Issue by mika76** [vuejs/vue-devtools#1199]
### What problem does this feature solve?
Implement vue 3 support - I know this is probably happening in the background but there does not seem to be an issue/milestone which people can follow and I though it would be helpful to create one.

I've been playing and converting my projects to vue next to understand and learn it and I'm very happy with everything, but the main stumbling block is debugging without devtools....

### What does the proposed API look like?
Some support for vue next, even if just rudimentary...

**Comment by thefoxie** [comment]
Any news on this? I don't think it's meaningful to start new project on vue2 at this point, but the support in devtools is essential for any development.

**Comment by bencodezen** [comment]
Hi @mika76 and @thefoxie! To check out progress on the Vue 3 DevTools, I'd recommend checking out the `next` branch of the repo!

**Comment by mika76** [comment]
Thanks @bencodezen - I actually created this issue before the first preview release with the hope of getting some info. Very little info coming out about devtools. I'm sure it's being worked on but it's be nice to see some movement.

**Comment by avimehenwal** [comment]
I was about to use vue3 for a new upcoming project but then I realised current version of devtool doen't detect vue3 app? Any chance I use newer version of devtools with vue3 support?

**Comment by bencodezen** [comment]
Hey @avimehenwal! You can actually use a local version of the DevTools by checking out the `next` branch. Let me know if you have troubles getting setup!

**Comment by calaoa** [comment]
fwiw: [v6.0.0-beta.2](https://github.com/vuejs/vue-devtools/releases/tag/v6.0.0-beta.2) includes a Firefox XPI working fine on my end :clap: – as for Chrome the instructions mentioned by @bencodezen work great :-)

**Comment by datashaman** [comment]
Note to use `v6.0.0-beta.2` you must add `vue@^3.0.0-rc.1` as a dependency as documented in release [v6.0.0-beta.1](https://github.com/vuejs/vue-devtools/releases/tag/v6.0.0-beta.1). Spinning my wheels for a bit on that one. :)

**Comment by peey** [comment]
Note that with `v6.0.0-beta.3` `vue@3.0.0` seems to work for me in firefox while the `rc.1` causes it to not be able to detect the components. YMMV.

**Comment by frankchou1** [comment]
git clone git@github.com:vuejs/vue-devtools.git

cd vue-devtools

git checkout next

yarn

yarn build:watch

and then throw error:
```
(node:11088) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ lerna run build --scope @vue-devtools/app-backend* --scope @vue/devtools-api && lerna run build:watch --stream --no-sort --concurrency 99
lerna notice cli v3.22.1
lerna info run Ran npm script 'build' in '@vue/devtools-api' in 6.6s:
$ rimraf lib && yarn build:esm && yarn build:cjs
$ tsc --module es2015 --outDir lib/esm
$ tsc --module commonjs --outDir lib/cjs -d
lerna ERR! yarn run build exited 1 in '@vue-devtools/app-backend-api'
lerna ERR! yarn run build stdout:
$ rimraf lib && yarn ts
$ tsc -d -outDir lib
src/api.ts(1,41): error TS2307: Cannot find module '@vue-devtools/shared-utils' or its corresponding type declarations.
src/backend-context.ts(1,24): error TS2307: Cannot find module '@vue-devtools/shared-utils' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
(node:28420) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.                                                                                                                                      f
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:23856) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Bu fer.from() methods instead.ffer.from() methods instead.                                                                                                                                      f
(Use `node --trace-deprecation ...` to show where the warning was created)                                                                                         fer.from() methods instead.
error Command failed with exit code 2.
error Command failed with exit code 1.
```

**Comment by Akryum** [comment]
To debug Vue 3, use the version 6 beta of the devtools. Thanks!
