### ISSUE TITLE
Publish Vue.js devtools to New Edge Store

### ISSUE THREAD

**Issue by sgf** [vuejs/vue-devtools#1214]
in china we cant access the chome store.
我不知道vue官方是不是为了逼格。
总之vue devtools 没有给国内 用户的安装提供任何便捷的途径。 
我不明白这是为什么。

**Comment by sgf** [comment]
关闭就关闭吧，我放弃了。

**Comment by sodatea** [comment]
Chrome 扩展商店国内有不少镜像。比如 https://pictureknow.com/extension?id=d50143a5f53d406dbe992277bfc90521

这里提供的扩展我刚下载下来验证过了 shasum 是靠谱的。
但是因为是非官方提供的镜像，我没办法提供更多的背书，不能保证未来一直没问题。
