### ISSUE TITLE
Config option to set auto-expand to false

### ISSUE THREAD

**Issue by jlmmns** [vuejs/vue-devtools#123]
It would be very helpful if we could disable the auto-expand feature.

A lot of my components inherit a rather large object, which appears at the top.

Because of this, I have to scroll down a lot, or collapse it every time.

**Comment by neeravp** [comment]
I totally agree and wish that such a config option is made available.

**Comment by zackcote** [comment]
Yeah this is huge for me, would be a great help!

**Comment by Renol7** [comment]
I agree with this feature request! When there is a components with some large objects it is **very difficult** to see the data. 
Also, if I **refresh** my browser after collapsing vue-devtools objects, they return to auto-expand state.

**Comment by posva** [comment]
I prefer having them expanded but I think we can leave them collapsed if there's a certain amount of properties being displayed. I think it's better to have a filter input in the vuex state too, though

**Comment by DannyFeliz** [comment]
I really need this feature x.x, every time I'm browsing in my components data I have to collapse the arrays and object, would be very cool if this feature is introduced in the next release

**Comment by ellisio** [comment]
We're building a large scale application with Vuex. At this time we have roughly 24 store objects. When I want to quickly scroll and view the payload, or find an object, there is a lot of slowish scrolling so I don't bypass the object I'm looking for.

I'm also one that constantly collapses my directory tree in my IDE and clicks back down to the file(s) I'm working on. It's something with my OCD.

Having this feature would make my work flow a lot less frustrating :)

**Comment by posva** [comment]
Added at #328
