### ISSUE TITLE
Installation beta link(s) broken

### ISSUE THREAD

**Issue by Uninen** [vuejs/vue-devtools#1231]
### Version
6.0.0-beta.1

### Browser and OS info
Chrome 83

### Steps to reproduce
"Get the Crome Extension" beta channel link pointing to ( https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg ) results in 404.

### What is expected?
The link to beta channel extension should work.

### What is actually happening?
404.

---
Also the Firefox link points to the releases page but I assume that's because there hasn't been a beta release for Firefox Addon store. (Maybe we could document this and point to build instructions.)

<s>Also, somewhat related, followed the build instructions in the readme but the build failed. I only tested with two different envs, I'll try this again and file a separate ticket if it still fails.</s> The build works fine with latest code and clean install.

**Comment by Akryum** [comment]
The Chrome web store page should be up again :)
