### ISSUE TITLE
Vue.js not detected w/ devtools 6.0.0 beta 1 and Vue 3

### ISSUE THREAD

**Issue by Uninen** [vuejs/vue-devtools#1232]
### Version
6.0.0-beta.1

### Browser and OS info
Chrome 84

### Steps to reproduce
Open a Vue 3 project dev URL w/ yarn serve or vue ui serve task.

### What is expected?
Devtools visible.

### What is actually happening?
"Vue.js not detected."

---
Some possibly related dependencies:

```
    "vue": "3.0.0-beta.24",
    "vue-router": "4.0.0-beta.2",
    "vuex": "4.0.0-beta.4"
    "typescript": "~3.9.7",
    "vue-cli-plugin-vue-next": "~0.1.3"
```

The devtools plugin itself works as it is enabled for Vue cli UI (and it displays some errors there due to missing Vue 2 support which is to be expected), I built it fresh from the repo.

I tried to first disable the old plugi, then I removed the old plugin completely. Also upgraded the browser and tried to refresh the page and close/open the devtools panel but no avail.

**Comment by glenn-at-mighty-ant** [comment]
Seeing the same here in latest Firefox browser (78.0.2) on Windows.  Also running Vue.js devtools version 6.0.0 beta 1 and running vue 3.0.0-beta.24

**Comment by Akryum** [comment]
Vue 3 beta.24 isn't compatible, you need to wait for the next release.

**Comment by Uninen** [comment]
Maybe it would be good to document this to the changelog as well :)

**Comment by Uninen** [comment]
Having still the same issue w/ Vue 3 RC1 and the downloaded version `vuejs_devtools_beta-6.0.0.1-chrome.zip` and also w/ the Firefox xpi.
