### ISSUE TITLE
Component with other component in template

### ISSUE THREAD

**Issue by RobbinBaauw** [vuejs/vue-devtools#1234]
### Version
6.0.0-beta.1

### Browser and OS info
Chrome 84.0.4147.89, Linux

### Steps to reproduce
1. Create new vite project, `yarn create vite-app some-proj` and install deps
2. Remove the  `<img>` in `App.vue` so the template only contains 
```vue
<template>
  <HelloWorld msg="Hello Vue 3.0   Vite" />
</template>
```
3. Open devtools, see that only the root `<App>` is detected:
![image](https://user-images.githubusercontent.com/5289010/87874050-defc3680-c9c6-11ea-8727-f54453431391.png)

### What is expected?
I see the entire component tree

### What is actually happening?
I only see the root component

---
When adding different elements, such as the original `<img>` tag, it does work, and it is marked with "fragment". It seems that this only occurs when there's only a component in a template.
![image](https://user-images.githubusercontent.com/5289010/87874064-fdfac880-c9c6-11ea-9f19-09572c7bf293.png)

**Edit:** it seems to be that when only having 1 element in the template, the `instance.subTree.children` is null, which is what causes this. I don't have time to debug any further right now.

**Comment by petterw03** [comment]
Is this the only outstanding bug preventing a stable v6 release?

**Comment by Akryum** [comment]
I cannot reproduce.
