### ISSUE TITLE
Component tree not supported

### ISSUE THREAD

**Issue by zareonline** [vuejs/vue-devtools#1238]
### Version
6.0.0-beta.1

### Browser and OS info
Chrome 84 / Windows 10

### Steps to reproduce
Open a Vue project, inspect elements and switch to Vue tab.

### What is expected?
Display components and component's data

### What is actually happening?
Error message "Component tree not supported". Also, console is showing up an error and a warning.

Error:  App with id null not found     backend.js:3638 ;
Warning: Instance uid=0:root not found     backend.js:3754.

**Comment by reed-jones** [comment]
Vue2 is no longer supported it by the beta version it seems, see: https://github.com/vuejs/vue-devtools/issues/1241#issuecomment-662074495

**Comment by Akryum** [comment]
Yet :D
