### ISSUE TITLE
Component tree not supported

### ISSUE THREAD

**Issue by lamoid** [vuejs/vue-devtools#1239]
### Version
6.0.0-beta.1

### Browser and OS info
google chrome latest, windows 10

### Steps to reproduce
load page and see Component tree not supported

### What is expected?
show the vue components

### What is actually happening?
nothing show, i dont see my vue components

**Comment by dudintv** [comment]
I've got the same issue.

**Comment by rwaltenberg** [comment]
Same here

**Comment by SowaProgramuje** [comment]
Same here

**Comment by PavlosPeridisOU** [comment]
Same here

**Comment by reed-jones** [comment]
My issue was I was using the beta & Vue 2 which is no longer supported. Maybe this helps someone here too https://github.com/vuejs/vue-devtools/issues/1241#issuecomment-662074495

**Comment by ferrinweb** [comment]
A very ridiculous version push, it's a completely separated version from before!

**Comment by jacky1234** [comment]
same here

**Comment by Akryum** [comment]
> My issue was I was using the beta & Vue 2 which is no longer supported. Maybe this helps someone here too [#1241 (comment)](https://github.com/vuejs/vue-devtools/issues/1241#issuecomment-662074495)

Yet! :cat2: 



> A very ridiculous version push, it's a completely separated version from before!

Hence the major version bump and the separate beta version.
