### ISSUE TITLE
Error in dev tools

### ISSUE THREAD

**Issue by IDTitanium** [vuejs/vue-devtools#1240]
### Version
6.0.0-beta.1

### Browser and OS info
Brave broswer

### Steps to reproduce
Open the dev tools in brave browser on a vue 2 project. Error noticed "Component tree not supported"

### What is expected?
See the components and states

### What is actually happening?
Error noticed "Component tree not supported"

---
Added to my headache, please fix.

**Comment by reed-jones** [comment]
Vue 2 is no longer supported it seems. See my comment here: https://github.com/vuejs/vue-devtools/issues/1241#issuecomment-662074495

**Comment by Akryum** [comment]
*Yet
