### ISSUE TITLE
Component tree not supported

### ISSUE THREAD

**Issue by alvise-citelis** [vuejs/vue-devtools#1241]
### Version
6.0.0-beta.1

### Browser and OS info
Chrome Versión 84, Windows 10

### Steps to reproduce
run vue-cli-service serve, open the chrome window and then the dev tools

### What is expected?
Use it normally

### What is actually happening?
Just can't detect my component tree when open my project on dev mode

**Comment by PROgram52bc** [comment]
Same for Ubuntu 18.04.4 LTS

**Comment by reed-jones** [comment]
Using a Laravel project (not vue-cli-service)   same issue. 
macOS 10.15.5
Chrome version 83
Vue 2.6.11

**Comment by reed-jones** [comment]
Just saw this notice 

![Screen Shot 2020-07-21 at 1 54 48 PM](https://user-images.githubusercontent.com/11511864/88100500-d7b96200-cb59-11ea-9a5f-7cefa22e422c.png)

**Comment by alvise-citelis** [comment]
> Just saw this notice
> 
> ![Screen Shot 2020-07-21 at 1 54 48 PM](https://user-images.githubusercontent.com/11511864/88100500-d7b96200-cb59-11ea-9a5f-7cefa22e422c.png)

Does anyone know how to rollback to the stable version?

**Comment by reed-jones** [comment]
It's a separate install, so you need to uninstall the extension, then install the stable one. There is a link in the readme.
