### ISSUE TITLE
Can't select Vue components with Date props

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-devtools#125]
I get an error in the console when I try to select some of my components with `props` of type `Date`:

```
backend.js:1 Uncaught TypeError: Cannot read property '1' of null
```

The error seems to be thrown by [this line](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L357) and the culprict [this RexExp](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L354). The value of `t` is the `Date` constructor that has some parameters and thus doesn't match the RegExp.

Maybe the RegExp should be `/^function (\w+)\(/`?

**Comment by Akryum** [comment]
I made a test [here](https://regex101.com/r/aP1sI8/1).

**Comment by yyx990803** [comment]
feel free to open a PR!
