### ISSUE TITLE
Vue DevTools does not work in firefox 79.0 (64 bit).

### ISSUE THREAD

**Issue by asgundogdu4e** [vuejs/vue-devtools#1254]
### Version
6.0.0-beta.1

### Browser and OS info
firefox 79.0 (64 bit)

### Steps to reproduce
Hi;
I am using firefox 79.0 (64 bit).
Vue DevTools is installed.
But it doesn't work.
It gives the following warning on the console:

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools

Good work.

### What is expected?
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools

### What is actually happening?
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools

---
Hi;
I am using firefox 79.0 (64 bit).
Vue DevTools is installed.
But it doesn't work.
It gives the following warning on the console:

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools

Good work.

**Comment by AliKOCA** [comment]
Hi;
I tested on Chromium 84.0.4147.105 (Official Compilation) snap (64 bit) Edition. It works in this version browser.

**Comment by tobiasboyd** [comment]
Can confirm, not working on FF Developer Edition 80.0b6 on macOS 10.15.6 for me.

**Comment by HorakAles** [comment]
Same problem, Vue is not detected by Vue DevTools on some websites, whereas in Chrome it works perfectly. I´m using a Firefox Developer Edition 80.0b6 Win 10 64-bit.

**Comment by Senpaiyaa** [comment]
[SedemQuame](https://github.com/vuejs/vue-devtools/issues/366#issuecomment-405993868)'s solution works. Vue DevTools took a while to show up on my developer tools.

Also I found that adblocker causes problems too with the addon. see the answer [here](https://stackoverflow.com/a/41740670/9059312)

**Comment by Roninii** [comment]
Seems to be working now v81.0b6 (64-bit)

**Comment by louwers** [comment]
Yes, working with v6.0.0-beta.2. :+1:

**Comment by jamesxv7** [comment]
Working with working with v6.0.0-beta.2.

Just to considered, you need to disable the non-beta version. Both do not work at the same time.

**Comment by Erfan-Motallebi** [comment]
same problem here. I'm facing the the same as the above-mentioned. Vue is not deteced but I'v already had it installed. Where is the problem using FF v80 ?

**Comment by djanym** [comment]
Same thing for FF 89.0.2
Note that Vue is running in Declarative Rendering mode (not Single File Components).
