### ISSUE TITLE
Vuex state properties didn't update in vue-devtools

### ISSUE THREAD

**Issue by pixieaka** [vuejs/vue-devtools#1257]
### Version
Vue.js devtools: 5.3.3 / Vue-js: 2.6.11

### Browser and OS info
chrome 84.0.4147.135, Windows 10 19041.264

### Steps to reproduce
1. init vuejs via CLI with router and vuex
2. install vuejs extension
3. add user state in vuex store.js file
4. add method to change this state

### What is expected?
state in vue-js cli update correctly

### What is actually happening?
state in vue-js cli didn't update

![Capture](https://user-images.githubusercontent.com/17777237/90761700-1753a500-e2e4-11ea-9b70-e6dd0e9abf5b.PNG)

```
export default new Vuex.Store({
    state: {
        user: 'test'
    },
    mutations: {
    },
    actions: {
    },
    modules: {
    }
});
```

```
<template>
    <div class="about">
        <h1>This is an about page</h1>
        <button @click="done">done</button>
    </div>
</template>

<script>
export default {
    methods: {
        done() {
            this.$store.commit.user = "test2";
            console.log(this.$store.commit.user);
        },
    },
};
</script>
```
### After click done button

![11](https://user-images.githubusercontent.com/17777237/90761973-829d7700-e2e4-11ea-8b8e-e605392e26a0.PNG)

![22](https://user-images.githubusercontent.com/17777237/90761987-892bee80-e2e4-11ea-93dc-da25d071f68c.PNG)

**Comment by jakubkoje** [comment]
You should read the documentation one more time. You are using it totally wrong.

**Comment by pixieaka** [comment]
Thanks @jakubkoje for reply, I appreciate.
