### ISSUE TITLE
Vue-cli aplication does not show vue-devtools

### ISSUE THREAD

**Issue by camohub** [vuejs/vue-devtools#1263]
### Version
6.0.0-beta.1

### Browser and OS info
Chrome on Win 10

### Steps to reproduce
I have vue-cli application which runs on localhost:8080. It works as expected but does not show vue-devtools. I dont understand cause other application based on vue script tag works with vue-devtools without any problems. Am I missing something or why Chrome does not offer veu-devtools for vue-cli app?

### What is expected?
See vue-devtools in Chrome.

### What is actually happening?
vue-devtools for Chrome does not appear.

It seems it is caused by minified version. But console says You are running a development build of Vue. So what is the problem?

**Comment by avimehenwal** [comment]
Are you using vue3 in in your app? I have similar issue only when I use vue3, with vue2 it works like a charm.
Seems like devtools for vue3 is still [under developmet](https://github.com/vuejs/vue-devtools/issues/1199)

**Comment by alwaei** [comment]
> ### Version
> 
> 6.0.0-beta.1
> 
> 
> 
> 
> 
> 
> 
> ### Browser and OS info
> 
> Chrome on Win 10
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ### Steps to reproduce
> 
> I have vue-cli application which runs on localhost:8080. It works as expected but does not show vue-devtools. I dont understand cause other application based on vue script tag works with vue-devtools without any problems. Am I missing something or why Chrome does not offer veu-devtools for vue-cli app?
> 
> 
> 
> ### What is expected?
> 
> See vue-devtools in Chrome.
> 
> 
> 
> ### What is actually happening?
> 
> vue-devtools for Chrome does not appear.
> 
> 
> 
> 
> 
> 
> 
> It seems it is caused by minified version. But console says You are running a development build of Vue. So what is the problem?

**Comment by camohub** [comment]
Yes Vue 3 is only in RC version. Id does not support devtool for now. Thanks.

**Comment by mohammadsultani** [comment]
Hey guys, 
any update about Vue devtools in Vue 3 projects.
Does Vue devtools support's Vue 3 now ?

**Comment by LinusBorg** [comment]
Have a look at the release page
