### ISSUE TITLE
Suspense not working w/ version 6.0.0-beta.2

### ISSUE THREAD

**Issue by Uninen** [vuejs/vue-devtools#1266]
### Version
6.0.0-beta.2

### Browser and OS info
Chrome 85 / Firefox 80.0

### Steps to reproduce
Load Vue 3 project with suspense and async setup component.

### What is expected?
Devtools working normally, app components visible.

### What is actually happening?
Devtools open with only App instance visible, no components or other app details available.

---
Tested with Vue 3 RC 10.

This issue was present with the previous version as well. If I remove the suspense-component and change components with `async setup` to normal setup, all components show and load up normally.

**Comment by Akryum** [comment]
Suspense and async setup are not supported by the devtools yet

**Comment by Uninen** [comment]
Ok, then it's not a bug 👍

**Comment by yeikiu** [comment]
All my Suspense components work perfectly replacing vue dependency to `"vue": "3.0.0-rc.5"` in my `package.json`

**Comment by Uninen** [comment]
Why would you use a version that is several versions behind? Vue 3 is in version 3.0.2 already.

As Akryum mentioned above, vue-devtools doesn't support async setup yet.

**Comment by parnus01** [comment]
I spend my whole day before see this issue  😂
