### ISSUE TITLE
devtools not detected in vue cli applications

### ISSUE THREAD

**Issue by Ahmed7fathi** [vuejs/vue-devtools#1275]
### Version
6.0.0-beta.2

### Browser and OS info
chrome 85 / kali linux

### Steps to reproduce
Allow this extension to read and change all your data on websites you visit,
Allow access to file URLs,
changing localhost to machine host,

### What is expected?
devtool to be working and debugging my project 

### What is actually happening?
 vue.js devtool works on normal html page but not in vue cli applications

**Comment by Akryum** [comment]
Are you using the v6 beta to inspect Vue 3 applications or Vue 2 apps?
