### ISSUE TITLE
when i use vuejs + turbolinks , vue-devtool just show the Root node.

### ISSUE THREAD

**Issue by lihlio** [vuejs/vue-devtools#128]
when i use turbolinks new the vue object when `document ready` or `turbolinks:load` events:
then screenshot
![image](https://cloud.githubusercontent.com/assets/10757551/17435412/43c7823c-5b43-11e6-8498-9b73ad5690c9.png)

when i use the jquery `window ready` events the screenshot:
![image](https://cloud.githubusercontent.com/assets/10757551/17295590/712d8774-582f-11e6-8d98-ed2bdbe8e857.png)

so i think have something wrong with the **vue-devtools**

**Comment by victorlcampos** [comment]
+1

**Comment by michalsnik** [comment]
It's been a long time since this issue was posted. Can you confirm it's still the case @lihlio @victorlcampos ? If yes - please feel free to reopen this issue and we'll investigate it.
