### ISSUE TITLE
No vuex info is present

### ISSUE THREAD

**Issue by Friedrich42** [vuejs/vue-devtools#1286]
### Version
6.0.0-beta.2

### Browser and OS info
 Google Chrome	85.0.4183.121 (Official Build) (64-bit) Revision	a81aa729a8e1fd413943a339393c82e7b8055ddc-refs/branch-heads/4183@{#1864} OS	Linux JavaScript	V8 8.5.210.26 Flash	32.0.0.433 /home/bert/.config/google-chrome/PepperFlash/32.0.0.433/libpepflashplayer.so User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

### Steps to reproduce
Open any dev site with "vuex": "^4.0.0-0", "vue": "^3.0.0-0"

### What is expected?
Should show vuex information

### What is actually happening?
No vuex info is present

**Comment by ux-engineer** [comment]
https://github.com/vuejs/vue-devtools/issues/1268

**Comment by shevchenko-web** [comment]
you have to remove old browser and install new one immediately.
and then install vue devtools.
regards.
