### ISSUE TITLE
Vue dev-tools cannot detect Vue3

### ISSUE THREAD

**Issue by IronManCool001** [vuejs/vue-devtools#1292]
### What problem does this feature solve?
This will solve the problem of Vue dev-tools detecting vue3 and allowing us to debug Vue3 using vue-devtools

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue-devtools/releases/tag/v6.0.0-beta.1

**Comment by shoaibsharif** [comment]
but it doesn't show VueX @LinusBorg. Any workaround for that?

**Comment by LinusBorg** [comment]
That's becvause the vuex plugin fo the new devtools is still being worked on.
