### ISSUE TITLE
Use different global hook name for v6

### ISSUE THREAD

**Issue by legnaleurc** [vuejs/vue-devtools#1293]
### What problem does this feature solve?
v5 and v6 both use the same variable `__VUE_DEVTOOLS_GLOBAL_HOOK__` to inject Vue instance.

It seems we cannot enable both version at the same time (one for Vue 2 and one for Vue 3).

If we are not going to make v6 compatible with Vue 2, maybe we can change the hook name (and other injected objects, if any), so they won't interfere each other.

### What does the proposed API look like?
For Vue 2:
```javascript
window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue = app.constructor
```

For Vue3:
```javascript
window.__VUE3_DEVTOOLS_GLOBAL_HOOK__.Vue = app
```

**Comment by Akryum** [comment]
V6 is going to be compatible with Vue 1 and Vue 2. :wink:
