### ISSUE TITLE
emitting inside component mounted() throws TypeError in backend.js

### ISSUE THREAD

**Issue by Miosame** [vuejs/vue-devtools#1296]
### Version
6.0.0-beta.2

### Browser and OS info
Firefox 82.0b9 / Fedora 32

### Steps to reproduce
1. $emit inside a components mounted() lifecycle
2. open "vue" devtools tab
3. console throws an error: "TypeError: can't access property "id", appRecord is undefined"

Source: backend.js line 2164: "const id = `${appRecord.id}:${instance.uid}`;".

### What is expected?
No errors

### What is actually happening?
TypeError

**Comment by q2578443177** [comment]
me too，so bad

**Comment by Akryum** [comment]
Please provide a runnable reproduction thanks!

**Comment by Miosame** [comment]
@Akryum sure I can do that, but should I wait till v6.0.0-beta.5 has a .xpi?

**Comment by Akryum** [comment]
It has one now

**Comment by Miosame** [comment]
@Akryum thanks! looks like the bug has been fixed since, I'll close this for now, if it comes up again, I can file a new issue with a new example. :tada:

**Comment by joinzhu** [comment]
我以为是项目有问题，草了
