### ISSUE TITLE
vue-dev-tools disappear sometimes.

### ISSUE THREAD

**Issue by ablipan** [vuejs/vue-devtools#13]
I've installed the vue-devtools1.0 and opened the [vue-hacknews](http://vuejs.github.io/vue-hackernews/#!/news/1), could't find the Vue-devtools in the Chrome-dev-tools.
![image](https://cloud.githubusercontent.com/assets/4636330/10902550/95533caa-823a-11e5-8f0b-48066d950244.png)

But the local demo with [vue-loader-example](https://github.com/vuejs/vue-loader-example) is ok.
![image](https://cloud.githubusercontent.com/assets/4636330/10902554/a44dbea6-823a-11e5-9df2-ca67363ace7c.png)

**Comment by Kerruba** [comment]
I can't see the Vue Devtools on the vue-hacknews too, didn't try we a local project yet

**Comment by yyx990803** [comment]
This is because the deployed Hackernew app is in production mode, it strips all the devtools hooks (for both performance and security reasons).

devtools will only work for non-production builds.

**Comment by charlielondon** [comment]
I just ran into this today, and the solution for me was to close and reopen the devtools.

**Comment by davidmoshal** [comment]
thanks!

**Comment by BrunildaDosti** [comment]
Many thanks to @charlielondon
