### ISSUE TITLE
Broken Vue Dev Tools

### ISSUE THREAD

**Issue by stiltet** [vuejs/vue-devtools#1302]
### Version
6.0.0-beta.2

### Browser and OS info
Chrome Version 86.0.4240.111 (Official Build) (64-bit) on Windows 10

### Steps to reproduce
When I open Vue Dev Tools I'm getting two errors;

"Uncaught (in promise) TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null
    at Object.registerApp (backend.js:1204)"

and:

"backend.js:570 Uncaught TypeError: Cannot read property 'id' of null
    at Bridge.<anonymous> (backend.js:570)
    at Bridge.emit (backend.js:3998)
    at Bridge._emit (backend.js:903)
    at backend.js:835
    at Array.forEach (<anonymous>)
    at backend.js:835
    at listener (backend.js:1477)"

### What is expected?
To Vue Devtools to work without errors.

### What is actually happening?
Vue Dev Tools are not working at all.

**Comment by gianlucadifrancesco** [comment]
**Same exact problem** for me, just after creating a basic project with the Vue CLI.
I searched a lot for a fix, but this bug seems "different" from the previous months/years one.

I wonder if I'm missing something in the docs, but I also tried to follow the "_Force enable the devtools_" section and nothing happened.
(Is it possible to fix it with some config?)

**Comment by stiltet** [comment]
The best and only way for now is to uninstall Vue Devtools extension and install the older, stable version that do work (https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en), I couldn't do anything with the new beta version, it's sadly unusable at the moment.

**Comment by gianlucadifrancesco** [comment]
@stiltet Thank you for the response and I confirm the stable version is working!
Yes anyway, I tried everything and this seems the only solution at the moment.
