### ISSUE TITLE
Vue.js not detected on vue3.0.2

### ISSUE THREAD

**Issue by hxshandle** [vuejs/vue-devtools#1304]
### Version
6.0.0-beta.2

### Browser and OS info
Chrome86/Mac OS 10.15.7

### Steps to reproduce
follow the Vite guide to create a fresh new vite-app

Remove devtool 5.3 from chrome

Reinstall devtools 6.0.0-beta.2 and restart the chrome

run yarn dev in console

Visit vite app in chrome.

### What is expected?
Devtools should work fine as Vue2 does

### What is actually happening?
Devtools shows  Vue.js not detected.

**Comment by hxshandle** [comment]
and here is the package.json content

```
{
  "name": "demo-vite-app",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "axios": "^0.21.0",
    "lodash": "^4.17.20",
    "vue": "^3.0.2",
    "vue-router": "^4.0.0-rc.1",
    "vuex": "^4.0.0-beta.4"
  },
  "devDependencies": {
    "@vue/compiler-sfc": "^3.0.2",
    "pug": "^3.0.0",
    "vite": "^1.0.0-rc.8"
  }
}
```

**Comment by drobati** [comment]
Similar issue, I used vue-cli and picked everything latest and greatest - vue 3 included. Firefox in my case doesn't detect vue running.

**Comment by matthewjflee** [comment]
I have the same issue, but there is a plugin for Chrome that can be found [here](https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg?hl=en)

**Comment by hxshandle** [comment]
The issue was gone now, after reboot the mac. LOL so close the ticket.
