### ISSUE TITLE
may it support nw.js platform ?

### ISSUE THREAD

**Issue by fish520** [vuejs/vue-devtools#131]
nw.js ( https://github.com/nwjs/nw.js ) support chrome extension now.  will it be possible to use vue-devtools in web-based desktop software development ?

**Comment by fish520** [comment]
I'm glad for having found the answer myself enventually.  And here is the solution that may help:

```bat
@echo off
cd %~dp0
start nw.exe -load-extension=./vue-devtools %1
exit
```

just create a file `start.bat` with the above content, and put it under the root of nw.js, now you can drag a vue-based application over that file, and enjoy a happy vue debugging. 
Thanks for such a good development plugin aynway !

**Comment by xland** [comment]
补充一点信息：
https://github.com/anchengjian/vue-nw-seed

这个项目才是我想要的

**Comment by qiang0** [comment]
there's another project similar with vue-nw-seed.
https://github.com/elegantweb/nwjs-vue
