### ISSUE TITLE
Component Name shown as "Anonymous Component"

### ISSUE THREAD

**Issue by pymike00** [vuejs/vue-devtools#1311]
6.0.0-beta.2

### Browser and OS info
Chromium Version 86.0.4240.111 (Official Build) Arch Linux (64-bit)

##### Create Basic Vue 3 App and Component:

```
const app = Vue.createApp({
    data() {
        return {
            comments: [
                {
                    username: "alice",
                    content: "First Comment!"
                },
                {
                    username: "bob",
                    content: "Hello World!"
                }
            ]
        }
    }
});


app.component("comment", {
    props: {
        comment: {
            type: Object,
            required: true
        }
    },
    template: `
        <div>
            <div class="card-body">
                <p><strong>{{ comment.username }}</strong></p>
                <p>{{ comment.content }}</p>
            </div>
            <hr>
        </div>
    `
});

const mountedApp = app.mount('#app');
```

```
<div id="app">
        <comment v-for="comment in comments" :comment="comment">
        </comment>
</div>
```

### What is expected?
I expect to see the component name (comment) in Vue Devtools. under Root

### What is actually happening?
Vue Devtools returns "Anonymous Component" for each component instance

![Screenshot from 2020-11-17 15-47-27](https://user-images.githubusercontent.com/32687496/99404770-4fbb4d00-28ec-11eb-9385-319e556562c9.png)

**Comment by TimRChen** [comment]
try to use named component.

**Comment by foyzhao** [comment]
Same problem, the name has been declared when registering the component

**Comment by TimRChen** [comment]
> try to use named component.

app.component("comment", {
    name: 'comment',  // component name declared in here.
    props: {
        comment: {
            type: Object,
            required: true
        }
    },
    template: `
        <div>
            <div class="card-body">
                <strong><p>{{ comment.username }}</p></strong>
                <p>{{ comment.content }}</p>
            </div>
            <hr>
        </div>
    `
});

**Comment by pymike00** [comment]
Hi both, and thanks for your answers.

@TimRChen , am I missing something in v3? 

Shouldn't this be optional at best, as the name is already declared as the first argument to app.component ?

https://v3.vuejs.org/guide/component-registration.html#component-names

**Comment by foyzhao** [comment]
> Hi both, and thanks for your answers.
> 
> @TimRChen , am I missing something in v3?
> 
> Shouldn't this be optional at best, as the name is already declared as the first argument to app.component ?
> 
> https://v3.vuejs.org/guide/component-registration.html#component-names

That's the point

**Comment by TimRChen** [comment]
Hi, there. I found this method: https://github.com/vuejs/vue-devtools/blob/6d8fee4d058716fe72825c9ae22cf831ef8f5172/packages/shared-utils/src/util.js#L260-L269
For reference only

**Comment by AdamPTD** [comment]
@TimRChen So if registration automatically sets the components name why does it need an additional name property to show up in dev tools as something other than Anonymous Component? Why doesn't dev tools show the name that the component was automatically given?

**Comment by TimRChen** [comment]
> @TimRChen So if registration automatically sets the components name why does it need an additional name property to show up in dev tools as something other than Anonymous Component? Why doesn't dev tools show the name that the component was automatically given?

I don't know. but you can find anser in source code.

**Comment by Akryum** [comment]
Please provide a runnable reproduction.

**Comment by lesderid** [comment]
I'm getting this issue with the `Home` component of the Hello World project created by Vue CLI v4.5.11 (with settings: Vue 3, TypeScript, class-based components, router enabled).

**Comment by tollswap** [comment]
I got this issue when using vue-styled-components. fixed it like this

    import styled from "vue3-styled-components"; 
    const Flexbox = styled.div`
       position: absolute;
       top: 0;
       left: 0;
       right: 0;
       bottom: 0;
     `;
    // this line is important
    
    Flexbox.name = Flexbox;
     
    /*VUEJS*/
    export default{
        components:{
            Flexbox
        }
    }

**Comment by hongquan** [comment]
I got this problem with the `Icon` component imported from `@iconify/vue` and setup script.

The fix is to register this component with a name in _main.ts_:

```ts
import { createApp } from 'vue'
import { Icon } from '@iconify/vue'
import App from './App.vue'

createApp(App).component('icon', Icon)
```

**Comment by gh-LZC** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by awacode21** [comment]
I have the same problem in 2022.

Latest stable devtools version (6.1.3) installed. Using Vue 3 with Single File Components and script setup.
