### ISSUE TITLE
$vm is no longer accessible in console

### ISSUE THREAD

**Issue by jessuni** [vuejs/vue-devtools#1315]
### Version
6.0.0-beta.2

### Browser and OS info
Edge Version 87.0.664.41 (Official build) (64-bit)
mac OS v10.15.1

### Steps to reproduce
1. Click a component in the devtool
2. type $vm in console

### What is expected?
Allowing access to $vm and its properties in console

### What is actually happening?
`Uncaught ReferenceError: $vm is not defined`

---
I wonder if this feature is removed in the beta version of the devtool?

**Comment by Akryum** [comment]
This will be implemented back soon

**Comment by Akryum** [comment]
Implemented in v6.0.0-beta.3
