### ISSUE TITLE
Cannot inspect injected data

### ISSUE THREAD

**Issue by lchrennew** [vuejs/vue-devtools#1316]
### Version
6.0.0-beta.2

### Browser and OS info
Chrome 86.0.4240.198 / MacOSX

### Steps to reproduce
inspect any component, and see its data on the right side.
there are only props, computed, data, no inject.

### What is expected?
show injected data

### What is actually happening?
no injected data shown

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/106336434-2d03c800-628f-11eb-88a3-578842bf03c2.png)

**Comment by spaceemotion** [comment]
Has there been a change to this? For some reason I'm unable to see provided/injected data during setup() with the latest vue (3.0.11) & devtools (6.0.0-beta.11)

**Comment by Akryum** [comment]
@spaceemotion Looks like it's a bug. Please open a new issue with a reproduction. Thanks!

**Comment by Akryum** [comment]
I can reproduce it, forget about the reproduction

**Comment by Akryum** [comment]
False alarm, I can't reproduce it. Is your provided value used somewhere in a template/render function/computed prop?

**Comment by spaceemotion** [comment]
no, it's just being used inside the setup method.

**Comment by Akryum** [comment]
I'm not sure the devtools can detect them until they are used.

**Comment by lchrennew** [comment]
> Has there been a change to this? For some reason I'm unable to see provided/injected data during setup() with the latest vue (3.0.11) & devtools (6.0.0-beta.11)

The latest version works great, I'll close this thread.
