### ISSUE TITLE
Add support for Microsoft Edge

### ISSUE THREAD

**Issue by lcdss** [vuejs/vue-devtools#132]
Today Microsoft released a small tool in the [Store](https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb) to help do the conversion of Chrome extensions to Edge. This tool adds 3 new files (appxmanifest.xml, backgroundScriptsAPIBridge.js and contentScriptsAPIBridge.js). The first is the manifest file used to identify the extension and the others two bridges the Chrome API to Edge API. Edge extensions uses two different square logo sizes, 44x44 and 150x150. So this repository would support both browsers.

**Comment by yajiex** [comment]
Microsoft Edge doesn't support [devtools extension api](https://developer.chrome.com/extensions/devtools) at present.

**Comment by shabushabu** [comment]
A standalone app similar to React Devtools would come in handy for IE:
https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.

**Comment by bkbillma** [comment]
> Considering Edge just switched to using Chromium and plan to support Chrome extensions, could this possibly be reopened?

Edge (chromium) can already add chrome extensions.  If you go to the chrome store from edge it even gives you a notification asking if you want to allow extensions from other stores.  Click accept/yes and boom you can download right from the chrome store to edge.

**Comment by broderick-s** [comment]
@bkbillma It seems that the Vue devtools do not consistently show in the Edge (chromium) devtools. The extension icon says it is a valid Vue page but it does not show in the devtools. The same page will work correctly in Chrome. Would I report that bug here or to Edge?

**Comment by jrd-lewis** [comment]
Any progress on this now that the new Chromium-based Edge is publicly available?

**Comment by JoshMountain** [comment]
@jrd-lewis did you see @bkbillma's reply? You can install and use the extension from the Chrome store.

**Comment by jrd-lewis** [comment]
@JoshMountain I had done that before I posted and it is still the same issue that @broderick-s had said, where it doesn't show in the devtools.

**Comment by bryceroney** [comment]
Hi has this discussion moved somewhere else now, I see it is marked as closed?
