### ISSUE TITLE
vuex invisible

### ISSUE THREAD

**Issue by owl-lei** [vuejs/vue-devtools#1324]
### Version
6.0.0-beta.2

### Browser and OS info
chrome 87 / mac os

### Steps to reproduce
    "vue": "^3.0.4",
    "vue-router": "^4.0.0-rc.6",
    "vuex": "^4.0.0-rc.2"

open devTools and you can't see the store

### What is expected?
view & debugger Store

### What is actually happening?
can see Components and Routes

**Comment by rdarcy1** [comment]
Duplicate https://github.com/vuejs/vue-devtools/issues/1268
