### ISSUE TITLE
 It doesn't appear in dev tools on Firefox

### ISSUE THREAD

**Issue by step135** [vuejs/vue-devtools#1326]
### Version
6.0.0-beta.2

### Browser and OS info
Firefox 83.0

### Steps to reproduce
After fresh install of Firefox without any other extensions, this extension doesn't appear there.

### What is expected?
Extension should be added to developer tools.

### What is actually happening?
It is not there even though it is unique extension so it can not collide with other extensions.

**Comment by weleoka** [comment]
Works for me: close devtools after enabing extension. Then open them again and you should see the Vue icon.

**Comment by ameotoko** [comment]
> Works for me: close devtools after enabing extension. Then open them again and you should see the Vue icon.

This worked in Chrome as well, thanks.

**Comment by 3nuc** [comment]
I consistently have this issue on -beta.3 on Firefox Nightly 86.0a1.

1. vue create someapp --default && cd someapp && npm run serve
2. go to localhost 8080 in firefox
3. press f12
4. vue devtools tab is not visible in devtools

The biggest problem is that each time a different solution works:
* sometimes it's "close localhost tab, close devtools, disable vue addon, enable vue addon, reopen localhost tab and press f12 to reopen devtools"
* other times it's the above but you also need to restart firefox before re-enabling vue addon

A similar issue happens from time to time with Vue 2 devtools to my colleagues using both Firefox and Chrome.

**Comment by LeBenLeBen** [comment]
I can reproduce this issue on Firefox 84.0.1 using beta 2 & 3. The extension icon is visible, Vue is detected, but the panel is not visible in the inspector. I tried to update the plugin, restart Firefox, nothing works.

I’m using Vue 3 with a Vite server.

**Comment by lucacataldo** [comment]
In case anyone has the issue where the Vue Devtools Extension detects Vue but doesn't show up in the firefox devtools I was able to fix it by:

1. Open devtools when Vue says "VueJS is detected on this page"
1. Click the 3 dots on the right of the devtools panel (next to the X to close)
1. Click "Settings"
1. Check Vue.js devtools under "Developer Tools installed by addons"

![image](https://user-images.githubusercontent.com/35984346/103579149-c533aa80-4ea5-11eb-92c7-7d305846d005.png)
![image](https://user-images.githubusercontent.com/35984346/103579164-cbc22200-4ea5-11eb-86ca-cfdc9698c990.png)

**Comment by LeBenLeBen** [comment]
This setting is already checked for me and toggling it doesn’t fix the issue 😭

**Comment by lucacataldo** [comment]
@LeBenLeBen Ah that's a shame, sorry. I just thought I'd share since that fixed it in my situation.

**Comment by metal3d** [comment]
Vue JS 3, locally started:

![image](https://user-images.githubusercontent.com/100080/104120875-8042c480-533a-11eb-8d81-7e9f0c92b572.png)

I tried to remove, reinstall, close firefox, and so on... Nothing...

And not error in console:

![image](https://user-images.githubusercontent.com/100080/104120901-b08a6300-533a-11eb-8815-c1883c5b81e7.png)


Firefox 84.0.1 on Fedora 33

**Comment by metal3d** [comment]
OK... Sorry...

https://v3.vuejs.org/guide/migration/introduction.html#devtools-extension

**Comment by LeBenLeBen** [comment]
There wasn’t new 6.x release and therefor it still doesn’t work on Firefox for me. Did I miss something?

**Comment by wrkyle** [comment]
This appears to still be a problem with dev tools v6.5.0 and Firefox v110.0.1.

**Comment by hamza221** [comment]
This is still a problem, I tried on multiple computers (fedora, macos) on firefox and firefox developer edition .
Ps: I made sure that it's enabled under 'Developer Tools installed by addons'

**Comment by kissdry** [comment]
Vue disappeared today and I can't get it back ((
![Screenshot 2023-07-27 180438](https://github.com/vuejs/devtools/assets/22590409/162a34e6-001e-424e-bcb5-43b1914954a9)
Windows 11 Pro, Firefox 115.0.2 (64-bit)

**Comment by sudofox** [comment]
Still an issue with latest firefox. I have to open Chrome (shudder) when I need to check my vue state data to debug.

**Comment by alemangui** [comment]
Still an issue with devtools version 7.7.7 and Firefox 138.0.4

**Comment by gh-LZC** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by lombervid** [comment]
I'm experiencing this problem:
- Extension: 7.7.7
- Vue: 3.5.21 
- Firefox 142.0.1 
- Fedora KDE 42

**Comment by gh-LZC** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
