### ISSUE TITLE
When i click the vue extension the app part is not found .

### ISSUE THREAD

**Issue by mi6969** [vuejs/vue-devtools#1328]
### Version
6.0.0-beta.2

### Browser and OS info
Google Chrome is up to date Version 87.0.4280.88 (Official Build) (64-bit) / Windows 8.1 pro

### Steps to reproduce
When i click the vue extension it don't show the app part ....

### What is expected?
no

### What is actually happening?
When i click the vue extension it don't show the app part ....

**Comment by ygj6** [comment]
@mi6969 In your environment, will other versions have this problem?

**Comment by Akryum** [comment]
Duplicate of #1341
