### ISSUE TITLE
When listing a Component's model, show the function signature of a value

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/vue-devtools#133]
If the value of a property of a Vue data model is a function. Vue Devtools currently just shows `"Function"` as the value. It would be neat if it showed the function signature instead (eg. `"function someFunction(arg)"`).

You can get the signature by calling `.toString()` on the function and getting everything up to the closing parenthesis:

```
if (typeof value === "function") {
    const valueStr = value.toString()
    return valueStr.slice(0, valueStr.indexOf(")") + 1)
}
```

**Comment by posva** [comment]
Definitely. PR are welcome!
