### ISSUE TITLE
Scroll on y axis doesn't work

### ISSUE THREAD

**Issue by mmihaipreda** [vuejs/vue-devtools#1336]
### Version
6.0.0-beta.3

### Browser and OS info
Electron dev tools standalone   windwos 10

### Steps to reproduce
Open an electron app
Open the Electron dev tools standalone
Try to scroll
See the error

### What is expected?
To be able to scrool through proeprties

### What is actually happening?
I can't see the other properties and as a 'hack' I decrease the zoom in roder to see all the elements 

---
Please fix this , thank you

**Comment by tbtalbottjr** [comment]
This is an issue on Mac OS 10.14.6 when used as a standalone electron app monitoring an app in Chrome.
