### ISSUE TITLE
Quick Edit Buttons (increase, decrease, cancel, save) shows html codes inside tooltip

### ISSUE THREAD

**Issue by ismailceylan** [vuejs/vue-devtools#1340]
### Version
6.0.0-beta.3

### Browser and OS info
Chrome 87, Windows 10

### Steps to reproduce
* Open Vue Devtools > App > Inspector > Components
* Click the pencil icon next to an item from the prop or data field
* Hover the mouse pointer over the cancel and save icons
* Hover the mouse pointer over the plus and minus symbols next to an item holding a numeric value in the prop or data field

### What is expected?
Simple instructions should appear in the tooltip.

### What is actually happening?
Some html codes appear.

![ screenshot ](https://i.imgur.com/SkU16vV.gif)

**Comment by ygj6** [comment]
@ismailceylan @Akryum  I am pretty sure that this problem is caused by upgrading `v-tooltip` from `3.0.0-alpha.11` to `3.0.0-alpha.13`. Next, we need to figure out what changes have been made by `v-tooltip`.

**Comment by ygj6** [comment]
@Akryum Would you consider rolling back `v-tooltip` to version `3.0.0-alpha.11`?
https://github.com/vuejs/vue-devtools/compare/next...ygj6:v-tooltip-version-back?expand=1

**Comment by ismailceylan** [comment]
@ygj6 @Akryum actually all the input field's text color and background both white. I couldn't be sure to open another issue about that. Should i?

**Comment by ygj6** [comment]
> @ygj6 @Akryum actually all input field's text color and background both white. I couldn't be sure to open another issue about that. Should i?

[This PR 1338](https://github.com/vuejs/vue-devtools/pull/1338) could solve this problem. But what color the font should be changed to can be discussed further.
