### ISSUE TITLE
Chrome shows no content, Firefox works. 6.0.0-beta.3 - Vue3 Composition API

### ISSUE THREAD

**Issue by mathiash98** [vuejs/vue-devtools#1341]
### Version
6.0.0-beta.3

### Browser and OS info
Chrome 87   Firefox 83   Windows 10

### Steps to reproduce
Generate Vu3 project with Vue-Cli-Service
Upgrade all packages in package.json to latest
Install Vue-Devtools Beta for Chrome for Chrome extension store.
Install Vue-Devtools beta for Firefox from GitHub release

### What is expected?
Application tree should show when opening devtools

### What is actually happening?
Only works in firefox using "xxx.api" package from GitHub release.

## Chrome:
![image](https://user-images.githubusercontent.com/5204006/103755749-9a189a80-500e-11eb-9df4-45fab780d2e9.png)
Console output:
![image](https://user-images.githubusercontent.com/5204006/103756079-20cd7780-500f-11eb-8d03-fd066d4af025.png)

## Firefox:
![image](https://user-images.githubusercontent.com/5204006/103755777-a7ce2000-500e-11eb-9779-2c9dbc3bc207.png)
Console output:
![image](https://user-images.githubusercontent.com/5204006/103756132-38a4fb80-500f-11eb-80d1-fe9b54f30395.png)

Might be a duplicate of: #1328 #1309 But in my case there are no error messages in the console.

**Comment by mathiash98** [comment]
Extra console logs from Chrome:
I opened the inspector for the vue-devtools plugin (Right click the interface inside the plugin and click inspect)
These errors show up:
This was after reinstall of plugin, hard refresh of localhost:8080 and several chrome dev tools refresh

```
ain._createAppUI: 26.34423828125 ms
main.js:1 Main._showAppUI: 10.86181640625 ms
main.js:1 Main._initializeTarget: 7.845703125 ms
main.js:1 Main._lateInitialization: 2.64599609375 ms
devtools.js:2 Inspector router-inspector:0 not found
(anonymous) @ devtools.js:2
devtools.js:2 Inspector router-inspector:0 not found
(anonymous) @ devtools.js:2
devtools.js:2 TypeError: Cannot read property '$options' of undefined
    at c.isChrome.r.default.config.errorHandler (devtools.js:2)
    at ie (devtools.js:2)
    at ne (devtools.js:2)
    at Array.<anonymous> (devtools.js:2)
    at le (devtools.js:2)
re @ devtools.js:2
devtools.js:2 TypeError: Cannot read property '_wrapper' of undefined
    at er (devtools.js:2)
    at _e (devtools.js:2)
    at Array.nr (devtools.js:2)
    at S (devtools.js:2)
    at a.__patch__ (devtools.js:2)
    at a.Hn.t._update (devtools.js:2)
    at a.o (devtools.js:2)
    at oo.get (devtools.js:2)
    at oo.run (devtools.js:2)
    at Jn (devtools.js:2)
re @ devtools.js:2
widget.js:1 [Headway Error] DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at n.lsGet (https://cdn.headwayapp.co/widget.js:1:18273)
    at n.lsGet (https://cdn.headwayapp.co/widget.js:1:1045)
    at n.<anonymous> (https://cdn.headwayapp.co/widget.js:1:17900)
    at n.lsGetState (https://cdn.headwayapp.co/widget.js:1:17967)
    at n.lsGetState (https://cdn.headwayapp.co/widget.js:1:1045)
    at n.onFrameLoad (https://cdn.headwayapp.co/widget.js:1:17644)
    at HTMLIFrameElement.<anonymous> (https://cdn.headwayapp.co/widget.js:1:1045)
n.warn @ widget.js:1
widget.js:1 [Headway Error] DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at n.lsGet (https://cdn.headwayapp.co/widget.js:1:18273)
    at n.lsGet (https://cdn.headwayapp.co/widget.js:1:1045)
    at n.<anonymous> (https://cdn.headwayapp.co/widget.js:1:18029)
    at n.lsGetState (https://cdn.headwayapp.co/widget.js:1:18096)
    at n.lsGetState (https://cdn.headwayapp.co/widget.js:1:1045)
    at n.onFrameLoad (https://cdn.headwayapp.co/widget.js:1:17644)
    at HTMLIFrameElement.<anonymous> (https://cdn.headwayapp.co/widget.js:1:1045)
```
![image](https://user-images.githubusercontent.com/5204006/106270199-e03bd500-622d-11eb-9eb7-176fccb38a62.png)

**Comment by mathiash98** [comment]
I have no clue how Vue-Devtools is built but this is my tiny discovery:
- It seems like the backend is sending the customInspector to the frontend too late.

![image](https://user-images.githubusercontent.com/5204006/106284643-c2796a80-6243-11eb-9864-90a1bc4b090c.png)
- See the logs:
1. First `bridge.on(BridgeEvents.TO_FRONT_CUSTOM_INSPECTOR_STATE` is unable to find `router-inspector:0`
2. Then afterwards `setupCustomInspectorBridgeEvents (bridge)` is called which populated the inspectors variable with `router-inspector:0`.
3. `bridge.on(BridgeEvents.TO_FRONT_CUSTOM_INSPECTOR_STATE` is not called again after this happens.

https://github.com/vuejs/vue-devtools/blob/next/packages/app-frontend/src/features/inspector/custom/index.js

Maybe the backend is the problem?

**Comment by Akryum** [comment]
Do you have a runnable reproduction please? :pray:

**Comment by mathiash98** [comment]
> Do you have a runnable reproduction please? 🙏

I made a stripped down version of the codebase here:
Here you go: https://github.com/mathiash98/vue-devtools/tree/mathiash98/%231341-chrome-no-component-show
Inside `Vue3-codebase-which-does-not-work` folder
- yarn install
- yarn serve
- application served on localhost:8080

**Comment by Akryum** [comment]
I can't reproduce on next branch:
![image](https://user-images.githubusercontent.com/2798204/106402338-58221f00-6429-11eb-9182-1fd77b20bdea.png)

**Comment by mathiash98** [comment]
Thanks for the time, I did some more digging and saw that the reason for it not working is that I have disabled third party cookies.

So after enabling third party cookies it works 🥳 
![image](https://user-images.githubusercontent.com/5204006/106438547-ea044900-6476-11eb-81a8-6731112ece7f.png)

**Comment by mathiash98** [comment]
Be sure to enable third party cookies in Chrome

**Comment by lambertkevin** [comment]
Can somebody explain why do I need to activate third on every website in the world (since I can't be selective about that in Chrome) just for my my dev tools to work ?
