### ISSUE TITLE
PLS make an Edge extension and upload to edge shop, THX.

### ISSUE THREAD

**Issue by sasha6806** [vuejs/vue-devtools#1343]
### What problem does this feature solve?
Users in china cannot visit chrome shop

### What does the proposed API look like?
same as vue-devtools chrome extension.

**Comment by westhom** [comment]
Use the standalone Electron app: https://github.com/vuejs/vue-devtools/blob/dev/packages/shell-electron/README.md

**Comment by nikmanzotti** [comment]
Seems to be a duplicate of https://github.com/vuejs/vue-devtools/issues/1155
