### ISSUE TITLE
provided/injected data doesn't show up in devtools

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-devtools#1346]
### Version
6.0.0-beta.3

### Browser and OS info
MacOS 10.15.7, Chrome 87.0.4280.141

### Steps to reproduce
When providing or injecting data in a component's setup function. The data/const doesn't show up in the devtools.
This makes it a bit hard to debug components that rely on data from a parent (or provide data to children).

Is there any way to make it show up, short of returning the variable in the setup function?

### What is expected?
provided/injected data to show in devtools without returning it to the template

### What is actually happening?
Not showing up.

**Comment by Akryum** [comment]
Duplicate of #1316
