### ISSUE TITLE
v-if components don't always show up in Inspector

### ISSUE THREAD

**Issue by q42jaap** [vuejs/vue-devtools#1348]
### Version
6.0.0-beta.3

### Browser and OS info
Chrome 87 macOS 11.1

### Steps to reproduce
Vue dev-tools doesn't always show components correctly in the Inspector, when they are rendered because a v-if expression turns to true.
In the attached github repo the issue is that toggling a component with v-if doesn't reflect in de devtools.
When switching to the Timeline and back to the Inspector, the components are rediscovered and displayed correctly.

### What is expected?
Components with v-if appear in devtools correctly depending on v-if

### What is actually happening?
Components with v-if don't always appear correctly in devtools.

---
See a reproduction in:
https://github.com/q42jaap/vue-devtools-bug-report

I've tried this with the beta chrome extension from the Chrome Webstore as well as a locally build devtool.

**Comment by ygj6** [comment]
@q42jaap I have reproduced the problem from the demo you provided. 


When both v-ifs are set to true, two components should be displayed, but none of them are actually displayed

![image](https://user-images.githubusercontent.com/7699524/105138326-ae40b980-5b2f-11eb-83fe-b956a42cefea.png)

===================================================================================

Then switching to the Timeline and back to the Inspector, the components are rediscovered and displayed correctly.

![image](https://user-images.githubusercontent.com/7699524/105138156-79346700-5b2f-11eb-84d9-f9c74513d28a.png)

**Comment by q42jaap** [comment]
There are also cases where 1 component would be toggled to true but wasn't displayed. It's probably all the same bug.
