### ISSUE TITLE
Overwrite app name and possibly order

### ISSUE THREAD

**Issue by bobvandevijver** [vuejs/vue-devtools#1354]
### What problem does this feature solve?
I build a plugin which add a new Vue app to the end of the dom, in order to show modals. However, in the debugger it shows as "App 1", and the main app as "App 2".

I would like to be able to name those instances.

![image](https://user-images.githubusercontent.com/1835343/106291161-93ff8d80-624b-11eb-8955-345c15b6c817.png)

### What does the proposed API look like?
Maybe it is already available, but otherwise adding properties to the element used to mount the app on could get some properties such as `data-vue-app-name` and `data-vue-app-order`.

**Comment by Akryum** [comment]
You can put a `name` on the root component and it will be used in the app dropdown.

**Comment by bobvandevijver** [comment]
You're absolutely right, thank you. How did I miss that?
