### ISSUE TITLE
Excessive logging in console (v6.0.0-beta.6)

### ISSUE THREAD

**Issue by Uninen** [vuejs/vue-devtools#1359]
### Version
6.0.0-beta.6

### Browser and OS info
Firefox 85

### Steps to reproduce
The plugin logs excessively to console whenever it's active. There should at least be a way to toggle this off or preferably turn logging on only when developing the plugin itself.

### What is expected?
Clean console log.

### What is actually happening?
Messy console (see image).

<img width="788" alt="Screenshot 2021-02-03 at 15 46 06" src="https://user-images.githubusercontent.com/43100/106756169-a7d63580-6637-11eb-82f5-9152bda8ee35.png">

**Comment by Akryum** [comment]
Those will be gone before getting out of beta.
