### ISSUE TITLE
Display all args of events in Event tab

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-devtools#136]
Now that Vue 2 events scope is limited it would be relatively easy to add a section Events for each component where those would be logged showing the arguments as well. I think that would be useful for debuging and knowing more about what is going on under the hood.

**Comment by frankdugan3** [comment]
> showing the _**arguments**_

We now have the tab thanks to #159, but it only shows the first arg as the payload. Would be great to see all the args of the event.

**Comment by yyx990803** [comment]
@frankdugan3 FYI the payload is an array representing the arguments.
