### ISSUE TITLE
Make vue-devtools 6 to be compatible with vue 2 or vue-devtools 5

### ISSUE THREAD

**Issue by LongTengDao** [vuejs/vue-devtools#1360]
### What problem does this feature solve?
vue-devtools 6 beta is not compatible with vue 2 currently.

### What does the proposed API look like?
Will it be compatible with vue 2 in the future (in 6 stable version)?

If not, maybe it would be good to make vue-devtools 6 to be compatible with vue-devtools 5 from now on.

**Comment by Akryum** [comment]
> Will it be compatible with vue 2 in the future (in 6 stable version)?
Yes.
