### ISSUE TITLE
vue-i18n  hook walkComponentTree registered by plugin vue-devtools-plugin-vue-i18n

### ISSUE THREAD

**Issue by FlyDancing** [vuejs/vue-devtools#1362]
### Version
6.0.0-beta.6

### Browser and OS info
FIxfox Lastest

### Steps to reproduce
vue-i18n show error
TypeError: treeData.children is undefined
    updateComponentTreeDataTags vue-i18n.esm-bundler.js:1367
    enableDevTools vue-i18n.esm-bundler.js:1299
    callHandlers backend.js:363
    callHook backend.js:144
    walkComponentTree backend.js:180
    sendComponentTreeData backend.js:3156
    connect backend.js:782
    connect backend.js:781
    emit (index):1
    createDevtoolsComponentHook runtime-core.esm-bundler.js:552
    unmountComponent runtime-core.esm-bundler.js:4770
    unmount runtime-core.esm-bundler.js:4644
    patch runtime-core.esm-bundler.js:3681
    componentEffect runtime-core.esm-bundler.js:4278
    reactiveEffect reactivity.esm-bundler.js:42
    callWithErrorHandling runtime-core.esm-bundler.js:154
    flushJobs runtime-core.esm-bundler.js:362
    promise callback*queueFlush runtime-core.esm-bundler.js:264
    queueCb runtime-core.esm-bundler.js:286
    queuePreFlushCb runtime-core.esm-bundler.js:289
    scheduler runtime-core.esm-bundler.js:2077
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    set value reactivity.esm-bundler.js:729
    finalizeNavigation vue-router.esm-bundler.js:3055
    removeHistoryListener vue-router.esm-bundler.js:3109
    promise callback*setupListeners/removeHistoryListener< vue-router.esm-bundler.js:3106
    popStateHandler vue-router.esm-bundler.js:437
    popStateHandler vue-router.esm-bundler.js:436
    useHistoryListeners vue-router.esm-bundler.js:476
    createWebHistory vue-router.esm-bundler.js:594
    createWebHashHistory vue-router.esm-bundler.js:733
    <anonymous> router.js:119
    js app.js:1374
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> main.js:24
    js app.js:1362
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1411
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997
backend.js:367:29

### What is expected?
no error 

### What is actually happening?
An error occured in hook walkComponentTree registered by plugin vue-devtools-plugin-vue-i18n backend.js:366:29
    callHandlers backend.js:366
    callHook backend.js:144
    walkComponentTree backend.js:180
    sendComponentTreeData backend.js:3156
    connect backend.js:782
    (异步：FrameRequestCallback)
    connect backend.js:781
    emit (index):1
    createDevtoolsComponentHook runtime-core.esm-bundler.js:552
    unmountComponent runtime-core.esm-bundler.js:4770
    unmount runtime-core.esm-bundler.js:4644
    patch runtime-core.esm-bundler.js:3681
    componentEffect runtime-core.esm-bundler.js:4278
    reactiveEffect reactivity.esm-bundler.js:42
    callWithErrorHandling runtime-core.esm-bundler.js:154
    flushJobs runtime-core.esm-bundler.js:362
    (异步：promise callback)
    queueFlush runtime-core.esm-bundler.js:264
    queueCb runtime-core.esm-bundler.js:286
    queuePreFlushCb runtime-core.esm-bundler.js:289
    scheduler runtime-core.esm-bundler.js:2077
    run reactivity.esm-bundler.js:183
    trigger reactivity.esm-bundler.js:189
    set value reactivity.esm-bundler.js:729
    finalizeNavigation vue-router.esm-bundler.js:3055
    removeHistoryListener vue-router.esm-bundler.js:3109
    (异步：promise callback)
    removeHistoryListener vue-router.esm-bundler.js:3106
    popStateHandler vue-router.esm-bundler.js:437
    popStateHandler vue-router.esm-bundler.js:436
    (异步：EventListener.handleEvent)
    useHistoryListeners vue-router.esm-bundler.js:476
    createWebHistory vue-router.esm-bundler.js:594
    createWebHashHistory vue-router.esm-bundler.js:733
    <anonymous> router.js:119
    js app.js:1374
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> main.js:24
    js app.js:1362
    __webpack_require__ app.js:854
    fn app.js:151
    1 app.js:1411
    __webpack_require__ app.js:854
    checkDeferredModules app.js:46
    <anonymous> app.js:994
    <anonymous> app.js:997

**Comment by ygj6** [comment]
> ### Steps to reproduce

In order to quickly solve your problem, this place should describe the reproduction steps in detail or attach a link to the reproduction code.

**Comment by alexandervu** [comment]
Same problem with 6.0.0-beta.7. Sorry repo is private company development.

**Comment by KalynDavis** [comment]
Encountering the same issue with a single component in a standard vue-cli project and vue-router installed.

**Comment by Akryum** [comment]
@kazupon If it's not the case yet, you choul probably switch to using [on.visitComponentTree](https://devtools.vuejs.org/plugin/api-reference.html#on-visitcomponenttree).

**Comment by kazupon** [comment]
@Akryum 
Thank you for your mention!

I already switched to `on.visitComponentTree` at [this commit](https://github.com/intlify/vue-i18n-next/commit/ff074077dbc94f9cfa515990389108b76a19bcaa#diff-ad3f8d19c2368143f20fbc5d714701755baada7a6f4ceba8db3fffd1b42626d5)

I think this issue can be solved by upgrading to vue-i18n v9.1
[here](https://github.com/intlify/vue-i18n-next/releases/tag/v9.1.0) is v9.1 release note

**Comment by kyrylo93** [comment]
I have this issue with "vue-i18n": "^9.1.6",

**Comment by whitersun** [comment]
I have the same issue with 'vue-i18n': '^9.1.0'
