### ISSUE TITLE
Can't see property starting with underscore in data

### ISSUE THREAD

**Issue by Mikaleb** [vuejs/vue-devtools#1369]
### Version
6.0.0-beta.7

### Browser and OS info
Chrome 88 / Ubuntu 20.10

### Steps to reproduce
Having a data like so : 
myArticles: [
0: {…}
_paging: {total: 1, totalPages: 1, links: {…}}
]

### What is expected?
To see _paging in the data part of the devtool

### What is actually happening?
Only the item 0 is shown, _paging is not despite existing

**Comment by Akryum** [comment]
It seems like you are adding non standard properties to `Array` which will not be serialized when sent to the devtools.
