### ISSUE TITLE
t.$el.getBoundingClientRect is not a function

### ISSUE THREAD

**Issue by lukepolo** [vuejs/vue-devtools#137]
### Reproduction Link
Vue Component 
https://jsfiddle.net/hvzcm89n/

Vue Pile Store
https://jsfiddle.net/2405e9Ln/

Vue UserTeam Store
https://jsfiddle.net/0pj8ogn8/

### Steps to reproduce
Click on route : sometimes it triggers error. Not always. No request fails from the API. Not easy to replicate. 

### What is actually happening?

![image](https://cloud.githubusercontent.com/assets/2066668/17838270/596b4122-6797-11e6-9b6b-4df0e7328acd.png)

Probably cant be solved from what I've given, which happens once in 10-15 requests.

**Comment by dalphyx** [comment]
I meet same problem when used empty root component.

Reproduction Link: [https://jsfiddle.net/z7k9ozpf/](https://jsfiddle.net/z7k9ozpf/)

Open vue-devtools, it will show the error.

**Comment by miljan-aleksic** [comment]
Also seen this one with same difficulties to reproduce...

**Comment by dalphyx** [comment]
Yeah... It seems like that `vue-devtools` can't detect vue in iframe, so jsfiddle can't reproduce it. Fortunately, my Reproduction code is pretty simple, just copy and paste in local file won't waste a lot of time :)

**Comment by getflourish** [comment]
Having a similiar issue over here. Vue app runs fine with no errors, but once I open Vue dev tools, it becomes unusable :(

I’m only guessing by looking at the line of code that causes it, but does this have something to do with a "fragment"?


<img width="501" alt="screen shot 2016-08-26 at 10 52 49" src="https://cloud.githubusercontent.com/assets/183989/17999832/6698e768-6b7b-11e6-9d03-9e093aa301cd.png">


<img width="566" alt="screen shot 2016-08-26 at 11 00 43" src="https://cloud.githubusercontent.com/assets/183989/18000038/6e1e8ce4-6b7c-11e6-94a4-4e71097a2a93.png">

**Comment by lukepolo** [comment]
thanks for the fix!

**Comment by dperrymorrow** [comment]
has this fix been released? I'm having this issue using ```vue-devtools@2.04```

**Comment by teleclimber** [comment]
I am also having this issue. Vue 2.1.3 and Vue-devtools 2.3.1. I am using it in Electron js FWIW. `backend.js line 1 col 19934`

![screen shot 2016-12-06 at 10 58 33 am](https://cloud.githubusercontent.com/assets/5631748/20935076/ffc437a4-bba2-11e6-9703-26244041944b.png)

**Comment by cnweibo** [comment]
@yyx990803 , have this issue been fixed? Unfortunately, i meet this also, i do not know what is the cause for this and how to debug or workaround it?

thanks~!!

**Comment by cnweibo** [comment]
@yyx990803 , please skip it, i find it is fixed after i upgrade to latest vue-devtool, that maybe caused by comment node created by v-if
