### ISSUE TITLE
Support for Safari Browser

### ISSUE THREAD

**Issue by nezaboravi** [vuejs/vue-devtools#1370]
### Version
6.0.0-beta.7

### Browser and OS info
Safari on Big Sur Mac M1 Silicon 

### Steps to reproduce
NO steps. Buy Mac, start developing without chrome - memory eater.

### What is expected?
many devs are using safari, so would be great to support it.

### What is actually happening?
not supported

---
this was asked but never got any answers from vue team

**Comment by Akryum** [comment]
For unsupported browsers, you can use the standalone devtools.
