### ISSUE TITLE
Does it work with vuejs 3?

### ISSUE THREAD

**Issue by Guervyl** [vuejs/vue-devtools#1380]
### Version
6.0.0-beta.7

### Browser and OS info
Chrome 88

### Steps to reproduce
Install it and open a vuejs 3 app in the browser.

### What is expected?
It should show up.

### What is actually happening?
The extension does not show up to debug the vuejs 3 app.

**Comment by Guervyl** [comment]
Actually, I just check the details of the extension and it show version '5.3.4'. I installed it today!!! Isn't the extension on the Chrome web store updated?

**Comment by Guervyl** [comment]
Hello? Why closing the issue without any exponation?

**Comment by Akryum** [comment]
Please install the correct version, which is 6.x for Vue 3.

**Comment by lastlink** [comment]
When will version 6 be published? do we have to build and manually use it?

**Comment by Akryum** [comment]
Read the docs?
