### ISSUE TITLE
$vm not working when sending to console

### ISSUE THREAD

**Issue by anlek** [vuejs/vue-devtools#139]
It used to work but now I'm no longer able to access $vm when clicking on the `send to console` button. The console outputs:

```
[vue-devtools] Ready. Detected Vue v1.0.26
[vue-devtools] <Field> is now available as $vm.
```

but when I access the $vm, I get: `Uncaught ReferenceError: $vm is not defined(…)`

Running chrome on mac version: 52.0.2743.116 (64-bit)

**Comment by yyx990803** [comment]
This seems to be a Chrome devtools bug, since I've run into it in other cases without vue-devtools too. (global variables not available in console)

Reloading the page seems to be have it working.

**Comment by dodas** [comment]
Do you have window set to `top`? It's select at the top of console,  next to `Preserve log` checkbox. Sometimes it switches itself to some chrome extension.

**Comment by vivekkumarmaru** [comment]
I am having the same issue too, my chrome window is set to `top` and everything is set, still unable to access vue property to console with `$vm`.

**Comment by posva** [comment]
Seems to be fixed now. @anlek if you still find the issue, please provide a repro using this as a base: http://codepen.io/pen?template=PWbYJO

**Comment by anlek** [comment]
I've switched to Vue 2.0 and now everything seems to work fine, thanks :)

**Comment by ilkermutlu** [comment]
In case anyone else is having still having this issue, my situation is a bit different.

When I assign the vue instance to a variable, then type in that variable in the console, `$vm0` becomes available. If I don't assign the instance to a variable, or try to access `$vm0` without first using the variable, `$vm0` is unavailable. 

It works, but I find it a bit odd. 

Vue version: `2.5.13`
