### ISSUE TITLE
No $vm0 when selecting a component in v6 beta

### ISSUE THREAD

**Issue by skmbr** [vuejs/vue-devtools#1396]
### Version
6.0.0-beta.7

### Browser and OS info
Chrome 89 / Mac OS Big Sur

### Steps to reproduce
Select a component in Vue Devtools
Attempt to access (eg) $vm0.computedName via console

### What is expected?
Be able to access props/data/computed properties etc via $vm0.*

### What is actually happening?
$vm0 doesn't exist

---
$vm exists which I discovered on another issue when googling for a solution to this, but it's not the same as I'm used to in the old dev tools.  I can see data in there but I can't see how to access computed properties.

I've looked for more detailed documentation but the official docs only really seem to cover how to install.

**Comment by Akryum** [comment]
The default variable in the old devtools was `$vm` too. Having multiple variable history ($vm0, $vm1, $vm2...) is not implemented in the rewrite (yet).

> $vm exists which I discovered on another issue when googling for a solution to this, but it's not the same as I'm used to in the old dev tools. I can see data in there but I can't see how to access computed properties.

The component instance object changed between Vue 2 and Vue 3, this has nothing to do with the devtools.

**Comment by skmbr** [comment]
Ok, thanks!

So is it possible to access all the properties of a specific component in the console without the $vm0 funcitonality?

Is there any timescale/roadmap for it to be added in v6?

**Comment by Akryum** [comment]
Select a component and use `$vm` in the console to access it.

**Comment by skmbr** [comment]
Yes, I can see that... as I said in my original post:

"I can see data in there but I can't see how to access computed properties."

I also used $vm0 a lot to directly run methods for testing and debugging.  Is there a way to do this via $vm?

I'm sorry if my questions seem stupid to you. I'm just getting to grips with Vue 3 and have spent ages trying to explore the $vm object without finding what I'm looking for.

**Comment by Akryum** [comment]
Use `$vm.proxy` which is equivalent to the `this` keyword in the component file.

**Comment by skmbr** [comment]
Perfect! Thanks for your help.
