### ISSUE TITLE
Tracking functional components in the component tree

### ISSUE THREAD

**Issue by zephraph** [vuejs/vue-devtools#140]
At this point it seems that the component tree is rendered out based on available vue component instances. Giving a component the property `functional: true` prevents it from creating a new instance. It'd still be nice to be able to see that component on the final tree. 

Is this a possibility?

**Comment by LinusBorg** [comment]
Since functional components dont have instances, that seem hardly possible.

**Comment by mrleblanc101** [comment]
Weird, I just came across this.
Some fonctional component do appear in the dev-tools, like Nuxt `client-only`.
But not my custom fonctional component `v-calendar-picker`
<img width="388" alt="Capture d’écran, le 2021-04-22 à 12 37 39" src="https://user-images.githubusercontent.com/17392251/115751964-a8918480-a367-11eb-8f17-0585e29ba593.png">
