### ISSUE TITLE
[Vue.js not detected] vue app with vue-cli

### ISSUE THREAD

**Issue by Flowe2** [vuejs/vue-devtools#1402]
### Version
5.3.4

### Browser and OS info
Chrome 89 / Windows 10

### Steps to reproduce
Vue version: 3.x
Vue-cli version:  4.5.11

I'm a new hand in vue develompment from China, and there's little document about the usage of newer version vue or vue-devtools. : (<br>
I tried many measures I coud find online, but the devtools still can't work properly in my chrome...<br>
The devtools addon can work in other vue pages like vuejs.org.<br>
However, I execute "npm run serve" and open my app on localhost:8080, then I just get [Vue.js not detected]<br>
Is there any step I miss?

### What is expected?
Vue.js is detected on this page.

↑ these words can show up in my app... : (

### What is actually happening?
Vue.js not detected

**Comment by LinusBorg** [comment]
For Vue 3 you need devtools v6, currently in beta and installable as a separate app in the respective browser's extensions store.

**Comment by Flowe2** [comment]
THANKS SO MUCH!
IT WORKS!
