### ISSUE TITLE
Downloaded .crx file of vue.js extension is broken

### ISSUE THREAD

**Issue by urszkb** [vuejs/vue-devtools#1403]
### Version
5.3.4

### Browser and OS info
Chrome 89 / Windows 10

### Steps to reproduce
Online updates of the chrome extensions are not allowed in our shop. When I download the vue.js extension with https://clients2.google.com/service/update2/crx?response=redirect&prodversion=89.0.4389.90&acceptformat=crx3&x=id%3Dnhdogjmejiglipccpnnnanhbledajbpd%26uc I got a broken extension_5_3_4_0.crx file. Open this file with 7-zip gives only a not readable file extension_5_3_4_0.

### What is expected?
Open the .crx file with 7-zip shows several .html files and directories

### What is actually happening?
Open the downloaded .crx file with 7-zip gives only a not readable file extension_5_3_4_0.

**Comment by Jokerwin** [comment]
Hi @urszkb, I cannot reproduce this issue using Windows 10 Home and Chrome Version 90.0.4430.85 (64 bits).

The link you have posted works well for me.

After you download it, you have to drop the `.crx` file in the Chrome extensions page [chrome://extensions/](chrome://extensions/) and acept the installation popup.

**Comment by urszkb** [comment]
Hi @Jokerwin 
Thank you for your response. Yes, this way works. But in our shop the install of extensions are suppressed. We have a solution with a ChromeExtensions.xml and a path to our filesystem with the .crx file in it. Our Chrome engineers suppose that the problem is the .crx file. But this test demonstrate that we have an other problem.
