### ISSUE TITLE
Components are not displaying in Dev tools after Vue got detected

### ISSUE THREAD

**Issue by KiranmayeeK** [vuejs/vue-devtools#1408]
[###](url) Version
6.0.0-beta.7

### Browser and OS info
Chrome  Version 90.0.4430.72 (Official Build) (x86_64) macOS Catalina 10.15.7ata

### Steps to reproduce
Open the URL   and able to see Vue got detected on page

Go to vue in devTool and not able to see any components or events
![image](https://user-images.githubusercontent.com/39571541/115185888-94aeff80-a095-11eb-9c86-a152d494bad3.png)

### What is expected?
Should able to see vue components & events in dev tools

### What is actually happening?
Not seeing any vue components and events in dev tools .

---
Its would be more helpfull if there any option to upload screenshots

**Comment by Akryum** [comment]
You are in the "Plugins" view, switch to the "Inspector" or "Timeline" view to see components and events.
