### ISSUE TITLE
Infinity values showing as null

### ISSUE THREAD

**Issue by dodas** [vuejs/vue-devtools#141]
Hello guys,
I just noticed properties of components with value of `Infinity` are showing as `null` when inspecting component. When I send `$vm` to console, I can see its actual value is `Infinity`.

See screenshot:
![vue-devtools-infinity](https://cloud.githubusercontent.com/assets/14360171/18302236/ed96ef12-74d6-11e6-94cb-08cbecd8c757.png)

**Comment by sirlancelot** [comment]
The good news is it's just in the inspector, the underlying object still contains the right value.

**Comment by sirlancelot** [comment]
Thank you, @yyx990803!
