### ISSUE TITLE
Missing getters grouping on root level with Vuex Inspector

### ISSUE THREAD

**Issue by CesarGomezTissini** [vuejs/vue-devtools#1413]
### Version
6.0.0-beta.8

### Browser and OS info
Edge 90.0.818.46 / Windows 10

### Steps to reproduce
1. Create a Vuex 3 single file store in a Vue 2 project, example, src/store.js
2. Set a new Vuex.Store instance with respectives state, mutations, getters and actions.
3. Go to Vue Devtools and select Vuex Inspector. Then, select root level as item to inspect

### What is expected?
Vuex inspector grouping states in State section and Getters in getter section like 5.3.4.

### What is actually happening?
States and Getters grouped all in one State section

---

https://gfycat.com/ifr/FavorableSkeletalKoodoo

**Comment by theZaX** [comment]
I also saw a similar bug, I was using the beta version of devtools and using the vuex store with modules loaded. Some of the getters did not show up and it would sometimes detect some and other times not detect any getters for the whole store. 

I switched back to the other dev tools (this project is in vue 2) and everything displays perfectly.

**Comment by Akryum** [comment]
@theZaX If you have an issue with Vuex on Vue 2 unrelated to this one please open another issue.
