### ISSUE TITLE
2.0 compatability

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vue-devtools#142]
Hi, just wondering if we'll see support for Vue 2.0 once that's officially released?

Thanks in advance.

**Comment by LinusBorg** [comment]
What is not working for you? devtools work with 2.0 already since the beta phase.

**Comment by niallobrien** [comment]
Oh really? I have the plugin installed and it's not working at all, docs had no mention of 2.0. I will try it on another, less enterprise-restricted machine. Thanks.

**Comment by LinusBorg** [comment]
June 22nd to be exact :-D

https://github.com/vuejs/vue-devtools/commit/035a3aa520f1d77bae6bbfebf04dfd2731f5ddce

**Comment by niallobrien** [comment]
Thanks @LinusBorg
