### ISSUE TITLE
TypeError: pluginOn[k].callHandlers is not a function

### ISSUE THREAD

**Issue by anish2690** [vuejs/vue-devtools#1422]
### Version
6.0.0-beta.8

### Browser and OS info
Firefox & OSX

### Steps to reproduce
Tried to enable it on a older Vue 2 project but not able to detect app, but works fine for newly created boilerplate from Vue CLI  

### What is expected?
Should detect Vue 2 app

### What is actually happening?
Not able to find Vue 2 app

![image](https://user-images.githubusercontent.com/22445409/116023627-20162b00-a66a-11eb-8282-10bd8a665b69.png)

**Comment by liuxilu** [comment]
Me too, but on 3.0.5 with direct `<script>` usage.

**Comment by jbmaisner** [comment]
Same here, on Vue 3.0.11, unfortunately didn't find the origin :/
It happened right after Devtool update

**Comment by cgarnier** [comment]
I got the same issue. 
I my project, i got a lib that add some methods to arrays.
The `in` is taking array keys AND the methods names. It should be replaced by `await Array.map` or something.

**Comment by cgarnier** [comment]
To reproduce, just add
```
Array.prototype.foo = 'bar'
``` 
In a vue project.

**Comment by liuxilu** [comment]
I defined **enumerable** prototype methods as well.
I solved this by creating nonenumerable methods with `Object.defineProperty`.
`for...of` seems won't fix this as it still enumerate enumerables.

**Comment by Akryum** [comment]
:sweat:

**Comment by cgarnier** [comment]
Ty @Akryum
