### ISSUE TITLE
Component tree keyboard navigation with arrow keys not working

### ISSUE THREAD

**Issue by bobvandevijver** [vuejs/vue-devtools#1430]
### Version
6.0.0-beta.9

### Browser and OS info
Edge 90 / Windows 10

### Steps to reproduce
Looks like the arrow navigation in the component tree is not (yet?) implemented in the new v6 version.

### What is expected?
Arrow keys to work for component navigation (with left & right for collapse & expand, and up & down for up & down). See also #665/#638/#283.

### What is actually happening?
The arrow keys don't do anything...

**Comment by Akryum** [comment]
Yup, it's not implemented yet.
