### ISSUE TITLE
dev tool did not show on the Chrome tool  in vue3.0 project

### ISSUE THREAD

**Issue by ItsNikkiZeng** [vuejs/vue-devtools#1445]
### Version
6.0.0-beta.10

### Browser and OS info
Google Chrome  90.0.4430.212/macOS 10.15.6

### Steps to reproduce
access https://github.com/vuejs/vue-devtools  and  click beta channel redirect to  https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg  add to Chrome,  it active on the top of right corner also show  Vue.js is detected on this page.Open DevTools and look for the Vue panel.

### What is expected?
even chrom canary still not show

### What is actually happening?
my project version is vue3.0 and  I am using 6.0-beta dev tool, it actived on the page but it  is not show on the chrome tool panel

**Comment by ameerHumza751** [comment]
For me I tried a couple of things but ended to get it working by `Empty cache and Hard Reload` with the latest version `devtools` that are in beta on chrome web store. Also try to close open chrome console to get the Vue console tab
![Capture](https://user-images.githubusercontent.com/56400981/119041176-ba4e6200-b9cf-11eb-93e2-f34de80312c7.PNG)

**Comment by Akryum** [comment]
Try restarting your browser after installing the devtools. You can also then try to refresh your page, then open the devtools.
