### ISSUE TITLE
How to enable the new performance monitoring in v6 beta 11?

### ISSUE THREAD

**Issue by puyt** [vuejs/vue-devtools#1448]
### Version
6.0.0-beta.11

### Browser and OS info
Chrome 90.0.4430.212

### Steps to reproduce
I tested this with a sample project that I found:
1. clone the [project](https://github.com/iosamuel/vue3-samples)
2. npm install
3. updated the main.js 
```js
app = createApp(App).mount('#app')
```
to 
```js
const app = createApp(App);
app.mount('#app);
app.config.performance = true;
```
4. npm run serve

### What is expected?
To see the various new features introduced in beta 11.

https://headwayapp.co/vue-js-devtools-changelog/performance-monitoring-195710

### What is actually happening?
Nothing is shown in the component tree list and the performance tab in the timeline is empty.

Having the same issue when reinstalling the chrome plugin or trying it in firefox.

So i'm not sure what i'm doing wrong or missing?

---
![Screenshot from 2021-05-24 19-21-09](https://user-images.githubusercontent.com/3668615/119385223-22e65900-bcc6-11eb-85c8-3583428b2687.png)

![Screenshot from 2021-05-24 19-21-25](https://user-images.githubusercontent.com/3668615/119385237-27ab0d00-bcc6-11eb-87bd-79888b03f7e5.png)

**Comment by Akryum** [comment]
It's pending https://github.com/vuejs/vue-next/commit/f7c54caeb1dac69a26b79c98409e9633a7fe4bd3 to be released
