### ISSUE TITLE
Failed at the chromedriver@2.24.1 install script 'node install.js'

### ISSUE THREAD

**Issue by felbry** [vuejs/vue-devtools#146]
When I run 'npm install',

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.24.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.24.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\vue-devtools\npm-debug.log

**Comment by devrsi0n** [comment]
chrome driver的下载地址是 http://chromedriver.storage.googleapis.com/2.24/chromedriver_win32.zip， 需要番羽土墙。可以按如下配置npm配合ss：
```json
strict-ssl=false
registry=http://registry.npmjs.org/
proxy=http://<ip>:<port>/
https-proxy=http://<ip>:<port>/
```
