### ISSUE TITLE
npm install fail with error

### ISSUE THREAD

**Issue by wj007881** [vuejs/vue-devtools#1463]
D:\qqqw>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-devtools@6.0.0-beta.12
npm ERR! Found: eslint-plugin-promise@5.1.0
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   dev eslint-plugin-promise@"^5.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-promise@"^4.2.1" from @vue/eslint-config-standard@6.0.0
npm ERR! node_modules/@vue/eslint-config-standard
npm ERR!   dev @vue/eslint-config-standard@"^6.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by dangsensen** [comment]
这个问题解决了 我也遇到这个问题

**Comment by dangsensen** [comment]
这个问题解决了吗  我也遇到了这个问题 不知道怎么解决

**Comment by wj007881** [comment]
> 这个问题解决了吗 我也遇到了这个问题 不知道怎么解决

忘了，后面好像没安装dev-tool了
