### ISSUE TITLE
 When app.unmount() is called immediately after app.mount(), an error will be reported, as follows:

### ISSUE THREAD

**Issue by withoutmeat** [vuejs/vue-devtools#1464]
### Version
6.0.0-beta.12

### Browser and OS info
Chrome 90 / Mac 10.15.7

### Steps to reproduce
main.ts

```ts
import { createApp } from "vue";
import App from "./App.vue";

const vm = createApp(App);
vm.mount("#app");
vm.unmount();
```

### What is expected?
no error.

### What is actually happening?
throw error: TypeError: Cannot set property '__VUE_DEVTOOLS_UID__' of null at registerAppJob (backend.js:743)

**Comment by Akryum** [comment]
Will display a warning
