### ISSUE TITLE
Beta Builds for Chrome

### ISSUE THREAD

**Issue by nVitius** [vuejs/vue-devtools#1466]
### Version
6.0.0-beta.12

### Browser and OS info
Chrome / Windows 10

### Steps to reproduce
Install Vue Devtools beta via Chrome web store.

### What is expected?
6.0.0-beta.12 would be installed

### What is actually happening?
6.0.0-beta-4 is installed

**Comment by nVitius** [comment]
The [changelog](https://headwayapp.co/vue-js-devtools-changelog) stopped being updated with links to the Chrome plugin since beta-4. Is there any way we can get the newer builds on chromium browsers?

**Comment by Akryum** [comment]
Read the docs
