### ISSUE TITLE
Crashing chrome devtools and requires reloading extension

### ISSUE THREAD

**Issue by codylandry** [vuejs/vue-devtools#147]
I've recently had this issue where the tab will hang, and devtools will close.  When I reopen devtools, vue does not appear.  So, I go into extensions and reload it.  Then I have to open a new tab to get vue dev tools back, only for all this to happen again within a half hour or so.  We recently switched to vue 2.0 and have ran the migration helper which has no errors left.

**Comment by posva** [comment]
Sorry for the delay, if you still face this issue with the devtools v3, please open a new issue with some reproduction. You can use this template as a base: http://codepen.io/pen?template=PWbYJO and provide a debug view
