### ISSUE TITLE
Prop name is an array, throw an error "TypeError: str.replace is not a function"

### ISSUE THREAD

**Issue by blusoul** [vuejs/vue-devtools#1470]
### Version
6.0.0-beta.12

### Browser and OS info
windows 10 21H1 Chrome 90 / mac Chrome 90.0.4430.212

### Steps to reproduce
1. I create a component "App",  it's prop name is an array 
1. I use vue-devtools find components "App", 
1. throw an error "TypeError: str.replace is not a function", and components tree not work
```javascript
<template>
  <div id="app">
    <p>when name is an array {{JSON.stringify(name)}}</p>
    <p>I find Commponents 'App'</P>
    <p>throw an error <span class="warn">"TypeError: str.replace is not a function"</span></P>
  </div>
</template>

<script>
export default {
  name: 'App',
  props: {
    // when name is an array, throw an error "TypeError: str.replace is not a function"
    name: {
      type: Array,
      default: () => ['start', 'end']
    }
  },
}
</script>
```
![image](https://user-images.githubusercontent.com/8167270/120877499-68215980-c5e9-11eb-88cd-b1f19447f571.png)
![image](https://user-images.githubusercontent.com/8167270/120877634-378def80-c5ea-11eb-8208-d68a1181e7a2.png)
![image](https://user-images.githubusercontent.com/8167270/120877703-99e6f000-c5ea-11eb-84bf-34375726f9a6.png)
1. [Demo](https://codesandbox.io/s/summer-glitter-47cqz?file=/src/App.vue)

### What is expected?
no error

### What is actually happening?
 throw an error "TypeError: str.replace is not a function", and components tree not work

 ```javascript
// packages\app-backend-vue2\src\components\tree.ts
// packages\app-backend-vue3\src\components\filter.ts
function isQualified (instance): boolean {
  // instance.name is prop name
  const name = classify(instance.name || getInstanceName(instance)).toLowerCase()
  return name.indexOf(filter) > -1
}
```

**Comment by Akryum** [comment]
I don't reproduce with latest next branch and your demo link.

**Comment by blusoul** [comment]
I upgrade to 6.00 beta 14 the error is existed.
![image](https://user-images.githubusercontent.com/8167270/121456581-e199bd00-c9d8-11eb-8515-fc4ea54b5830.png)
mac / chrome 91.0.4472.77 / Vue.js devtools 6.0.0 beta 14 | Vue.js devtools 5.3.4
step 1:  link to [codesandbox](https://47cqz.csb.app/)
step 2: keypress F12  vue devtools
step 3: findComponent App
