### ISSUE TITLE
Cannot update (= successfully edit)  reactive data

### ISSUE THREAD

**Issue by wsw70** [vuejs/vue-devtools#1472]
### Version
6.0.0-beta.12

### Browser and OS info
Chrome 90, Windows 10

### Steps to reproduce
Inspect a page with reactive data, choose a component to show that data. Try to edit the data (pencil icon, edit, the save icon)

### What is expected?
The data changes both in vue-devtools and in the app

### What is actually happening?
The data does not change. When editing and saving the previous value is retained (as if the data was read-only) and the app does not see the change either.

**Comment by Akryum** [comment]
Please provide a runnable reproduction, thanks!

**Comment by wsw70** [comment]
It is interesting - I created a simple Vue3 document and I see no problems: the reactive data is updated in real time in vue-devtools, and I can edit them there (and the change is reflected on the page).

I will dig deeper, buy creating something from vue-cli and try to replicate the issue I have. Closing for now.

```
<div id="app"></div>


<script src="http://unpkg.com/vue@next"></script>

<script>
  const { createApp, ref } = Vue;

  const App = {
    setup() {
      let name = ref("aaa");
      let mytext = ref("xxx")
      return {name, mytext};
    },

    template: `<h1>Hello {{ name }}</h1><input v-model="mytext"/><div>{{mytext}}</div>`,
  };

  createApp(App).mount("#app");
</script>
```
