### ISSUE TITLE
Possibility to see where a router push/replace was called from

### ISSUE THREAD

**Issue by kurbar** [vuejs/vue-devtools#1474]
### What problem does this feature solve?
When viewing the Routing tab in Vue DevTools, it would be beneficial for debugging to be able to see from where a router push/replace was called from (file and/or line).

If encountering weird routing bounces in an application, it could be cumbersome to track it down by searching through the code where such an invocation is happening from (especially foreign code). It would greatly increase debugging speed if Vue Devtools showed the file and line where the routing navigation was invoked from.

### What does the proposed API look like?
-

**Comment by Akryum** [comment]
Please post a feature suggestion in the vue-router-next repository.
