### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "http://dev.example.com" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by zigomir** [vuejs/vue-devtools#1481]
### Version
6.0.0-beta.14

### Browser and OS info
Chrome 91 / macOS 11.4

### Steps to reproduce
Open dev tools, see the error.

```
Uncaught DOMException: Blocked a frame with origin "http://dev.example.com" from accessing a cross-origin frame.
    at e (<anonymous>:1:218)
    at HTMLIFrameElement.<anonymous> (<anonymous>:1:432)
```

### What is expected?
No error.

### What is actually happening?
Error.

**Comment by Akryum** [comment]
There is nothing I can do if an iframe can't be accessed for security reasons.

**Comment by zigomir** [comment]
Sorry, my bad :( I incorrectly assumed this came from devtools somehow.
