### ISSUE TITLE
Vue devtools raises an exception when something has been added to an iframe

### ISSUE THREAD

**Issue by kemyd** [vuejs/vue-devtools#1483]
### Version
6.0.0-beta.14

### Browser and OS info
Chrome (all)

### Steps to reproduce
Vue Devtools raises an exception when something has been added to an iframe.

1. Install the latest version of devtools 6.0.0 - beta14
2. Go to https://shuffle.dev/editor (no registration is required)
3. Drag any component from the left menu to a browser mockup. 

### What is expected?
No errors :)

### What is actually happening?
When a component is dropped on browser mockup (iframe), the extension raises this error:

2VM212:1 Uncaught DOMException: Blocked a frame with origin "https://shuffle.dev" from accessing a cross-origin frame.
    at e (<anonymous>:1:218)
    at HTMLIFrameElement.<anonymous> (<anonymous>:1:432)

---
This started to occur on June 9th, so when you released the latest version.

**Comment by zigomir** [comment]
I reported the same in https://github.com/vuejs/vue-devtools/issues/1481 and then I thought it's not `vue-devtools`'s problem. But now I'm more convinced that it is. I can only reproduce error when `vue-devtools` are installed and enabled in Chrome browser.

**Comment by CalebKester** [comment]
I also run into this issue on windows chrome.

![image](https://user-images.githubusercontent.com/1319995/122123513-ac83d500-cdf3-11eb-931e-6a79365a116c.png)
