### ISSUE TITLE
TypeError: Cannot destructure property 'mixins' of 'from' as it is undefined.

### ISSUE THREAD

**Issue by KaelWD** [vuejs/vue-devtools#1491]
### Version
6.0.0-beta.14

### Browser and OS info
Chrome 91

### Steps to reproduce
Use global mixins and functional components. 

`options` is the mixin
![image](https://user-images.githubusercontent.com/16421948/122929542-6b209600-d3ae-11eb-8a1e-b4193b71bb81.png)
`raw` is a functional component
![image](https://user-images.githubusercontent.com/16421948/122929576-75db2b00-d3ae-11eb-8ded-8d03cf3d2399.png)

`mergeOptions` sees it's a function and tries to access `from.options`, but functional components have no options so that is undefined, causing the destructure to throw this error. If `raw` is a function and has no options it should probably early return `undefined`

### What is actually happening?
![image](https://user-images.githubusercontent.com/16421948/122929775-ac18aa80-d3ae-11eb-9141-6cc6273f57e7.png)

---

**Comment by KaelWD** [comment]
@Akryum wrong issue reference in the commit message?

**Comment by Akryum** [comment]
Yes, I fixed the commit

**Comment by KaelWD** [comment]
I don't think that'll fix it - `from` was defined, `from.options` wasn't

**Comment by Topograph** [comment]
I am getting this error when using a child component, which has a transition as root element (wrapping a v-show).
![Screenshot 2021-07-01 135043](https://user-images.githubusercontent.com/19184869/124119926-6a08fc00-da73-11eb-9c0e-f2d84af4f286.png)

I don't get this in the firefox-version of the beta dev tools. only chrome/edge.

I also dont know if this is related to this issue.

**Comment by phil-w** [comment]
I'm getting precisely this issue with 6.0.0 beta 15 on Brave. If that fix above is in a later release, all is good. 
But it's still broken as per Topograph's report in this set up.

**Comment by muhammedkaraoglu** [comment]
I get this error when I use "transition" Can you help?
` <transition name="slide-fade">
            <h1>Testing</h1>
          </transition>`

**Console >**  

<img width="1430" alt="Ekran Resmi 2021-09-06 14 25 11" src="https://user-images.githubusercontent.com/25641500/132210289-255f598c-7cc6-4746-93e1-2b4b5dd11d96.png">
