### ISSUE TITLE
Vue 3.0 sites not detected

### ISSUE THREAD

**Issue by jpgringo** [vuejs/vue-devtools#1492]
Hi… the extension continues to work perfectly for me for all Vue 2.x sites, but is failing to detect Vue 3.0 sites in either Chrome or Firefox (Mac.) I have tried disabling all other extensions, restarting the Vue dev server, etc., etc., but results are consistent.

In Firefox, I'm getting a "Vue.js not detected" warning; in Chrome, the icon indicates that it is detected, but the extension does not show up in the devtools menu.

Is this a known issue?

**Comment by LinusBorg** [comment]
Are you using devtools 6.0 (currently available on the beta channel)? 5.0 doesn't support Vue 2
