### ISSUE TITLE
Vue 3.0 sites not detected

### ISSUE THREAD

**Issue by jpgringo** [vuejs/vue-devtools#1493]
### Version
5.3.4

### Browser and OS info
Firefox 89.0.2 & Chrome 91.0.4472.114 / Mac OS 11.4

### Steps to reproduce
- create a Vue 3.0 site using the Vue CLI (`create vue site-name` and choose 3.x as the version)
- serve the new site using `yarn serve`
- attempt to access Vue devtools

### What is expected?
- Vue icon in the toolbar should be highlighted
- Vue devtools should appear in the devtools menu

### What is actually happening?
Firefox:
- icon not highlighted; display "Vue.js not detected" message
- menu item missing from devtools menu

Chrome
- icon is highlighted
- menu item missing from devtools menu

---
First encountered this now that I'm trying to create some new sites for production using Vue 3.0… 

I've tried turning off _all_ other extensions in both browsers, relaunching the dev server, clearing the cache, etc., but the results are consistent.

Is this a known issue?

**Comment by Akryum** [comment]
Install the devtools 6.x beta to inspect Vue 3 apps.

**Comment by jpgringo** [comment]
👍 thanks
