### ISSUE TITLE
Shows incorrect data when variable is updated from transition hook

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-devtools#151]
Reproduction code - https://jsfiddle.net/ebb7bt3L/

And recorded video showing bug in action -  https://vid.me/QSEl

**Comment by posva** [comment]
The transition isn't working but the data seems to be updating properly: http://s.codepen.io/posva/debug/ggLMoZ/VJrxxwNDRnKr (link expires)

If the issue still exist open a new issue using this template: http://codepen.io/pen?template=PWbYJO
