### ISSUE TITLE
Vue 2 Support

### ISSUE THREAD

**Issue by blackfyre** [vuejs/vue-devtools#152]
We've started exploring the new version as soon as it came out, and the devtools would be a great help!

**Comment by sqal** [comment]
But it works with Vue 2 :) What is the problem?

**Comment by gocanto** [comment]
for me, the components props do not show up there

**Comment by npulidom** [comment]
Make sure you are using the non minified version for dev. 
For Production use `Vue.config.devtools = false;`

**Comment by yyx990803** [comment]
It does support Vue 2.0 - please open separate issue if you find problems where it doesn't work properly with 2.0.
