### ISSUE TITLE
Devtools Cannot be Enabled

### ISSUE THREAD

**Issue by kamilersz** [vuejs/vue-devtools#153]
It seems that after my Google Chrome was updated automatically (to this version: 53.0.2785.143 m) Vue Devtools became disabled. It was fine before.

Here is the screenshot
![vue-disabled](https://cloud.githubusercontent.com/assets/2652633/19143695/ca37ba14-8bcf-11e6-934e-1ebf2e06cfcf.png)

**Comment by sqal** [comment]
This icon always looks like this, it doesn't mean extension is not activated. Open chrome devtools and just click on the Vue tab.

**Comment by kamilersz** [comment]
yeah usually on devtools there is Vue tab, but it was gone last afternoon

but it is shown now 🤔 dunno why

**Comment by mcacek** [comment]
I have that problem from time to time but restarting my browser has always fixed it. /shrug

**Comment by yyx990803** [comment]
That button is Chrome's weird design decision to always show an icon for a newly installed extension even if the extension doesn't use that button at all.
