### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by allan98** [vuejs/vue-devtools#154]
When install devtools（npm run dev）,meet errors,anyone help me .thanks.
![image](https://cloud.githubusercontent.com/assets/18660781/19185649/22d8dfd2-8cb5-11e6-855e-d2b5c73a67f8.png)

**Comment by acelan86** [comment]
哈喽，我也遇到同样问题，但是报错中，“webpack 2 no longer allows custom properties in configuration”，这里写的很清楚了，所以在shells/chrome里面需要修改webpack.config.js 把vue一段去掉并修改

**Comment by xxxxxMiss** [comment]
那一段要怎么修改呢？

**Comment by yyx990803** [comment]
See http://vue-loader.vuejs.org/en/options.html

**Comment by allan98** [comment]
build success ,thanks.
