### ISSUE TITLE
Vue-devtools work in production since 1.0.28

### ISSUE THREAD

**Issue by lavezzi1** [vuejs/vue-devtools#155]
Hello community! Today I noticed that vue-devtools work on my production site. I think it's happens since I updated vue to 1.0.28. I use webpack for build. That's my production section in webpack.config.js:

```
var prod = process.env.NODE_ENV === 'production';
module.exports.plugins = (module.exports.plugins || []);
if (prod) {
    module.exports.plugins = module.exports.plugins.concat([
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: 'production'
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            minimize: true,
            compress: {
                warnings: false
            }
        }),
        new webpack.optimize.OccurenceOrderPlugin()
    ]);
} else {
    module.exports.output.publicPath = '/';
}
```

I didn't use this option `Vue.config.devtools = true`.

Chrome version is `Version 54.0.2840.59 (64-bit)`
Thank you.

**Comment by lavezzi1** [comment]
Hello guys! Somebody help me!

**Comment by yyx990803** [comment]
Sorry, cannot reproduce this with a fresh vue-cli install. Are you sure you deployed the production build?
