### ISSUE TITLE
No possible interactions

### ISSUE THREAD

**Issue by gregballot** [vuejs/vue-devtools#157]
Hello, 

The devtool is in my extensions bar but I cannot interact with it even if I'm in dev mode. My vue version is 1.0.21. I also added the following line in my main.js : 
`Vue.config.devtools = true;`

Any ideas of what prevents vue-devtools to be active ?
Thanks,
Greg

**Comment by simplesmiler** [comment]
Make sure your page is served from `http://...` rather than from the filesystem (i.e. `file:///...`).
If you don't have a server, you can `# npm i -g http-server` and then `# http-server` from the directory with your `index.html`.

**Comment by gregballot** [comment]
My page is served from a server, but the extension is grayed and I cannot interact with it :/

**Comment by yyx990803** [comment]
**The button doesn't do anything. You need to open the devtools manually.**

**Comment by gregballot** [comment]
No I never had it in the developer console. I fixed it by patching the sources ;)
