### ISSUE TITLE
respect chrome devtool's ctrl+num shortcuts

### ISSUE THREAD

**Issue by JJPandari** [vuejs/vue-devtools#158]
Chrome devtool has an option of "Enable Ctrl + 1-9 shortcut to switch panels", currently unavailable when under the "Vue" tab (would jump between browser tabs rather than devtool tabs). It would be nice if it's made the other way.

**Comment by posva** [comment]
@JJPandari I checked other extensions (ChromeLens, React, Pixi) and it looks like that behaviour cannot be preserved while in extensions panels. I googled for a fix but couldn't find one. If you find one, feel free to open a PR or a new issue with more information
