### ISSUE TITLE
Instance $children can be undefined

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/vue-devtools#16]
Looks like `$children` array can be `undefined` at least then `instance._inactive` is `true`.
It causes [this](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L190-L194) to fail with error:
```
backend.js:321 Uncaught TypeError: Cannot read property 'map' of null
```

**Comment by yyx990803** [comment]
should be fixed in https://github.com/vuejs/vue-devtools/commit/653cd33a9f3208a212e947f77f3112ac4f308883 - can you build locally to test it?

**Comment by OEvgeny** [comment]
Quick check in devtools says me that affected instance had `isBeingDestroyed: false`. Thank you :)
Anyway, I will try to build it and test it. Will reopen it if something goes wrong.

**Comment by OEvgeny** [comment]
It works great. Thanks again!
