### ISSUE TITLE
Properties that begin with an underscore don't show their value in devtools

### ISSUE THREAD

**Issue by adamwathan** [vuejs/vue-devtools#160]
This works properly as you'd expect; updating the input updates the `p` tag:

``` html
<script src="https://unpkg.com/vue@next/dist/vue.js"></script>

<div id="app">
  <input type="text" v-model="$data._message">
  <p>{{ $data._message }}</p>
</div>

<script>
new Vue({
  el: '#app',
  data: {
    _message: 'Hello Vue.js!'
  }
})
</script>
```

The devtools however just shows `undefined` the whole time:

![devtools-bug](https://cloud.githubusercontent.com/assets/4323180/19621341/c59831ec-985d-11e6-96f6-9465bd86f5d0.gif)

**Comment by mblarsen** [comment]
It looks to me they are not getting a reactive setter and getter. Tested in v2.2.4 @yyx990803
