### ISSUE TITLE
Download message in console log for production

### ISSUE THREAD

**Issue by PascalAOMS** [vuejs/vue-devtools#164]
**Versions**
VueJS: 2.0.3
Vue Devtools: 2.1.2
Webpack: 2.1.0-beta.25

**What is the problem?**
When creating my production build with Webpack, I receive `Download the Vue Devtools for a better development experience` in the console log.  
Vue.config.devtools is not being set to false automatically.

**How to reproduce?**
Run: `NODE_ENV=production webpack`
Setup Webpack like this:
```js
const ENV = process.env.NODE_ENV

if( ENV === 'production' ) {
  ...
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    })
  ]
}
```

**Notes**
The bundle is minimized correctly and all other warnings are being stripped.  
Using `Vue.config.devtools = false` manually works.

**Comment by NoNameProvided** [comment]
I get the same warning, but the vue-devtools plugin is installed for me.

**Comment by DCzajkowski** [comment]
I think this is a *Vue*/*Webpack template* issue rather than *Vue Devtools*.

I'd create it here: https://github.com/vuejs-templates/webpack/issues

**Comment by posva** [comment]
This has been fixed somewhere in between the v3
