### ISSUE TITLE
Not working on current Vivaldi

### ISSUE THREAD

**Issue by murbanowicz** [vuejs/vue-devtools#166]
Hi, it was working before, but now after some Vivaldi update it is showing
`Download Vue DevTools...` even if it is installed...

**Comment by yyx990803** [comment]
The extension is only designed to work on Chrome, as long as it works intended on Chrome, it seems to be Vivaldi's issue.

**Comment by grafa** [comment]
It's confirmed Vivaldi issue. They say the team is working on it tho.
