### ISSUE TITLE
nothing changes on chrome after the installing extension 

### ISSUE THREAD

**Issue by NikosEfthias** [vuejs/vue-devtools#167]

**Comment by w3code** [comment]
Dito.

**Comment by dre1080** [comment]
Same here

**Comment by joshbrw** [comment]
+1

**Comment by NikosEfthias** [comment]
@w3code what does dito mean ?

**Comment by joshbrw** [comment]
@NikosEfthias It means "me too" - http://dictionary.cambridge.org/dictionary/english/ditto

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue-devtools#vue-devtools - does that help?

**Comment by w3code** [comment]
No, I followed the instructions, but it still doesn't work.

**Comment by w3code** [comment]
Well, I just deactivated and activated again, now it works. ;)

**Comment by mityukov** [comment]
I have the extension icon Active (as it have detected Vue on the page), but no "Vue" tab in th development console.. Does it have limitations like.. MacOs, Webpac?

https://www.evernote.com/l/ACgS9fkI2J5D7aQHeCTWm7QWfqxi_yvpTRQ

**Comment by simplesmiler** [comment]
@mityukov try refreshing the page and reopening the devtools.

**Comment by w3code** [comment]
Make sure that the extension has access to file:// protocol. You can activate this in the Chrome's extensions management panel -> Type in the URL `chrome:extensions` and watch for the Vue extension, then there're two checkboxes (one for incognito mode and one for file access).

**Comment by mityukov** [comment]
@w3code I use Laravel's Valet for the development, so, the site is not accessed by file:// (I believe..)
