### ISSUE TITLE
JS error in Chrome dev tools with Prototype js

### ISSUE THREAD

**Issue by davemerrill** [vuejs/vue-devtools#171]
With the latest version of Prototype.js loading (1.7.3), vue-devtools enabled, and Chrome dev tools open, I see this error:
    Uncaught TypeError: this.each is not a function(…)
    detect	@	prototype.js:905
    (anonymous function)	@	VM175:1

The 'VM...' reference changes, but is always there. Happens in any file, no js except a link to Prototype. Removing Prototype or disabling vue-devtools avoids the error.

Just to be clear, I'm not using Prototype in Vue projects, but I work on both, and it's slightly unfortunate to have to disable the extension for Prototype work. Not critical, but if the problem is easily avoided, it should be.

Example file attached, nothing in it but a link to Prototype on CDN.
[vue-dev-tools-test.zip](https://github.com/vuejs/vue-devtools/files/583361/vue-dev-tools-test.zip)

**Comment by euperia** [comment]
I'm also having this issue.  Shows on any websites that use prototype.js.  I'm using Vuejs on a Magento site and seeing this on every page load regardless of Vue being loaded or not.

**Comment by nickgr6** [comment]
> Just to be clear, I'm not using Prototype in Vue projects, but I work on both, and it's slightly unfortunate to have to disable the extension for Prototype work. Not critical, but if the problem is easily avoided, it should be.

Same here. Would be nice, if it'll be fixed :)

**Comment by shershen08** [comment]
It could be fixed with following patching the nodes list in the detector.js

```
  let all = document.querySelectorAll('*')
        let prototypeJSSafeNodesList = [].map.apply(all, (el) => {
            el.each = function() {};
            return el;
        })
        const el = [].find.call(prototypeJSSafeNodesList, e => e.__vue__)
        if (el) {
//
```

**Comment by posva** [comment]
So it's prototype.js just breaking because it's overriding prototypes, which, is a known bad practice 😩 ?
@shershen08 I think it'll be better to do a simple for loop instead

**Comment by shershen08** [comment]
@posva that's what prototype.js is about, patching native objects. It's so old that good / bad practices didn't exist at those days I guess. 
Thing with for-loop will iterate all nodes in the dom tree, while find should return first isn't it?

**Comment by posva** [comment]
@shershen08 yes, that's it. You can even create a `find` function. It stops when it finds one occurrence that meets the condition

**Comment by shershen08** [comment]
> You can even create a find function.
But the Array.prototype.find is already _patched_ by prototype.js if it's on the page. That's why I wanted to patch each object in the `document.querySelectorAll('*')` list accordingly

**Comment by posva** [comment]
I was talking about a simple function like: 

```js
function find (array, condition) {}
```

**Comment by shershen08** [comment]
Ah, got your point. I'll add it this way and send a PR then.
