### ISSUE TITLE
Support chrome remote debugging

### ISSUE THREAD

**Issue by ytudt** [vuejs/vue-devtools#183]
I use vue to  make a Hybrid App，I want to use vue-devtools,I download vue-devtools plugin in chrome.
but I can not find the  vue-devtools pannel.
![1](https://cloud.githubusercontent.com/assets/16434007/20453700/2719cd8e-ae68-11e6-8faf-7bbe9e100a3f.png)
what should I do to use vue-devtools in chrome://inspect?

**Comment by zuibunan** [comment]
![image](https://cloud.githubusercontent.com/assets/3386786/20857459/5f0c5ca6-b968-11e6-9905-9db394aef375.png)
AdBlock

**Comment by doodlewind** [comment]
@zuibunan Did your AdBlock extension exist in remote debugging window? Can't reproduce this.

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.
