### ISSUE TITLE
vuex stack trace

### ISSUE THREAD

**Issue by weepy** [vuejs/vue-devtools#184]
it would be pretty useful to pull out a stack trace for each of the mutations ? 

something like: 
```
var currentFunction = arguments.callee.caller;
    while (currentFunction) {
      var fn = currentFunction.toString();
      var fname = fn.substring(fn.indexOf(&amp;quot;function&amp;quot;) + 8, fn.indexOf('')) || 'anonymous';
      callstack.push(fname);
      currentFunction = currentFunction.caller;
    }
```

There's obviously a perf hit, but it would be super useful to be able to jump into where that particular mutation was called from.

Thoughts ?

**Comment by HerringtonDarkholme** [comment]
Hi, you can add a new Plugin like this.

```ts
const myPlugin = store => {
  store.subscribe((mutation, state) => {
      console.log((new Error).stack)
  })
}

const store = new Vuex.Store({
  // ...
  plugins: [myPlugin]
})
```

It relies on subscription is called synchronously, and only trace synchronous call stack.

For tracing async tracing, you either need long-stack-trace support or globally hacking function call.
