### ISSUE TITLE
Send to console missing?

### ISSUE THREAD

**Issue by ipa1981** [vuejs/vue-devtools#188]
I'm not sure what has happened, but now I don't see Send to console button: 

This is on my machine
![image](https://cloud.githubusercontent.com/assets/15179453/20569348/7b3618da-b1a8-11e6-8f53-9ef14e42efbb.png)

This is how it should look (screen from your manual) and how it worked on my machine previously:

![image](https://cloud.githubusercontent.com/assets/15179453/20569395/a557b632-b1a8-11e6-83c4-e99e8d55328b.png)

Is it a bug, did I misconfigured something or something has changed?

**Comment by simplesmiler** [comment]
Instances now automatically bind to console when you click on them, see #111, #106

**Comment by ipa1981** [comment]
Clear now. Not very obvious. But maybe just because I had experience with previous way. Some explanation in panel could be the key.
