### ISSUE TITLE
Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

### ISSUE THREAD

**Issue by akshayrpatel** [vuejs/vue-devtools#190]
Does anyone know why am I having this issue ?

**Comment by simplesmiler** [comment]
You are probably using Vue from CDN, and probably using a production build (`dist/vue.min.js`). Either replace it with a dev build (`dist/vue.js`) or add `Vue.config.devtools = true` to the main js file.

**Comment by blake-newman** [comment]
This issue will now be closed, please reopen when relevant information is provided.

Thanks.

**Comment by davidmoshal** [comment]
Still getting this error with `Vue.config.devtools = true`

**Comment by nikklass** [comment]
where do we put this directive? I placed the command "Vue.config.devtools = true" in the file app.js in laravel but it stil shows the same message. As below:

...
Vue.config.devtools = true

Vue.component('new-artist', require('./components/NewArtist.vue'));

const app = new Vue({
    el: '#app'
});
...

**Comment by davidmoshal** [comment]
I've found that the directive has to go before any other references to Vue.
so, if the app.js file is your entry point, put it at the very top of the file.

**Comment by mknooihuisen** [comment]
@nikklass When using Laravel just make sure you run the proper webpack for your environment.  running 'npm run watch' should build Vue with debug mode on.  Use 'npm run production' to use minified Vue for production.  This will save you having to remember to toggle the debug mode when building for production.

**Comment by Byronsargeant** [comment]
new Vue({        
        el: '#app',
        data: {
            message: 'hello world'
        }        
});
Vue.config.devtools = true;

This seems to have solved this issue for me in laravel 5.4

**Comment by vinodjoshi** [comment]
Does anyone found solution for this ?

**Comment by Ding-Fan** [comment]
@vinodjoshi #62 check out this
As my situation, I change my CDN to a non-minified version and have `Vue.config.devtools = true` in my js file, then it shows up.

**Comment by scasic** [comment]
In laravel 5.6 I solved this by
`php artisan preset vue
`

**Comment by appsparkler** [comment]
Set the following before any references to `Vue`:

```
Vue.config.devtools = true
```
then also **close and repopen the browser or developer console**

Good Luck...

**Comment by judge2020** [comment]
Quick question, why is devtools disabled in production in Vue? Unless Vue exposes some extra debug information not present in production, it could work similar to React's devtools extension where the only true debug information is unavailable and the full names of components aren't available.

 I just hope this isn't a "political" decision chosen because some companies or developers want to prevent users, other developers, from snooping around how their components work.

**Comment by catskull** [comment]
My argument is that all other devtools are available in production (network tab, js console, etc), so why not go all in? What harm can it do?

**Comment by LinusBorg** [comment]
@judge devtools hook into your application, so they can both impact performance and behaviour (i.e. through a bug in the devtools). Disabling them makes the app safer in that regard, and we don't want to force developers accept that risk for their production code. 

And as you say, the devtools also make snooping around in an application much easier, and I think the decision about wether to allow that is up to the owner of the code, now us.

So we have them deactivated by default and make enabling them an opt-in for the developer.

Of course frontend code is never "secure", and anyone can snoop around if they want to, and activate the devtools by "force" if they are able and inclined to do so, but that doesn't mean that it's prudent to open up your app's inner workings to anyone able to install a browser extension. Some safguards are better than none.

**Comment by mgrollins** [comment]
There is also an option in the extension that will allow Vue devtools to"Allow access to file URLs" if running locally.

**Comment by Wolverine7** [comment]
I place the `Vue.config.devtools = true;` right above my Vue instance and it worked
Example: 

```
Vue.config.devtools = true;
new Vue({
    el: '#app',
```

**Comment by Qwertie-** [comment]
@LinusBorg Shouldn't users have the right to see what is running on their own machine? The dev tools let the user more easily see what is happening with their data and what things are being collected. The react dev tools work on production mode and there seems to be no issues there.

**Comment by akimlyubchenko** [comment]
Hope it'll help someone.
I'm using webpack as bundle collector and vue dev tool did not work because `publicPath` contained a '.' line `path`
```javascript
output: {
        path: path.resolve(__dirname, './dir/bundles/'),
        publicPath: '/dir/bundles/',
        filename: '[name].js'
    }
```

**Comment by shirshak55** [comment]
What is advantage of disabling vue dev tools by default? I don't think there is any performance penalty using react right so that should be same case for vue also? I can also freely browse facebook in react devtools.  I guess people are happy with false illusion of security.

**Comment by dassio** [comment]
[this answer works for me ](https://forum.vuejs.org/t/how-to-access-vue-from-chrome-console/3606/5)

`$vm = $0.__vue__`

**Comment by shirshak55** [comment]
@dassio no this doesn't help. The question is about how to enable vue dev just like react devtool in production mode. Facebook and million of other react sites etc aren't having any security issue however vue core dev thinks disabling makes it hard. It makes hard for newbie but not for pro developer which might even be more risk tbh.

**Comment by dassio** [comment]
> @dassio no this doesn't help. The question is about how to enable vue dev just like react devtool in production mode. Facebook and million of other react sites etc aren't having any security issue however vue core dev thinks disabling makes it hard. It makes hard for newbie but not for pro developer which might even be more risk tbh.

i agree , this is more like a hack and i put it here till vue core resolve this issue

**Comment by Romerolweb** [comment]
> Still getting this error with `Vue.config.devtools = true`

WHere?

**Comment by shirshak55** [comment]
@Romerolweb u can do it in entry of application. Like usually it is index.js . Use it before you initialize vue components.

**Comment by mjzarrin** [comment]
If you are using Nuxt.js, add the following inside your nuxt.config.js
```
vue: {
    config: {
      devtools: true,
      productionTip: false,
    },
  },
```

**Comment by adamkhan** [comment]
In case you missed it, there are checkbox settings within DevTools itself to hide or display "Developer Tools installed by add-ons". Checking these solved it for me.
![Screen Shot](https://user-images.githubusercontent.com/776967/94361868-4f05f780-00af-11eb-956c-0fcecec9e77b.png)

**Comment by ProgrammingPete** [comment]
For those of you who are using the CDN version of Vue.js. You can use the non-production package for debugging and the (production) packages for your production. See the screenshot below. 

`vue.js` for debugging
'vue.min.js' for production 


![70aabb6d-6740-469a-8948-9ee99cc8a850](https://user-images.githubusercontent.com/10091505/112215193-fce5ff00-8c17-11eb-88d9-cc1553991204.jpg)

**Comment by AverageCakeSlice** [comment]
l'm also having this issue with a Vue 3 app of mine, but I'm not in production mode. I'm not sure what's going on and there doesn't seem to be any way to override the behavior.

**Comment by rb0w** [comment]
Hi. The last thing I did to get this working is adding

**Comment by nth-chile** [comment]
Is `devtools` still a config option? Not seeing anything about it in the docs.

**Comment by semiaddict** [comment]
If using vue-cli with vue 3, you need to tap into the "_feature-flags_" plugin to change the value of `__VUE_PROD_DEVTOOLS__` to the `true`. See https://github.com/vuejs/core/tree/main/packages/vue#bundler-build-feature-flags.

Here's how I did it in vue.config.js:

```
module.exports = defineConfig({
  chainWebpack: (config) => {
    config.plugin("feature-flags").tap((args) => {
      args[0].__VUE_PROD_DEVTOOLS__ = true;
      return args;
    });
});
```

I believe this can also be done when not using the cli, but then I guess you'll have to define the plugin as [done by the cli](https://github.com/vuejs/vue-cli/blob/926855fac7a52ea960c00720f09196cd13b443ff/packages/%40vue/cli-service/lib/config/base.js#L150).

**Comment by nth-chile** [comment]
Unfortunately my project is not using the cli or webpack. Just a vue.js file

**Comment by douglasg14b** [comment]
Is there  afix for Vue3?

I'm using `vite`  and during dev serve, the dev tools are unavailable because they claim it's a production build when it most definitely is not.

**Comment by 0xdevalias** [comment]
> [this answer works for me ](https://forum.vuejs.org/t/how-to-access-vue-from-chrome-console/3606/5)
> 
> `$vm = $0.__vue__`
> 
> edit: you need to select the dom in the inspect tab to get the $0

People looking to do this who can't just change their code and re-deploy may like these 2 blogs:

- https://www.damianmullins.com/inspecting-a-vue-application-in-production/
- https://www.damianmullins.com/logging-vuex-actions-and-mutations-in-the-wild/

Based on that, you could get a list of all of the Vue elements by running the following snippet in the JS console:

```js
let vueElements = [...document.querySelectorAll('*')].filter(el => el.__vue__);

console.log(vueElements);
```

You can then access the Vue internals from `element.__vue__` (eg. `vueElements[0].__vue__`)

**Comment by tcrite1** [comment]
> If using vue-cli with vue 3, you need to tap into the "_feature-flags_" plugin to change the value of `__VUE_PROD_DEVTOOLS__` to `true`. See https://github.com/vuejs/core/tree/main/packages/vue#bundler-build-feature-flags.
> 
> Here's how I did it in vue.config.js:
> 
> ```
> module.exports = defineConfig({
>   chainWebpack: (config) => {
>     config.plugin("feature-flags").tap((args) => {
>       args[0].__VUE_PROD_DEVTOOLS__ = true;
>       return args;
>     });
> });
> ```
> 
> I believe this can also be done when not using the cli, but then I guess you'll have to define the plugin as [done by the cli](https://github.com/vuejs/vue-cli/blob/926855fac7a52ea960c00720f09196cd13b443ff/packages/%40vue/cli-service/lib/config/base.js#L150).

this fixed it form me!

**Comment by yasirhere123** [comment]
i went with this command in my console and also add in main js file it worked perfectly for me 
command = " Vue.config.devtools = true; " 

example of js file below
Vue.config.devtools = true;

const app = new Vue({
    el: '#app',
});

**Comment by rollersteaam** [comment]
# For Vue 2 users
This can happen if you're on Vue 2 and haven't installed the legacy version of DevTools yet, and your current version was auto-updated for Vue 3.

1. Install legacy here: https://chromewebstore.google.com/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp
2. Restart your browser
3. Hard refresh the page using Control + Shift + R or Shift + F5
4. Be sure to wait a few moments for the "Vue (legacy)" tab to load in
