### ISSUE TITLE
Can't install on Fedora 25

### ISSUE THREAD

**Issue by romu70** [vuejs/vue-devtools#196]
Pretty all in the title, tested with Chrome and Chromium. When I click "Add Extension", download starts and I get a "Network error". And as you can see, my internet access is in good conditions.

**Comment by LinusBorg** [comment]
> And as you can see, my internet access is in good conditions.

See where?

**Comment by romu70** [comment]
I was able to write this issue from the same computer I get the "Network error", so I guess my internet connection is working as expected. But the problem came from my pretty aggressive hosts file which filters too much addresses.

**Comment by LinusBorg** [comment]
> I was able to write this issue from the same computer I get the "Network error", so I guess my internet connection is working as expected. 

internet access is not "on" or "off" - works or doesn't work - as you just learned yourself. :)

Things get blocked in various countries, DNS you need servers can be down for you, but not for others, some software (or in your case your hosts file) blocks certain connections - a proxy e.g. in your compona  is messing with yourt traffic ... there can be countless reasons why your internet access is partially not working.

**Comment by romu70** [comment]
Thanks for this wise comment. And now, I'll enjoy vue-devtools!!
