### ISSUE TITLE
Bug in tool?

### ISSUE THREAD

**Issue by robertmylne** [vuejs/vue-devtools#201]
I have the following function below that gets run on a semantic ui dropdown.

```
let vue = this;
$('.ui.dropdown').dropdown({
    onChange(value, text, $selectedItem) {
        let type = $selectedItem[0].dataset.type;
        console.log(type)
        if(type == 'month') {
            vue.newCard['exp_month'] = value;
            console.log(vue)
        }
        if(type == 'year') {
            vue.newCard['exp_year'] = value;
            console.log(vue)
        }
    }
})
```

This does update the value in the data object, I can see this by logging it out, but it does not update in the vue devtools, well it does randomly (about 1 in every 10 times). 

**Vue DevTools**
![image](https://cloud.githubusercontent.com/assets/10385217/21174719/8abfe1f4-c22a-11e6-8f30-96d2a0bbb5ec.png)

**Chrome Console**
![image](https://cloud.githubusercontent.com/assets/10385217/21174727/95c21ec8-c22a-11e6-8db5-43a582fea07a.png)

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/guide/list.html#Caveats

**Comment by robertmylne** [comment]
Thanks for letting me know. I tried the below but it still _does not_ work in the dev tools.

`Vue.set(vue.newCard, 'exp_month', value);`

**Comment by robertmylne** [comment]
So another bit of code i'm using where the reactivity does not show in the vue dev tools. It only shows when I press the 'vue refresh' button.

```
window.addEventListener('trix-change', (e) => {
    let description = e.target.inputElement.defaultValue;
//  Vue.set(this.listing, 'description', description)
    this.$set(this.listing, 'description', description)
});
```

**Comment by LinusBorg** [comment]
Further support on forum.vuejs.org, not on github issues.
