### ISSUE TITLE
Vue.js not detected in Chrome & Vivaldi

### ISSUE THREAD

**Issue by joaumg** [vuejs/vue-devtools#202]
Hello, and thanks for helping me out on this one:

I'm using a `non-minified` version of Vue from cdnjs (I also tried including it with bower, but no joy)
It's a rails app (`localhost:3000`) so no `file://`
Vue version `2.1.6`, and Vuex `2.0.0`
Tested in Chrome and Vivaldi, versions: `53.0.2785.101` and `54.0.2840.100`
My OS is `4.8.0-kali-amd64` (Kali Linux)

In both cases vue-devtools only shows up saying `Vue.js not detected`

Also, is there "any magical key" to also enable Vue-devtools in production (minified) sources?

Thanks :wink:

### Update 1:

Tested with another application (webpack), which uses (`localhost:9000`) and it works.

The Vue version of there is `2.0.1` and the Vuex is `2.0.0`.

Will continue to debug this.

### Update 2:

Downgraded the version on the Rails app, and it still goes undetected. (most likely there is some mistake in the app by now.)

### Final update:

Ok, this is an interesting finding.

The Vue components weren't being included, so there was no `new Vue` or not even no `new Vuex.Store` in the source code. (and as so, no component to inspect)

Which brings back the production question:

    Is there "any magical key" to also enable Vue-devtools in production (minified) sources?

**Comment by joaumg** [comment]
Tested with another application (webpack), which uses (localhost:9000) and it works.

The Vue version of there is 2.0.1 and the Vuex is 2.0.0.

Will continue to debug this.

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/api/#devtools

**Comment by joaumg** [comment]
@LinusBorg thanks ;D :tada:

**Comment by pjar** [comment]
I can see only `Vue.js not detected` too. It's also Rails app. My manifest file looks like this:

```
...
//= require ./lib/vue.js
Vue.config.devtools = true
```
After page loads I can see in console:

```
Vue.config.devtools
#=> true
```

Is it just looking for `vue.js` file in the sources? Vue is being bundled together with all other libs in a file not called `vue.js`

**Comment by cedricbdev** [comment]
Same issue here.
Setting the el property and wrapping the code in a window.onload function worked for me.
`window.onload = function(){
  var vm = new Vue({
    el: '#app'
  })
}`
