### ISSUE TITLE
Methods of objects in state lost when doing time-travel

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue-devtools#209]
I have an object named `quizzes` in the $store.state, which has a method called `remove()`. Normally I can access $store.state.quizzes.remove() as following:

![image](https://cloud.githubusercontent.com/assets/13058150/21466277/00c1df34-c9ff-11e6-874a-d9abde60a783.png)

But after I did time-travel like this:
![image](https://cloud.githubusercontent.com/assets/13058150/21466300/8a36e290-ca00-11e6-9855-6a7ca7667ba9.png)

I found the `remove` method is lost:

![image](https://cloud.githubusercontent.com/assets/13058150/21466301/9c87ed9a-ca00-11e6-849d-782200bc3c9a.png)

**Comment by simplesmiler** [comment]
Having methods in the state undermines many ideas of Vuex, including serializability of the state and ability to track changes to the state to make time travel possible. Mutations and actions is where you should put the behavior instead.

**Comment by beeplin** [comment]
Got it. Thanks~
