### ISSUE TITLE
data 高度太小  

### ISSUE THREAD

**Issue by zhangzan** [vuejs/vue-devtools#21]
![2015-11-04 7 05 57 2](https://cloud.githubusercontent.com/assets/3841321/10936408/808931a6-8327-11e5-854a-7342e9e606b6.png)

**Comment by yyx990803** [comment]
Hmm 你的 chrome 啥版本？

**Comment by zhangzan** [comment]
Chrome 版本 46.0.2490.71 (64-bit)
Chrome Canary 版本 47.0.2512.0 canary (64-bit) 都是同样 的问题

**Comment by yyx990803** [comment]
这不科学啊... 你的 OS X 版本是不是比较旧？

**Comment by zhangzan** [comment]
![1 pic_hd](https://cloud.githubusercontent.com/assets/3841321/10960097/905a1c82-83bb-11e5-8053-06c554bdff15.jpg)

**Comment by zhangzan** [comment]
![2015-11-05 12 50 35 2](https://cloud.githubusercontent.com/assets/3841321/10960145/46e7d9d0-83bc-11e5-923b-3afcd7bdd75c.png)

**Comment by yyx990803** [comment]
哦哦，明白了。。你是指那个 tooltip。。。。

**Comment by yyx990803** [comment]
1.0.2 已修正
