### ISSUE TITLE
Memory leak / crashing when handling rapid Vuex mutations

### ISSUE THREAD

**Issue by BartCorremans** [vuejs/vue-devtools#210]
I'm building an application which receives very fast updates via WebSocket (sometimes over 1000 per second). I'm also building a set of reusable modules for future applications, so I've made a store to handle my WebSocket connection, which commits a mutation every time it receives a message. Applications can dispatch an action to initialise the connection and use a plugin to listen for mutations in order to handle messages.

The problem I'm running into is that the Vuex devtools seem unable to process so many mutations so quickly. When I have the devtools enabled my browser tab will lock up in a matter of seconds while Chrome will keep using more and more memory.

Manually disabling Vuex integration by running devtools locally and commenting out the mutation hook (https://github.com/vuejs/vue-devtools/blob/master/src/backend/vuex.js#L12-L19) will prevent this from happening (but disable the mutation log of course).

If I get some spare time I might look into this further.

**Comment by yyx990803** [comment]
You can now turn off mutation logging in 3.0.

**Comment by pablougas** [comment]
How do you turn off mutation logging? I tried to create the logger inside vuex and turn it off that way but it does not. Having same issue currently
