### ISSUE TITLE
[Vuex] [Feature] Keep state on reload 

### ISSUE THREAD

**Issue by Be-ngt-oH** [vuejs/vue-devtools#215]
Issue #174 suggested to clean the mutation record on initialization which was added in PR #189 . I actually enjoyed being able to restore the state with one click after a page reload or when re-opening the dev tools. Would it be possible to make this a feature instead?

A solution could be as simple as checking for a flag prior calling reset in the [initialization mutation](https://github.com/vuejs/vue-devtools/blob/master/src/devtools/views/vuex/module.js#L19). The toggle for the flag could be added somewhere toe the vuex panel.

I think it's not a must-have since we have hot module replacement, but sometimes page reloads are necessary when working with elements that are added to the DOM via javascript (e.g. external plugins).

What do you think?

**Comment by BartCorremans** [comment]
Not necessarily on topic, but have you considered writing Vue components to work with these external plugins, so you can talk to them "the Vue way" and clean them up when the Vue component is destroyed? That way they'll play nicely with HMR.

**Comment by Be-ngt-oH** [comment]
Hi there,

You're right: I had already encapsulated the plugin nicely and just re-checked. Surprisingly it works quite nicely with the hot module replacement so my example from above does not really hold anymore (code is fluctuating a lot right now).

But anyway there are still situations where full reloads happen, for example when changing code referenced in the store.

**Comment by posva** [comment]
It makes sense to clean the mutation record when you reload the page. If you want to keep the state you should export it, reload the page, and import it

**Comment by Be-ngt-oH** [comment]
Please read closely what I wrote. I did not suggest to make this the default behaviour (because yes, cleaning the record make sense as the default). The export - reload - import cycle has bad UX and can't be applied when page reloads are caused externally (i.e. live reload).
Anyway, as I wrote before, it's not a crucial feature, so do as you like :-)

**Comment by posva** [comment]
oh sorry. Yes, I think having some options could be useful for some customisation in some specific behaviours. And this is definitely something that could go in
