### ISSUE TITLE
Empty devtools tab content after latest update

### ISSUE THREAD

**Issue by ksdev-pl** [vuejs/vue-devtools#218]
Hi

Weird thing after latest update (3.0.1 from the chrome web store) - the devtools tab content is empty for me:

![screenshot from 2017-01-05 18-52-05](https://cloud.githubusercontent.com/assets/4216259/21691389/b0c018ce-d378-11e6-854b-cedf7c8764e6.png)

95341fde886de7285e45611aeb689fd878653047 didn't have this problem. In next commits I started to get an error during `npm run build` ("localStorage is not defined"), so I'm not sure from which commit the problem started.

I'm on Debian Stretch, Chrome 55.0.2883.87.

**Comment by quagliero** [comment]
Similar for me, just a plain white box during `npm run dev` on devtools 3.0.1

macOS Sierra 10.12.2, Chrome 55.0.2883.95

**Comment by yyx990803** [comment]
@ksdev-pl are you building this from source yourself or are you just using it over the Chrome web store?

**Comment by ksdev-pl** [comment]
I have removed the unpacked extension that I've used and installed the devtools from chrome web store. The tab with this extension was empty, so to check what is happening I've disabled the extension from chrome web store, cloned the repository and `npm run dev` it to load unpacked extension. The unpacked extension also was empty. So I started to checkout commits to see which one is last working; the 95341fd works for sure, in next commit I've had a problem during build.

**Comment by ksdev-pl** [comment]
The `npm run dev` on master looks correctly for me on http://localhost:8080/, but when I `npm run build` on master and load unpacked extension (or use the extension from chrome web store), the tab is empty.

**Comment by yyx990803** [comment]
It most likely has to do with your application. Try replacing `shells/dev/target` with your application (may need configuration changes) and then `npm run dev` to see what errors you get.

**Comment by ksdev-pl** [comment]
I thought about that - so I've removed the unpacked extension again and installed official extension from the chrome shop - and used it on https://vuejs.org. Still the tab content is empty.

Maybe it's just some hard to debug problem related to my configuration, let's wait. I can try to debug it of course, I just need some tips what to do because I don't know much about debugging chrome extensions (I will try what you have written with `shells/dev/target` to be sure).

**Comment by yyx990803** [comment]
Hmm that's weird indeed, I'm suspecting it maybe a different issue from what @quagliero is running into. Maybe something with Linux Chrome only...

**Comment by quagliero** [comment]
It doesn't work for me even on the https://vuejs.org/v2/guide/ site. Must be browser or ad blocker related then, rather than something within my own application.

**Comment by ksdev-pl** [comment]
Can be, I will install the devtools on windows and on another linux vm and will let you know.

**Comment by yyx990803** [comment]
Do you happen to have any sort of security settings that prevents access to `localStorage`?

**Comment by ksdev-pl** [comment]
Ublock origin + ublock origin extra, but I've disabled them to test if it is related, without success. But maybe it's something else? I need some time to check it in a pure chrome on another linux. In windows 10 chrome it works without problem.

**Comment by quagliero** [comment]
@yyx990803 Yeah, just figured it out. Chrome's "block 3rd party cookies and site data" will prevent it from working. Untick and all is fine.. so may have to add an exception for it (if possible).
![screen shot 2017-01-05 at 20 44 50](https://cloud.githubusercontent.com/assets/4254570/21696921/fca741fe-d387-11e6-9ea5-4d346b32c7e0.png)

**Comment by ksdev-pl** [comment]
Thank you quagliero! It works.

But it would be nice to have a possibility to block the third party cookies ;) Or maybe exceptions will work, indeed, must try.

**Comment by yyx990803** [comment]
Yeah I think I just need to add a try catch for localStorage access.

**Comment by quagliero** [comment]
Thanks @yyx990803 👍

**Comment by ksdev-pl** [comment]
Sorry, did not see the question. After update it works with third-party blocked, thanks!
