### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by gridsystem** [vuejs/vue-devtools#227]
Installed from Chrome web store. Let me know if I can provide further info.

![screen shot 2017-01-08 at 1 47 03 pm](https://cloud.githubusercontent.com/assets/2365737/21750343/fde9d978-d5a8-11e6-8c61-2bdfbd3f30a5.png)

**Comment by LinusBorg** [comment]
Haev you tried re-installing it? Do you see any errors in the console? What's your chrome version?

**Comment by samrose3** [comment]
I am getting the exact same issue. I have tried reinstalling and do not see any console errors.  
I am using Chrome 55.0.2883.95 (64-bit)

**Comment by posva** [comment]
@gridsystem Couldn't reproduce. Did you try clearing your cache after uninstalling and installing again or rebooting?

**Comment by gridsystem** [comment]
Google Chrome	55.0.2883.95 (Official Build) (64-bit)

I have rebooted, uninstalled and reinstalled from extensions store and the problem persists. How would I clear the cache for the devtools?

Is there a particular icon font being used? I may have a conflicting font on my system?

**Comment by posva** [comment]
@gridsystem The material icons is being used. Can you check on the network and sources panels? https://github.com/vuejs/vue-devtools/blob/d8b9a84057a348244f887e273c45230c12ae3ca4/src/devtools/global.styl#L7

**Comment by gridsystem** [comment]
It's not being loaded, the only thing in both of those panels is backend.js

![screen shot 2017-01-19 at 12 37 41 pm](https://cloud.githubusercontent.com/assets/2365737/22107115/18a1fbda-de44-11e6-9265-9e48d754dccb.png)

**Comment by gridsystem** [comment]
Disabling a local copy of materialicon-regular fixed the issue.

**Comment by posva** [comment]
@gridsystem Ok, thanks maybe we shouldn't rely on local copies of the fonts

**Comment by gridsystem** [comment]
I updated my installed copy of the font to the .ttf from the latest stable version from http://google.github.io/material-design-icons/ and re-enabled the font. It works fine. Presumably I was using an older version without the characters vue-devtools uses.

**Comment by samrose3** [comment]
I installed a local copy of the material icon font and re-installed the extension. Still isn't working properly for me. Any suggestions?

**Comment by gridsystem** [comment]
@samrose3 Which file did you install?

**Comment by samrose3** [comment]
`MaterialIcons-Regular.ttf`

**Comment by gridsystem** [comment]
From the page I linked above? Do you have any font duplicates in Font Book?

**Comment by samrose3** [comment]
Removed the font, then re-installed. Now it works 🙌

**Comment by gridsystem** [comment]
@posva quick fix would be to rename the file in the devtools.
