### ISSUE TITLE
Vue 1 (1.0.24) multiple Vuejs instances on same page

### ISSUE THREAD

**Issue by RedLucas** [vuejs/vue-devtools#234]
For some reason, if I have multiple Vuejs instances on the same page, the Root elements get merged together in the Devtools. (We are rolling Vuejs into our project slowly, so that's why we have multiple instances). 

![screen shot 2017-01-11 at 1 52 06 pm](https://cloud.githubusercontent.com/assets/8796324/21867932/4902c646-d805-11e6-8aa4-9af2044f498f.png)

**Comment by RedLucas** [comment]
Upgraded to 1.0.28 to eliminate the possibility that it's the issue, but nothin...

**Comment by posva** [comment]
If you introducing Vue progressively you should add Vue 2 instead. It works fine with Vue 2.
PRs to fix this are welcome but I think this is probably going to be a wontfix

**Comment by guidobouman** [comment]
@posva We're running Vue2 on our project, and still have this issue. See #98.

**Comment by guidobouman** [comment]
Btw, fixed by https://github.com/vuejs/vue-devtools/pull/292 as well.

**Comment by michalsnik** [comment]
I also think this should rather be a wontfix @posva and we should close this issue, as it works properly with Vue 2 :)
