### ISSUE TITLE
Vue.js not detected

### ISSUE THREAD

**Issue by g-patel** [vuejs/vue-devtools#236]
**Setup**

- Running the page at localhost:3070/* url, so http protocol, not file:// protocol.
- Using development version on my page as follows:
```<script src="https://unpkg.com/vue@2.1.8/dist/vue.js" type="text/javascript"></script>```

![image](https://cloud.githubusercontent.com/assets/12045773/21951277/21cf6b6e-d9b9-11e6-9143-1836cf5278b2.png)
- Chrome extension setting: 
![image](https://cloud.githubusercontent.com/assets/12045773/21951364/11ca0638-d9ba-11e6-8a6b-519da312b7fb.png)
- Chrome version: Version 55.0.2883.95 (64-bit) on macOS Sierra

In the console:
![image](https://cloud.githubusercontent.com/assets/12045773/21951403/9040bb4c-d9ba-11e6-8a68-00ab6b93533a.png)

**Comment by g-patel** [comment]
Actually, I see it in the chrome dev tools pane, but I got confused by the fact that it says `Vue.js not detected` when I click on grey Vue icon in the "Chrome Menu".

**Comment by g-patel** [comment]
Closing this since I can debug using the dev tools pane.

**Comment by Haprog** [comment]
I also spent an hour or two trying to figure out why Vue Devtools toolbar button in the Chrome Menu always stays grey and says `Vue.js not detected` when clicked until I found this closed issue.

It looks like the Vue pane shows up in the dev tools anyway at least for localhost and the Vue guide/docs where Vue is loaded.

The issue still persists though and should be fixed, so that the button also states that Vue is detected (when it actually is), because otherwise it is very confusing to new users. So I suggest to reopen this issue.

For some reason though the Vue pane doesn't seem to show in JSFiddle with the [Hello Vue example](https://jsfiddle.net/chrisvfritz/50wL7mdz/). Maybe this should be opened as another issue?

**Comment by posva** [comment]
> or some reason though the Vue pane doesn't seem to show in JSFiddle with the Hello Vue example. Maybe this should be opened as another issue?

No, that's normal, it's on an iframe

If you can boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO), feel free to open a new issue

**Comment by Dorian** [comment]
I get 'Vue.js not detected' for a simple `index.html` file with:

```html
<script src="https://unpkg.com/vue"></script>

<div id="app">
  <p>{{ message }}</p>
</div>

<script>
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  }
})
</script>
```

**Comment by Akryum** [comment]
@Dorian https://github.com/vuejs/vue-devtools#commom-problems-and-how-to-fix

> Fixing "Download the Vue Devtools for a better development experience" console message when working locally over file:// protocol: 1.1 - Google Chrome: Right click on vue-devtools icon and click "Manage Extensions" then search for vue-devtools on the extensions list. Check the "Allow access to file URLs" box.

**Comment by caglaror** [comment]
I experienced the same. Simply solve by adding js files (as vue.js ) at the end of the html codes. I think rendering order is going wrong somehow.

**Comment by steveross1975** [comment]
@Akryum Thank you mate! I solved the issue with your help!

**Comment by peterchaula** [comment]
Restart the browser after installing Vue devtools

**Comment by InnocentPuff** [comment]
If your not using a server, then you might have a url with **file://your_file_location.html**. In chrome this can be fixed by right clicking on _Vue JS icon, -> Manager Extensions_ and under Vue JS Extension there will be option to _allow access to file URL_. Refresh your page and this should solve this problem (at least on chrome).

**Comment by thuannp95** [comment]
@InnocentPuff I used server but it didn't work. I used laragon

**Comment by chendoly** [comment]
When i check the "Allow access to file URLs" box and open again the index.html with
```
<script src="https://unpkg.com/vue"></script>
<div id="app">
		<p>{{message}}</p>
	</div>
	<script>
		var app = new Vue({
			el:'#app',
			data:{
				message:'Hello Vue.js!'
			}
		})
	</script>
```

the Vue Devtools toolbar button is on

![22](https://user-images.githubusercontent.com/4989999/38545585-ec851b6a-3cdc-11e8-8ac1-dda050af8fff.png)

**Comment by dingb** [comment]
I came across this same issue, after I upgrade Chrome and restart Chrome, it works fine.

**Comment by thevruno** [comment]
I solved this problem with right clicki on the Vue icon, managing extension, click on 'Allow access to file URL'

 F5 in your project and ready. Cheers. 👽

**Comment by taoliujun** [comment]
> @Dorian https://github.com/vuejs/vue-devtools#commom-problems-and-how-to-fix
> 
> > Fixing "Download the Vue Devtools for a better development experience" console message when working locally over file:// protocol: 1.1 - Google Chrome: Right click on vue-devtools icon and click "Manage Extensions" then search for vue-devtools on the extensions list. Check the "Allow access to file URLs" box.

Not working after i done like this. `Vue.js not detected` happened when:
1. Url is `http://127.0.0.1:8081`
2. vue.js script url is `https://cdn.jsdelivr.net/npm/vue@2.5.16/dist/vue.js`
3. console `Vue.config.devtools` was `true`

**Comment by yarcowang** [comment]
Yep, I have the same problem... I'm using the file generated by `vue build <file>.vue` and with `https://cdn.jsdelivr.net/npm/vue/dist/vue.js`...
![Admin___Math_Problem](https://user-images.githubusercontent.com/1576504/60396950-5ff94d80-9b7a-11e9-9906-33474e987aff.png)

**Comment by tomhanlon** [comment]
Thanks @Akryum

**Comment by hungcg** [comment]
I came across this same issue and i resolved it following Akryum's comment, but I need to do that step:
https://github.com/vuejs/vue-devtools/issues/445#issuecomment-340376475
> Close the devtools and reopen them
> Vue devtools only appear when Vue is detected, that way you can drag it upfront and it will not bother you when developing non-vue apps
