### ISSUE TITLE
vue-devtools in CEF

### ISSUE THREAD

**Issue by undavide** [vuejs/vue-devtools#237]
Hi,
I'm using Vue.js in a web application running within an instance of the Chromium Embedded Framework (CEF) – FYI I'm talking about a Photoshop HTML Panel (some Adobe's applications use CEF in their extensibility layer).
In that context, debugging is done connecting Chrome to a specified port of localhost, so that we can use the Chrome Dev Tools:

![image](https://cloud.githubusercontent.com/assets/5939127/22174652/08cb7bea-dfe4-11e6-8cba-54e581a728d1.png)

Problem is that Chrome has Dev Tools as *the* displayed/only page in the browser (for the actual HTML/JS is hosted in Photoshop), and if you try to run the Vue Devtool, it obviously complains because it can't *see* any Vue action going on in there.

As far as I get it, Vue Dev Tool is inspecting Chrome Dev Tools as the only page available, and of course it gets mad. Do you think there is a way to successfully use Vue Dev Tool in this peculiar context? I had the very same problem back in the day I used Angular, with the Batarang extension – I'm afraid it might be an architectural issue, but it's worth asking nonetheless.

Thank you!

**Comment by ciddan** [comment]
@undavide CEF currently doesn't support Chrome extensions. Source: https://bitbucket.org/chromiumembedded/cef/issues/1947/add-support-for-chrome-extensions
Plus I don't know that you'd be able to fix your use case even if it did, since the Adobe application hosts and controls the particular CEF instance.

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.
