### ISSUE TITLE
Right click to inspect component

### ISSUE THREAD

**Issue by scottbedard** [vuejs/vue-devtools#242]
The feature I'm requesting is a context menu button to inspect a component. It can be annoying having to walk down your component tree to get to the one you want to inspect. We should be able to set up a context menu to walk up the dom tree until it finds an element that is being managed by our Vue app. If this feature is acceptable, I'll take a crack at it.

**Comment by posva** [comment]
I think this is a good idea. It'll definitely make the DX better.
Just to make sure, you're talking about this, right?:
<img width="337" alt="screen shot 2017-01-28 at 13 18 33" src="https://cloud.githubusercontent.com/assets/664177/22396536/5318cbda-e55c-11e6-83a7-e7a1b861f065.png">

Let me ask the contributors first, but I don't see a reason for this not to exist 🙂

**Comment by scottbedard** [comment]
@posva yes, that is what I'm describing :)

**Comment by Herteby** [comment]
Yes, just like you can right click to inspect the DOM!

**Comment by MSCAU** [comment]
I thought I saw this working a few weeks ago but don't see that option anymore (eg. Chrome context menu on Windows 10)...

**Comment by tobiasfeil** [comment]
> I thought I saw this working a few weeks ago but don't see that option anymore (eg. Chrome context menu on Windows 10)... Ah. I see it now, under Ctrl+1 Switch to components in DevTools.

Thank you for highlighting this @MSCAU. I think it would we worthwile making it possible to do this without having to have the components view open - I was surprised a minute ago why the option wasn't there, searched on the Internet and came across this thread - it would be awesome for the option to just always be there.
