### ISSUE TITLE
Dev Tools does not work on chrome-extension:// protocol

### ISSUE THREAD

**Issue by mabumusa1** [vuejs/vue-devtools#244]
I am developing a chrome extension one the content pages is based on Vue.JS, when I try to use the devtools it says that vue.js is not detected. 

I think devtools do not work on chrome-extension:// protocol, what would be the solution to solve this issue to make it work within this protocol.

I will keep searching for solutions but if you have any suggestions I would appreciate the discussion

**Comment by posva** [comment]
Closing in favour of #130
