### ISSUE TITLE
Events are not shown in Devtools

### ISSUE THREAD

**Issue by mark-vesterskov** [vuejs/vue-devtools#245]
**Vue version:** 2.1.10
**Chrome version:** 56.0.2924.87

I have an application i have been working on for a couple of months, and just recently, the Events tab in Devtools has stopped working. I can navigate to the tab, but no events are shown in it.

The events work fine, as my application is still functioning as expected, i just have a real hard time debugging it, because i cannot see the events in the Devtools.

My setup is a global Event instance, which is initialized in my bootstrap.js before the components are loaded, and the App Vue initialized.

`window.Event = new Vue();`

..`Vue.components` loaded..

`const app = new Vue({
    el: '#app'
});`

Event are `$emit`ed and `$on`ed using `Event.$emit` and `Event.$on`. 

I'm building the app using Laravel Mix, which is a wrapper for Webpack.

I've tried reinstalling the devtools, updating Chrome, and pretty much everything else i could think of.

**Comment by posva** [comment]
Can you provide a repro please, use this template: http://codepen.io/pen?template=PWbYJO
I tried to reproduce with no luck: http://s.codepen.io/posva/debug/ygqBrp/DqrDdVxQyJdr

**Comment by mark-vesterskov** [comment]
http://s.codepen.io/markvesterskov/debug/NdBKZj/PBMNWGQpmmWr

Works here as well, which makes it doubly strange that it doesn't in my setup.

**Comment by posva** [comment]
Ok, I'll close this but feel free to ping me here once you have a repro 🙂

**Comment by mark-vesterskov** [comment]
On further research it seems to have something to do with the webpack output; because replacing the webpacked Vue with the CDN one, and everything works. I'll keep researching.

**Comment by mark-vesterskov** [comment]
OK, culprit found.

When using Laravel Mix' extract function, events do not show up in the developer console. Omitting the extract function, and the events show up. I'll create an issue on the Mix repo.

**Comment by pilsoftTeam** [comment]
@mark-vesterskov did you guys found a solution ?

**Comment by mark-vesterskov** [comment]
@pilsoftTeam Unfortunately no. For now, i've disabled extract while in development, although it feeld like a workaround.

**Comment by pilsoftTeam** [comment]
@mark-vesterskov Ok . Thanks

**Comment by innominata** [comment]
@mark-vesterskov How did you disable it? I can't find it mentioned in the configs, however I have the exact same issue.

**Comment by mark-vesterskov** [comment]
@innominata I just commented out the `.extract` line from my mix config - I'll readd it when going to production.

**Comment by valmb** [comment]
Have same issue, no .extract in my config. Or I cant find it. Could you add details how to find '.extract' ?

**Comment by flamytwista** [comment]
Same problem.
Problem appears with laravel mix and with clear webpack.

Vue version: 2.4.2
Vue.js devtools 3.1.6
Chrome version: Version 61.0.3163.79 (Official Build) (64-bit)
Windows 10

**Comment by valmb** [comment]
@flamytwista 
My issue was with bad vue-tinymca package, that was containing vue 2.1 compiled inside.
So, I was getting 'Vue detected' twice in console. Once have fixed that, events appeared on the panel.

**Comment by saintplay** [comment]
I ran in this issue, I figured out
if you are using two version of vue in your application, say `vue.esm.js` and `vue.js`
events won't show on vue.devtool panel

**Comment by Fierozen** [comment]
> What is the easiest way to tell if you have two versions of vue in your application?

**Comment by eliranmal** [comment]
@Fierozen, you can check the **sources** tab of your favored browser's dev-tools. search `vue.esm` and look for duplicates.

**Comment by pleek91** [comment]
@eliranmal how did you fix that?

**Comment by eliranmal** [comment]
@pleek91 - i didn't have to - my app did not need the store eventually.

but i presume you could fix it if you point the `vue` alias (e.g. via webpack) to a fixed release, like `vue.runtime.esm.js`. that way, every time you import `vue` in the source code, the resolved module will be the same one.
