### ISSUE TITLE
Toggling child element of root component will hide root component in component tree 

### ISSUE THREAD

**Issue by egoist** [vuejs/vue-devtools#246]
You can repro this in official webpack template, simply update `./src/App.vue` to:

```vue
<template>
  <div id="app">
    <h2 v-if="user">{{user}}</h2>
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {user: null}
  },
  created () {
    // and it's weird that only set `this.user` asynchronously will trigger this bug
    setTimeout(() => {
      this.user = 'egoist'
    })
  }
}
</script>
```

*For quick repro, just create `App.vue` with the code above and run `vue build App.vue`*

Then open chrome devtools, switch to `vue` tab, you will see something like:

<img width="255" alt="2017-02-06 9 43 11" src="https://cloud.githubusercontent.com/assets/8784712/22649346/7cc4d752-ecb5-11e6-9a16-1ea36f93211b.png">

Instead of the expected one:

<img width="397" alt="2017-02-06 9 44 36" src="https://cloud.githubusercontent.com/assets/8784712/22649361/88beb474-ecb5-11e6-9865-ab033b9f2396.png">

**Comment by posva** [comment]
A simple repro on codepen to make sure it doesn't depend on the webpack build: http://s.codepen.io/posva/debug/jypEbJ/yYryLYmemZOM

**Comment by yyx990803** [comment]
This is actually a bug in Vue core: the child component overwrites the `__vue__` reference of the parent because they share the same element. Let's open it in the core repo instead.
