### ISSUE TITLE
Dynamic module registration does not refresh state

### ISSUE THREAD

**Issue by trunda** [vuejs/vue-devtools#247]
When [dynamic module registration / unregistration](https://vuex.vuejs.org/en/modules.html#dynamic-module-registration) is used, change of the state is not reflected in Vuex view (I know that is probably because it is not a mutation). 

This is the problem, when you want to use time travel feature - one mutation back takes you into inconsistent state.

**Comment by posva** [comment]
Why would it take you to an inconsistent state? If the module didn't exist, it normal for the state not to be there.

Can you, please, provide a repro using this template: http://codepen.io/pen?template=PWbYJO

**Comment by posva** [comment]
Closing, inactivity

**Comment by trunda** [comment]
I am sorry for inactivity, I was on vacation. You can let it go, it was my bad, I was going to write you back to close this issue.
