### ISSUE TITLE
Not detected vue in nwjs

### ISSUE THREAD

**Issue by sarik93** [vuejs/vue-devtools#249]
nwjs version after 0.18.8 have a problem before this version all work.
vue-devtools 3.0.6_0

Reproduction Link
Simple Project nwjs + vue - https://github.com/sarik93/simple-nw-vue-example

Steps to reproduce
npm install -g nw@0.19.0-sdk
run: nw -load-extension=full_path_to_vue-devtool
In window open chrome devtools
Click in vue tab

What is Expected?
vue-devtool detected Vue instance in page

What is actually happening?
Now vue-devtool is empty, not detect instance Vue.

I tested in colleagues Mac and Linux, the result is the same.
In nw version 0.19.0 update Chromium to 55.

**Comment by f3l1x** [comment]
Same by me. Nwjs 0.20.3 (sdk), vue-devtools 3.0.8, vue 2.1.0.

**Comment by f3l1x** [comment]
@posva Any hints/tips how to accomplish this ticket?

**Comment by posva** [comment]
You can maybe inspire yourself from other devtools that work on nw, maybe react? But I cannot help  you further

**Comment by Goopil** [comment]
To use vue devtools in a nw app.

```
// manifest.json
  "chromium-args": "--load-extension='./devtools'",
  "webkit": {
    "plugin": true
  }
```
```
//main.js
import Vue from 'Vue'
import App from './App.vue'
import store from './store'

window.Vue = Vue // the vue dev tools look for the global vue package. just assign it to the window

new Vue({
  el: '#app',
  render: h => h(App),
  store
})
```

**Comment by f3l1x** [comment]
@Goopil Thank you, I'll test it.

**Comment by oaleynik** [comment]
Vue tab works just fine if open devtools via CMD+ALT+I or via top app menu. When devtools opened via right click context menu - Vue tab doesn't work.

**Comment by f3l1x** [comment]
@Goopil I'have tested it and it works;

- NW.js 0.25.0 
- Vue.js 2.4.2
- Vue-Dev-Tools 3.1.4
- Webpack 3.5.5

![developer tools - chrome-extension --pmagnoncdfmcnflnlmcmjhgdlldbippp-dist-manager html_007](https://user-images.githubusercontent.com/538058/30198447-0c4d6ed8-946e-11e7-9dd3-cd11b4523538.png)

**Comment by frankhale** [comment]
Any idea how to get Vue Devtools to work when your app is loaded in a webview? Currently the devtools load but Vue is never detected. Additionally Vue Devtools always complains that the app is in dev mode even when it's not.

**Comment by foolishchow** [comment]
in nwjs webView    `chrome.devtools.inspectedWindow.tabId`  got `null` , so there will no message between the `app context`  and `backend` .
may be you have to modify the code  , implement this code like [shells/dev/src/devtools.js](https://github.com/vuejs/vue-devtools/blob/master/shells/dev/src/devtools.js)
enjoy~

**Comment by rogerwang** [comment]
support for chrome.devtools.inspectedWindow.tabId in webview in NW was just added in git. It will be available in the next nightly build.

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.

**Comment by TheJaredWilcurt** [comment]
We've updated the NW.js documentation to show how to get the latest Vue-DevTools in NW.js.

* [docs.nwjs.io/en/latest/For Users/Debugging with DevTools](http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools)

**Instructions:**

1. `npm install --save-dev nw-vue-devtools`
1. Add this to your `package.json`:
   * `"chromium-args": "--load-extension='./node_modules/nw-vue-devtools/extension'",`
1. Vue.js must be in use in your app, and cannot be minified (use `vue.js` not `vue.min.js`).

**For more information:**

* https://github.com/TheJaredWilcurt/nw-vue-devtools#readme

@sarik93 @f3l1x @Goopil @oaleynik

**Comment by f3l1x** [comment]
Thanks @TheJaredWilcurt. I'm using it right the same way. Thank you anyway.
