### ISSUE TITLE
walk() never stops and raises Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andreiglingeanu** [vuejs/vue-devtools#251]
I'm getting this error when devtools try to [scan](https://github.com/vuejs/vue-devtools/blob/66e318a554de79aadc50b39a0c0722c87f94a724/src/backend/index.js#L94) the whole [document](https://github.com/vuejs/vue-devtools/blob/66e318a554de79aadc50b39a0c0722c87f94a724/src/backend/index.js#L98-L115), looking for root level Vue instances.

```javascript

Uncaught RangeError: Maximum call stack size exceeded.
    at walk (index.js:142)
    at iterator (index.js:138)
    at walk (index.js:142)
    at iterator (index.js:138)
    at walk (index.js:142)
    at iterator (index.js:138)
    at walk (index.js:142)
    at iterator (index.js:138)
    at walk (index.js:142)
    at iterator (index.js:138)

```

The thing is that I have a very large DOM structure (which is not entirely composed by Vue) and I'm loading one single Vue component asynchronously, with webpack and I `$mount` it somewhere on the page, also in a dynamic fashion.

The most interesting thing is that when I skip `$mount` for my component, the `walk()` function doesn't execute infinitely. I've tried to understand what's the logic behind the [`stop`](https://github.com/vuejs/vue-devtools/blob/66e318a554de79aadc50b39a0c0722c87f94a724/src/backend/index.js#L128) [callback](https://github.com/vuejs/vue-devtools/blob/66e318a554de79aadc50b39a0c0722c87f94a724/src/backend/index.js#L99-L114) but without too much success. I understand that my DOM nodes are storing vue instances as `__vue__` properties and they are indeed in place - I've checked that via manual inspection.

And, really, I can't seem to do anything special in my components that will make `walk()` to behave in such a way.

Any help is highly appreciated!

**Comment by posva** [comment]
Hey, can you boil down the error using this template http://codepen.io/pen?template=PWbYJO ?
I'll take a look

**Comment by andreiglingeanu** [comment]
This thing is hard to spot, I didn't understand why it breaks for me...

Still can't get a consistent reproduction, sadly.

**Comment by andreiglingeanu** [comment]
I figured out, by try and fail, that ba9a836c49e947bd2556e90eef786649c2c5e683 was the cause of the error.

But, I never used dev version of the extension and I was using the one from Chrome Store. Do you guys managed to release a version that has latest master into it without publishing a new tag?

cc. @danieldiekmeier @yyx990803

**Comment by andreiglingeanu** [comment]
Just confirmed. Yesterday, 14 february, was release `3.0.7` version which behaves like that.

**Comment by yyx990803** [comment]
Do you have Custom Elements that have Shadow DOM on the page?

**Comment by andreiglingeanu** [comment]
@yyx990803 Nope, I'm not.

**Comment by yyx990803** [comment]
Well that's quite weird. I just published 3.0.8 which (in fixing another issue) rewrote the commit you identified - let me know if that happens to address your issue when it's updated.

**Comment by andreiglingeanu** [comment]
Bingo, Thank you!

4ad6d6b7ca3585ae11d6b4ba803af4f8e5926241 did it. Looks like `for` loops work better than `forEach` for DOM nodes in some edge cases.

**Comment by yyx990803** [comment]
Great!
