### ISSUE TITLE
can vue-devtools support data variable search feature(similar to search component)?

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue-devtools#252]
For a bigger project, there will be pretty much data items, it is a little boring to find a variable and see how it changes during app testing.
Can vue-devtool support a feature of searching data variables similar to searching component?

thanks!

**Comment by bartlomieju** [comment]
I'll happily do it once #261 is merged

**Comment by posva** [comment]
This was actually added in #261

**Comment by cnweibo** [comment]
great, it works as a dream now. Development with vue-devtool and vue is an interesting job!
thanks to vue team
