### ISSUE TITLE
Uncaught TypeError: e.childNodes.forEach is not a function     backend.js:1

### ISSUE THREAD

**Issue by symfonycoda** [vuejs/vue-devtools#253]
Hi

I am using VueJS and Laravel 5.3, and have been creating some Notifications using Pusher. 
Everything seems to be working ok, except when I use the Chrome devtools and click on the Console tab, I get the following red text:

Uncaught TypeError: e.childNodes.forEach is not a function

So far it hasn't affected the working of any of my functions, but I can not see my components in the devtool Vue tab

I have no childNodes in my code, and I do not have a file called backend.js that I can find, so I think this file is in the devtool.

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this template http://codepen.io/pen?template=PWbYJO ?
Thanks!

**Comment by jpommerening** [comment]
Regarding repro: http://codepen.io/anon/pen/JEzZLP
I had to open the inner iframe though, because the Devtool didn't kick in with the codepen frame around it.

**Comment by yyx990803** [comment]
Are you using an older version of Chrome? e.g. <52?

**Comment by symfonycoda** [comment]
The update worked. thanks guys. most impressive, I hadn't even got to uploading my code and you have fixed it. You have no idea how much that kind of efficiency helps. Good job!

**Comment by jpommerening** [comment]
@yyx990803, yup, old indeed 😅
