### ISSUE TITLE
unnamed component's tag name shows as its file path

### ISSUE THREAD

**Issue by UncleBill** [vuejs/vue-devtools#256]
## env
- chrome  56.0.2924.87
- vue 2.1.10
- vue-devtools 3.0.8

## screenshot

![image](https://cloud.githubusercontent.com/assets/1141198/23017277/926aa20a-f474-11e6-9f52-82e89acb0b1f.png)

Naming `<ProgressBar>` 
```javascript
{
name: 'progress-bar'
}
```
![image](https://cloud.githubusercontent.com/assets/1141198/23017062/d2319ee4-f473-11e6-944e-33e9dcb0aad9.png)

fix this tag.

**Comment by posva** [comment]
I couldn't reproduce using webpack. Can you please provide a **minima** repro for this? Thanks!

**Comment by UncleBill** [comment]
>Can you please provide a minima repro for this?

I can't now. It was OK yesterday. And it just happened with none **config** changed.
I will try reverting my code base.
PS: I use the official boilerplate [vuejs-templates/webpack](https://github.com/)  (webpack@v1)

**Comment by posva** [comment]
tested both v2 and v1 template on OSX and works nicely.
It don't have to be right now 😄 Doing it in the following days is just fine

**Comment by UncleBill** [comment]
OK! Thanks for reply!

**Comment by posva** [comment]
I just run `yarn dev` in windows and it happens

**Comment by posva** [comment]
@yyx990803 So the `basename` fn from the `path` package (which is different from the node one) is not doing its job. Do you know where is that package so I can open an issue there? I searched in the webpack repo with no luck.
We can also use a replace on the file `file.replace(/^[a-zA-Z]:/, '').replace(/\\/g, '/')` to temporaly fix this or use a path browser package like https://github.com/snowyu/path.js

**Comment by yyx990803** [comment]
@posva hmm, looks like Webpack's `path` shim is not OS-agnostic. We can just use a better `basename` fn instead.
