### ISSUE TITLE
vue data accessible to vue-devtools even in production on a laravel spark installation

### ISSUE THREAD

**Issue by EventFellows** [vuejs/vue-devtools#257]
I am using vue 2.1.10  and did run the `production` flag

**Comment by posva** [comment]
You should open the issue in that project instead.

The way it works is by replacing `process.env.NODE_ENV` with `'production'`. With webpack we use `DefinePlugin` to do it.

There's also an `devtools` option: https://vuejs.org/v2/api/#devtools in Vue to disable it.

Hope it helps to solve the issue on the build process of laravel spark 🙂
