### ISSUE TITLE
Please update the version in npm

### ISSUE THREAD

**Issue by niceue** [vuejs/vue-devtools#266]
The current version of vue-devtools in npm is outdated at “2.3.1-beta1”.
https://www.npmjs.com/package/vue-devtools

I use vue-devtools in electron by the fowllowing code, and need npm install this module
```javascript
if (isDev) {
  BrowserWindow.addDevToolsExtension(path.join(__dirname, '../node_modules/vue-devtools'))
}
```

**Comment by LinusBorg** [comment]
ping @yyx990803

**Comment by yyx990803** [comment]
Hmm, that package is not published by us. It's maintained by a 3rd party user.

In fact we never intended to publish this as an npm package, but maybe we can incorporate that for Electron users?

**Comment by LinusBorg** [comment]
Oh, didn't even check, assumed it was ours ...

Yeah, sounds like a good idea.

**Comment by niceue** [comment]
April Fool's Day comes early ! :sob: 
@zce

**Comment by zce** [comment]
[9cd19ef](https://github.com/zce/vue-devtools/commit/9cd19ef84b97419270c1ee631e0a0d3cb43ce8cc)

**Comment by niceue** [comment]
@zce thx! I have used the latest version
I install the vue-devtools in main process just once. My code can also work

**Comment by zce** [comment]
👌

**Comment by yyx990803** [comment]
@zce thanks! Would you interested in creating a PR so that we can publish the npm version from here on new releases?

**Comment by zce** [comment]
@yyx990803 👌

**Comment by Akryum** [comment]
@zce Any news on this? 😄

**Comment by Akryum** [comment]
Use the [electron app](https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md)

**Comment by zce** [comment]
@yyx990803 I can transfer `vue-devtools` to you if you like

**Comment by LinusBorg** [comment]
@zce thanks! 

maybe write him on Twitter, mentioned in closed github issues tend to get drowned out.

**Comment by Akryum** [comment]
We are now using scoped npm packages.
