### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by eliurkis** [vuejs/vue-devtools#267]
I am having this issue **only** when I start recording the events.

Hard to reproduce.

![image](https://cloud.githubusercontent.com/assets/59236/23231048/5532af78-f914-11e6-8872-936e73d5f07f.png)

**Comment by posva** [comment]
Hey, I see the error is happening in vue-multiselect.
Please, take the time to debug further and provide a repro. Otherwise we cannot help. You can use this [template](http://codepen.io/pen?template=PWbYJO)
Thanks!

**Comment by posva** [comment]
Closing, inactivity
