### ISSUE TITLE
vue.js not detected when using devtools with chrome extension pages

### ISSUE THREAD

**Issue by JonathanLouw** [vuejs/vue-devtools#268]
Vue Devtools doesn't work on chrome extension pages it says 'Vue.js not detected' in the popup. 

for vue to even work in my extension I had to add a content security policy, I don't know if this is what's stopping it from being detected but I'll include the string here anyway just incase:
> `"script-src 'self' 'unsafe-eval'; object-src 'self'"`

example of extension page url
> `chrome-extension://<EXTENSIONID>/manage.html`

So far I've tried:

- enabling _Allow access to File URLs_

- set `Vue.config.devtools` to `true`

and still it's not detecting vue.js

**Comment by posva** [comment]
Dup of #120

**Comment by ppKrauss** [comment]
**Is a bug**, please see https://stackoverflow.com/q/49196181/287948

**Comment by torarnv** [comment]
This is still an issue. Using Vue in a Chrome extension, eg: `chrome-extension://<hash>/app.html`, results in `Vue.config.devtools` being true, but `devetools` is undefined, resulting in this message on every reload:

```
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
```

The Vue devtools button is grayed ut, and says "Vue.js not detected" when clicking it.

**Comment by monomente** [comment]
Trying to follow the [first introductory tutorial](https://www.vuemastery.com/courses/intro-to-vue-js/vue-instance/) and they are using vue in jsfiddle /w chrome extension just fine in their video, but in my hands I cannot launch the console and get a "Vue.js not detected" popup when I click the chrome extension.  Not sure what the discrepancy could be.

**Comment by angelhearted** [comment]
Enabling extension's "Allow access to file URLs" did the trick for me.
