### ISSUE TITLE
Root component disappears in specific situation

### ISSUE THREAD

**Issue by posva** [vuejs/vue-devtools#269]
repro:  https://codepen.io/skyrpex/pen/mwmJRe?editors=1010 (thanks @skyrpex )

Root instance (`vm = new Vue`) created with:
- string template or render fuction
- template depending on data
- Using one component

If we modify a reactive property of the `vm`, the Root component disappears from the devtools:
<img width="380" alt="screen shot 2017-02-25 at 18 29 28" src="https://cloud.githubusercontent.com/assets/664177/23333233/5dd3194e-fb88-11e6-8268-c571a7f8bcc9.png">

Commenting that line fixes it:
<img width="447" alt="screen shot 2017-02-25 at 18 30 07" src="https://cloud.githubusercontent.com/assets/664177/23333239/79a7e7b2-fb88-11e6-87d9-dd598635adb7.png">

**Current workaround**: select the topmost Vue instance and, in theconsole, write `$vm.$root` to debug the root Vue instance

**Comment by edDimensi** [comment]
have same problem.
Then i try use this computed methods, i lost <Root>
```
  computed: {
    getAlbums () {
      return this.$root.base.albums
    },
    getPosts () {
      return this.$root.base.posts
    }
  }
```

**Comment by skyrpex** [comment]
I loose <Root> too, but not sure what triggers it. All I know is:
* I load my page, and there's no <root>.
* I navigate to other page (I'm using vue-router), and then everything dissapears from the vue-devtools.
* I press the vue-devtools refresh button and <root> is correctly displayed for the rest of the session.

**Comment by thomthom** [comment]
I'm seeing similar issue as well when I set some properties. Haven't been able to exactly pin down the exact trigger conditions.

**Comment by bobmoff** [comment]
Same issue here

**Comment by MaxMilton** [comment]
Since the latest version of vue-devtools I haven't experienced this anymore. It might be worth double checking it's still an issue for you.

**Comment by bobmoff** [comment]
Yes! I can see Root again, sweet!

**Comment by skyrpex** [comment]
With vue-devtools 3.1.4 and Vue 2.3.4 I keep experiencing the error in my setup.

**Comment by posva** [comment]
I accidentally deleted my old repro but I cannot reproduce it anymore 🙁 
@skyrpex If you manage to reproduce it in a boiled down codepen (https://codepen.io/pen?template=PWbYJO) or a simple html file, please, could you open a new issue with it?

**Comment by skyrpex** [comment]
I did it: https://codepen.io/skyrpex/pen/mwmJRe?editors=1010 (here the [debug view](https://s.codepen.io/skyrpex/debug/mwmJRe/vPAKKVNdPQjA)).

You can see the Root component if you load the devtools before the timeout in the code happens. Then, if you press the reload button, it'll be gone.

Seems related to:
* Altering a data variable in `created()` using a timeout (haven't tried changing the variable using a button, though).
* Using the data mentioned before to display or not an element (v-if or ternary operator).

**Comment by posva** [comment]
Thanks a lot!

**Comment by bobmoff** [comment]
I can verify that it is the same behaviour for me. As soon as I am modifying a data property on the root component in a callback from either created() or mounted() AND using that property in a v-if to display/hide component => Root is removed from devtools.

**Comment by senid231** [comment]
same issue here
main.js
```es6
import App from "./app.vue";
new Vue({
    el: '#main-app',
    store,
    data: {},
    components: {App},
    render: (h) => h(App)
});
```
app.vue
```vue
<template>
    <app-layout>
        ...
    </app-layout>
</template>
<script>
 export default {
        name: 'MainApp',
        components: {
            AppLayout
        },
       ...
}
</script>
```
with such configuration i can't see Root and MainApp in the devtools
i tried to remove `el: '#main-app'` with `new Vue({...}).$mount(element)`
i tried to replace `render: (h) => h(App)` with `template: '<App/>'` but nothing changed

**Comment by utbroker** [comment]
This was happening to me and the problem was due to an invalid component in my router/index.js. Commented out the import and the path reference and problem solved.

**Comment by Phlow2001** [comment]
I have the exact same problem, with vue-devtools 3.1.6, vue 2.5.2 with a very similar setup to @senid231 above.  No Root entry ever appears.  Even the main layout component doesn't show up.  The root node in my tree is the VApp component from Vuetify.

**Comment by andywarren86** [comment]
This is happening to me whenever I load data in the created hook. Would be very grateful if this issue could receive some attention.

**Comment by lorddubbs** [comment]
Did anyone get a solution to this ?
