### ISSUE TITLE
Bug: Won't display computed from mixins

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue-devtools#271]
Hi,
Never happened before, but I noticed that some computed properties are not displayed when they are coming from mixins && no computed object is register in component definition (see screenshots)

#Case 1
![screen shot 2017-03-02 at 13 16 03](https://cloud.githubusercontent.com/assets/4596409/23520831/81d8f91a-ff4a-11e6-9300-95984522886b.png)
![screen shot 2017-03-02 at 13 11 19](https://cloud.githubusercontent.com/assets/4596409/23520887/b0f42b20-ff4a-11e6-9e87-56a8cc7dcc8f.png)

#Case 2
![screen shot 2017-03-02 at 13 15 49](https://cloud.githubusercontent.com/assets/4596409/23520858/98c3dc26-ff4a-11e6-9698-590a205bb70e.png)
![screen shot 2017-03-02 at 13 14 14](https://cloud.githubusercontent.com/assets/4596409/23520901/c3929050-ff4a-11e6-96b0-3dccc0d780c6.png)

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by bartlomieju** [comment]
I can confirm that, made a small PR to fix this problem.

**Comment by bartlomieju** [comment]
This might be related as well: #199
