### ISSUE TITLE
Support native classes as types in props

### ISSUE THREAD

**Issue by ariera** [vuejs/vue-devtools#273]
I have a component that contains the following property:

```js
    props: {
      owner: { required: true, type: Owner }
    },
```

In this case Owner is a ES6 class with the same name that I `import` from another file.
Whenever I try to inspect the component i get this error in the console:

```
Uncaught TypeError: Cannot read property '1' of null
    at y (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:4057)
    at chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:3950
    at Array.map (native)
    at d (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:3854)
    at p (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:3334)
    at u (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:2334)
    at t.<anonymous> (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:1524)
    at t.n.emit (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:15051)
    at chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:12718
    at n (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1:761)
```

If I remove the type validation, or set it to `Object` it works.

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by ariera** [comment]
I think this pen should reproduce the error, but I can't test it from this computer.
http://codepen.io/ariera/pen/WpxmGE

And here is the code:

**js code**
```js
class MyModel {
  constructor(){
    this.message = "hi there";
  }
}

Vue.component("my-component", {
  props:{
    model: {
      required: true,
      type: MyModel
    }
  },
  
  template: `
    <div>
      {{ model.message }}
    </div>
  `,
})

new Vue({
  el: '#app',
  data: {
    myModel: new MyModel,
  },
})
```

**html code**
```html
<div id="app">
  <my-component :model="myModel"></my-component>
</div>
```

**Comment by posva** [comment]
I clicked around but it doesn't throw any error 😕

**Comment by ariera** [comment]
I can't seem to reproduce it in codepen since it doesn't activate the vue devtools chrome extension.

I created a gist [1] with just one html file. Download it and open it with chrome and try to select `MyComponent`. I am getting this error:

![screen shot 2017-03-06 at 08 04 04](https://cloud.githubusercontent.com/assets/154871/23599867/e574c0a2-0243-11e7-8ba1-63a8ec32ad50.png)


[1] https://gist.github.com/ariera/65f9a987d96b67a386bfb670f236cd0b

**Comment by posva** [comment]
Oh, I see, it was working on Codepen because it was using babel and the class was being transformed into a function. In codepen, if you have an account, you can change the view to the debug view. In that case you cas use the devtools. But a simple html file is good too 🙂 
Thanks for sharing, I'll fix it

**Comment by ariera** [comment]
Ahhh, ok, that's good to know!
Glad to help :)
