### ISSUE TITLE
RegExp are displayed as empty objects

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-devtools#276]
In the component properties pane, Regex are not displayed:

![image](https://cloud.githubusercontent.com/assets/2798204/23611755/d9cea65c-0278-11e7-8275-bbe805be7154.png)

To reproduce: add a data or computed property that holds a Regex.

What's expected: displaying the Regex

![image](https://cloud.githubusercontent.com/assets/2798204/23611798/0f88f842-0279-11e7-93ca-e0a0ec61d31c.png)

**Comment by posva** [comment]
You can definitely submit a PR for that 🙂

**Comment by Akryum** [comment]
When I have time 😊
