### ISSUE TITLE
Proxy injection failed.

### ISSUE THREAD

**Issue by MaxPleaner** [vuejs/vue-devtools#277]
You can see the error here:  
![vue](https://cloud.githubusercontent.com/assets/5035719/23692610/9cf714b4-0384-11e7-9d16-0b2b919804ba.png)

It says 'Proxy injection failed". I don't know what it means, and I don't have any errors in my dev console or my terminal tab (webpack).

Chrome version Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by rwlinda** [comment]
I'm having the same issue. I worked on Vue locally, but have put the code in a Java-based project (with .jsp-files) and since then I get this message. Like the OP, there're no errors or any other pointers to look for the issue. So, my bet is that it's not a Vue thing, but the environment in which its being used. If I find out the issue, I'll come back here...

**Comment by MaxPleaner** [comment]
When I got this error I was proxying my Rack server (port 3000) to a
Webpack server (port 8080). That was my attempt to have the frontend and
api running on the same host so that I would be able to set cookies.

This was buggy for reasons other than the error in Vue dev tools, so I
ended up ditching this idea and am hosting the two apps separately now. The
error "proxy injecion failed" is gone.

**Comment by rwlinda** [comment]
We got the issue solved by changing some security settings. The error has nothing to do with Vue. The app worked fine in IE as that browser handles the security policies differently. We have everything working in all browsers now. Sorry, I don't know exactly what settings were changed, but your Vue is most likely just fine

**Comment by yyx990803** [comment]
Closing since there doesn't seem to be anything actionable now.

**Comment by dobromir-hristov** [comment]
This error comes up when using devtools with firefox on a hot-reloaded app using Laravel Mix.

**Comment by dobromir-hristov** [comment]
Ways to fix this:
Restart Firefox (mostly fixes it... rsrly)
This happens to me when:
a) My PC was a sleep for some time
b) When Firefox needs to update it self

**Comment by noBlubb** [comment]
Same for me - restarting Chrome was all it took

**Comment by dengshenkk** [comment]
> Same for me - restarting Chrome was all it took

this does not work!
