### ISSUE TITLE
Large RAM usage

### ISSUE THREAD

**Issue by OmgImAlexis** [vuejs/vue-devtools#279]
I've noticed when using this with Vuex if I leave the dev tools open in a tab in the background and forget about it for a few hours I end up with the process for the dev tools using upwards of 1GB, some of the time even getting as high as 3GB of RAM just by itself.

I don't know where to start looking for issues but I thought I'd report it so someone may be able to look into it.

**Comment by posva** [comment]
I've never faced this problem.
Can you, please, boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by yyx990803** [comment]
This makes sense when you are recording actions with high frequency updates - Vuex stores snapshots of your state so it incurs a lot of memory usage.

You can turn off the recording when you don't need it to prevent this from happening.

In the meanwhile, we may want to add a max entry limit to the vuex history.

**Comment by OmgImAlexis** [comment]
@yyx990803 I've done some more testing and this looks like it actually happens AFTER the vuex store is filled. While history is being added it goes up a tad but not all that much. I've seen my RAM at 500MB or so after using it for a while but leaving it causes it to get over 1GB which shouldn't  be happening as the app only handles updating the state when I click a button in my app.

I'm guessing this is some kinda of memory leak that's happening in the background. Is there anything I can do to help you guys find the issue?

**Comment by posva** [comment]
Hey, sorry for the delay. Yeah, a boiled down repro would help 🙂

**Comment by buddyff** [comment]
@yyx990803 how can I turn off the recording ?

**Comment by fridgerator** [comment]
@yyx990803 @buddyff I would like to know how to turn off "recording" as well

**Comment by yyx990803** [comment]
There's a recording button in the Vuex tab (also in events tab)
<img width="447" alt="screen shot 2017-06-28 at 2 47 22 pm" src="https://user-images.githubusercontent.com/499550/27623801-bad51ca8-5c10-11e7-95f4-51e2489bdce2.png">
:

**Comment by al1b** [comment]
@yyx990803  @posva I face this problem too. I'm using VueCLI for my development so there is lots of browser refreshes. After a while ram usage goes to 2.7 GB.

**Comment by bresson** [comment]
I'm facing the same issue. As soon as Vuex is clicked on devtools, the browser will freeze and my iMac will drop from 19G to 9G. Turning off recording seems to help but both Vuex and Events have to be toggled "off" -- not easy since the entire devtool is unresponsive.

**Comment by Ar7profacex** [comment]
you can try this, sometimes the problem is libraries external to Vue, https://vuejs.org/v2/cookbook/avoiding-memory-leaks.html

**Comment by xereda** [comment]
Do we have news about this?
