### ISSUE TITLE
Vue chrome extension only showing <Root> node

### ISSUE THREAD

**Issue by stevekrouse** [vuejs/vue-devtools#280]
The Vue Chrome Extension is only showing the node, and this is happening for me in two different Vue Projects:

![](https://vue-forum-vuejsorg.netdna-ssl.com/uploads/default/original/2X/2/293eff29fb7582a775420b2a914c09225328688c.png)

![](https://vue-forum-vuejsorg.netdna-ssl.com/uploads/default/original/2X/6/6e9f05d432aa4fd92db8b99c26507b16e124b82f.png)

Am I doing something wrong?

I uninstalled and re-installed the chrome extension. I'm on a chromebook with Chrome version 56.0.2924.87. I'm using Vue versions 2.0.1 and 2.2.1.

However, when I'm on the VueJS homepage, looking at those examples, the extension works properly showing different components.

Any tips? Thanks!

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by stevekrouse** [comment]
I've gotten the dev tools component viewer to work but only with non functional components. Is there a way to also view functional components?

**Comment by posva** [comment]
no, functional components are stateless and therefore aren't displayed in the devtools

**Comment by stevekrouse** [comment]
Ah gotcha! Thanks! That might be a good thing to add to the documentation.
