### ISSUE TITLE
Vivaldi vs Chrome | unvisible root

### ISSUE THREAD

**Issue by AlennGK** [vuejs/vue-devtools#281]
Don't know why, but extensions do not show root files in Vivaldi(chromium) browser.
I will post bug in Vivaldi forum too.

![30b23060f7ce46758b997f11bc2a86ae 1](https://cloud.githubusercontent.com/assets/13176180/23856177/f3115ee0-07f8-11e7-8cd6-54243503380f.png)

**Comment by posva** [comment]
I have never used Vivaldi before, I suppose there may be some differences concerning the extensions API.

**Comment by adridev** [comment]
I'm having the same error in Vivaldi and Chrome, both on their latest version. After a few seconds, the Root appears. 

Cheers.

**Comment by dsl101** [comment]
I'm in the same boat - I can never get anything to display in the Vivalid devtools window. The extension recognises Vue on the page (icon lights up and says 'Vue.js is detected on this page.'), but the devtools panel is just empty. But for me on Chrome (55.0.2883.87) it works fine. It would be really great if this could be supported on Vivaldi. @adridev did you post this to the Vivaldi forum?

I also looked at the background page for Vue-Devtools, and nothing is shown in the console. I would expect something if there were errors - is there any debugging info produced by the extension?

**Comment by AlennGK** [comment]
@dsl101 Yes I did post this on Vivaldi formu, but not even after 2min Root is not loaded.

**Comment by dsl101** [comment]
@AlennGK Sorry - I got the comments mixed up :) For me, on Chrome everything works as it should. On Vivaldi, I never see anything in the Vue panel. I think that's the same for you? 

@adridev perhaps you have a different issue. Are you saying that Vue-devtools _does_ work in Vivaldi, but only after a few seconds? My Vivaldi version is "1.8.770.44 (Official Build) (64-bit)", and I've never been able to get anything to show

**Comment by adridev** [comment]
Hi,

No, in Vivaldi sometimes it appears after a few time and sometimes it doesn't. In Chrome It has a little delay sometimes but less frequently.

I'm running Manajaro Linux with the latest LTS kernel, Chrome  57.0.2987.110 (64-bit) and Vivaldi 1.8.770.50 (Stable channel) (64-bit).


Chrome 
![screenshot_20170329_181815](https://cloud.githubusercontent.com/assets/895348/24465078/30db0856-14ac-11e7-98e0-ad36d679f5c8.png)

Vivaldi
![screenshot_20170329_181745](https://cloud.githubusercontent.com/assets/895348/24465077/30da78aa-14ac-11e7-97bd-8e5712c5e131.png)

Both screenshots are from the same App and URL.

**Comment by adridev** [comment]
@dsl101 I fact, after today's update of Vivaldi It doesn't work at all.

**Comment by Hades32** [comment]
Seems to be a general issue. Doesn't work under Windows 10 and Vivaldi 1.8.770.56 (Stable channel) (32-Bit) either.

**Comment by hultberg** [comment]
Funny thing. The newest vivaldi snapshot that allows docked devtools, the vue devtools work as in chrome. Using vue 2.3.0.

**Comment by raniesantos** [comment]
@hultberg Lets wait until that version of Vivaldi is officially released. BTW, just a side question, does the latest snapshot have mobile emuiation too? I haven't seen it.

**Comment by hultberg** [comment]
@raniesantos Yes, there is a button for it. However, it only works when the devtools is docked.
![2017-05-03_104x90](https://cloud.githubusercontent.com/assets/1257913/25650231/ce103854-2fdb-11e7-8ecb-acc8f556b32a.png)

**Comment by armano2** [comment]
From what i can see, any of extensions to devtool from chrome is not working under this browser, eg. react/angular 🗡

**Comment by raniesantos** [comment]
Based on what @hultberg said, it seems like this issue is related to the fact that the devtools can't be docked.

**Comment by raniesantos** [comment]
Confirmed working in Vivaldi 1.10 (docked devtools)
![1581e330-aec9-4e0b-ba95-763f5f1604db](https://user-images.githubusercontent.com/8528269/27171821-77812d0a-51e5-11e7-8153-1d8947c484ca.jpg)

**Comment by dsl101** [comment]
Just FYI, Vue Devtools has been working for me for the past few weeks _non_-docled. I vaguely remember that I had to dock the devtools window at first to get it to work, but since then, it's been fine. I'm using Vivaldi 1.10.862.6 (Official Build) (64-bit) on Windows 10 Pro

**Comment by MaxMilton** [comment]
Just tried this and it seems to work great docked or undocked on:
```
Vivaldi: 1.10.867.38
vue-devtools: 3.1.4
Vue: 2.3.4
OS: Fedora Linux 26 x86_64
```
