### ISSUE TITLE
vue-devtools 3.1.0 doesn't work everywhere

### ISSUE THREAD

**Issue by EroTiXx** [vuejs/vue-devtools#286]
Hi,

I use the new vue-devtools 3.1.0 on 2 projects and i have this error in console :
`Uncaught TypeError: Cannot read property 'config' of undefined`

Bug present on : 
MacOS, Prod & Local, Vue => 2.0.1
Windows, Prod & Local, Vue => 1.0.28

I'm waiting for your feedback

**Comment by posva** [comment]
Closing in favour of #287
