### ISSUE TITLE
Vue.js devtools 3.1.0: Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by wangduanduan** [vuejs/vue-devtools#287]
it can not find components.  when i click the refresh button, then a error shown.

Vue.js devtools 3.1.0

```
vue-devtools] Ready. Detected Vue v1.0.26
backend.js:1 Uncaught TypeError: Cannot read property 'config' of undefined
    at backend.js:1
    at u (backend.js:1)
    at u (backend.js:1)
    at u (backend.js:1)
    at u (backend.js:1)
    at u (backend.js:1)


    at u (backend.js:1)
    at u (backend.js:1)
    at s (backend.js:1)
    at o (backend.js:1)
````

![2017-03-15_153759](https://cloud.githubusercontent.com/assets/16631306/23938675/3c17447e-0998-11e7-9f5e-974f39daf6e7.jpg)

**Comment by komirad** [comment]
Facing the same issue. Using vue 1.0.

**Comment by anxolin** [comment]
![screenshot_20170315_090844](https://cloud.githubusercontent.com/assets/2352112/23939125/a7172494-095f-11e7-93c7-cb878f2dd82f.png)

Same problem here with v1.0.28.

It looks like it's dependant on something that has only be added into Vue2:
![screenshot_20170315_090844](https://cloud.githubusercontent.com/assets/2352112/23939227/0dfb6bde-0960-11e7-8764-af77c0e4e49f.png)

**Comment by raimi6** [comment]
Facing the same issue. Using vue v1.0.28

**Comment by wangduanduan** [comment]
i download the Vue.js devtools 3.0.0 and use manual install, it works without error.

**Comment by mtctonyhkhk2010** [comment]
Please don't give up vue 1.0 just yet😢 Still using it. I think a lot of people still do too.

**Comment by posva** [comment]
This was fixed on 38e925c55218d1cb1326a0146f519cbc8ac46379
Sorry for the inconvinience! 😅

**Comment by mtctonyhkhk2010** [comment]
Well that was fast. LOL

**Comment by kenberkeley** [comment]
now is ok, so fast! good job!

**Comment by posva** [comment]
Good job to Evan, he's the one who fixed it 😉
