### ISSUE TITLE
Clicking the component redirects to different page

### ISSUE THREAD

**Issue by coleHafner** [vuejs/vue-devtools#289]
Versions:
vue-devtools: 3.1.2
chrome:  56.0.2924.87 (64-bit)
vue: 2.1.10
vuex: 2.1.2

STR:
- Go to a page with 2 different vue instance on it, each instance has at least one component
- Open Vue Devtools and go to the 'Components' tab
- Click on a component in the list

Expected:
- The component (and only that component) will be selected
- The component's scope will appear in the right hand panel

Actual:
- Both the item click on and it's corresponding item in the list for the other Vue instance is selected.
- App redirects to the login page.

This is really weird. Perhaps it's something to do with multiple Vue instances on the same page?

![screen shot 2017-03-15 at 2 24 35 pm](https://cloud.githubusercontent.com/assets/380835/23971585/c96d5fbe-098b-11e7-9f2d-dab6b03e20bd.png)

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by coleHafner** [comment]
Thanks. I created a new pen with essentially what's happening. I can't bring up Vue Developer Tools with Codepen though, so it's hard to verify. Here's the pen:

http://codepen.io/coleHafner/pen/mWqEgB

**Comment by bartlomieju** [comment]
I has a similar problem when I used two root instances from two different packages (I injected two full Vue apps into the same page). I guess it might be connected with clashes of `_uid` each instance has. Since the two packages are unaware of each other (they do not share same Vue lib)  they both start from `_uid = 0`. I think adding some entropy to each `_uid` inside devtools should resolve this case. I think I can slap some solution this weekend, but first I'll have to get reproducible error. We'll keep to posted.

**Comment by posva** [comment]
In the codepen you can change the view to have the devtools. I tried your repro but there's no issue. If you're including two different versions of Vue, what @bartlomieju is what's happening

**Comment by bartlomieju** [comment]
I managed to get a reproducible example. You can see it [here](https://github.com/bartlomieju/vue-id-clash).

Basically what you have to do is:
1. start a new project (with `vue cli`) with some root component
2. load `vue` from cdn and make another root component (e.g. in index.html)
3. both root components have `_uid = 0` 
4. devtools can't manage both of them

Excerpt with interesting stuff:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vuet</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.4/vue.js"></script>
  </head>
  <body>
    <div id="app"></div>
    <div id="app1"></div>
    <!-- first root instance in in build.js -->
    <script src="/dist/build.js"></script>
   <!-- here we create other root instance using vue from cdn -->
    <script>
      new Vue({
        name: 'Root2',
        el: '#app1',
        template: '<p>{{ msg }}</p>',
        data: {
          msg: 'The other Vue'
        }
      })
    </script>
  </body>
</html>
```

I'm not saying that it is a good practice to do such things, but devtools should have it covered.

Opening a PR with fix right now.

**Comment by posva** [comment]
@coleHafner As a side note, it's a bad idea to have multiple Vue instances on the same page. It's better for you if you could make sure to only have one
