### ISSUE TITLE
Chrome Workspaces support?

### ISSUE THREAD

**Issue by DCzajkowski** [vuejs/vue-devtools#290]
Hello :)

I often like to edit sass styles in Chrome and see them appear in my local files (a.k.a. Chrome workspaces).
Is it possible to use this Chrome feature using Vue.js and single file components? If yes, could someone point out how? If not, is it possible that this extension would add support for that?

**Comment by posva** [comment]
Hi! That already works:
Serving with `vue build`
I simply added the dir to my workspace
![screenflow](https://cloud.githubusercontent.com/assets/664177/24052946/92b23014-0b37-11e7-8e44-780dec167b55.gif)

**Comment by DCzajkowski** [comment]
I know that, sorry I wasn't clear enough.
What I meant is editing directly via the devtools, not using dev tools as an editor (ie. from the elements panel, not from the sources panel)

**Comment by posva** [comment]
I see, that's out of the scope of the Devtools, at least for the moment

**Comment by DCzajkowski** [comment]
That's what I was worried about. Nevertheless, thank you very much for your response 👍
