### ISSUE TITLE
Does it work with vuejs 0.12?

### ISSUE THREAD

**Issue by nniicc** [vuejs/vue-devtools#294]
Hey,

I'm editing a old project that was written with vuejs 0.12. And when i try to enable vue devtools, i always get that its detected but is in production mode or disabled by the user.

> Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

Im setting the debug to true
```javascript
Vue.config.debug = true;
```

So I'm wondering if devtools even work with vue 0.12 and if it does, how do i enable it.

**Comment by posva** [comment]
It doesn't seem like they do. If you manage to find a fix for it, we're open to a PR. But unfortunately, we're not going to do it because it's not worth anymore.
