### ISSUE TITLE
Dev tools Components tab is empty after switching to Webpack

### ISSUE THREAD

**Issue by vedmant** [vuejs/vue-devtools#295]
I have a problem with Vue-devtools, after switching my build system from Browserify to Webpack 2 All components disappeared from Components tab, yet it shows events in Events tabs https://screencast.com/t/hjmd0VMwQ

Js is not minified. I googled and tried different approaches, and it works only if I set `Vue.config.devtool = true;` on version after Vue 1.0.18, however my application depends on Vue 1.0.17, with next version my app isn't working properly so I can't upgrade without refactoring a lot of code.

Additional, I can see my Vue configuration `window.__VUE_DEVTOOLS_GLOBAL_HOOK__.Vue.config`
but `window.__VUE_DEVTOOLS_INSTANCE_MAP__` is empty

Maybe there is a simple fix with Webpack or Vue configuration?

Vue version: 1.0.17
MacOs: 10.12.3 (16D32)
Chrome: Version 56.0.2924.87 (64-bit)
DevTools: 3.1.2

Thanks!

**Comment by posva** [comment]
This was introduced on purpose: https://github.com/vuejs/vue/releases/tag/v1.0.18 because people was complaining about the devtools appearing in production apps. You can clone the repo, delete the check and install them to make it work in your case, but we cannot add that back.

**Comment by vedmant** [comment]
Thanks @posva, however it worked just fine recently, it looks like Vue Dev Tools were updated and it stopped working after it. Is there a way to downgrade google chrome extension?

**Comment by posva** [comment]
Yes, clone the repo and go back to a specific tag, build instructions are on the readme and very easy to follow 🙂

**Comment by DiegoFleitas** [comment]
Same issue, this solved it!
