### ISSUE TITLE
state auto expanded

### ISSUE THREAD

**Issue by NieShuai** [vuejs/vue-devtools#297]
Someday I find that state and mutation are auto expanded in vuex view, and it is really difficult for me to find what I am focusing on. Is there any posibility to add a 'auto expand' setting?

**Comment by posva** [comment]
Can you be a bit more explicit about what's happening and what you would like to happen instead?

**Comment by NieShuai** [comment]
@posva 
![1](https://cloud.githubusercontent.com/assets/14159721/24140296/70b0f9c0-0e5a-11e7-9898-866a935ae7ae.jpg)
![2](https://cloud.githubusercontent.com/assets/14159721/24140297/70b2338a-0e5a-11e7-979b-ea2a32fc11d1.jpg)

**Comment by Renol7** [comment]
I totally agree with that. 'Auto expand' setting is a small feature but it has a huge benefits.

**Comment by posva** [comment]
closing in favour of #123
