### ISSUE TITLE
Support for <docs> tag in single file components

### ISSUE THREAD

**Issue by gustojs** [vuejs/vue-devtools#298]
Some of us use an additional `<docs>` tag for component's documentation in `.vue` files.

I wonder, would support for that be technically possible in `vue-devtools`? Purely in the form of displaying the content when the currently selected component has such a tag.

**Comment by posva** [comment]
It's technically possible, but it'll bloat the view. I don't think it belongs to the devtools because you can read it directly in your component file, while the state, props, etc is dynamic and cannot

**Comment by gustojs** [comment]
Thanks, I'm satisfied with the answer. I'll keep it open for a day in case somebody wants to add something, then close it.

**Comment by iBobik** [comment]
Does somebody have tip for a tool what can generate some kind of styleguide from single file components and can use something like <docs> in it?
