### ISSUE TITLE
Not working Vuex Export

### ISSUE THREAD

**Issue by arszp10** [vuejs/vue-devtools#299]
When i push button Export in Vuex section vue-devtools print "Copied to clipboard!" but clipboard is empty.
vue-devtools version 3.1.2
vue version 2.2.3
vuex version 2.2.1
chrome version  57.0.2987.110 (64-bit)
OS GNU/Linux Ubuntu 16.04

**Comment by posva** [comment]
Hey, I tested and it's working fine with the last version of the devtools. Can you provide a repro using this [template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by arszp10** [comment]
It does not depend on the code

**Comment by posva** [comment]
Well, in that case I can't do anything for you... In case you want to look further, this is the piece of code that does the copy: https://github.com/vuejs/vue-devtools/blob/master/src/devtools/views/vuex/VuexStateInspector.vue#L111. It should work on your env
