### ISSUE TITLE
InvalidStateError

### ISSUE THREAD

**Issue by janschoenherr** [vuejs/vue-devtools#3]
I am receiving the error below:

code: 11
message: "Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('number') does not support selection."
name: "InvalidStateError"
stack: "Error: Failed to read the 'selectionDirection' property from 'HTMLInputElement': The input element's type ('number') does not support selection.↵    at Error (native)↵    at Object.stringify (native)↵    at setPanelContent (<anonymous>:39:31)↵    at <anonymous>:54:3↵    at Object.InjectedScript._evaluateOn (<anonymous>:847:140)↵    at Object.InjectedScript._evaluateAndWrap (<anonymous>:780:34)↵    at Object.InjectedScript.evaluate (<anonymous>:646:21)"
__proto__: DOMException

This might be due to using jQuery within the vuejs scope?

**Comment by yyx990803** [comment]
What browser version are you on? Is this error thrown just by using vue-devtools?

**Comment by janschoenherr** [comment]
Google Chrome: Version 41.0.2272.104 (64-bit)

I am applying a jQuery modal on parts of the _vueified_ DOM. That triggers the error.
