### ISSUE TITLE
It is really difficult to inspect mutations

### ISSUE THREAD

**Issue by canamo06** [vuejs/vue-devtools#301]
When I'm inspecting a mutation I want to easily check the mutation data.

Right now, the mutation information is listed at the end of the inspect panel, the user needs to scroll all the way down(Through state & getters) to see it, this is an issue if your state and getters are big.

Solutions:

- Move the mutation information to the top.
- Create like tabs, or app bar with direct access buttons to the state, getters, a mutation information
- Collapse state tree

**Comment by Akryum** [comment]
Potentially fixed by #477
