### ISSUE TITLE
Vue.js is detected and devtool tab is showing but no instance showing

### ISSUE THREAD

**Issue by mehwww** [vuejs/vue-devtools#302]
<img width="1680" alt="2017-03-27 3 10 02" src="https://cloud.githubusercontent.com/assets/5417556/24345029/c846e14a-1300-11e7-9ec6-24963bfa6701.png">

It suddenly does not work today, my Chrome version is  57.0.2987.110 . Anyone has same issue ?

**Comment by posva** [comment]
Close the dev panel and open it again. Maybe reload the page. Tested with vue-hackernews 2 and it works fine
