### ISSUE TITLE
Props are not displayed when they all come from a mixin

### ISSUE THREAD

**Issue by dlwjiang** [vuejs/vue-devtools#304]
If a widget uses a mixin and the mixin has props "foo", I'm unable to see "foo" in the tool

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by dlwjiang** [comment]
Hi @posva, here is an example: http://codepen.io/anon/pen/qrwWQX I am unable to get vue-devtools to show up in codepen though, but similar usage in my codebase creates this condition.

**Comment by posva** [comment]
Thanks, it looks like it only happens if no props are provided in the component. In the meanwhile you can add `props: []` to the  component using the mixin
