### ISSUE TITLE
Possible to hide/filter out <router-link> components?

### ISSUE THREAD

**Issue by amnah** [vuejs/vue-devtools#308]
I am finding it difficult to select the component I want when I have too many router-links in the page. For example,

```javascript
<history>
    <router-link> x50
    <child>
    <router-link> x15
```

Is there a way to hide or filter out those router-links so I can select the child easily?

![router](https://cloud.githubusercontent.com/assets/2630503/24824754/b6209c62-1bdf-11e7-8a90-41aef004e2e1.png)

**Comment by posva** [comment]
Well, you can search `child` to filter them out. This issue will also happen when using common ui components, so adding an explicit way to filter out just `router-link` is not enough. Maybe adding something like `!` to filter out text like `!router` will do a negate search on `router`

**Comment by amnah** [comment]
Ah. I didn't actually think of searching for the component directly - what a major brain fart.

Would still be a nifty little feature to do `!filter` negation, but no longer needed. 

Thanks - closing issue.

**Comment by rifton007** [comment]
Any news about this feature request ?
