### ISSUE TITLE
Doesn't see mutations that execute on root's created or mounted hook

### ISSUE THREAD

**Issue by megapctr** [vuejs/vue-devtools#312]
If I commit a mutation (indirectly) from a lifecycle hook, like `mounted`, for a component that mounts as soon as the page is loaded, no mutation is being registered. If I delay the mutation via `setTimeout` for ~1000ms, the mutation is being registered. Is it possible to register the mutation instantly, without delay?

**Comment by posva** [comment]
It's probably not possible if the devtools aren't loaded and connected yet 🙁 

If you can showcase it using this [template](http://codepen.io/pen?template=PWbYJO), I can take a look

**Comment by megapctr** [comment]
Thanks for quick reply! Here's the repro: http://codepen.io/anon/pen/ybLMGO/?editors=0010

Perhaps this issue can be resolved by writing a plugin that registers all mutations until the devtool plugin registers itself. Redux devtools extension does a similar thing, where you need to add a middleware to get the extension to work [(link)](https://github.com/zalmoxisus/redux-devtools-extension#1-with-redux)

**Comment by skyrpex** [comment]
I want this fixed too. Can I contribute somehow?

> Perhaps this issue can be resolved by writing a plugin that registers all mutations until the devtool plugin registers itself.

This could happen only in non-production builds :+1:.

**Comment by rtfleg** [comment]
Good news, everyone!
Looks like I made workaround which might be helpful.
https://gist.github.com/rtfleg/cc159e4f773a8a3d9ec3a0f8ca821464

**Comment by Akryum** [comment]
Let's continue in #408
