### ISSUE TITLE
Problem with display of computed value

### ISSUE THREAD

**Issue by davidkhess** [vuejs/vue-devtools#315]
I've stumbled across a strange bug in 3.1.2 (via Chrome auto-update) against Vue 2.2.6 where the inspector is showing the wrong value for an array computed. Here's a screenshot showing how the computed "symptoms" (among others) is not displayed correctly.

<img width="1060" alt="vuedevtools" src="https://cloud.githubusercontent.com/assets/184167/25135697/aeae6e6e-2418-11e7-9b66-2188402b6cf1.png">

The app operates properly and the actual value on the VM is as would be expected. The only interesting thing about this computed is that it is using _.filter and _.forEach in LoDash on a combination of reactive and non-reactive data.

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by davidkhess** [comment]
Do you have instructions on how to get the extension to display the Vue tab on CodePen? It won't display for me (I think because the window isn't loading Vue - the frame is).

**Comment by posva** [comment]
You have to change the view to the debug view.
If it's easier for you, you can share a `vue` file content, it's easy to debug with `vue build App.vue` 🙂

**Comment by davidkhess** [comment]
Ah, debug view was the trick. Thanks.

Here's a reproduction https://codepen.io/dhess/pen/ybYEoL

**Comment by posva** [comment]
oh, it's so weird it only happens when doing it in the mounted hook... It's as if the computed property was using the data object as its value

**Comment by coolzjy** [comment]
Seems same bug with #316 , have tried run given demo with a patched version of `circular-json-es6`, and got expected result.
![image](https://cloud.githubusercontent.com/assets/3762377/25159140/47215266-24e0-11e7-81f6-9cd7df8e75e7.png)

**Comment by posva** [comment]
@coolzjy Ok, thanks I'll take a look

**Comment by Akryum** [comment]
Can't reproduce on 4.1.1.
