### ISSUE TITLE
在mac下，占用内存资源很多

### ISSUE THREAD

**Issue by ruofeng086** [vuejs/vue-devtools#318]
打开开发者模式，使用插件的时候，内存占用时常2GB左右

![image](https://cloud.githubusercontent.com/assets/14192308/25734786/fd878cb8-3198-11e7-9044-075ae7f3d201.png)

**Comment by posva** [comment]
Pretty much the same as #317 
If you have a **minimal** reproduction, I can take a look

**Comment by ruofeng086** [comment]
Don't you encounter this problem? I just write a few pages, but I do have the page content length is very long, but this should not be an excuse for caton right

**Comment by ruofeng086** [comment]
If we can have a best solution. Thanks

**Comment by posva** [comment]
Sorry, I don't understand the last sentence of your first comment.
No, I don't have this problem.

**Comment by ruofeng086** [comment]
My template with less than 500 lines of code, perhaps this should not be an excuse for caton.

**Comment by posva** [comment]
What is caton?

**Comment by ruofeng086** [comment]
The computer Memory is very high
MAC is not very smooth running fast

**Comment by posva** [comment]
hmm, if you display too much data, it's normal to consume more, the same way an application with a lot of content would consume more.
You may search for help or ask at https://forum.vuejs.org/c/chinese but I'm sorry I really can't help you here
