### ISSUE TITLE
Devtools don't update independently.

### ISSUE THREAD

**Issue by bigZ-again** [vuejs/vue-devtools#323]
If there isn't any update in web pages, the devtools don't update independently.
For example, when i click this buttons on web page, the devtools don't update the value of b. 
![image](https://cloud.githubusercontent.com/assets/15630922/25813684/0a9ef3da-344d-11e7-9b8e-0d793ecb4e06.png)

If change something, for example: add `disabled`, then everything is OK.
![image](https://cloud.githubusercontent.com/assets/15630922/25813774/6d201c28-344d-11e7-929f-349b7afdc9bd.png)

---
Vue.js devtools 3.1.2

**Comment by posva** [comment]
Since the value is not used, the dev tools doesn't catch up but don't worry, you have a force refresh button on the top right 🙂

**Comment by bigZ-again** [comment]
Froce refresh is helpful. But why depend it? And I do some test...
Maybe it's magic.
- If a variable potentially affect the state of web page(DOM), every change on it will be catch up by the devtools. 
- If a variable has nothing to do with the state of web page(DOM), then the dev tools doesn't catch up any change on it.

Is my understanding right? @posva
