### ISSUE TITLE
Problem with showing the recursive state 

### ISSUE THREAD

**Issue by mumutu** [vuejs/vue-devtools#325]
here is the sample https://codepen.io/anon/pen/OmQvpO
I am new to vue so the problem was not separated well。

Three components was defined `parentCmp` ,`child`,`childB` and a  shared state class `TableStore` 
parentCmp create a new tableStore as a root state, and has a `slot` tag to render the child component which would insert a column info into the state.columns, here is {"foo":"bar"} and  there is a childB ,the child component of the parentCmp and accept the  `store` of parentCmp,  also a columns computed value is used. 
Everything works well if the TableStore not hold the `this`(the parentCmp instance), otherwise when using the  vuedevtool to observe the `state.columns` a weired object was assigned instead of the array([{"foo":"bar","foo":"bar"}]).
if using a method within the parentCmp to show the store  the result is correct so the real state is right 

[update] may be the reason is the store's table which hold the instance make a recursive ref , but I think the unrelated  property `columns` should not be polluted 

![image](https://cloud.githubusercontent.com/assets/1217857/25898396/8fe59702-35be-11e7-818f-264f46c707a2.png)

**Comment by posva** [comment]
Please, fix the errors on the console first, thanks.

**Comment by mumutu** [comment]
@posva   oh sorry it's my fault   fixed~

**Comment by posva** [comment]
Can you please describe the steps to reproduce the problem and what is expected vs what is happening?

**Comment by mumutu** [comment]
I thought i had described the case above , unfortunately  it is my poor english to blame.
Anyway if you run the code in the chrome with vue devtools . You will see 
*  in the case the TableStore has a property which holds the component instance `this` , then the `store.states.columns` would be a weired object  instead of the array([{"foo":"bar","foo":"bar"}]). 
* if the TableStore has no property which holds the component instance `this` then the `store.states.columns` would be the expected array([{"foo":"bar","foo":"bar"}]).

**Comment by Akryum** [comment]
Are you using vee-validate?

**Comment by Akryum** [comment]
Can't reproduce using 4.1.1.
