### ISSUE TITLE
show vuex getters per modules

### ISSUE THREAD

**Issue by andredewaard** [vuejs/vue-devtools#327]
Enhancement:
If should be nice to have tabs per Vuex module. So foreach module you have a tab that shows the state and getters of that module.

**Comment by Sp1ker** [comment]
I think it would be like this:
![](https://i.imgur.com/8z9eWs0.png)

After select module `mutations` and `state` should be filtered by `Vuex Module`.

I will try to make this feature.

**Comment by Akryum** [comment]
Closed by https://github.com/vuejs/vue-devtools/commit/65e92463d42261660cba5a952854b9f80d53e304
