### ISSUE TITLE
Vuex state export doesn't work

### ISSUE THREAD

**Issue by YassineGherbi** [vuejs/vue-devtools#334]
When I "Export" in Vuex section, it shows "Copied to clipboard!" But my clipboard is empty (or filled with my last copied text).

The problem also occurs on a fresh install of a Vue/Vuex project.

-MacOs Sierra 10.12.5
-Chrome Version 58.0.3029.110 (Official Build) (64-bit)
-Vue.js devtools 3.1.2

**Comment by posva** [comment]
Sorry for the delay, this got fixed in current releases
