### ISSUE TITLE
Add info of `this._uid` in Components and Events

### ISSUE THREAD

**Issue by beeplin** [vuejs/vue-devtools#336]
Currently, when there are multiple components with the same name on the page, it is hard to tell which event is emitted by which component. Adding `this._uid` to the `Components` view and `Events` view in the dev tool would be greatly helpful.

![image](https://cloud.githubusercontent.com/assets/13058150/26399588/04f5930c-40b0-11e7-97de-05257a5a3e48.png)

![image](https://cloud.githubusercontent.com/assets/13058150/26399601/11f187be-40b0-11e7-942b-f85a9a52bb36.png)

**Comment by Akryum** [comment]
Users are not supposed to know about `_uid` since it belongs to Vue internals. Maybe we could also highlight the components in the Events history like we already do in the Components tree.
