### ISSUE TITLE
Automatic scroll-to-bottom while recording Events

### ISSUE THREAD

**Issue by cb109** [vuejs/vue-devtools#338]
When recording Events, the latest event quickly moves out of sight because the are added to the bottom of the list, but the scroll position is not updated accordingly.

![image](https://cloud.githubusercontent.com/assets/6052590/26589068/51f40b74-4557-11e7-8b93-244fa5810524.png)

It would be great to have an option to either automatically scroll to the bottom of the list as events come in or reverse the event list so that newer events are added to the top instead.

Cheers

**Comment by anteriovieira** [comment]
Maybe reverse the order of the event list and not select the last logged event.  

Below I am inspecting an event and when another event is registered I am moved to the new event. 

![events](https://cloud.githubusercontent.com/assets/1490347/26597570/c94d41f4-4548-11e7-84c4-f7dfc97adfab.gif)

**Comment by cb109** [comment]
I am not sure what you are trying to say. Yes it selects the last event, but try with more events than fit into the indow. It does not scroll with it, so I moves out of sight, which is kind of annoying.

![peek 2017-06-01 10-30](https://cloud.githubusercontent.com/assets/6052590/26671336/5e0dc7e2-46b5-11e7-9e37-df655baf0d79.gif)

**Comment by anteriovieira** [comment]
@cb109 , I agree with you,  is kind of annoying. But scroll  automatically to the bottom of the list may not be the best solution here. I guess not selecting the event automatically would be a good solution. 

It's a bit annoying too when I'm inspecting an event and suddenly another event is selected.

**Comment by cb109** [comment]
Thanks now I understand. I see benefits for both ways, that would make a great checkbox probably.
