### ISSUE TITLE
Decrease app render performance after version update

### ISSUE THREAD

**Issue by psycura** [vuejs/vue-devtools#342]
Hello, guys.

I`m working on some complex web-app built on vue+vuex

And today i`ve noticed that my app begin work much slower than before - with no relevent reason,

i`ve did some research and found out that if i disable action recording on vuex tab - everything work as expected.
And i saw that  my dev-tool extension was updated yestarday.

Why is this happen?

**Comment by v-Stein** [comment]
I noticed the same problem without `vuex`.
I have a complex datatable that deals with a lot of data and when I set a sorting column, I noticed I had a small time of freeze on the browser tab.
When I put the `debugger;` instruction at the end of the code, I saw many function calls that deal with `vue-devtools`.

I then uninstalled `vue-devtools` and everything were fine.

**Comment by fritx** [comment]
+1, I'm doing a three.js bindings for vue, my components props mutate very frequently (requestAnimationFrame). When I open the vue-devtools, app's performance gets much worse.

**Comment by Akryum** [comment]
Enabling Vuex mutation recording makes the devtool to save snapshots of the entire Vuex state each time a mutation is committed. Also, fetching the App components tree and component states will naturally incur some overhead. I'm not saying we can't improve performance though. :smile:

**Comment by Akryum** [comment]
Let's continue in #649
