### ISSUE TITLE
When an external component is not built as production mode, vue devtools shows anyways

### ISSUE THREAD

**Issue by goalie7** [vuejs/vue-devtools#343]
Hello,

I have a project that uses several external components, and one of them are not compiled with production flag.

The problem appears when I compile as production, because when is run it shows in console the "Vue is run under development mode" message.

Moreover, vue-devtools is available and I can check all the state of my application despite is in production mode just because the external component is in development.

Is that the normal behaviour?

**Comment by posva** [comment]
Maybe the external component is forcing the devtools or something. If that's not the case you may want to ask for help in the [forum](http://forum.vuejs.org/) or submit a new issue with a minimal repro. I can also take a quick look at the external component itself if it's on github
