### ISSUE TITLE
Sort state/getters in Vuex tab

### ISSUE THREAD

**Issue by stephantabor** [vuejs/vue-devtools#344]
If you have a lot of getters it's difficult to find what you are looking for (especially since they are expanded by default). If they were alphabetized it would be much easier.

**Comment by robodude** [comment]
It'd be great if getters could appear 'nested' like state does when using namespacing

**Comment by puyt** [comment]
Especially when you're using nested modules

`some/nested/module/count: 0`
`some/nested/module2/count: 1`
### vs
- some
    - nested
         - `module/count: 0`
         - `module2/count: 1`

**Comment by devistar** [comment]
They should be nested by modules like state, with or without namespace.

**Comment by Akryum** [comment]
#327
