### ISSUE TITLE
Cannot read property 'matched' of undefined

### ISSUE THREAD

**Issue by boudydegeer** [vuejs/vue-devtools#345]
When routes are an empty array, and you create the routes on the fly for example on the `beforeCreate` method like this : 

``` javascript
beforeCreate () {
    let routes = []
    this.$modules = Object.assign(modules, this.$options.modules)

    for (var [name, module] of Object.entries(modules)) {
      if (module['routes']) routes.push(module.routes.reduce(r => r))
      if (module['store'] && !this.$store.state[name]) this.$store.registerModule(name, module.store)
    }

    // Add routes for all the modules
    this.$router.addRoutes(routes)
  }
```

You get an error: 
`Cannot read property 'matched' of undefined`

**Comment by LinusBorg** [comment]
in what way is that related to vue-devtools? IT sounds like a vue-router issue.

Can you share a repo with a working reproduction of that behaviour?

**Comment by boudydegeer** [comment]
Actually the application is working like expected, but the vue-devtools are broken when you try this approach.

Tnx

**Comment by posva** [comment]
Hey Boudy, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)? I created a test with an empty routes array but couldn't reproduce the error
Thanks for the PR btw!
