### ISSUE TITLE
show structure Set

### ISSUE THREAD

**Issue by arszp10** [vuejs/vue-devtools#349]
code like this
```javascript
data() {
   setKeys: new Set(),
}
```
vue-devtools will be show this
![image](https://cloud.githubusercontent.com/assets/12972343/26825878/65ff3a5e-4abf-11e7-97d8-7a4908b5b4d6.png)
better cast **new Set()** to structure **Array** in show result

**Comment by AdamNiederer** [comment]
On it.

**Comment by awacode21** [comment]
It is the same problem for Maps

**Comment by awacode21** [comment]
Code like

data() {
   myMap: new Map(),
}

looks like 

![map-devtools](https://user-images.githubusercontent.com/30939926/44207417-757da880-a15d-11e8-94e7-1414851e84b2.PNG)

in the vue devtools, but you cannot inspect its map content.

**Comment by awacode21** [comment]
Here is a little code sandbox: https://codesandbox.io/s/m9qr69jmkp

Using the inputs you can add values to the map. With console.log you can see all the map content, but using vue-devtools it is not possible to inspect the map. You can only see "myMap: Map" .. so you can see that it is a map, but cannot see what it contains.

**Comment by awacode21** [comment]
Created the following issue: https://github.com/vuejs/vue-devtools/issues/742
