### ISSUE TITLE
Ability to inspect parent Vue object(s), not just root component

### ISSUE THREAD

**Issue by Eiskis** [vuejs/vue-devtools#350]
In any Vue app, at the core you have a Vue object that renders a root component to an element. This Vue object has properties like any other, and commonly gets plugins etc. attached to it. Like so:

```js
// main.js
var state = {
    foo: 0
};

new Vue({  // <- I want to inspect this guy...
    el: '#app',
    template: '<app></app>',  // <- ...but I can only inspect this guy
    computed: {
        fooTimesTwo: function () {
            return state.foo * 2; // <- no way to see this in Vue devtools?
        }
    }
});
```

It seems to me that currently the dev tools only seem to let the user inspect a) Vue components and b) Vuex, but not the actual root object of the Vue app. I'd like to be able to inspect the root Vue object(s) that renders the root component(s).

I might have more than one of these Vue objects running at once. I might have either multiple rendered apps, or have viewless Vue objects running on the page (I quite frequently prefer to just use shared Vue objects for state management/services instead of introducing another pattern like Vuex: think of the example above, but with `state` being another Vue object).

There's another feature request (#98) filed for "multiple roots", which seems to specifically refer to multiple root _components_.

Am I correct in that there's no way to inspect the viewless Vue objects, and does this use case make sense?

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this[ template](http://codepen.io/pen?template=PWbYJO)? Root get displayed when I test in Devtools
Thanks!

**Comment by Eiskis** [comment]
You are right, I can see <root> both there and in my project now. I don't know if there was something up with my dev tools or if I'm really just that blind I didn't see it. Totally makes sense now. For multiple roots #98 is the right ticket, I'll just close this one as I can't even reproduce it myself right now.

**Comment by posva** [comment]
Maybe it got fixed in the mean time 😆

**Comment by Eiskis** [comment]
Looks like I'm not blind, I have a project where sometimes I see `<Root>`, sometimes I don't. It seems to come and go as I open/close the dev tools, and/or if I reload the application.

I will try to reproduce with a simple application, but there's definitely something up with this.
