### ISSUE TITLE
[Firefox] StateInspector content doesn't scroll properly

### ISSUE THREAD

**Issue by mtpc** [vuejs/vue-devtools#355]
This is due to `ScrollPane.vue`'s css `overflow` property being set to `overlay`, which is a non-standard webkit property unsupported in firefox.

Afaik it's supposed to behave exactly like `overflow: auto`, which makes me wonder why `overlay` was chosen in the first place

**Comment by Zetaphor** [comment]
Added #359 that appears to resolve this issue. Can please someone take a look?

**Comment by gluons** [comment]
I really need this to be fixed. The most annoying issue that bother me.
