### ISSUE TITLE
Vue.js not detected on moz-extension:// pages

### ISSUE THREAD

**Issue by dessant** [vuejs/vue-devtools#363]
WebExtensions can serve local pages at moz-extension://*, but Vue does not seem to be detected on them. The same happens with add-on preferences at about:addons.

Tested with Firefox 55 and Vue.js devtools 3.1.5.

**Comment by clarkbw** [comment]
This is by design at the moment.  In Firefox content scripts are only injected in web pages (and some of the "about:" pages, the non privileged ones).  Without the content scripts the detection cannot work.

**Comment by dessant** [comment]
@clarkbw, you're right. A related issue for Chromium is marked as WontFix: https://bugs.chromium.org/p/chromium/issues/detail?id=30756.
