### ISSUE TITLE
[Firefox] No VueJS tab in developer tools

### ISSUE THREAD

**Issue by manniL** [vuejs/vue-devtools#366]
OS: Ubuntu 17.04 zesty
Firefox Version: 54.0 (64 bit)
VueJS dev tools version: 3.1.5 (official one)

After using the VueJS dev tools for a while, it happend to me that the Vue tab doesn't pop up in the developer tools anymore. It doesn't work on any site which uses Vue (in dev mode). In Google Chrome, the tools work as before. Other Dev Tools (like React) do work too.

![image](https://user-images.githubusercontent.com/640208/27906486-049811a4-6244-11e7-8b81-8eb40e4acacf.png)

**Comment by manniL** [comment]
However, it started working for me again.

Still letting this open because it looks like people having this issue too (#367)

**Comment by ypeskov** [comment]
Firefox 54.0 (x64) Ubuntu 16.04  
I have the same issue. Vue is detected on but the panel is absent
![vue-absent](https://user-images.githubusercontent.com/5215834/28383691-bb7423c8-6cca-11e7-98d1-a6af606d202b.png)

Any ideas?

**Comment by TehTotalPwnage** [comment]
Yeah, this is a very mysterious issue.

I installed the Vue DevTools yesterday and had the same issue occur with the missing tab. But it's here now, about 24 hours later.

**Comment by ypeskov** [comment]
I have resolved the issue (at least for myself).

The tab appears after removing React Devtools extension. It seems they are in a conflict.

**Comment by GeekJosh** [comment]
@ypeskov thank you! It's a shame that we can't use both tools simultaneously but so grateful for a workaround

**Comment by TehTotalPwnage** [comment]
Hmm, that makes me wonder about whether or not this is actually two separate issues. I didn't have React Devtools installed but had the same issue with the missing menu.

**Comment by smallp** [comment]
Same issue. Ubuntu 17.04 x64, Firefox Version: 53.0.2 (64 bit). I have disabled all other extensions. However, it still not shows. Click the botton in toolbar, it shows "Vue.js is detected on this page. Open DevTools and look for the Vue panel. "

**Comment by Jantho1990** [comment]
Same issue. Ubuntu 16.04 x64, Firefox Version: 54.0 (64bit).

**Comment by hbielenia** [comment]
Same issue. Debian Buster, Firefox 52.2.0 ESR (64-bit). Don't have React DevTools.

I thought that maybe WebSockets extension conflicts with Vue DevTools in a similar way, but disabling it didn't solve the issue.

**Comment by i-erokhin** [comment]
Same issue. Version 3.6.1, Firefox 52.3.0 (64-bit), Debian 9.1

![screenshot from 2017-08-11 14-04-35](https://user-images.githubusercontent.com/9545969/29211031-4006a148-7e9f-11e7-9f87-731205f66104.png)
![screenshot from 2017-08-11 14-05-12](https://user-images.githubusercontent.com/9545969/29211036-470dd484-7e9f-11e7-8083-db04ea52bec8.png)
![screenshot from 2017-08-11 14-06-12](https://user-images.githubusercontent.com/9545969/29211038-470ff098-7e9f-11e7-9aec-e70133fdd327.png)
![screenshot from 2017-08-11 14-11-48](https://user-images.githubusercontent.com/9545969/29211037-470f8b30-7e9f-11e7-9d3f-a4c8289dbd93.png)

**Comment by Anand-Moghe** [comment]
I am having same issue today August 29, 2017. 
I had VueJS developer extension working in firefox and now suddenly stopped working. I reinstalled the firefox using brew cask install and the version is 55.0.3 (64-bit). Still no extension tab is visible to debug VueJS in firefox.  But I can see that the VueJS is enabled on the toolbar.

**Comment by 01BTC10** [comment]
Same problem with Firefox ESR 52.3.0

I reset the browser to default then reinstalled the extension. I got this log in the console:

> TypeError: can't redefine non-configurable property "__VUE_DEVTOOLS_GLOBAL_HOOK__"  localhost:8000:66:3
	installHook http://localhost:8000/:66:3
	<anonymous> http://localhost:8000/:1:12
	[17] jar:file:///home/r2d2/.mozilla/firefox/bsfzuii9.default/extensions/%7B5caff8cc-3d2e-4110-a88a-003cc85b3858%7D.xpi!/build/hook.js:80:1
	__webpack_require__ jar:file:///home/r2d2/.mozilla/firefox/bsfzuii9.default/extensions/%7B5caff8cc-3d2e-4110-a88a-003cc85b3858%7D.xpi!/build/hook.js:20:12
	<anonymous> jar:file:///home/r2d2/.mozilla/firefox/bsfzuii9.default/extensions/%7B5caff8cc-3d2e-4110-a88a-003cc85b3858%7D.xpi!/build/hook.js:63:18
	<anonymous> jar:file:///home/r2d2/.mozilla/firefox/bsfzuii9.default/extensions/%7B5caff8cc-3d2e-4110-a88a-003cc85b3858%7D.xpi!/build/hook.js:1:11

**Comment by 01BTC10** [comment]
After some more digging I found out that Debian ship with Firefox ESR. I installed Firefox instead and now it works fine.

**Comment by blackinitial** [comment]
The fixes solution is **disable addons vue-devtools** in firefox **and restore again**.

**Comment by fanyer** [comment]
@ypeskov  react devtool has conflicts with vue devtool

**Comment by hanxue** [comment]
Confirm that the workaround is to **disable vue-devtools**, then restart Firefox's developer tool again. 

OS: macOS 10.10.5
Firefox: 55.0.3
React Developer Tools: 2.5.0
Vue.js Devtools: 3.1.6

**Comment by neithere** [comment]
Confirming that this solves the problem:
1. Close devtools
2. Disable Vue.js devtools add-on
3. Enable it again
4. Open devtools

OS: GNU/Linux (ArchLinux)
Firefox: 55.0.3 (64-bit)
Vue.js devtools: 3.1.6
No React-related add-on installed.

**Comment by vizvamitra** [comment]
Solution above doesn't work in vivaldi 1.12.955.48, Ubuntu 16.04

**Comment by benheu** [comment]
**Confirming** as @neithere :

1.     Close devtools
2.     Disable Vue.js devtools add-on
3.     Enable it again
4.     Open devtools

OS: Ubuntu 16.04 LTS
Firefox: 56.0 (64-bit)
Vue.js devtools: 3.1.6
No React-related add-on installed.

I **also had the problem in Chrome(62)**, and the same trick solved it.

**Comment by gima** [comment]
The trick works (disable,enable the extension & re-open devtools).

Not sure if this is relevant, but web page's console shows this after enabling the extension:

![image](https://user-images.githubusercontent.com/1252061/33102034-9da3d27e-cf23-11e7-953f-02bbcfe3fbee.png)

**Comment by kslstn** [comment]
Same issue in Firefox for Mac 57.0. The disable/enable workaround doesn't work for me. Uninstall, install does however.

**Comment by cedricium** [comment]
I too am seeing the same error @gima showed. Following the above four steps that has been suggested to get the Vue.js devtools working does not work on my machine.

**Comment by mikaelhadler** [comment]
Hello guys, i seeing the same error @gima. 

I tried the above steps without success.

![error-firefox-57 0 3](https://user-images.githubusercontent.com/6784777/34495380-0f1ada64-efdc-11e7-9222-69f9db9af08d.PNG)

Vue.js devtools 3.1.7, Firefox 57.0.3 (32-bit), Windows.

**Comment by lomelisan** [comment]
I had the same problem in Xubuntu 64bit Firefox 58.0.1. Tried everything you said here but it didn't help me. I finally solved using the dist cdn "https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js" instead of the regular cdn "https://cdn.jsdelivr.net/npm/vue"...

**Comment by fonfon** [comment]
Same issue here:
Firefox ESR 52.3.0 (64-bit) on Debian jessie;
Disabling/enabling doesn't work for me.

**Comment by shrekting** [comment]
same issue, ff 58.02, adds-on, 4.1.3

**Comment by jonathanmusto** [comment]
same, ff quantum 58.0.2, osx 10.13.3, addon 4.1.3

**Comment by morcegon** [comment]
Same here:
ff quantum 60.0b5, osx 10.13.3, addon 4.1.4

**Comment by lomelisan** [comment]
I have posted the solution for my case here. Hope it works for yours too. https://stackoverflow.com/questions/49640076/no-vuejs-tab-in-firefox-developer-tools/49640077?noredirect=1#comment86288081_49640077

**Comment by SedemQuame** [comment]
was having the same problem, solved it by restarting the developer console.
closing and currents tabs using the inspector or console

**Comment by MiguelAtTweddle** [comment]
> 
> 
> I have resolved the issue (at least for myself).
> 
> The tab appears after removing React Devtools extension. It seems they are in a conflict.

Instead of removing you can disable React DevTools.

**Comment by SedemQuame** [comment]
okay thanks for the info will try it out

**Comment by AliN11** [comment]
My problem solved by using non-minified version.

**Comment by aneurysmjs** [comment]
> Confirming that this solves the problem:
> 
> 1. Close devtools
> 2. Disable Vue.js devtools add-on
> 3. Enable it again
> 4. Open devtools
> 
> OS: GNU/Linux (ArchLinux)
> Firefox: 55.0.3 (64-bit)
> Vue.js devtools: 3.1.6
> No React-related add-on installed.

yeah, it solved for me

**Comment by problemmaths** [comment]
I am having the same issue.  Vue is recognised but does not appear in the devtools as a tab.  None of the above solutions have worked for me.

**Comment by markpesantes** [comment]
@problemmaths What worked for me is going to dev tools settings (top right corner 3 dots icon), find the section _Developer tools installed by add-ons_ and toggle the Vue.js devtools checkbox on & off while on the page

**Comment by jclopmel** [comment]
Happens the same here but, after a navigator restart and opening a Vue.js project, it perfectly worked. Try it!

**Comment by DrCardamom** [comment]
If you are using firefox and having this problem, disable Firefox DevTools ADB Extension. The tab finally shoed up for me by doing so

**Comment by Inffinite** [comment]
> OS: Ubuntu 17.04 zesty
> Firefox Version: 54.0 (64 bit)
> VueJS dev tools version: 3.1.5 (official one)
> 
> After using the VueJS dev tools for a while, it happend to me that the Vue tab doesn't pop up in the developer tools anymore. It doesn't work on any site which uses Vue (in dev mode). In Google Chrome, the tools work as before. Other Dev Tools (like React) do work too.
> 
> ![image](https://user-images.githubusercontent.com/640208/27906486-049811a4-6244-11e7-8b81-8eb40e4acacf.png)

Just close all tabs in the browser and launch it again. Problem solved.

**Comment by Bac3Phi** [comment]
disable React Developer Tools, it worked for me <3

**Comment by femaimi9527** [comment]
> 
> 
> OS: Ubuntu 17.04 zesty
> Firefox Version: 54.0 (64 bit)
> VueJS dev tools version: 3.1.5 (official one)
> 
> After using the VueJS dev tools for a while, it happend to me that the Vue tab doesn't pop up in the developer tools anymore. It doesn't work on any site which uses Vue (in dev mode). In Google Chrome, the tools work as before. Other Dev Tools (like React) do work too.
> 
> ![image](https://user-images.githubusercontent.com/640208/27906486-049811a4-6244-11e7-8b81-8eb40e4acacf.png)

Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

**Comment by Akryum** [comment]
@femaimi9527 Spamming closed issues won't get you help 😕

**Comment by Kyrluckechuck** [comment]
Has anyone been able to locate a workaround or would it make more sense at this point to create a new issue for tracking this incompatibility?

**Comment by jerrychong25** [comment]
For me, I managed to make it working by:
1. Close all Vue.js websites
2. Close DevTools
3. Disable Vue.js DevTools add-on
4. Enable DevTools again
5. Open DevTools

**Comment by ahmy1996404** [comment]
open devtool or right click then inspect element  then press 'F1'  then mark on Vue.js dev tools under the `Developer tools installed by add-ons`

**Comment by mitestainer** [comment]
> 
> 
> open devtool or right click then inspect element then press 'F1' then mark on Vue.js dev tools under the `Developer tools installed by add-ons`

This worked for me, thanks!

**Comment by uros-5** [comment]
try this:

![vue_disabled_firefox](https://user-images.githubusercontent.com/59397844/103088586-8bcc8680-45eb-11eb-98b9-b975b4586e2d.png)
