### ISSUE TITLE
Can not find the Vue panel. 

### ISSUE THREAD

**Issue by zppro** [vuejs/vue-devtools#367]
OS: CentOS 7.2 
Firefox Version: 52.2 (64 bit)
VueJS dev tools version: 3.1.5 (official one)

![2017-07-07 09-24-56](https://user-images.githubusercontent.com/706344/27939371-c86c3c92-62f6-11e7-9699-aff7f2fcc63d.png)

**Comment by posva** [comment]
dup of #366
