### ISSUE TITLE
[Firefox] Add dark theme support

### ISSUE THREAD

**Issue by avrelaun** [vuejs/vue-devtools#373]
Port dark theme detection to Firefox. Currently I have the dark theme enabled in FF devtools but Vue devtools are light/white/bright.

**Comment by hultberg** [comment]
With nightly (56) my vue devtools is dark as the devtools window.
![2017-07-14_553x100](https://user-images.githubusercontent.com/1257913/28208111-79ec8310-688c-11e7-8a44-cecca20874d8.png)

**Comment by avrelaun** [comment]
I'm running stable (54.0.1) with the dev theme.
![vue-dark-ff](https://user-images.githubusercontent.com/412102/28260496-9944ada4-6adb-11e7-94d2-737b39ba51b9.png)

**Comment by hultberg** [comment]
@avrelaun Could you try to install nightly and attempt to open vue devtools with dark dev theme? https://www.mozilla.org/en-US/firefox/nightly/all/

**Comment by avrelaun** [comment]
@hultberg It is indeed dark in nightly.
