### ISSUE TITLE
Vue.js not detected with Babel plugin

### ISSUE THREAD

**Issue by JonathanTroyer** [vuejs/vue-devtools#376]
After adding the [function bind transform](https://babeljs.io/docs/plugins/transform-function-bind/) to Babel the devtools no longer detect Vue in Chrome 59. However, it still functions properly in Firefox 54.

**Comment by posva** [comment]
Please follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) and provide a minimal JSFiddle or Github repository containing a set of reproducible steps that can lead to the behaviour you described. Make sure to boil down the problem as much as possible. Thanks!

**Comment by JonathanTroyer** [comment]
Closing as I can no longer reproduce the issue in the original code. Turning it off an on again really does wonders.
