### ISSUE TITLE
windows用户用这个chrome插件内存会越占越多

### ISSUE THREAD

**Issue by peakchen90** [vuejs/vue-devtools#377]
windows用户用这个chrome插件内存会越占越多，最后直接卡死。

**Comment by qianxinfeng** [comment]
mac也会

**Comment by posva** [comment]
You can stop event and vuex mutations recording by clicking the red circle

**Comment by qianxinfeng** [comment]
@posva thanks

**Comment by wooderpecker** [comment]
how to fix the problems

**Comment by huyansheng3** [comment]
great !

**Comment by xssxxssx** [comment]
yes,i'do

**Comment by Xmb-form** [comment]
在Mac上 使用经常性导致浏览器假死，消耗运行内存，过一会Vue-devtools崩溃
