### ISSUE TITLE
Icon missing in Firefox Developer Edition

### ISSUE THREAD

**Issue by AdrianDuan** [vuejs/vue-devtools#381]
My environment
Browser: Firefox Developer Edition 55.0b13 (64 bit)
Vue.js Devtools: 3.1.6
<img width="1627" alt="_ _vue_js" src="https://user-images.githubusercontent.com/26034046/28745632-c53eb6fc-74ae-11e7-986a-19f34383877a.png">

**Comment by caugner** [comment]
Duplicate of #366

**Comment by posva** [comment]
Thanks for signaling it @caugner  🙂

**Comment by femaimi9527** [comment]
Devtools inspection is not available because it's in production mode or explicitly disabled by the author.
