### ISSUE TITLE
Safari certificate missing

### ISSUE THREAD

**Issue by mitramejia** [vuejs/vue-devtools#383]
It would be great not having to reinstall the extension. Is there a way to overcome this? can we just use a self signed certificate or something like that?

![extension_builder](https://user-images.githubusercontent.com/2616517/28790873-9942c318-75f8-11e7-9c5e-48e8ac889656.jpg)

**Comment by iBobik** [comment]
Maintainers needs to issue trusted certificate from Apple: https://knackforge.com/blog/karalmax/how-create-safari-extension-certificate

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.

**Comment by ceesco53** [comment]
Would it be a problem if I just go ahead and publish this on the App Store for free?  I've got an Apple id dev account and can pretty much update this with releases.  If it isn't a problem I'll just use these for the Information fields:

Display Name: Vue.js devtools
Author: Jared Hobbs
Description: Safari extension for debugging Vue.js applications.
Website: https://github.com/vuejs/vue-devtools
