### ISSUE TITLE
Vue.js not detected when bundled

### ISSUE THREAD

**Issue by agrath** [vuejs/vue-devtools#386]
It appears that when you bundle vue.js (locally) with other JS files so you end up with a xyz.bundle.js that includes vue.js inline; the vue devtools does not detect vue.js with an error:
![image](https://user-images.githubusercontent.com/78284/28950676-18b23790-791a-11e7-992f-03d2a1bffd0d.png)
yet the JS bundle file definitely includes and loads vue.js
![image](https://user-images.githubusercontent.com/78284/28950686-2f328a7e-791a-11e7-910d-6836e2d848d5.png)

Perhaps a fallback to check if window.Vue exists if there is no script include for Vue.js?

**Comment by posva** [comment]
This is probably because you used a production version of Vue that purposely disable the devtools (https://vuejs.org/v2/api/#devtools)
