### ISSUE TITLE
Overlapping text and icons

### ISSUE THREAD

**Issue by chrisprior1995** [vuejs/vue-devtools#389]
<img width="325" alt="screen shot 2017-08-09 at 10 42 22" src="https://user-images.githubusercontent.com/22473727/29115439-99a4dd7a-7cef-11e7-983f-2493eef846e7.png">

**To reproduce:**
- Go for example on the Vuex tab
- make sure the application has triggered several Vuex events (actions or mutation)
- reduce the width of extension, forcing the lines to wrap

**I would expect** 
- That the lines would be pushed down and given additional height, so that they are still readable and clickable.
 
**Instead** 
The lines overlap or produce other weird behaviors as shown in the screenshot attached.

**Comment by crcatala** [comment]
Hello! First timer here 👋 I’d like to help out with this issue. Is there specific implementation you had in mind?
