### ISSUE TITLE
Fonts in Safari Extension

### ISSUE THREAD

**Issue by Johnathan** [vuejs/vue-devtools#390]
<img width="811" alt="screen shot 2017-08-09 at 22 15 51" src="https://user-images.githubusercontent.com/144165/29144334-79d131d6-7d50-11e7-9d7b-a04db0c1e20e.png">

This is how it's looking for me in Safari 10.1.2 on OSX 10.11.6

I've given it access to all domains and the actual data and stuff is correct it just doesn't seem to be loading fonts properly.

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.
