### ISSUE TITLE
An idea of making vue-devtools work with iframes

### ISSUE THREAD

**Issue by crimx** [vuejs/vue-devtools#396]
As far as I understand, vue-devtools hooks `__VUE_DEVTOOLS_GLOBAL_HOOK__` in a page's `window`, then manipulates it through `src/backend`. 

I don't see why not make it work with iframes throungh `all_frames` [option](https://developer.chrome.com/extensions/content_scripts) on chrome. The hooks work the same, except the front end part might change to lazy connection with the hook that is selected by user.

**Comment by posva** [comment]
Hmm, the `all_frames` doc isn't very clear to me. Wouldn't this run a copy of the extension in every iframe?

**Comment by crimx** [comment]
@posva with all_frames you can run the specific content script in every frame, not just the toppest one.

**Comment by posva** [comment]
ok, I'll have to take a look at that option

**Comment by davinov** [comment]
This would be quite useful, especially with the recent release of vue storybooks (which uses iframes).
@posva I'd be happy to help if needed!

**Comment by posva** [comment]
I started some work on the iframes branch but it experimental and doesn't work correctly yet. Feel free to give it a look and improve it 😄

**Comment by wmichelin** [comment]
This would be super helpful!

**Comment by Akryum** [comment]
Let's close this in favor of #353.
