### ISSUE TITLE
Vue 1 events are not recorded

### ISSUE THREAD

**Issue by leighman** [vuejs/vue-devtools#397]
Are all features supported when using Vue 1?
I do not see any events in the Events tab even when using `$emit()`.

**Comment by DannyFeliz** [comment]
I have this issue too 😢, I need this to be able to work.

**Comment by Akryum** [comment]
Testing on [this app](https://github.com/Akryum/vue-devtools/blob/vue1-compat/vue1-test.html), I get the events recorderd fine:

![capture d ecran du 2018-01-20 13 28 01](https://user-images.githubusercontent.com/2798204/35183400-c5feb838-fde5-11e7-95cc-5502cb9fc7fe.png)

**Comment by leighman** [comment]
For us, this was caused by importing `vue/dist/vue.min.js`. Switching to `import Vue from 'vue'` made it work.

**Comment by Akryum** [comment]
See [the Readme](https://github.com/vuejs/vue-devtools#important-usage-notes).
