### ISSUE TITLE
vue pane not showing?

### ISSUE THREAD

**Issue by mark-hahn** [vuejs/vue-devtools#4]
I'm trying vue-devtools for the first time on a simple app and I can't see any new pane in dev tools.  Isn't it supposed to be to the right of the properties pane I've got selected here?

![screenshot 2015-05-07 at 10 23 13 pm](https://cloud.githubusercontent.com/assets/811455/7531011/ba3ee0e8-f507-11e4-9512-ae23c8b0ccc6.png)

![screenshot 2015-05-07 at 10 34 14 pm](https://cloud.githubusercontent.com/assets/811455/7531093/3dc33256-f509-11e4-89bd-27273e64938f.png)

Google Chrome 42.0.2311.134 (Official Build) (64-bit)
On Ubuntu 14.04

**Comment by mark-hahn** [comment]
I forgot to say it is version 0.11.10 of Vue.

**Comment by yyx990803** [comment]
Hmm this is weird, probably has nothing to do with the version of Vue itself. What version of Chrome/OS are you running?

**Comment by mark-hahn** [comment]
Version 42.0.2311.134 (64-bit)
Platform 6812.83.0 (Official Build) stable-channel samus
Firmware Google_Samus.6300.103.0

BTW, I just happened to wipe my chromebook this morning.  Maybe it will
work now (long shot).  I'll let you know if the problem persists.

**Comment by yyx990803** [comment]
Most likely a Chromebook-related issue (the extension API/environment could be slightly different). Unfortunately I don't have a Chromebook to test on at the moment...

**Comment by mark-hahn** [comment]
Maybe you could remote desktop in?

**Comment by mark-hahn** [comment]
Wow.  My hunch was right.  Wiping my chromebook and reinstalling everything fixed the problem.  Go figure.

Thanks for your trouble.
