### ISSUE TITLE
Got error when click on a component which created before vue-router installed.

### ISSUE THREAD

**Issue by UncleBill** [vuejs/vue-devtools#406]
![image](https://user-images.githubusercontent.com/1141198/29958135-ba59b842-8f23-11e7-9790-94bd17c0f75a.png)

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this [template](http://codepen.io/pen?template=PWbYJO)?
Thanks!

**Comment by UncleBill** [comment]
@posva Can't provide one with codepen or some other online environment. Because, they all add vendor scripts before user code.

I write a example:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>testvue</title>
  </head>
  <body>
      <div id="before-router-installed"></div>
      <div id="after-router-installed"></div>

      <script type="text/javascript" src='https://unpkg.com/vue@2.4.2/dist/vue.js'></script>
      <script type="text/javascript">
          // this instance doesn't require vue-router
          new Vue({
              name: 'before-router-installed',
              el: '#before-router-installed'
          })
      </script>
      <!-- then install vue-router -->
      <script type="text/javascript" src='https://unpkg.com/vue-router@2.7.0/dist/vue-router.js'></script>
      <script type="text/javascript">
          new Vue({
              name: 'after-router-installed',
              router: new VueRouter([]),
              el: '#after-router-installed'
          })
      </script>
  </body>
</html>
```

Open it as a html file in your browser, then open `dev-tools`, and click on the `BeforeRouterInstalled` instance.

![image](https://user-images.githubusercontent.com/1141198/29979582-aac91bca-8f78-11e7-988d-74f2d96d43e9.png)

**Comment by UncleBill** [comment]
It's should be an issue of `vue-router` instead.

**Comment by posva** [comment]
` router: new VueRouter([]),` should be ` router: new VueRouter({ routes: [] }),`
An HTML file is absolutely fine 🙂

**Comment by UncleBill** [comment]
> router: new VueRouter([]), should be router: new VueRouter({ routes: [] }),
Oh, it's my mistake. But it doesn't interrelate the issue.

**Comment by UncleBill** [comment]
It's still `need-repro". Is there any problem to reproduce this?

**Comment by posva** [comment]
Sorry, I just didn't have the time to check 🙂 
It's actually not a bug on the devtools but rather something that happens in vue-router. You can trigger it without the devtools with a created hook in the first instance:

```js
created () {
    this.$route // boom
}
```

edit: It may not happen all the time because of a race condition probably

But at the same time, you're using Vue twice in your code but only installing vue-router after initializing a part of your application... So, I don't really know if we want to support it. Eitherways, you can open an issue on vue-router, you can put this in a fiddle:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>testvue</title>
  </head>
  <body>
      <div id="before-router-installed"></div>
      <div id="after-router-installed"></div>

      <script type="text/javascript" src='https://unpkg.com/vue@2.4.2/dist/vue.js'></script>
      <script type="text/javascript">
        // this instance doesn't require vue-router
        new Vue({
          name: 'before-router-installed',
          el: '#before-router-installed',
          mounted () {
            setTimeout(() => {
              console.log(this.$router)
            }, 300)
          }
        })
      </script>
      <!-- then install vue-router -->
      <script type="text/javascript" src='https://unpkg.com/vue-router@2.7.0/dist/vue-router.js'></script>
      <script type="text/javascript">
          new Vue({
              name: 'after-router-installed',
              router: new VueRouter({ routes: [] }),
              el: '#after-router-installed'
          })
      </script>
  </body>
</html>
```

**Comment by UncleBill** [comment]
>Sorry, I just didn't have the time to check :slightly_smiling_face:

It's OK!

>It's actually not a bug on the devtools but rather something that happens in vue-router.

Same thought. I will submit an issue on `vue-router` later.

Thanks!
