### ISSUE TITLE
Vue Devtools not capturing initial vuex commits

### ISSUE THREAD

**Issue by skovmand** [vuejs/vue-devtools#408]
Hi.

I have a simple application which fetches users on initialization. This uses the `FETCH_USERS` action and commits the mutation `USERS_FETCHED` when done. I never see this commit in the devtools, presumably because the devtools are not ready yet.

In the example below I use setTimeout to wait 500ms. Then the commit always shows in the devtools. 

It would be very nice if this could be avoided. Am I doing something wrong? The same problem is referenced here: https://github.com/vuejs/vue-devtools/issues/124 however the issue was closed with the message that the devtools should be open, then the page should be refreshed. But it doesn't solve the problem.

This is my `main.js`, which dispatches the action that doesn't show up as a commit:

```js
import Vue from "vue";
import VueRouter from "vue-router";
import Vuex from "vuex";

import { FETCH_USERS } from "./store";

import styles from "./styles.css";
import routes from "./routes";

import Application from "./components/Application";
import store from "./store";

Vue.use(VueRouter);

const router = new VueRouter({
  mode: "history",
  routes
});

new Vue({
  el: "#app",
  store,
  render: h => h(Application),
  router,
  created() {
    this.$store.dispatch(FETCH_USERS);
  }
});
```

if I change the initialisation to the following, the initial event is captured.

```js

setTimeout(
  () =>
    new Vue({
      el: "#app",
      store,
      render: h => h(Application),
      router,
      created() {
        this.$store.dispatch(FETCH_USERS);
      }
    }),
  500
);
```

Can I fix this in some way?

Oh, and by the way, I'm running Chrome 61.

Thanks for your great work!

![screenshot from 2017-09-11 13-51-53](https://user-images.githubusercontent.com/1387518/30273240-745989bc-96f8-11e7-9666-369ddd985260.png)

---

repro:

```html
<html>
<head>
  <title>Welcome to Vue</title>
  <script src="https://unpkg.com/vue"></script>
  <script src="https://unpkg.com/vuex"></script>
</head>
<body>
  <div id="app">
  </div>

  <script>
  function webRequest() {
    return {username: 'vuejs-hackman'};
  }
  var store = new Vuex.Store({
    state: {
      user: {}
    },
    mutations: {
      STORE_DATA(state, payload) {
        console.log('irun');
        window.localStorage.setItem("user", JSON.stringify(payload));
        state.user = payload;
      }
    },
    actions: {
      loadUser: function (ctx, payload) {
        ctx.commit('STORE_DATA', payload)
      }
    }
  });

  var app = new Vue({
    el: '#app',
    store: store,
    methods: {
      initUser: function(user) {
        // this.$store.commit('STORE_DATA', user);
        this.$store.dispatch('loadUser', webRequest());
      },
      loadUser: function() {
        // this.$store.dispatch('loadUser', webRequest());
        this.$store.commit('STORE_DATA', {user:'hi'});
      }
    },
    template: '<button @click="loadUser">click</button>',
    created: function() {
      const user = window.localStorage.getItem("user");
      if (user) {
        this.initUser(JSON.parse(user));
      }
    }
  })
  </script>
</body>
</html>
```

**Comment by skovmand** [comment]
Could it have anything to do with the devtools not being ready? Just an idea.
When using Redux devtools it is open in a separate window from Chrome. So maybe it is ready sooner than if you're using a devtool integrated in Chrome. On the other hand, the Network-tab doesn't have that problem.

**Comment by posva** [comment]
Hey, really sorry for the delay. Do you have a boiled down repro for this (an HTML file is enough)

**Comment by naringas** [comment]
it seems that if i commit a mutation from `created` that mutation is never shown in the vuejs devtools.
The following is my attempt at a single file reproduction, I also tested in firefox to the same result

`<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Vue</title>
  <script src="https://unpkg.com/vue"></script>
  <script src="https://unpkg.com/vuex"></script>
</head>
<body>
  <div id="app">
  </div>

  <script>
  function webRequest() {
    return {username: 'vuejs-hackman'};
  }
  var store = new Vuex.Store({
    state: {
      user: {}
    },
    mutations: {
      STORE_DATA(state, payload) {
        console.log('irun');
        window.localStorage.setItem("user", JSON.stringify(payload));
        state.user = payload;
      }
    },
    actions: {
      loadUser: function (ctx, payload) {
        ctx.commit('STORE_DATA', payload)
      }
    }
  });

  var app = new Vue({
    el: '#app',
    store: store,
    methods: {
      initUser: function(user) {
        // this.$store.commit('STORE_DATA', user);
        this.$store.dispatch('loadUser', webRequest());
      },
      loadUser: function() {
        // this.$store.dispatch('loadUser', webRequest());
        this.$store.commit('STORE_DATA', {user:'hi'});
      }
    },
    template: '<button @click="loadUser">click</button>',
    created: function() {
      const user = window.localStorage.getItem("user");
      if (user) {
        this.initUser(JSON.parse(user));
      }
    }
  })
  </script>
</body>
</html>
`

p.s. I hope this is useful, but I'm uncertain due to being new too new to vue.js

**Comment by digitalle** [comment]
@posva @skovmand thanks for the setTimeout suggestion - this was causing me some serious head scratching! I too am trying to set some initialised data on create whereby I have an incoming "navID" which I then use to query the state of nav objects before updating/changing them to "on", but this was processing before the dev tools were "seeing" it. 
This any closer to being fixed as obs not ideal to have to slow down an application! And as you point out, the network tab is monitoring everything throughout the entire life-cycle, so I doubt it is a problem with Chrome.

**Comment by nickknissen** [comment]
I have have had create success with 
```js
const app = new Vue({
  store,
  router,
  ...App,
});

if (process.env.NODE_ENV !== 'production') {
  setTimeout(() => { app.$mount('#app'); }, 500);
} else {
  app.$mount('#app');
}
```

**Comment by galenjiang** [comment]
same issue!

**Comment by exarus** [comment]
same issue! Just simple `vue-cli` template

**Comment by mjbates7** [comment]
I also have this issue when running on the new vue-cli 3. It won't register the initial mutations in the devtools as a heads up.

**Comment by mustafaekim** [comment]
I had the same problem and solved it by delaying the "created" by one tick.

```ts
  created() {
    this.$nextTick(()=> {
      this.init();
    })    
  },
```

**Comment by MartinYounghoonKim** [comment]
Nobody solved this problem without nextTick or setTimeout ?

**Comment by axit-joost** [comment]
@MartinYounghoonKim 

Ran into this problem today. There has been a Merge Request (#723) that remembers the initial mutations. I just updated to a beta of the Vue.js Dev Tools

**Comment by chanmathew** [comment]
> @MartinYounghoonKim
> 
> Ran into this problem today. There has been a Merge Request (#723) that remembers the initial mutations. I just updated to a beta of the Vue.js Dev Tools and can confirm that it works.
> 
> https://github.com/vuejs/vue-devtools/releases

Having this problem too when dispatching actions in `nuxtServerInit`, which version did you install?

**Comment by stouch** [comment]
Still having the problem...
