### ISSUE TITLE
Value from Component's Data are not refreshed in live mode

### ISSUE THREAD

**Issue by thibaud-be** [vuejs/vue-devtools#41]
I have a data object inside a component. the data is returned by a function as suggested in the exemple here:
http://vuejs.org/guide/components.html#Component_Option_Caveats

Issue:
with vue devtools in live mode, that data value is not properly refreshed when the value changes.

Workaround:
disabling the live mode and hitting refresh after the vale has changed does work.

I started using vue a couple of days ago, I'm liking it alot so far. thanks a lot :)

**Comment by yyx990803** [comment]
Hmm, I'll need a bit more information as this is supposed to work. Make sure that:

1. You've updated to the latest version of vue-devtools (1.0.4)
2. There's no error in the console

If both 1 and 2 are true, then it's most likely the data itself is not properly reactive...

**Comment by thibaud-be** [comment]
1. Ready detected Vue 1.04
2. Console only has one [Vue warn] and a bunch of 404 but no real show stopper

here is what I have:
```javascript
		Vue.component('actorcomp', {
			props: ['actor','subjectindex'],
			data: function() {
				return {actorData: {}};
			},
			created: function() {
				this.loadActorData(this.subjectindex);
			},
			methods: {
				loadActorData: function(index) {
					//loading data here
					}
				},
				actorDataLoaded: function(result) {
					this.actorData = JSON.parse(result);
				}
			},
			watch: {
				subjectindex: function(newVal, oldVal) {
					this.loadActorData(newVal);
				}
			},
			template: '<div class="group"><h3>{{actor.label}}</h3><div class="icon icon-{{actor.key}}"></div></div>'
		});	
```
boths props are properly refreshed but not the data.
How can I make sure that the data is reactive ?

**Comment by belisarh** [comment]
Most probably the data is actually reactive, but its reactivity it's not being used to do anything on the DOM. In this situation, clicking on the data property in question in Vue devtools would actually "wake it up" and show it's actual value. From what I can see in the template, while you using the prop, you are not referring to data anywhere on the template, thus devtools, in live mode, happily ignores it. Clicking on it should give you its current value.

**Comment by posva** [comment]
related #393

**Comment by brandonpittman** [comment]
This bit me in the ass. Wasted 30 minutes thinking my code was wrong.

**Comment by YihooIsMe** [comment]
> This bit me in the ass. Wasted 30 minutes thinking my code was wrong.

+1

**Comment by thedomeffm** [comment]
It took me 3 hours...
Bug is still there

**Comment by brandonpittman** [comment]
> It took me 3 hours...
> Bug is still there

After learning why it didn't update, I didn't consider it a bug, but it's still not what I expected to happen.

**Comment by Nanobrainiac** [comment]
If possible to implement, this might make a nice feature request.

**Comment by developius** [comment]
Yeah. When building components, I usually build the API and data structure first, before putting any elements together. It's really annoying when this bug happens because you often spend ages trying to work out why the data isn't updating (when viewing via dev tools). As a last resort, you throw the value into the DOM and voila. Extremely frustrating.

**Comment by hrsetyono** [comment]
This bug is still here, I thought there's something wrong with my code and wasted hours on it

**Comment by tombohub** [comment]
For me nothing works except refreshing the tools

**Comment by rublev** [comment]
is this fixed yet?
