### ISSUE TITLE
Suggestion: option to only show deepest route

### ISSUE THREAD

**Issue by Christilut** [vuejs/vue-devtools#410]
I'm not sure if this is just my use case or that is common so I'm just going to suggest it:

Most of the time when I'm in the dev tools, I need either the deepest `router-view` component (eg the current page I'm working on) or one of it's children (eg a component on the page I'm working on).

So it would be nice if there is a quick setting (checkbox?) that changes the component tree to only show the deepest `router-view` and all it's children. That way I don't  need to dive in past all these other irrelevant routerviews.

Simple example, this gets way more messy with larger projects:
![image](https://user-images.githubusercontent.com/3471363/30476794-6743c128-9a0b-11e7-8dc0-574e4ac0ecca.png)
With the checkbox enabled, start the root at the above selected component.

**Comment by posva** [comment]
We cannot directly skip the component tree because we may want to inspect other components used inside of that page component. We don't have an options panel yet but we may consider this once we have it
