### ISSUE TITLE
Reselect component after refresh and HMR

### ISSUE THREAD

**Issue by Christilut** [vuejs/vue-devtools#411]
If you select a component in the dev tools and refresh the page, the tree stays open (which is great!) but it would be even better if the last selected component can be reselected automatically. That way if you're testing a component (for example, to see how it responds to an ajax request every time you refresh), you can quickly see it's properties without having to move your mouse there.

This seems to happen on page refresh but HMR also.

**Comment by posva** [comment]
It's probably not possible to detect which should be the selected component when we refresh the page though.
I'm not sure if it's feasible for HMR either.
Would it be cool? yes, definitely

**Comment by benjaminpwarren** [comment]
+1
You should by able to do it by just grabbing the selected position in the hierarchy (when a component is clicked) and storing that in the extension storage, no?

**Comment by xelinel32** [comment]
> +1
> You should by able to do it by just grabbing the selected position in the hierarchy (when a component is clicked) and storing that in the extension storage, no?

Yes, I think it is possible to implement it. It would be wonderful.

**Comment by Akryum** [comment]
Added auto-expand in the tree in 6 beta 8. If anyone has issues with component not re-inspecting after page refresh or HMR, please open an issue. Thanks!
