### ISSUE TITLE
Bug: keyboard controls in components changes their position

### ISSUE THREAD

**Issue by Christilut** [vuejs/vue-devtools#412]
In the component tree, I like to move around with the keyboard (up and down arrow to move and right arrow to open components) just like in the DOM tree. 
Moving the selection with up and down arrows makes the components jump around. Seems like their index gets changed and dev tools immediately re-organizes them. This doesn't happen at all when only using the mouse. 
This happens almost every time I use the keyboard.

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this [template](http://codepen.io/pen?template=PWbYJO) or providing a simple HTML page?
Thanks!

**Comment by Christilut** [comment]
I can make a repro with the webpack template but making multiple router views in a codepen is beyond me :|

**Comment by posva** [comment]
a single html then 🙂

**Comment by posva** [comment]
Ok, good luck and thanks!
