### ISSUE TITLE
chrome dev tool not find vue

### ISSUE THREAD

**Issue by SeanBurt** [vuejs/vue-devtools#423]
I install vue-devtools by chrome app store. But, i open the vue web, the vue devtool don't show in chrome devtool.
  what's the configuration need i set ? Who can help me ? Thanks !

**Comment by posva** [comment]
You need to be running in development mode. To test you can open the devtools on the vuejs.org website

**Comment by SeanBurt** [comment]
I open the chrome dev tool, see the console log, the web work in development mode. I set the vue dev-tool , but it prompt me "Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author.".

**Comment by xuejiangjun** [comment]
I have the same problem
