### ISSUE TITLE
Is there a way to use this tool in my own vuejs boiler plate without installing anything from here?

### ISSUE THREAD

**Issue by AAhrit** [vuejs/vue-devtools#424]
Recently I made my own custom vuejs boilerplate template and I would like to use this tool but I don't want to install anything from here, is that possible? to made my owm?

**Comment by posva** [comment]
yes, search for devtools in the documentation and you'll find the relevant help. Although it should work by default if you use a dev build of Vue :)

**Comment by AAhrit** [comment]
Oh you mean and get activated if I am in development with vue? I see the menssage in the consolé with the Chrome browser, so I just install the extensión?

**Comment by AAhrit** [comment]
Thank you so much I just installed the extensión 😀

**Comment by posva** [comment]
Oh, I didn't get that you hadn't installed the extension yet 😆 .
