### ISSUE TITLE
Cannot open console while vue-devtools tab is open

### ISSUE THREAD

**Issue by jwkicklighter** [vuejs/vue-devtools#426]
Chrome devtools allows a JS console to be opened in the lower part of the screen by pressing <esc> on any tab. This does not seem to work on a recent version of vue-devtools, but it was previously fine. I am not aware of when it broke. There is a dedicated tab for the console, but this is very convenient when trying to watch Vuex and console logs/errors.

Behavior:
1. Open Chrome Devtools
2. Navigate to Vue tab
3. Press <esc>
4. JS Console pops open and immediately closes

Workaround for the moment:
1. Open Chrome Devtools
2. Navigate to any tab that is not Vue
3. Press <esc>
4. JS Console opens
5. Navigate to Vue tab
6. Do not press <esc>, console will stay open
7. Repeat 2-5 to reopen the console

**Comment by yyx990803** [comment]
What version of Chrome are you using? I cannot reproduce this with Chrome 61 on Mac.

**Comment by posva** [comment]
@yyx990803 happens in version 62. Opening the devtools with the console collapsed seems to always trigger the bug

**Comment by jwkicklighter** [comment]
@yyx990803 I'm currently 61 as well, and interestingly it seemed not to be happening for me anymore either. Found that the key is you need to have some component in the Components tab of the Vue Devtools selected. If you have not clicked on a component from the list, the console opens as expected with <ESC>.

**Comment by jwkicklighter** [comment]
I have noticed that scrolling the Vue Devtools has weird behavior while the console is open as well. It scrolls the entire devtools area rather than scrolling inside whatever element you are hovering (e.g. the Vuex pane). Makes it impossible to get to some items if the pane is too long.

**Comment by Akryum** [comment]
I can reproduce this by pressing Esc on Chrome 63 (Linux).

**Comment by Akryum** [comment]
This is a Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=772697

**Comment by jwkicklighter** [comment]
Oh great, glad it's marked as fixed!

**Comment by jwkicklighter** [comment]
Oh great, glad it's marked as fixed!
