### ISSUE TITLE
The Vuex, Events and Refresh are not clickable

### ISSUE THREAD

**Issue by pmesgari** [vuejs/vue-devtools#428]
The 4 buttons located on the top right corner of the vue-devtools are not all clickable. The Components is, Vuex is only if the mouse points to the far left side and the other two are not clickable at all.
I updated my Chrome to version 61 and since then this has happened.

**Comment by posva** [comment]
It works fine for me. Could you boil down the problem and provide a repro using this [template](http://codepen.io/pen?template=PWbYJO) or providing a simple HTML page?
Thanks!

**Comment by websmarts** [comment]
Similar issue for me too. I would add that it is also very unresponsive when trying to click on or expand components in the components tab. Search provides the only option for displaying an component other than Root and App - and search itself is pretty unresponsive and at times wont respond at all. 
I too updated to Chrome 61 recently, before update vue-devtools worked as expected. I know you need a repo but thought I would mention I too have the issue in the meantime.

**Comment by gustojs** [comment]
This may be a Windows 10 + Chrome 61 related issue. 

Results from chat.vuejs.org:

Issues for Chrome 61 / Windows 10
Works fine for Firefox / Windows 10 (same person)
Works fine for Chrome 61 / Linux
Works fine for Chrome 61 / Mac

**Comment by websmarts** [comment]
Thanks gustojs - switching to Firefox in Win 10 has done the trick for me until issue fixed in Chrome 61 ( I hadn't realised devtools was available in Firefox )

**Comment by lzl529** [comment]
I got same issue on Chrome 61 with Windows 10, Thanks gustojs advise, I switched to FireFox. hope posva solve the problem.(cause FireFox seem not clear at Chrome)

**Comment by mAAdhaTTah** [comment]
Related to #433?

**Comment by nirkki** [comment]
Seems to be related to the dual screen & zoom. I have 100% zoom on one and 150% on the other, Win 10 and Chrome 62.0.3202.62. Moving the browser window to the other screen fixed the problem. Weird enough, after that the buttons work on both screens.

**Comment by pmesgari** [comment]
@nirkki I tried, it is the same here. Double screen issue.

**Comment by posva** [comment]
Closing in favour of #433
