### ISSUE TITLE
NPM require('vue')

### ISSUE THREAD

**Issue by Francismori7** [vuejs/vue-devtools#43]
My code is not minified, how come I cannot use the devtools?

I am using this by the way:

```
window.Vue = require('vue');

require('vue-resource');`
```

Running browserify on it then.

**Comment by yyx990803** [comment]
Make sure you are using 1.0+, and serving the app over HTTP.

**Comment by Francismori7** [comment]
I am using 1.0.7, the Devtools tells me it is found. And using HTTP of course. I just don't get any components in the list.

**Comment by yyx990803** [comment]
Are you mounting the root component asynchronously?

**Comment by Francismori7** [comment]
No, the Vue element is attached to the body itself.

**Comment by yyx990803** [comment]
Ah, that's it... for now mount it on a childNode of body. It will be fixed in next version.

**Comment by Francismori7** [comment]
Alright!

**Comment by yyx990803** [comment]
Fixed in 1.0.5, should be pushed out within an hour.
