### ISSUE TITLE
Unresponsive clicks with multiple screens

### ISSUE THREAD

**Issue by dmmikkel** [vuejs/vue-devtools#433]
When opening vue devtools it renders fine, but will not let me click anything and it is generally unresponsive.

After a lot of trial and error I am not closer to finding the reason behind this, but I have found a solution which works 100% of the time. By dragging the devtools window from my main monitor to my laptop monitor and back it starts working as normal.

Same thing happens for all vue projects.

I have 100% scaling on main monitor and 150% scaling on laptop monitor.
I am using Chrome (Version 61.0.3163.100 (Official Build) (64-bit)) on Windows 10.

**Comment by jasonlfunk** [comment]
Something very similar is happening to me.... also with a dual-screen. I usually end up having to dock the devtools in order to get it to work, but the solution is pretty much the same - moving it back to the same monitor.

I'm using Chrome (Version 61.0.3163.100) on OS X 10.13

**Comment by mAAdhaTTah** [comment]
Yeah, just ran into this. At least I have a solution, but that's... really bizarre.

**Comment by CoeusCC** [comment]
Whoa, nice fix! Moved it to main screen and back to secondary and I'm in business. Very strange indeed. Even closing Chrome and reopening didn't seem to fix it.

**Comment by mAAdhaTTah** [comment]
It's possible this is a Chrome issue. I experienced something similar outside of the Vue devtools the other day that was resolved by moving the window over to my main screen.

**Comment by jonathanprl** [comment]
Same issue here. 150% scaling on main screen, and 100% on other screens. It did work a couple of months ago, most likely a chrome issue.

**Comment by codecadwallader** [comment]
This issue appeared to be Chrome specific (not reproduced in FireFox).

**Comment by yyx990803** [comment]
Unfortunately cannot reproduce this in my environment, and I suspect this is a Chrome bug instead of something we can fix on Vue's side.

**Comment by bartvanandel** [comment]
FWIW: I've run into this as well this afternoon. Laptop (primary screen) connected to 2 external monitors, Chrome running multiple windows, main window on the laptop screen, another one on monitor 2. Vue app + docked dev-tools both on monitor 2. Earlier this afternoon it worked fine, at some point it stopped working. Reopening dev-tools didn't work, disabling/enabling extension didn't work. Finally I found this issue and tried moving the window to the laptop screen, and it's responsive again. After that, I could move the window to the external monitor again, the Vue dev-tools are still responsive then. Let's see how long before it hangs again.
