### ISSUE TITLE
not visible tab on vivaldi dev tools

### ISSUE THREAD

**Issue by jeffrey-igaw** [vuejs/vue-devtools#436]
Hi, l really love to use vue.js dev tools every day!

but, when i updating vivaldi version to `1.12.955.38 (Stable channel)` as below image, vue tab is not visible. 

how can i fix this issue?

![image](https://user-images.githubusercontent.com/30995427/31805831-fda2c890-b59e-11e7-8ac2-1664f9bdce26.png)

**Comment by Wisleur** [comment]
Same here.... :(
But I think it's a problem related to Vivaldi browser.

**Comment by telamon** [comment]
Same problem here, it worked flawlessly a few weeks ago and then it just disappeared..

**Comment by raniesantos** [comment]
@jeffrey-igaw @Melchyore @telamon It looks like a chromium problem, not specific to Vivaldi. See #445

**Comment by telamon** [comment]
@raniesantos thanks but I'm not sure that the issue you linked is related to the one described here, I used to have the same "temporary" vanishing of the vue-devtool tab in vivaldi which was easily solved by closing/reopening chrome-devtools and/or restarting browser sometimes, but the vue-dev-tab disapeared permanently a few weeks ago and no open/close trick works anymore :(

**Comment by raniesantos** [comment]
Just gonna put this link here to direct further discussion to the right place.

https://vivaldi.com/bugreport/

**Comment by anjia0532** [comment]
windows 10
chrome 65.0.3298.4 (Official Build) dev (64-bit) +1

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.
