### ISSUE TITLE
devtools for Safari

### ISSUE THREAD

**Issue by Aleishus** [vuejs/vue-devtools#437]
Hi，this plugin is awesome, but I have a suggestion like this . Is that possible?
￼
￼
![1508493926106](https://user-images.githubusercontent.com/3436724/31816024-42db7b1a-b5c1-11e7-9b47-e05a5d592c04.jpg)

￼￼

**Comment by posva** [comment]
I personally don't know if it's possible to add it there, but open to suggestions if anybody knows 🙂

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.

**Comment by jasonxia23** [comment]
I don't think it it a good way to make changes in my own project.
