### ISSUE TITLE
problems with http-proxy-middleware

### ISSUE THREAD

**Issue by dc3671** [vuejs/vue-devtools#439]
- webpack@2.7.0, vuex@2.4.1, vue@2.4.4, vux@2.6.5, vue-router@2.7.0, http-proxy-middleware@0.17.4

- a simple config shown below:

```js
// config/index.js
module.exports = {
  // ...
  dev: {
    proxyTable: {
      '/app/': {
        target: 'http://mysite.com',
      },
      '/userfile/': {
        target: 'http://mysite.com',
      }
    }
  }
}
```

- unable to get devtools in my chrome, why?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by dc3671** [comment]
@posva Actually I think it's a bug. vue-devtools works fine alone without `http-proxy-middleware` triggered with that config. But together, vue-devtools shutdown.

I firstly put it:
```js
      '/app': {
        target: 'http://mysite.com',
      }
```
But it will handle local js files(main js file: app.js) , too. So I change it to ‘/app/’.

**Comment by posva** [comment]
the devtools do not depend on the domain, so it looks more like a problem on your end. That's why I'm asking you to ask for help in the forum or the chat. Of course, feel free to come back with a boiled down reproduction if it turns out to be a bug
