### ISSUE TITLE
Ability to copy an object to text

### ISSUE THREAD

**Issue by MikaelEdebro** [vuejs/vue-devtools#442]
One feature that would be awesome is to be able to right click an object in the vue-devtools store panel, and select "Copy to text".
Sometimes I find it can be very useful to be able to copy for example an array of objects, and paste it to a text editor. That way I don't have to expand all the array objects one by one, and I can perform text searches of the data.

**Comment by posva** [comment]
Are you aware you can copy the state already by clicking on the copy button?

**Comment by MikaelEdebro** [comment]
@posva Yes I've seen this. However this copies the entire state. It would be nice to be able to copy just one single object/array/etc.

**Comment by crcatala** [comment]
This would be useful to copy partial state, an for the component inspector to copy values there also. We could add to the existing inline quick edit actions in `DataField`. Maybe something like:

<img width="209" alt="copy-value" src="https://user-images.githubusercontent.com/1514479/35197549-45509c76-fea6-11e7-873a-c436efa57006.png"> <img width="245" alt="copy-value-hover" src="https://user-images.githubusercontent.com/1514479/35197550-48ac1878-fea6-11e7-813e-9fe5744b419e.png">

Would love to contribute a PR on this. Thoughts or any specific implementation you had in mind?

**Comment by MikaelEdebro** [comment]
@crcatala Yes, something like that would be awesome. Don't know if anyone else than me think this would be a great feature? 
I find myself wanting to copy some object (as JSON) quite often, just to paste it in to some text editor to diff with another one.

**Comment by Akryum** [comment]
I suggest adding a context menu with several items, like copy value or store as global var. Let's not clutter the state inspector too much (there are Edit buttons already).

**Comment by crcatala** [comment]
@Akryum fair point, to support further actions in the future perhaps a context dropdown such as:

<img width="292" alt="more-actions-dropdown" src="https://user-images.githubusercontent.com/1514479/35351428-78735c58-0106-11e8-9ac1-9932e938b3e6.png">
