### ISSUE TITLE
can not find `Vue` pannel on chrome devtool when detected the vue.js

### ISSUE THREAD

**Issue by kevinaskin** [vuejs/vue-devtools#445]
![0dd1a00c-568e-463c-abe3-c0ef58f1397a](https://user-images.githubusercontent.com/20034891/32155797-8fe78efc-bd74-11e7-818e-7314b83e94a1.png)

* sure about the `Vue.config.devtools = true` in the entry js file
* and it is not at the `production mode`
* chrome version is `62.0.3202.75`

why not show the Vue devtool pannel always on the chrome devtools tab(like the extension `Redux DevTools`)

**Comment by posva** [comment]
Close the devtools and reopen them
Vue devtools only appear when Vue is detected, that way you can drag it upfront and it will not bother you when developing non-vue apps

**Comment by newtonkim** [comment]
thanks worked

**Comment by adamr714** [comment]
Worked...found I have more than 1 dev tool open.  Need to close them all for this to work.
