### ISSUE TITLE
In Vuex tab, state's property value changes only when mutation occurs

### ISSUE THREAD

**Issue by meetzaveri** [vuejs/vue-devtools#453]
**Problem is when I update counter, Mutating only changes state's counter in vuex tab.**

**Otherwise when I update counter without mutation as described below then state's value doesn't change in vuex tab. And again when I do mutate, then it changes like direct from 2 to 8 .**

I have two files which does counter increment and decrement.

- Store which has state, getters and mutations

- A counter which increments and decrements (but not mutating state)

- A another counter which also increments and decrements (mutating state)

1. When I update counter through - counter( counter.vue ), it increments counter which is property in state.

**Code -
`this.$store.state.counter++;` ( increment ) => this one doesn't affect state's property in vuex tab**

2.  When I update counter through - Another counter( Anothercounter.vue ), it increments counter which is property in state with mutation.

**Code -
`this.$store.commit('increment');` ( increment ) => this one affect state's property in vuex tab**

Conclusion - Thing is state's value in **Vuex** tab only changes when I do mutation on state not when I do binding explicitly.

**Comment by meetzaveri** [comment]
See here is the screenshot where I have 

> incremented from second row's **_increment_** button

> and then decremented from first row's **_decrement_** button

![vuexdevbug](https://user-images.githubusercontent.com/21293048/32696472-d6076568-c79e-11e7-91fb-33d1654edb16.png)

**Comment by posva** [comment]
You must use mutations to modify the state. Directly modifying the state is not valid and using `strict` mode will throw an error

**Comment by meetzaveri** [comment]
Okay thanks for notifying @posva
