### ISSUE TITLE
Where is the Vue panel ?

### ISSUE THREAD

**Issue by BrickXu** [vuejs/vue-devtools#457]
I've let my code in dev stage:
```
Vue.config.devtools = true
```
and install the vue-devtools from google chrome store, then check "Allow access to file URLs" for this plugin, fully restart the chrome.

After all above, I open my Vue app page in the chrome and click the Vue icon, but nothing shows up, no vue panel, where is it ?

My chrome version is 62.0.3202.89

**Comment by rigor789** [comment]
Have you tried opening the Chrome Dev Tools (with f12)? It should be there like so
![vue-devtools](https://i.imgur.com/Pg3hnpd.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
