### ISSUE TITLE
add shells\chrome have a problem

### ISSUE THREAD

**Issue by Fzyfeng** [vuejs/vue-devtools#458]
![1510740595](https://user-images.githubusercontent.com/23629370/32830570-8f357bcc-ca30-11e7-927e-9cb394446ec9.png)

just like this，i‘m clone this in your project

**Comment by rigor789** [comment]
I don't understand what is on the screenshot, but I assume files are missing. If that is the case, you need to run the build command (`npm run dev:chrome`)

**Comment by posva** [comment]
Sorry but this is not enough for an issue...

**Comment by Fzyfeng** [comment]
Unable to load extension programs from the following sources，that is what  the screenshot mean.And the ‘build’ not under directory，just have the 'src' . you can see it in your project directory.
My firefox browser is available for download in its app store，so my project is ok. I dont have VPN so i cant link to Google app store. Cause I  find the plugins in your github project.Now it has this problem.

**Comment by rigor789** [comment]
You need to build the repository `npm install && npm run build`

**Comment by flowerxuegao** [comment]
npm install && npm run build 这两步我都执行了，但是还是报错，跟Fzyfeng的错误一样的，最后怎么解决的啊

**Comment by Fzyfeng** [comment]
@flowerxuegao 我是vpn翻墙上google商店直接下载的，反正带google的都被墙了。
cnpm说不定可以用，但下下来也没用啊，他的配置不对的丢进去根本用不了的。
