### ISSUE TITLE
vue-devtools can't work well in chrome 62.0

### ISSUE THREAD

**Issue by yangchendoit** [vuejs/vue-devtools#459]
I use vue-devtools to view store, it works well before, but after updating chrome, I find it doesn't work well any more,

**Comment by LinusBorg** [comment]
> I find it doesn't work well any more,

What is that supposed to mean?

**Comment by posva** [comment]
Make sure to open the devtools after the page with Vue is opened.
Devtools are working fine with latest Chrome. You may want to ask for some help over the [forum](http://forum.vuejs.org/) or the [Discord server](https://vue-land.js.org/), but I recommend you giving more details 😉 . Make your bundle is non-minified and doesn't have the option `Vue.config.devtools` to false
