### ISSUE TITLE
Property or method "toJSON" is not defined

### ISSUE THREAD

**Issue by codermarcos** [vuejs/vue-devtools#460]
This error happens when i pass the component by param to action in vuex.

To ***reproduce*** the error
```javascript
  //  Call an action in component passing the component as param to vuex
  this.$store.dispatch('metadataAddBox', { component: this });
```

![screenshot](https://user-images.githubusercontent.com/12430365/33130628-c380890c-cf72-11e7-941e-7f77ba4997b9.png)

> [Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by roger-russel** [comment]
Yeah, it happens with me too.

**Comment by rDr4g0n** [comment]
I found that elementui triggers this pretty frequently and [commented](https://github.com/ElemeFE/element/issues/3120#issuecomment-348214789) on a [thread](https://github.com/ElemeFE/element/issues/3120) on their issues page, but I suspect the fix may lie within vue devtools, rather than elementui.

**Comment by rDr4g0n** [comment]
This is probably related to #464

**Comment by posva** [comment]
Thanks for the extra information about recursive data @rDr4g0n

**Comment by Akryum** [comment]
Maybe we could treat components like a special type (kinda like RegExp).

**Comment by posva** [comment]
Yeah, it cannot be displayed like the other content because of cyclic references, so it needs special treatment

**Comment by Akryum** [comment]
Cyclic references are already taken care of, it must be something else.

**Comment by posva** [comment]
oh right, there was a package for that

**Comment by sangdth** [comment]
Today I encountered this error again. 
```
vue: 2.5.13
vue-devtools: 4.1.3
```

![screen shot 2018-02-27 at 10 10 54](https://user-images.githubusercontent.com/1083478/36717495-f361441a-1ba6-11e8-976d-18239fedea1f.png)

**Comment by jamelt** [comment]
I'm having this issue too, with element-ui.

**Comment by erwer8363** [comment]
how to fix this ? help help help

**Comment by onergang** [comment]
In my project, I opened the console,  by this 
```javascript
window.vConsole = new VConsole();
```
but when I commentedit. It works, the Vue warn was disappeared.

**Comment by trollderius** [comment]
Sentry seems to cause this error

**Comment by MarvinXu** [comment]
In my case, I used VConsole and print vue instance by `console.log(this)`, then caused this error. Hope this can help.

**Comment by qiuyudong** [comment]
> Sentry seems to cause this error

yep. I close Sentry and fix this error

**Comment by guan6** [comment]
> > Sentry seems to cause this error
> 
> yep. I close Sentry and fix this error

me too

**Comment by towry** [comment]
vConsole

**Comment by martin-haryanto** [comment]
any workaround for problem coming from Sentry? this is very frustrating for me since i makes the application hangs and make the CPU spike to 100%

I was using raven-js to capture error and processed it for sentry, so i cannot just remove it. But an error in action level, will trigger a log from all over the component in that `Page`.

**Comment by rmarmitt** [comment]
Any updates about this with Sentry?

**Comment by jarrodwhitley** [comment]
Bump

**Comment by loehx** [comment]
Bump
