### ISSUE TITLE
nothing is clickable

### ISSUE THREAD

**Issue by vaaski** [vuejs/vue-devtools#461]
Hello, I've used Vue for a while now without running into any problems.
But since today I can't get the Devtools to work.

They're showing up, and everything seems to be fine, but I can click on nothing.
It feels like everything has "pointer-events: none;" applied to it.
I'm on the latest Windows 10, Chrome 62, Vue 2.5.8, DevTools 3.1.6.
I've rebooted, reinstalled the extension, tried with a different project in which it worked with, and it's working fine inside an electron app.

If you need any more information, I'd be happy to provide them.

**Comment by vaaski** [comment]
I honestly don't know how or why, but it just fixed itself.
Maybe it was related to the resolution of the Chome DevTools window.

Sorry to bother 🤦‍♂️

**Comment by vaaski** [comment]
I was able to reproduce it today. 
You can have a look at [this gfycat](https://gfycat.com/gifs/detail/FirmWavyJuliabutterfly).

It seems to me like it's because of the weird resolution I have to work with right now.
I have my Surface Pro 4 connected to a screen double the physical size, but with a much smaller resolution, 2736x1824 vs 1920x1080.

I am going to leave this issue closed because this seems like an edge case to me, but I'm happy to provide any more information if needed.

**Comment by posva** [comment]
Thanks for the feeback there's also #433
