### ISSUE TITLE
Devtools in production not showing vuex store

### ISSUE THREAD

**Issue by hauptrolle** [vuejs/vue-devtools#462]
Hi,

when activating the devtools explicitly with `Vue.config.devtools = true` for a production build (please don't ask why I have to do that ...) the devtools are visible but the vuex tab says `No Vuex store detected`.
Is it possible see the vuex state also in production mode?

**Comment by posva** [comment]
Hey, can you boil down the error and provide a repro using this [template](http://codepen.io/pen?template=PWbYJO) or providing a simple HTML page? You should be able to reproduce it by using minified versions of the build (no need to use webpack)
Thanks!

**Comment by hauptrolle** [comment]
Hey @posva. Thank you for your fast reply!

Unfortunately I can not reproduce the problem on a fresh vue project 😞
It seems to be a problem with the custom build scripts we use.

I think we can close the issue here.

**Btw: Thank you for this awesome Plugin! 😅**

**Comment by posva** [comment]
Thanks, but this was developed by Evan 😛
