### ISSUE TITLE
Prop 'tooltip' covers value, can't select to copy a prop's value

### ISSUE THREAD

**Issue by checktravis** [vuejs/vue-devtools#463]
I'm on a corporate-macbook pro (admin available), running chrome Version 62.0.3202.94 (Official Build) (64-bit)

When I try to select the value of a prop (often have need to copy it), the prop's params pop up in the way and i can't get to it. 

![screen shot 2017-11-29 at 3 20 30 pm](https://user-images.githubusercontent.com/9468264/33397220-07576154-d519-11e7-9791-af4b1b816f6c.png)

I'd be happy to provide any additional details if needed.

Vue-devtools has really helped me in learning and working with Vue, nice work.

Thanks

**Comment by posva** [comment]
Maybe the tooltip could appear on the left instead
