### ISSUE TITLE
what happen in my application? some problem in the devtools?

### ISSUE THREAD

**Issue by vegawong** [vuejs/vue-devtools#473]
![image](https://user-images.githubusercontent.com/17271745/34143774-6a8a0938-e4c9-11e7-81f9-15c56471ca5d.png)

when i open the devtools to debug my application?  i get the trouble...

the xhr state changed event spent so much time and the page would be in stalled state, it spents 52s to run the code, why?   

and then i check the performence panel i found that: 
![image](https://user-images.githubusercontent.com/17271745/34143902-ff9f945c-e4c9-11e7-9973-1260f62f4613.png)

anybody can tell me are there some porblem with the extension?

my debug envirment is :   osx 10.13.2, chrome  62.0.3202.94,  vue 2.5.9, vue-devtools-extension 3.1.7.

**Comment by posva** [comment]
Hey, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Also make sure to provide more info there so people can help you. [this](https://vuejs.org/v2/api/#performance) may also help you to debug the perf of your app
