### ISSUE TITLE
Dates are restored as Strings when time traveling

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-devtools#475]
Using time-travel debugging with a store that contains date will lead to errors like this:

```
Error in render: "TypeError: b.date.getTime is not a function"
```

This is because the dates are restored as Strings instead of actual `Date` objects.

**Comment by GufNZ** [comment]
Probably related to this, I store classes in my state, but when timetraveling, they are not restored correctly.
For that matter, they don't show up as classes in the dev tool, only as Object.  This makes me think that the snapshot copy is not capturing everything.

**Comment by Akryum** [comment]
Well, the snapshots are JSON data, so no class information is retrieved.

**Comment by GufNZ** [comment]
Bummer - it's preventing me from using the timeTravel at all.

**Comment by Akryum** [comment]
@GufNZ You can open a new issue.

**Comment by GufNZ** [comment]
opened #492
