### ISSUE TITLE
Unused component data in devtools won't be changed by event methods

### ISSUE THREAD

**Issue by ForeverSc** [vuejs/vue-devtools#480]
### Version
Vue: 2.5.13
Chrome: 62.0.3202.75
Vue-devtools: 3.1.7

### Reproduction link
https://github.com/vuejs/vuex/tree/dev/examples/shopping-cart 

### Steps to reproduce
In App.vue file, i add some simple code, a button click method:
``` html
<template>
  <div id="app">
    <h1>Shopping Cart Example</h1>
    <hr>
    <h2>Products</h2>
    <product-list></product-list>
    <hr>
    <cart></cart>
    <button @click="handleClick">click me</button>
  </div>
</template>

<script>
import ProductList from './ProductList.vue'
import Cart from './Cart.vue'

export default {
  components: { ProductList, Cart },
  data () {
    return {
      test: 1
    }
  },
  methods: {
    handleClick () {
      this.test++
    }
  }
}
</script>

```
when you click the `click me` button, the `App` component's data in devtools won't change, the `test` value is still 1, but when you click the `Refresh` button, it will change to 2.
But if you use test data in this component, like adding a `<p>{{ test }}</p>` or watch the test value, the devtools will change correctly.
### What is expected?
component's data will change to new value

### What is actually happening?
component's data is still old value

### Others
At first, i think it seems to be a devtool's bug, but i add some breakpoint in source code, i found the problem was in vue.js source code.
I add breakpoint in: https://github.com/vuejs/vue/blob/e274c96881f8b14486587e93f404be489454d781/src/core/observer/scheduler.js#L88-L90
But when i click the button, `devtools.emit('flush')` was not paused, it's weird.

**Comment by Akryum** [comment]
This may be because Vue doesn't register any dependency to `test` because it is never used in any template/render function/computed property/vuex getter, so Vue doesn't keep track of its state.

**Comment by ForeverSc** [comment]
@Akryum 
Thanks for your answer:)  
But i still have some questions. If you add another data value such as `test2`, add `<p>{{test2}}</p>` in template, add `this.test2++` in `handleClick` method, then click the button.  
``` html
<template>
  <div id="app">
    <h1>Shopping Cart Example</h1>
    <hr>
    <h2>Products</h2>
    <product-list></product-list>
    <hr>
    <cart></cart>
    <button @click="handleClick">click me</button>
   <!--add test2-->
    <p>{{test2}}</p>
  </div>
</template>

<script>
import ProductList from './ProductList.vue'
import Cart from './Cart.vue'

export default {
  components: { ProductList, Cart },
  data () {
    return {
      test: 1,
      test2: 2
    }
  },
  methods: {
    handleClick () {
      this.test++ // test value will change too!
      this.test2++ 
    }
  }
}
</script>
```
As we know, `test2` will change value. But the `test` will also change value, in Devtools.  
It makes me confused. If Vue doesn't keep track of its state, `test` should still be 1.

**Comment by Akryum** [comment]
This is because the devtool fetches the whole component state when it is refreshed.

**Comment by ForeverSc** [comment]
@Akryum Thanks :)
