### ISSUE TITLE
devtools gives errors with vuex getters

### ISSUE THREAD

**Issue by SnooHD** [vuejs/vue-devtools#482]
I am running some getters that are directly getting certain DOM elements directly with querySelector.
It seems that the devtools is triggering getters on moments that the DOM elements are not rendered yet, This is giving me errors in my console.
When i removed the devtools, all errors are gone.

I am using querySelector because i need to change the element to get its boundingClientRect() dimensions and commit these to the object.
Using nextTick renders the DOM with a delay, which is a not an option for me.

The only workaround for me is to return null if the element can't be found.

**Comment by Akryum** [comment]
Using DOM elements in getters is wrong since it's not a Vue reactive data source. You should commit their boundingClientRect plain values instead. Also, you can use [vue-resize](https://github.com/Akryum/vue-resize) to detect DOM element size changes, it might help you.

**Comment by SnooHD** [comment]
@Akryum thanks for sharing, i think i can solve this use case by using vue-resize.
