### ISSUE TITLE
browsing history

### ISSUE THREAD

**Issue by jpkontreras** [vuejs/vue-devtools#493]
hello 
devtools now is asking for permission for browsing history
Can you elaborate why you need this? 

Thanks

**Comment by Akryum** [comment]
[Here](https://github.com/vuejs/vue-devtools/blob/24812e5542bb359a06a3e62379fd8c8633ae6034/shells/chrome/manifest.json#L31-L36) are the permissions asked by the extension. We need to access all website in order to detect any Vue app. Not sure why you get asked browsing history though. Is it on Chrome or Firefox?

**Comment by jpkontreras** [comment]
Chrome . win10  . Its in spanish 

![3bf90e9ffa5801d1c5d0e7204653c0a6](https://user-images.githubusercontent.com/7862089/34899530-4bd147c8-f7d8-11e7-8e4d-466806358dc2.png)

**Comment by revolter** [comment]
Me too.

**Comment by willnode** [comment]
Looking at manifest.json there's new permissions `tabs` and `context-menus` in 4.0.0. Not sure what are they.

**Comment by serkanyersen** [comment]
![screen shot 2018-01-12 at 16 08 59](https://user-images.githubusercontent.com/30582/34900220-f020a5ce-f7b2-11e7-8921-978b47c9ddd7.png)
here is the warning in English.

**Comment by Exitialis** [comment]
I have the same question
![image](https://user-images.githubusercontent.com/7029837/34900800-06003132-f814-11e7-86f1-5a9e92fa4470.png)

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/34900607-4cafe672-f83c-11e7-8883-ee5e90bd680b.png)
![image](https://user-images.githubusercontent.com/11240579/34900886-d7a5cf88-f83e-11e7-8f18-547d2530c5da.png)
The version in `manifest.json` file on `master` branch is `3.1.7`
The online version (from Chrome Web Store) is `4.0.0`

**Comment by Rundik** [comment]
@Genteure 
![screenshot_1](https://user-images.githubusercontent.com/13032812/34900979-0586f48e-f805-11e7-81f3-a73f1d6474a6.png)

**Comment by a-eid** [comment]
I just got that request as well, I was about to create an issue!!

**Comment by Genteure** [comment]
@Rundik I'm confused.
`b3f217d` is tagged `v4.0.0` and is the newest commit on the branch `master` according to releases page
and meanwhile `master`'s newest commit is `24812e5`
![image](https://user-images.githubusercontent.com/11240579/34901166-da0b2b44-f841-11e7-94bc-7952fc490b7a.png)

**Comment by Svenskunganka** [comment]
@Genteure GitHub Releases are based on [Git Tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging), and you can see commit `b3f217d` is the latest for the [v4.0.0 tag](https://github.com/vuejs/vue-devtools/tree/v4.0.0), among [some other commits](https://github.com/vuejs/vue-devtools/commits/v4.0.0) (test fixes and build). Evan probably forgot or hasn't had the time yet to push those commits to the master branch, and instead have them locally, which he created a *local* tag from, then pushed it to GitHub and lastly created a release out of. Does that make sense? 😄

**Comment by crimx** [comment]
Will there be a hot fix for this?

**Comment by dmmikkel** [comment]
I hope this can be resolved quickly. I can not acccept vue devtools accessing my browser history and I really need the devtools for work.

**Comment by errozero** [comment]
I have also received this notification today asking for permission to access browser history.

**Comment by byCedric** [comment]
I've disabled it too until this can be resolved. It's a no-go for me and the company I work for to allow a development tool to read my browsing history. If I can help with anything I would be glad to help!

**Comment by Akryum** [comment]
Sorry folks, it seems the permission wasn't necessary and it has been removed now. We will push a new release asap! 😉

**Comment by DeanMW** [comment]
Ohh thats awkward. Thanks for the quick response 👍

**Comment by martinbean** [comment]
Subscribing to this thread. Could it be updated when this has been fixed? As not really willing to give unnecessary permissions to a Chrome extension.

**Comment by jackbarham** [comment]
Delte the extension from Chrome then reinstalled it.

**Comment by jeremyjh** [comment]
> Evan probably forgot or hasn't had the time yet to push those commits to the master branch, and instead have them locally, which he created a local tag from, then pushed it to GitHub and lastly created a release out of. 

This is not an acceptable development practice for a tool of this nature. For adequate security and transparency we need the source to every release to be tagged and available in Github before it is deployed to the Chrome Store. Otherwise we do not even know the legitimate maintainers of this tool are still in control of it on the store.

**Comment by martinbean** [comment]
> Delete the extension from Chrome then reinstall it from the Chrome Store.

@jackbarham Cool, didn’t know the fix had already been pushed/was available. Thanks!

**Comment by Akryum** [comment]
The update 4.0.1 is live with the removed permission.

**Comment by Svenskunganka** [comment]
@jeremyjh I think you've misunderstood me, the full source and commit history of the release was always available on GitHub, just not under the `master` branch, but rather under the `v4.0.0` tag.
