### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by nasirouwagana** [vuejs/vue-devtools#499]
OS : Ubuntu 16.04
Chrome : 63.0.3239.84
vue : 2.5.13
vuex : 3.0.1
vue-devtools: 4.0.0

No content is appeared at right side, when I click on a component to inspect it. 
After I click on a component to inspect it, there are also a lot of errors in my console.

Please look at these two images below.

![image](https://user-images.githubusercontent.com/8539387/34902392-e160e432-f81a-11e7-9ed2-7462f8507799.png)

![image](https://user-images.githubusercontent.com/8539387/34902380-9e7ef42e-f81a-11e7-810c-5431093d8ec6.png)

**Comment by MinimiseNZ** [comment]
Same issues here. Is affecting the functionality of entire app. Functionality is restored only when vue-devtools is uninstalled

**Comment by Nikolay200669** [comment]
+1

**Comment by ankurk91** [comment]
I have the same error.
Version 63.0.3239.108 (Official Build) (64-bit)
![screenshot from 2018-01-13 12 49 53](https://user-images.githubusercontent.com/6111524/34903865-46dbb388-f860-11e7-84e0-f958d329eed7.png)
I uninstalled the extension and re-installed but it issue remain same.

**Comment by patrikengborg** [comment]
I have the same issue.

**Comment by mariomka** [comment]
I have too the same issue

OS : macOS 10.13.2
Chrome : 63.0.3239.132
vue : 2.5.9
vuex : 2.5.0
vue-devtools: 4.0.0

**Comment by DannyHinshaw** [comment]
Same issue here.

Appears to be solved by checking 'Allow access to file URLs' on extension' on the chrome extension.

**Comment by einnar82** [comment]
+1
Also in `npm run build`

**Comment by pedramk** [comment]
Same issue here...

**Comment by ArjenNZ** [comment]
This seems to be an issue concerning https://vuejs.org/v2/api/#provide-inject . For me, vee-validate was the problem. 

Fix: set Component Injections to false, and inject the validator in the specific component. Hope this helps anybody with the errors in vee-validate.

**Comment by nasirouwagana** [comment]
Exactly @ArjenNZ, you are right. If I desactivate vee-validate, vue-devtools is work properly.
I forgot to mention earlier I have used vee-validate : 2.0.2.

**Comment by mariomka** [comment]
@ArjenNZ yep! Devtools works well, disabling vee-validate.

**Comment by kaankucukx** [comment]
![image](https://user-images.githubusercontent.com/20001862/34907462-d0602a1a-f88f-11e7-8888-a0127f092092.png)

growing crowd

**Comment by sigfriedseldeslachts** [comment]
You can fix the issue by placing an input or so and add v-validate attribute on it. This however is not a permanent solution, and not a good one either.

`html
<input type="hidden" v-validate="'required'">
`

**Comment by groenroos** [comment]
Same issue here; disabling v-validate makes the problems go away, but obviously that's not a real fix.

**Comment by codeofsumit** [comment]
same here

**Comment by logaretm** [comment]
I've tagged 2.0.3 with a fix for the issue, could you guys upgrade `vee-validate` and test it?

**Comment by nasirouwagana** [comment]
@logaretm vue-devtools now works. Thank for your awesome work.

**Comment by groenroos** [comment]
I've got vue-devtools 4.0.1 and vee-validate 2.0.3, and the issue seems to have gone away!

**Comment by sigfriedseldeslachts** [comment]
Issue has been fixed in vee-validate 2.0.3

**Comment by thomassjogren** [comment]
@logaretm Thanks for the fast fix.

**Comment by Akryum** [comment]
This shouldn't happen again with #523.

**Comment by bomb1e** [comment]
Yep, `npm install --save vee-validate@2.0.3` fixes this issue! Thanks @logaretm

**Comment by Mouvedia** [comment]
I am stuck with 2.0.0-rc.25 due to the breaking changes in rc 26 that are too numerous.

**Comment by kaungmyatlwin** [comment]
This is also happening on Element UI 1.4.x with Vue 2.4.x.

**Comment by Akryum** [comment]
Try this branch: https://github.com/Akryum/vue-devtools/tree/types-improvements

**Comment by sellou** [comment]
Any clues how to resolve this issue with vuelidate ?
Thanks

**Comment by sigfriedseldeslachts** [comment]
@sellou R E A D. You should read an issue topic before asking something. This issue has been solved. Just update vee-validate.

**Comment by sigfriedseldeslachts** [comment]
@sellou use vee-validate. The issue has been solved there.

Sorry. I thought you meant vee-validate (removed previous message).
