### ISSUE TITLE
Open in editor path is missing slashes

### ISSUE THREAD

**Issue by Samuell1** [vuejs/vue-devtools#501]
When opening file from devtools there are missing slashes in path for file. This issue is caused because of template literals is escaping with `\`.

![obrazok](https://user-images.githubusercontent.com/3110002/34906291-0256ced6-f86b-11e7-90ef-42c5cf8422c4.png)

To fast fix this issue simply add replace on this line: https://github.com/vuejs/vue-devtools/blob/24812e5542bb359a06a3e62379fd8c8633ae6034/src/devtools/views/components/ComponentInspector.vue#L87
`const file = this.target.file.replace(/\\/g, '/')`

**Comment by yyx990803** [comment]
Looks like a windows issue? Might need to be fixed in `vue-loader` as the file path info comes from vue-loader.

**Comment by Samuell1** [comment]
Yes, iam using windows.

**Comment by yyx990803** [comment]
Nevermind, looks like it can be fixed here with the proposed change. Although I'm not entirely sure if all Windows editors can handle `/` delimited paths, would it be safer to replace them to `'\\\\'` instead? @Akryum can you confirm on windows?
