### ISSUE TITLE
v4.0.0 Requires "Browser History" permission.

### ISSUE THREAD

**Issue by AbhishekBiswal** [vuejs/vue-devtools#502]
v4.0.0 by default was disabled on chrome (after update) because it required a new permission : "Browser History". I don't see any reason for this change, and I can see a lot of users complaining on the chrome store review page as well.

**Comment by Samuell1** [comment]
https://github.com/vuejs/vue-devtools/pull/500

**Comment by Akryum** [comment]
Duplicate of #493
