### ISSUE TITLE
devtools asking for access to browser history

### ISSUE THREAD

**Issue by jgn-epp** [vuejs/vue-devtools#503]
I turned on my PC, opened my browser and I got a notification about vue-devtools asking for access to my browser history. Why does it need my browser history? I can't remember seeing this notification before.

**Comment by yyx990803** [comment]
We used `chrome.tabs.onActivated` and thought it required `tabs` permission - turns out it's not actually necessary and we've removed it in 4.0.1.

**Comment by jgn-epp** [comment]
Ok, thanks for the snappy reply. Was afraid something dodgy was going on.
