### ISSUE TITLE
[v4][question] Why devtools needs browsing history permission?

### ISSUE THREAD

**Issue by aleksandrlat** [vuejs/vue-devtools#505]
As I understand after recent devtools update it requires browsing history permission. Why is it required now?
![vuejs needs browsing history](https://user-images.githubusercontent.com/3708309/34909674-9bc3a2d8-f8b6-11e7-89a5-88f0875c7cb0.png)

**Comment by jtnelson** [comment]
I'd also like to know the answer to this question...

**Comment by pooot** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">The chrome.tabs permission was not actually needed in the new version of devtools and we’ve removed it in 4.0.1 :)</p>&mdash; Vue.js (@vuejs) <a href="https://twitter.com/vuejs/status/952232848429342722?ref_src=twsrc%5Etfw">January 13, 2018</a></blockquote>

**Comment by yyx990803** [comment]
4.0.1 is already out without the permission requirements, try deleting the extension and re-install.
