### ISSUE TITLE
Couldn't select component (click on it does nothing)

### ISSUE THREAD

**Issue by Koc** [vuejs/vue-devtools#508]
Firefox 55, devtools 4.0.1

Hover on the component works ok, but when I click on it - nothing happens.

![default](https://user-images.githubusercontent.com/191082/34912542-ed81e68a-f91e-11e7-8d0f-c0f79604873c.png)

Console:

![default](https://user-images.githubusercontent.com/191082/34912551-41b82818-f91f-11e7-96ce-d57009a31cd4.png)

**Comment by andreatulimiero** [comment]
I'm experiencing the same exact problem of @Koc

**Comment by Akryum** [comment]
Hi @Koc, we need a boiled-down reproduction to be able to pinpoint where the issue is.

**Comment by Koc** [comment]
How can I switch from minified version of plugin to dev? I can show normal stacktrace when switching.

**Comment by Akryum** [comment]
Follow [thos steps](https://github.com/vuejs/vue-devtools#manual-installation) to test it in dev mode.

**Comment by Koc** [comment]
Possible source of this bug: https://github.com/baianat/vee-validate/issues/1111

**Comment by Akryum** [comment]
Does the latest version of vee-validate solves this?

**Comment by Koc** [comment]
Yes, have checked it now. vee-validate 2.0.3 fixes this issue. Maybe add note to the docs about conflict.

**Comment by Koc** [comment]
relates to #499

**Comment by Serubin** [comment]
Reposting from #527 

> I'm experiencing a similar issue but I'm not using vee-validate. Also experiencing #507
>
> It seems like it can't correctly connect to the vue instance. All the various tabs in the vue devtools are empty and say "no component" or "cannot detect vuex."

3.x.x works fine, however.
