### ISSUE TITLE
Github Issue + PR Templates

### ISSUE THREAD

**Issue by crcatala** [vuejs/vue-devtools#511]
Setting up Issue and PR templates could be useful to guide users on providing enough detail to reproduce issues, etc. Hoping this can help maintainers of this project a little more :)

See:

https://help.github.com/articles/creating-an-issue-template-for-your-repository/
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by yyx990803** [comment]
Enabled vue-issue-bot for this repo.
