### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by erdoganoksuz** [vuejs/vue-devtools#513]
### Version
4.0.1

### Browser and OS info
chrome 63.0.3239.132

### Steps to reproduce
-v4.0.1
If I click any component "Uncaught TypeError: Cannot read property 'type' of null" on my console.

### What is expected?
I must see my component data

### What is actually happening?
If I click any component 
![untitled](https://user-images.githubusercontent.com/13199681/34930137-1b4d5b34-f9d9-11e7-946b-b29e8bc7f42a.png)
"Uncaught TypeError: Cannot read property 'type' of null" on my console.

**Comment by mesutgok** [comment]
i have same problem

**Comment by dmitrijsmihailovs** [comment]
Same here.

**Comment by larfeus** [comment]
+1

**Comment by begbeder** [comment]
+1

**Comment by mehdi-reza** [comment]
+1

![image](https://user-images.githubusercontent.com/5369680/34932363-57d714bc-f9f4-11e7-9d81-e810f4fe3f48.png)

**Comment by spamhead2k** [comment]
+1 impossible to work with!

**Comment by julesbloemen** [comment]
+1

**Comment by Akryum** [comment]
Do you use [vee-validate](https://github.com/baianat/vee-validate/issues/1111)?

**Comment by julesbloemen** [comment]
I do.

**Comment by mehdi-reza** [comment]
Yes I am using vee-validate.

**Comment by mehdi-reza** [comment]
vee-validate@2.0.3 fixed the issue

**Comment by spamhead2k** [comment]
Yes. When I deactivate vee-validate, the devtools work as expected

**Comment by Akryum** [comment]
Please update to vee-validate@2.0.3.
