### ISSUE TITLE
Message length exceeded maximum allowed length

### ISSUE THREAD

**Issue by w1ndy** [vuejs/vue-devtools#515]
### Version
4.0.0

### Browser and OS info
Chrome 63

### Steps to reproduce
Put a large amount of data in components and open Vue devtools.

### What is expected?
Devtools open correctly.

### What is actually happening?
![vue-devtools](https://user-images.githubusercontent.com/652068/34939784-0c9d1cd8-fa28-11e7-9764-6ba51406b81a.png)
Error thrown: Message length exceeded maximum allowed length.
Could be similar to [this](https://github.com/BabylonJS/Spector.js/issues/69).

**Comment by w1ndy** [comment]
A minimal repo:
```html
<!DOCTYPE html>
<body>
    <div id="app"></div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.js"></script>
<script>
new Vue({
    el: '#app',
    mounted () {
        for (let i = 0; i < 10000000; i++)
            this.largeArray.push(i)
    },
    data: {
        largeArray: []
    }
})
</script>
```

**Comment by w1ndy** [comment]
vue-devtools completely freezes on this code, and the error will be thrown a moment later.

**Comment by Akryum** [comment]
Please try this branch: https://github.com/Akryum/vue-devtools/tree/component-inspect-optimizations

**Comment by Akryum** [comment]
Please try this branch: https://github.com/Akryum/vue-devtools/tree/component-inspect-optimizations

**Comment by w1ndy** [comment]
@Akryum Sorry for the late reply, but the patch merged did not resolve this issue... The latest vue-devtools is still throwing errors and violations on the example I gave earlier.

**Comment by w1ndy** [comment]
Is it possible to not serialize and transfer data entirely, but retrieve their values on demand?

**Comment by colinfike** [comment]
I can confirm that I am also still seeing this issue.

**Comment by maverickchangithub** [comment]
@colinfike    I got the same issue in a PC environment  , but it is OK in a MAC dev machine.  Don't know why , same code , internet problem?

**Comment by Akryum** [comment]
How much RAM do you have?

**Comment by colinfike** [comment]
I don't actually have the machine I was working on at the time but I believe I had 16gb with 8gb allocated to docker.

**Comment by maverickchangithub** [comment]
@Akryum now i have the same issue on a Mac dev machine too . I use 2048M ram in both machine , php 7.2 . Really strange issue  , maybe it is my code which broke the tool , not confirmed yet.

i am using a laravel imap parser to parse gmail , and i am using vue for the front end , there is lot of problems now , but it shows the data , only cannot use vue-dev-tools to monitor the properties

**Comment by davidkhess** [comment]
Seeing this problem also. @Akryum can we reopen this issue?

**Comment by landart** [comment]
Still seeing the issue here. I'm on Chrome 65. 16GB RAM of which 2.9 available.

**Comment by lalmat** [comment]
Same problem here with a base64 (almost 100Ko) image in vue data. In my case, maybe a big data content should be truncated in data preview... But for an array, I've no idea.

**Comment by davidkhess** [comment]
About the only work around I've been able to come up with is to select the Vue component I need to inspect, wait for the error to pop up, switch the display to Events.

At least that way I can inspect the Vue using $vm0 in the console.

**Comment by davidkhess** [comment]
@Akryum the folks at zalmoxisus/redux-devtools-extension fixed this problem like this:

https://github.com/zalmoxisus/redux-devtools-extension/pull/582/files

Seems that solution should be easily ported to vue-devtools?

**Comment by vcastro45** [comment]
Considering the @davidkhess  's answer and the problem that still be, is it possible to re-open the issue ? @Akryum
