### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by asmyshlyaev177** [vuejs/vue-devtools#517]
### Version
4.0.0

### Browser and OS info
Chrome 63.0.3239.132 / Ubuntu 16.04 x64

### Steps to reproduce
After last update in vue-devtools  extension when  i try to select any component i got error in console

Can't see data and component property.

Same situation in firefor browser. I tried to checkout code version from 12.01.2018 and have same problem.

### What is expected?
I can select component and see data, properties, computed etc.

### What is actually happening?
I got following error in console 
```
Uncaught TypeError: Cannot read property 'type' of null
    at VM22763 backend.js:1
    at x (VM22763 backend.js:1)
    at t.a (VM22763 backend.js:1)
    at Object.y (VM22763 backend.js:1)
    at e (VM22763 backend.js:1)
    at e (VM22763 backend.js:1)
    at e (VM22763 backend.js:1)
    at e (VM22763 backend.js:1)
    at Object.t.stringifyStrict (VM22763 backend.js:1)
    at Object.t.stringify (VM22763 backend.js:1)
```

**Comment by minatonda** [comment]
+1

**Comment by pavelpage** [comment]
Has the same problem.

**Comment by Akryum** [comment]
Do you use vee-validate? If so, see https://github.com/vuejs/vue-devtools/issues/499#issuecomment-357506247

**Comment by asmyshlyaev177** [comment]
Yes, we are. Version:
"vee-validate": "^2.0.0-rc.25",

**Comment by Akryum** [comment]
Try to update to 2.0.3.

**Comment by asmyshlyaev177** [comment]
It works! Thank you.

Also found hou you can improve code
lines 445-446, 462-463

https://github.com/vuejs/vue-devtools/blob/a79d9c55176ed8146b3631256a869d6938209c3e/src/backend/index.js#L445

this line 
`type: prop.type ? getPropType(prop.type) : 'any',`
change to 
`type: prop && prop.type ? getPropType(prop.type) : 'any',`

Same with **options.type** and 
`required: !!options.required,`

I checked with old version vee-validate and no errors.
