### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by csicky** [vuejs/vue-devtools#522]
### Version
4.0.1

### Browser and OS info
Chrome 63.0.3239.132 (64-bit) / Windows 10

### Steps to reproduce
Click on a component in Vue devtools component inspector.

### What is expected?
To be able to inspect the component state.

### What is actually happening?
Error is thrown in the browser console.

```
backend.js:formatted:1095 Uncaught TypeError: Cannot read property 'type' of null
    at backend.js:formatted:1095
    at x (backend.js:formatted:1103)
    at t.a (backend.js:formatted:847)
    at Object.y (backend.js:formatted:134)
    at e (backend.js:formatted:395)
    at e (backend.js:formatted:405)
    at e (backend.js:formatted:396)
    at e (backend.js:formatted:396)
    at Object.t.stringifyStrict (backend.js:formatted:410)
    at Object.t.stringify (backend.js:formatted:350)
```

---
This appeared last week on my colleague's machine, in another country. Using remote desktop I allowed to use my machine to inspect something, we thought it's specific to his machine Today it hit also my machine, exactly the same thing. At that line `o` is `null` but the code tries to read from it `o.type`. 

Breaks on `type: o.type ? D(o.type) : "any"`
Possible fix would be: `type: (o && o.type) ? D(o.type) : "any"`

![image](https://user-images.githubusercontent.com/3931907/34984183-aa6339b2-fab8-11e7-8af5-3e20c23cb957.png)

**Comment by MatthewDanielLA** [comment]
Are you using vee-validate? See #499 
If so, update vee-validate to 2.0.3 and everything should be back to normal.

**Comment by csicky** [comment]
Yes, that fixed it, thank you! I did search for the same issue before creating the one but somehow I missed it. Great development experience and Vue.js is super! Thanks again!
