### ISSUE TITLE
Browser Extensions icon state error

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vue-devtools#525]
### Version
4.0.0

### Browser and OS info
Chrome 63/Window 10 FCU

### Steps to reproduce
None

### What is expected?
Icon color is highlighted

### What is actually happening?
Icon color is not highlighted

**Comment by yoyo837** [comment]
![fd8aef6b-5a7d-4246-9a09-b935d024f72d](https://user-images.githubusercontent.com/6134547/35022497-3ac8d35a-fb71-11e7-8880-77a2d9f4be77.png)

**Comment by yoyo837** [comment]
The same is true in the production environment

**Comment by Akryum** [comment]
Please provide a runnable reproduction that demonstrate this behavior.
