### ISSUE TITLE
Property not updating its state unless called on the template

### ISSUE THREAD

**Issue by belisarh** [vuejs/vue-devtools#53]
Let's see if I can explain this because it is kind of weird:

Given that we have a property set to a certain value.
We react to a DOM event by setting this property to another value.
The value will show in dev tools with its original value (not update) unless the value is called anywhere in the template.
If we send the component to the console, $vm.property will give the correct value, however the property in the devtools window will not change. 
So the value actually changes, but devtools will not react to its change unless the value is called in the template.

Template:
```html
<a href="#0" v-for="item in items" 
    @mouseover="setActiveItem($index)"
    @mouseout="unsetActiveItem"
    v-bind:style="currentItemMarker($index)">
</a>
```
Methods:
```javascript
setActiveItem: function(index) {
    setTimeout(function() {
          return this.activeItem = index;
      }.bind(this), 300)
},
unsetActiveItem: function() {
  this.activeItem = false;
}
```
Now this does not update the activeItem property on the devtools window. The data however is reactive and its value changes on mouseover. In fact if we do this:
```html
<a href="#0" v-for="item in items" 
    @mouseover="setActiveItem($index)"
    @mouseout="unsetActiveItem"
    v-bind:style="currentItemMarker($index)">{{ activeItem }}
</a>
```
Devtools will show the changes, the trick being "activeItem" is being called inside the template.

Makes sense? Is this behavior expected?

**Comment by yyx990803** [comment]
Hmm, yeah this is somewhat expected because the devtool's refresh is tied to Vue's async update queue. So if a reactive property change did not trigger any updates, it will not notify the devtools.

But this could be fixed - I'll look into it when I have time.

**Comment by belisarh** [comment]
Thanks Evan, makes sense like that. Would make debugging easier in specific scenarios but not a an issue of course.
