### ISSUE TITLE
Performance Tab

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-devtools#536]
### What problem does this feature solve?
From #354

### What does the proposed API look like?
TODO

> Perf panel that profiles component render/patch, computed properties, vuex getters etc...

**Comment by nshntarora** [comment]
Hi @Akryum , I'd love to help with this. I think we can use the [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver) API to profile the render.

I'd love to know if you have any detailed ideas on how to approach this problem.
