### ISSUE TITLE
html content broken

### ISSUE THREAD

**Issue by Jack85** [vuejs/vue-devtools#560]
### Version
4.1.0

### Browser and OS info
latest chrome

### Steps to reproduce
use v-html with longer transformed markdown or html content in data

### What is expected?
should be displayed correctly

### What is actually happening?
text of the properties is overlapped over each other in data window

---

![image](https://user-images.githubusercontent.com/16955647/35377224-9c5da350-01ae-11e8-9ee8-fe2e1b42ef22.png)

**Comment by Akryum** [comment]
Duplicate of #555
