### ISSUE TITLE
Context Menu Error: Uncaught ReferenceError: event is not defined

### ISSUE THREAD

**Issue by jpamorgan** [vuejs/vue-devtools#566]
Getting a console error when right clicking on web pages.  It says the event is not defined.

I am on Mac with Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Same issue on chrome in a Linux PC so I don't think its my setup.

The code is here:
https://github.com/vuejs/vue-devtools/blob/2df80656476bd039fe49a2f4f9c0f579fc9c8845/src/backend/index.js#L736

Screenshot of the console error:
![console](https://useproof.s3.amazonaws.com/turbo1/Proof__Increase_Your_Conversion_Rates_with_Recent_Customer_Activity_2018-01-25_07-08-51.png)

**Comment by Akryum** [comment]
Duplicate of #514
