### ISSUE TITLE
getCustomFunctionDetails throwing exception for anonymous functions

### ISSUE THREAD

**Issue by badams2527** [vuejs/vue-devtools#568]
### Version
4.1.0

### Browser and OS info
Chrome 64.0.3282.119 / Windows 10

### Steps to reproduce
**This occurred on version 4.1.1 but that was not an option on the issue helper site**

Clone repository from: https://github.com/badams2527/devtools-issue

Install npm packages `npm install`

Run the project using `npm run dev`

Open the application in Chrome, then open Vue devtools.

In Vue devtools, navigate down the component tree to KendoGrid.

Click on KendoGrid.

Notice the console error

[Here's a screenshot of the error](https://imgur.com/a/TlNW3)

### What is expected?
It should populate the component instance details in the right panel. 

### What is actually happening?
It is throwing an exception in the log and not populating the right panel

---
I set a debug point at that line in backend.js (after pretty printing), and checking the argument. It's returning
 
```
"function anonymous(d
/*``*/) {
return d.Total
}"
```

after the toString, leading me to believe it's just not set to handle anonymous functions properly.

**Comment by simplesmiler** [comment]
Also stumbled upon something similar to this. I was adding lodash with a global mixin to be used in component templates. And lodash has this feature of overloading `lodash.toString` with a completely different meaning (specifically, it is used to cast arguments to string instead of serialization), so it's not being serialized properly.

**Comment by Elevista** [comment]
Same problem
![image](https://user-images.githubusercontent.com/9513647/35420773-b32aca52-0282-11e8-9df4-43a64fc9ce6b.png)
```js
(x => x+1).toString().match(/\(.*\)/)
```
result is `null` will cause `null[0]` error

**Comment by francoisromain** [comment]
Same bug for me. I can not use vue-devtools currently. Please could you release the fix? Thank you
