### ISSUE TITLE
[Feature request] Add a 'settings' page where you could change the visuals

### ISSUE THREAD

**Issue by AlexandreBonneau** [vuejs/vue-devtools#570]
### What problem does this feature solve?
It would be great to be able to change the font size of the Vue devtools, as well as being able to define custom syntax highlighting color for the property labels, numbers, strings, types, null/undefined values, etc.

Currently when using the devtools in Firefox dev, you can see that the font is somewhat bigger than in the inspector, and that the color scheme is totally different.

### What does the proposed API look like?
I envision a basic list of every element that could be styled, with a color picker / text field.
Ideally, an import/export configuration would be even better :)

**Comment by Akryum** [comment]
Let's continue in #547
