### ISSUE TITLE
Uncaught ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by jason-engage** [vuejs/vue-devtools#578]
### Version
4.1.1

### Browser and OS info
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### Steps to reproduce
Load vuejs site in dev mode

### What is expected?
Should show Root Components in the Vue Devtools

### What is actually happening?
Devtools component list is just blank

---
Been using without issue for years. This just started happening, I guess recently. Maybe from last update Jan 25?

**Comment by Akryum** [comment]
Hi! Thanks for reporting your issue, but we need a minimal reproduction to find the origin of the issue.

**Comment by haco28** [comment]
Hi @Akryum I have the same problem.
I don't know if @jason-engage use a similar environment.
My stack contain webpack.
And i have the same message in dev mode.
Sometimes any vue component or instance in Vue devtools.

**Comment by bhnddowinf** [comment]
in created ()
    self.fetchDataItem();

f12 will  display : 
Uncaught ReferenceError: setImmediate is not defined     backend.js 1


all code ↓
```
<!-- app -->
<div id="app">

</div>
<!-- vue -->
<script>
var app = new Vue({
  el: '#app',
  data: {
      msg: {}
  },//data
  mounted:function () {
    console.log('mounted');
    self = this;
    self.fetchDataItem();
    console.log('mounted1');

  },// mounted
  methods: {
    fetchDataItem: function () {
      self = this;      
      console.log('fetchDataItem');
      //self.handlerData(); 
    },// fetchDataItem
    fetchDataQuoteSource: function () {
        console.log('fetchDataQuoteSource');
        self = this;
        //self.fetchDataItem();
    },// fetchDataQuoteSource
    handlerData: function (msg) {
      console.log('handlerData');
      this.DBItem = msg;
      this.MessageLoading=false;
    },// handlerData
  },//methods
});
</script>
```
