### ISSUE TITLE
Vue Devtools tab is not visible

### ISSUE THREAD

**Issue by ispal** [vuejs/vue-devtools#58]
I downloaded vue-loader-example and installed Vue Devtools extension for Chrome. I can get the example working by running **npm run dev**. The problem is that I don't see the Vue Devtools tab on my Chrome devtools.

I'm running Chrome version 46.0.2490.86 on my Macbook Pro.

<img width="1277" alt="screen shot 2015-11-28 at 15 27 51" src="https://cloud.githubusercontent.com/assets/1437652/11452121/2c7a2b80-95e5-11e5-93f2-cdc1b4c9e772.png">

**Comment by haydenbbickerton** [comment]
Happened to me, although it was working yesterday. Reinstalled the extension and restarted chrome seems to have brought the tab back.

**Comment by yyx990803** [comment]
This is because you are opening the wrapped page served by `webpack-dev-server`, which in turn loads the actual app in an iframe.

Just go to `localhost:8080` directly without the `/webpack-dev-server` path.

**Comment by wbpmrck** [comment]
i have an same question,does it means vue-devtools cannot work with iframe?

**Comment by yusukeokui** [comment]
you need use development (non-minified) versions of Vue. use vue.js, not vue.min.js.
https://github.com/vuejs/vue-devtools#notes
