### ISSUE TITLE
Open in editor button doesn't show up for non SFC

### ISSUE THREAD

**Issue by sqal** [vuejs/vue-devtools#582]
### Version
4.1.2

### Browser and OS info
Chrome 64 / Windows 10

### Steps to reproduce
Create some component written in plain JS using `render` function and inspect it in the Vue devtools

### What is expected?
I would like to see Open in editor button for that component.

### What is actually happening?
Open in editor button is missing for components that are not SFC.

**Comment by Akryum** [comment]
This is because the js and jsx files aren't processed by vue-loader which is injecting the file path to the component definition.
