### ISSUE TITLE
Vue panel stuck across three environments 

### ISSUE THREAD

**Issue by JustinDraude** [vuejs/vue-devtools#588]
### Version
4.1.2

### Browser and OS info
Chrome 64.0.3282.119/ Windows 7   Mozilla 58.01/Windows 7   Electron version of Vue devtools

### Steps to reproduce
*Running Vue through npm installed package vue@2.5.13

*Laravel backend

*No Vue router, as Laravel handles routing through views

*Initial load of page (any page) works fine. Vue devtools working accordingly, inputs get updated, events tab 
can be seen, etc

*Access different page url of the website

*Panel is now non-reactive to any mouse clicks

*Components from old url page still showing

*Cannot switch to events tab or any other tab

*Cannot do anything

*Vue panel works again after closing browser tab completely and reopening

*Hard refresh doesn't fix it

### What is expected?
Vue panel to work accordingly

### What is actually happening?
Vue panel is non-responsive

---
Same issue with Mozilla plugin, as well as electron standalone. All reinstalled today, issue remains.
Three different apps were tested, making sure no existing endless loop could cause this. Same issue.
It was working fine 3 hours ago. 
Uncertain if issue is AFTER 29.01.2018 devtools update, as I don't notice when chrome updates my extensions

**Comment by samydoesit** [comment]
Same here

**Comment by poldixd** [comment]
Same here. VueJS Panel works and when i reload the page i can't click on any tabs like _Components_ or _Vuex_. Only if i close the Developer Console in Chrome and restart it, i can do anything again.

I tried it in Chrome and Firefox. I removed the extension and reinstall them.

**Comment by fnkky** [comment]
Same hier

**Comment by fnkky** [comment]
Same here, Chrome 64.0.3282.119

**Comment by csicky** [comment]
When this happens there is also an error in console:

> backend.js:1 Uncaught TypeError: Cannot read property '__VUE_DEVTOOLS_UID__' of undefined
>     at backend.js:1
>     at t.a.v.on.e (backend.js:1)
>     at t.a.n.emit (backend.js:1)
>     at e.listen.e (backend.js:1)
>     at n (backend.js:1)

**Comment by JustinDraude** [comment]
@csicky No error for me, perhaps project related on your end.

**Comment by franzi50** [comment]
Exact same error as csicky.

**Comment by ejdrian313** [comment]
same error

**Comment by samydoesit** [comment]
@csicky thats the same error we get

**Comment by csicky** [comment]
@JustinDraude To see error in console use the Vue devtools, refresh page, try to use Vue devtools again, error appears in console, at least on my side.
Anyway, all the things you described are exactly like that on my side too.

**Comment by memic84** [comment]
Same here

Version 63.0.3239.132 (Official Build) (64-bit)

Works again when i close the dev toolbar and open it

**Comment by Akryum** [comment]
Please update to 4.1.3 on Firefox (Chrome Web Store takes time to publish) and report back if the issue isn't fixed.

**Comment by inkbeard** [comment]
I'm still getting the issue in with Chrome Version 64.0.3282.119 (Official Build) (64-bit). @memic84 workaround of closing the dev toolbar and opening it again seems to work though.

**Comment by Akryum** [comment]
@inkbeard Which version of the devtools?

**Comment by inkbeard** [comment]
@Akryum 
mac chrome: Version 64.0.3282.119 (Official Build) (64-bit)
vue: 2.5.13
vue-devtools: 4.1.2

**Comment by Amador368** [comment]
same error
Vue 2.5.9
Windows Version 64.0.3282.119 (Official Build) (64-bit)
vue-devtools: 4.1.2

**Comment by inkbeard** [comment]
@Akryum : Sorry, I just saw your note about updating to `4.1.3`, which the Chrome Store hasn't updated yet.

@Amador368 : You're running the same `4.1.2` version that I am.

Once I see the update come through the store, I'll check again.

**Comment by Akryum** [comment]
In the meantime, you can just use Firefox and vue-devtools 4.1.3.

**Comment by Somrlik** [comment]
Another workaround is Right click -> Reload frame in the panel.

**Comment by ffxsam** [comment]
@Somrlik THANK YOU for that tip. This has been driving me insane.

**Comment by hyounoo** [comment]
@Somrlik Thanks it is resolved for now

**Comment by mmieluch** [comment]
Chrome Store is now hosting the update 4.1.3 version. However, in my case (macOS, Chrome latest stable) the browser wasn't updating the extension. So I had to remove the extension, install it again, and then restart the browser for the changes to be picked up. After that everything worked like a charm.

**Comment by Akryum** [comment]
You can enable the 'Developer Mode' in the extensions tab and a 'Update extensions now' button will appear. 🎩 ✨

**Comment by DannyFeliz** [comment]
In case you're using electron as me just update `electron-devtools-installer` to the latest version.

**Comment by mekhami** [comment]
I'm getting this error when I try to use the select tool on an element that's wrapped in a transition.

**Comment by tronjs** [comment]
Same error, can not get it works
Chrome Version 66.0.3359.181 (Official Build) (64-bit) on Windows
Vue Dev Tools 4.1.4

**Comment by AlexanderZon** [comment]
Same error, this happens when i had displaying a component in inspector that i've passed an array by prop, and i have a computed property that sort this array. When i change something that causes reactivity on this computed property is when this breaks down. If i delete the sort on this array in the computed property this came alive again.

**Comment by goodpixels** [comment]
Same here, when I have a getter that returns a sorted array, Vue dev tools die.

**Comment by neeravp** [comment]
I was having the same problem with Vue devtools 4.1.3 on macOs High Sierra in Chrome 69.0.3497.100 . 
Devtools crash every 3-5 minutes, had to reload again and again.   
Removed the extension and reinstalled it. Yet to check how it performs.  
Seriously, team - an appeal to you - please resolve the issue asap. Without devtools vuejs looses its appeal as the go to framework for me.

**Comment by eyaylagul** [comment]
macOs High Sierra in Chrome 69.0.3497.100 same error

**Comment by cerw** [comment]
Same here newest version on mac

**Comment by jordanranson** [comment]
Still happening here in 2019. MacOS 10.13.16 with Chrome 70.0.3538.110.

```
backend.js:1 Uncaught TypeError: Cannot read property '__VUE_DEVTOOLS_UID__' of undefined
    at backend.js:1
    at t.a.v.on.e (backend.js:1)
    at t.a.n.emit (backend.js:1)
    at e.listen.e (backend.js:1)
    at n (backend.js:1)
```

**Comment by daniele-orlando** [comment]
I can reproduce with `Vue 2.5.22` and `Vue DevTools 4.1.5 beta`, on `Chrome 71`.

**Comment by nathanchere** [comment]
Still happening here, Windows 10 with Vivaldi 2.2.1388.37. Not sure what version of vue devtools I had before but I just updated to 4.1.5 beta and it's still happening.

`Cannot read property '__VUE_DEVTOOLS_UID__' of undefined`

**Comment by alirezamirsepassi** [comment]
Any update?
Still experiencing this problem, although everything is up-to-date.

**Comment by nathanchere** [comment]
For me, the problem only occurs when having multiple vue instances bound on a single page.

**Comment by Kolbasyatin** [comment]
In my case this appears when I create vue component in callback function after fetching data from api.

**Comment by nathanchere** [comment]
In my instance it turned out we had part of the build bundling vue.min.js instead of vue.js
It isn't just minified, it is also missing things like dev tools support
Ensuring we reference/bundle/whatever the non-minified (see: not production) vue.js fixed the problem for me.

**Comment by cecotw** [comment]
Same problem here. Reloading the frame works - but it's annoying.

**Comment by skyzhao1223** [comment]
right click might be a workaround, but **reinstalling** the extension solved this forever, at least for me

**Comment by BlitZz96** [comment]
[release 5.2.0](https://github.com/vuejs/vue-devtools/releases/tag/v5.2.0 ) Seemed to fix this issue for me. 
Awesome release. It's so snappy now 💯
Good job!

**Comment by alexandar87** [comment]
I still have the issue with the latest version from Oct 30th.
