### ISSUE TITLE
Getting an "Uncaught TypeError: Converting circular structure to JSON"

### ISSUE THREAD

**Issue by jimmypuckett** [vuejs/vue-devtools#59]
I am working with a deeply nested JSON object, and I am getting an "Uncaught TypeError: Converting circular structure to JSON" error when I try to examine my component in devtools.

I know that there is not much in this report to go on, so what could I provide to help troubleshoot?

**Comment by yyx990803** [comment]
What does the error stack look like?

**Comment by jimmypuckett** [comment]
Here you go...

```
Uncaught TypeError: Converting circular structure to JSON
Save.stringify @ extensions::SafeBuiltins:82
PortImpl.postMessage @ extensions::messaging:53
target.(anonymous function) @ extensions::SafeBuiltins:19
publicClass.(anonymous function) @ extensions::utils:94
sendMessageToDevtools @ proxy.js:73

**Comment by skyrpex** [comment]
Pretty sure you've got an object inside itself somewhere in your data. Should vue-devtools handle this case?

**Comment by jimmypuckett** [comment]
So I have an instance of leaflet map inside the vue instance & a string (API token for leaflet). I'm pretty sure that is all.

**Comment by rigor789** [comment]
Just came across this issue, in my case I have an object (es6 class) that gets the `$vm` in it's constructor, and then the object is set in the vm's `$data` array and that causes a circular reference that can't be converted to JSON.

**Comment by gdecris** [comment]
I am having the same issue using Mapbox (built on Leaflet). Makes me wonder if that is no coincidence. This could be an issue with how the Leaflet object is structured.

**Comment by rigor789** [comment]
I personally restructured my code, and didn't have any more issues after that. Basically I have a class that gets `$vm` through the constructor, but I don't set that object as a `$data` attribute to avoid circular references.

**Comment by kjessec** [comment]
In my case this happened when I somehow make a object reference between child component's `data` and whatever passed via props. This **IS** an anti-pattern, but I did this because the object passed via prop may be missing some the required default values for a specific sub-component to be properly rendered, yet I wanted the two-way reactivity, so doing this kind of thing

````javascript
// ... in sub-component declaration
data: function() {
    return Object.assign(this.someProp, {
        someDefaultValue: []
    }, this.someProp); // filthy, I know
}

````

In the end I settled to 
1. No more direct referencing; rather create a copy of prop, then shim with default values
2. Updating parent data store through $dispatch and $on when there's a change.

**Comment by kjessec** [comment]
Looks like I can give default prop values in a simpler way. Totally missed that!
http://vuejs.org/api/#props

**Comment by srhise** [comment]
Having the same issue with google maps

**Comment by EdwardNelson** [comment]
I too am having the same problem with google maps

**Comment by Glutnix** [comment]
Vue Devtools should definitely handle circular references gracefully.

When Vue Devtools is generating the data/property value tree, it should check to see if an object is the same object as any of its parents, and instead of going deeper, show "«circular reference»".

**Comment by srhise** [comment]
@Glutnix where in the code does that occur? Sounds like something this group could fix for @yyx990803

**Comment by Glutnix** [comment]
I don't know, I haven't consulted the source code. I just described how you prevent circular references.

**Comment by yyx990803** [comment]
fixed via 2a626a3

**Comment by Glutnix** [comment]
Thank you Evan!

**Comment by codeofsumit** [comment]
I still have this issue in vue 2.0-rc.6 with leaflet

**Comment by Allen-Wei** [comment]
@codeofsumit try `circular-json`: 

```javascript
const CircularJSON = require('circular-json');

let json = CircularJSON.stringify(yourObject);
```

**Comment by vahlo** [comment]
I'm working with Typescript + Vue project, had this error when working with openlayers.

The fix for me was to : **Mounted()** { <code>} in my .ts file.

 Ref: https://forum.vuejs.org/t/reference-an-inner-div-inside-of-template/19903/2
