### ISSUE TITLE
Use standalone version with HTTPS

### ISSUE THREAD

**Issue by fgilio** [vuejs/vue-devtools#597]
### What problem does this feature solve?
Hello!
Well, the tittle says it all, is it possible to make the standalone version of the devtools use HTTPS? I tried to hack my way through it but my knowledge about Express and Socket.IO is non existent.

In our case, we use a HTTPS only dev environment and sadly this is not working.

### What does the proposed API look like?
If it were to use HTTPS by default, it'd "just work" for any HTTP and HTTPS environment.

Thanks in advance!
F

**Comment by michalsnik** [comment]
Hey @fgilio, thanks for posting this and sorry for late response. I'm just getting into this, had crazy time recently :D

**Comment by fgilio** [comment]
Thank you for even looking into it, and I hope you find it worth the effort

**Comment by michalsnik** [comment]
Ok, looks like this is a bit tricky, as we can only use self-signed certificate on localhost. And this results in browser warnings.. before you're able to inspect anything you have to either accept `insecure localhost` warning, or turn on the flag #allow-insecure-localhost in chrome (or add your IP as exception host in firefox). Same issue is present in electron, but fortunately there we can programatically turn on `ignore-certificate-errors`. I'd rather try to keep `http` version the default one, and add optional setting for turning on `https` with proper notes in readme, but it might be impossible to allow insecure localhost on mobile devices' browsers..

We could also generate free certificate for let's say `vue-devtools.dev` domain and then tell users to map it to localhost in hosts file, but if you'd want to debug app remotely, you'd have to also map this domain to your local network's IP, not only localhost - thus we'd probably need two certificates and setting them would be probably impossible.

Last idea that pops out in my mind is to tell users to add them to trusted root certificates, but it won't solve warnings on mobile devices :/

I need to get my head clear :D Perhaps I'm missing something here, I didn't play much with SSL in the past.

**Comment by fgilio** [comment]
Well that's certainly much more convoluted than I thought.

I think it's a perfectly valid trade off to have to enable the feature, and follow some instructions, to make HTTPS work. But even there, it seems there's no way to make it work seamlessly in mobile devices...

The root certificate thing looks like a good option, but I think Firefox uses its own certificate storage so users might have to manually add the exception.
I'll go grab my Android device and test this: https://support.google.com/nexus/answer/2844832?hl=en (but it does say "Some of these steps work only on Android 8.0 and up")

-
It seems like the only real solution is to bounce everything to a real server with a real certificate. But, of course, security, privacy and connection dependence render this into a no go.

**Comment by Akryum** [comment]
Maybe try https://ngrok.com/

**Comment by fgilio** [comment]
@Akryum Just found out that websocket works trough ngrok 🎉

**Comment by michalsnik** [comment]
Good idea. I just checked it and the only thing I need to do is to make port explicit in connection and not set it by default, so once user provide ngrok host without port it won't add any - causing connection issue. And ofc documentation need to updated. I'm on it. Thanks for pointing ngrok @Akryum , I totally forgot it proxies https to http <3

**Comment by fgilio** [comment]
Awesome! Count me in if you need someone to help test it

On Feb 21, 2018 13:40, "Michał Sajnóg" <notifications@github.com> wrote:

Good idea. I just checked it and the only thing I need to do is to make
port explicit in connection and not set it by default, so once user provide
ngrok host without port it won't add any - causing connection issue. And
ofc documentation need to updated. I'm on it. Thanks for pointing ngrok
@Akryum <https://github.com/akryum> , I totally forgot it proxies https to
http <3

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vuejs/vue-devtools/issues/597#issuecomment-367388752>,
or mute the thread

**Comment by michalsnik** [comment]
@fgilio you can check out @vue/devtools v1.1.0 :) Documentation have also been updated https://github.com/vuejs/vue-devtools/tree/master/shells/electron

**Comment by fgilio** [comment]
Just tested it by inspecting inside an iframe loaded with HTTPS and It's working perfectly!

This is truly a game changer for us, it's been a nightmare to debug inside iframes. And now we can even do it from a real device, thanks you!!

**Comment by fgilio** [comment]
In case someone finds this, this is the only thing I added to my app's html `<script src="https://e75b1e01.ngrok.io"></script>` (of course ngrok id will be different each time)

**Comment by svenez** [comment]
I have vue app running inside iframe with https, served by vue-cli dev server. And it cant connect to dev-tools middleware server 

`https://localhost:8098/socket.io/?EIO=3&transport=polling&t=Ny2ct51 net::ERR_SSL_PROTOCOL_ERROR`

is there any run argument to start middleware server via ssl? e.g.

`./node_modules/.bin/vue-devtools --with-ssl`

**Comment by BartTactick** [comment]
> I have vue app running inside iframe with https, served by vue-cli dev server. And it cant connect to dev-tools middleware server
> 
> `https://localhost:8098/socket.io/?EIO=3&transport=polling&t=Ny2ct51 net::ERR_SSL_PROTOCOL_ERROR`
> 
> is there any run argument to start middleware server via ssl? e.g.
> 
> `./node_modules/.bin/vue-devtools --with-ssl`

I am experiencing the same issue, even with ngrok.
Does someone have a solution?

**Comment by coder-at-heart** [comment]
I solved this using a caddy reverse proxy.  (I used caddy as my local server anyway)

`Caddyfile` 
```
https://vdt.csd {
	reverse_proxy localhost:8098
}
```
(I have a `/etc/hosts` entry for vdt.csd) 

Then in my `app.js` file
```
import devtools from '@vue/devtools'
import {createApp, h} from 'vue'
...
if (process.env.NODE_ENV === 'development') {
  devtools.connect('https://vdt.csd', null)
}
```
Hope this helps someone
