### ISSUE TITLE
Open in editor not working when not served by node.

### ISSUE THREAD

**Issue by mathieutu** [vuejs/vue-devtools#598]
### Version
4.1.2

### Browser and OS info
All

### The problem
Hi,

This issue concerns both the vuejs devtools and the @yyx990803 [Lauch editor](https://github.com/yyx990803/launch-editor).

I'll take my example to explain the problem but it's exactly the same for every projet where vue is not served by nodejs.

I'm a Laravel user and I use laravel-mix which is just a wrapper over webpack.
Our html files are served by php, but we also have a hot reloading function which start a node server, and serve the js and css files. (see https://laravel.com/docs/master/mix)

The problem here is that the fetch here is done relatively, and so the '/__open-in-editor' route will be asked on the php server : 
https://github.com/vuejs/vue-devtools/blob/dc75c5f63d0041f7a5bed24dc7902223f0e42c2a/src/util.js#L497

So we have two options:
- If the node server is launched, and so that the '/__open-in-editor' route is up, we have to make a php route to redirect to its url (but, actually, make a php route to use vuejs devtools is really overkill).

- If the node server isn't launched and files are just built and served by nginx, we can't do anything.

Moreover, if the ide is not installed exactly where you planned, this doesn't work at all (I'm using PhpStom EAP version, which is not in the folder you supposed)

Why don't use the IDEs APIs for that ? they (almost) all have an url to show the file. 
Examples:

- "sublime"  => "subl://open?url=file://%file&line=%line",
- "textmate" => "txmt://open?url=file://%file&line=%line",
- "emacs"    => "emacs://open?url=file://%file&line=%line",
- "macvim"   => "mvim://open/?url=file://%file&line=%line",
- "phpstorm" => "phpstorm://open?file=%file&line=%line",
- "idea"     => "idea://open?file=%file&line=%line",
- "vscode"   => "vscode://file/%file:%line",

I have not the answers to all my questions, but thoughts about some (to start, fetch the absolute url from the real node server)

Thanks for your help, and your amazing job.
Matt'

### What is expected?
Component should be opened in editor.

### What is actually happening?
Component is not opened, and a 404 is returned by backend.

**Comment by yyx990803** [comment]
The devtool doesn't have access to run arbitrary commands on your system, the only thing it can do is to make an HTTP request - which is why you need a server (with the privilege to execute commands) to handle that request.

On the other hand, this means the server doesn't really have to be in Node or even using `launch-editor`. As long as it can handle a request in the form of `/__open-in-editor?file=xxx`, it can work. You can implement the equivalent of `launch-editor` in PHP, or just a simple script that launches only the IDE you are using.

**Comment by mathieutu** [comment]
@yyx990803 Yeah but here, it doesn't work!
It at least should fetch the server which really serve the js files!

Or directly fetch the url to open the ide as we don't need more...

**Comment by Akryum** [comment]
Fixed by #575

**Comment by mathieutu** [comment]
👌

**Comment by ctf0** [comment]
@mathieutu have u managed to get this to work with laravel ? if yes can you share the steps ?

**Comment by mathieutu** [comment]
Hi, I didn't re-tried after @Akryum fix, but it should work with a WIP package I made at this time: try https://github.com/mathieutu/laravel-mix-editor.

Don't hesitate to make issue or PR on it, I have to take time to finish it.

**Comment by emadel80** [comment]
@mathieutu Doesn't work with laravel.  By adding to webpack.mix.js:

```
...
import openInEditor from 'launch-editor-middleware';

mix.openInEditor = (editor = null) => {
    if (mix.config.hmr) {
        const http = process.argv.includes('--https') ? 'https' : 'http';
        const {host, port} = mix.config.hmrOptions;
        window.VUE_DEVTOOLS_CONFIG = http + '://' + host + ':' + port + '/';

        mix.webpackConfig({
            devServer: {
                before(app) {
                    app.use('/__open-in-editor', openInEditor(editor));
                },
            },
        });
    }

    return mix;
};

...
```

Also, tried the following but doesn't work either:

```
...
const openInEditor = require('launch-editor-middleware');

mix.webpackConfig({
            devServer: {
                before(app) {
                    app.use('/__open-in-editor', openInEditor('code'));
                },
            },
        });
...
```

I use Laravel with Valet instead of artisan serve.  Any suggestions on how I could make it work?
