### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by ksdev-pl** [vuejs/vue-devtools#60]
Hello

Could you please add scrollbars? With mouse without scroll or RSI (with which you should not use mouse scroll), it's not very comfortable to scroll long lists.

Thanks for your great work.

**Comment by skyrpex** [comment]
Yes please. I came here for that reason.

**Comment by kaleb** [comment]
I am seeing scrollbars in mine in the components and the events views. Where are you not seeing scrollbars where there should be scrollbars?

**Comment by ksdev-pl** [comment]
It's an issue for old devtools version, should be closed.
