### ISSUE TITLE
Mutations double when "filter inspected state" something and reload the page

### ISSUE THREAD

**Issue by Xationch** [vuejs/vue-devtools#604]
### Version
4.1.3

### Browser and OS info
chrome windows 7

### Steps to reproduce
When you search with the "Filter inspected state" input and reload the page. All the mutations is double and everything become slow.

I need to close and reopen the chrome devtool

### What is expected?
should not double mutations when reloading the page

### What is actually happening?
![Image of bug](https://i.imgur.com/HDmllsLg.jpg)
see the screenshot https://imgur.com/HDmllsL

**Comment by Akryum** [comment]
Cannot reproduce on dev branch.
