### ISSUE TITLE
Trouble with Vuex store display online (for the vue-cli template "webpack")

### ISSUE THREAD

**Issue by glomotion** [vuejs/vue-devtools#605]
### Version
4.1.3

### Browser and OS info
MacOS 10.13.3 - Chrome 63.0.3239.132 - Node 8.6.0 - Webpack 3.6.0 - yarn 1.3.2

### Steps to reproduce
So to reproduce this bug:

1- create project: (basic project with vue-router && airbnb eslinting)

`
$ vue init webpack test-vue-vuex
`

2- install vuex as a depdency:

`
$ yarn add vuex
`

3- make /src/main.js the following:

```javascript
import Vue from 'vue';
import Vuex from 'vuex';

import App from './App';
import router from './router';

Vue.use(Vuex);
const store = new Vuex.Store({
  state: {
    moo: true,
  },

  mutations: {
  },

  getters: {
  },

  actions: {
  },
  strict: process.env.NODE_ENV !== 'production',
});

Vue.config.productionTip = false;
Vue.config.devtools = true;

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>',
});
```

4- build, then deploy to surge: 

`
$ yarn build; surge dist/
`

### What is expected?
When deployed online, the store appears inside of the devtools inspector, just like when it's run locally.

### What is actually happening?
Devtools cannot find / inspect the vuex store (displays: "No Vuex store detected"), despite all store based logic still working correctly.

---
https://github.com/vuejs-templates/webpack/issues/1286

I created an issue on the "Webpack" vue-cli template repo, and a contributer (LinusBorg) suggested this was more likely an issue with devtools, and not the template.

screenshot examples below:

**working locally:**
![screen shot 2018-02-02 at 5 53 29 pm](https://user-images.githubusercontent.com/1452237/35720501-10947372-0842-11e8-9412-a0a2f4133fde.png)

**not working online:**
![screen shot 2018-02-02 at 5 44 20 pm](https://user-images.githubusercontent.com/1452237/35720188-b8b93e4a-0840-11e8-8a52-c0672c9f2e6e.png)

**Comment by LinusBorg** [comment]
Hey, would you do the maintainers a favor and create a simple repository where this is already set up to reproduce the problem?

**Comment by glomotion** [comment]
repo:
https://github.com/glomotion/test-vuex

example of built / deployed instance:
http://orange-ant.surge.sh/

**Comment by wtm17** [comment]
Same issue! 

Note if you change the vue-cli production build config in `/config/prod.env.js` to use `"development"` as the `NODE_ENV` variable, then the Vuex store shows up in devtools. Obviously not the ideal solution, though.

https://github.com/glomotion/test-vuex/blob/master/config/prod.env.js

**Comment by wangxiangyao** [comment]
Same issue! 

the env:
  chrome:  65.0.3325.162
  vue-cli:  3.0 beta
  vue-devtools: 4.1.4

My computer was reloaded yesterday.This problem occurs after the new vue-cli is installed.

![image](https://user-images.githubusercontent.com/23569474/37502099-396a3940-290c-11e8-9734-cb1c09e2df26.png)

![image](https://user-images.githubusercontent.com/23569474/37502115-47d88f04-290c-11e8-9d3a-3cbdfe76571f.png)

**Comment by Akryum** [comment]
@glomotion Write `Vue.config.devtools = true` before creating the store (the check is done in the store constructor [here](https://github.com/vuejs/vuex/blob/dev/src/store.js#L66)).

**Comment by glomotion** [comment]
Thank you @akryum! That did the trick.

**Comment by LinusBorg** [comment]
@Akryum the original report was that this flag didn't work.

**Comment by Akryum** [comment]
Well it works if used before creating the store. 😉

**Comment by Akryum** [comment]
Maybe a note could be added in the docs?

**Comment by LinusBorg** [comment]
Oh, now I got it, thanks.
