### ISSUE TITLE
Issue installing vue-remote-devtools global addon

### ISSUE THREAD

**Issue by auzystephens** [vuejs/vue-devtools#609]
## Version
4.1.3

### Browser and OS info

macOS High Sierra
Vue CLI 3
5.6.0 of NPM

### Steps to reproduce

Run `sudo npm i -g @vue/devtools`

### What is expected?
Install of `@vue/devtools`

### What is actually happening?

```/usr/local/lib/node_modules/@vue/devtools/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@vue/devtools/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.11 postinstall: `node install.js`
npm ERR! Exit status 1
```
[Here's the full NPM log](https://gist.githubusercontent.com/auzystephens/ace1c04fd54bb0462a9f165d6262f152/raw/a42aa529f90b836843671d068ee727379cd5dd96/2018-02-08T23_06_28_394Z-debug.log)
---

I have been able to install the `cli-init` global addon without an issue if that eliminates anything.

It also is able to install as long as I don't do a global install.

Please forgive if this is in the wrong format, this is my first bug report.

**Comment by auzystephens** [comment]
[Here is the full npm log](https://gist.githubusercontent.com/auzystephens/ace1c04fd54bb0462a9f165d6262f152/raw/a42aa529f90b836843671d068ee727379cd5dd96/2018-02-08T23_06_28_394Z-debug.log)

**Comment by auzystephens** [comment]
This appears to be a common issue with Electron and npm permissions. More info [here](https://github.com/electron/electron/blob/8a4c76d6558cffa53400e54317f0f9b1da22f7ef/docs/tutorial/installation.md#troubleshooting). Since this is not related to the vue-devtools I will close issue.

**Comment by auzystephens** [comment]
This appears to be a common issue with Electron and NPM permissions. More info [here](https://github.com/electron/electron/blob/8a4c76d6558cffa53400e54317f0f9b1da22f7ef/docs/tutorial/installation.md#troubleshooting). Since this is not related to the `vue-devtools` I will close this issue.

**Comment by ascarter** [comment]
It would be useful to put the above command and links to the reasons in the README. I don't see how this won't be a common problem if you are using global install and the Node package installer.
