### ISSUE TITLE
Add the ability to copy props

### ISSUE THREAD

**Issue by BeauAgst** [vuejs/vue-devtools#611]
### What problem does this feature solve?
When doing unit tests, I need to grab props data, as an example. Rather than trawling through the data from a parent component, it would be nice to be able to just copy it directly from devtools for that component specifically.

### What does the proposed API look like?
It would work in a similar way to the `data` properties do, except instead of a pencil (to edit) there's an icon to copy to clipboard.

**Comment by Akryum** [comment]
Duplicate of #442
