### ISSUE TITLE
vue-perf-devtool   vue-devtools = "No Vuex store detected."

### ISSUE THREAD

**Issue by lionel-bijaoui** [vuejs/vue-devtools#612]
### Version
4.1.3

### Browser and OS info
Firefox 58.0.2 / Windows 10

### Steps to reproduce
Install vue-devtools and vue-perf-devtool extensions.
Open a vue project that use Vuex and open vue-devtools panel on Vuex tab.

### What is expected?
Detect the Vuex store and show it

### What is actually happening?
Show "No Vuex store detected."

---
If you deactivate vue-perf-devtool everything goes back to normal.
There seem to be some kind of interference between the two devtool panel

**Comment by LinusBorg** [comment]
We don't maintain that other tool (which you provided no information about). Have you opened an issue in their repository?

I suggest the author(s) of that other tool should look into this first.

**Comment by lionel-bijaoui** [comment]
Thank you for your answer.
I thought this was part of the same family of devtools for Vue.
My mistake, I will open another issue there.
Have a nice day !

Le 9 févr. 2018 22:53, "Thorsten Lünborg" <notifications@github.com> a
écrit :

**Comment by probil** [comment]
@lionel-bijaoui `vue-perf-devtool` is a source of the bug. "Vuex detected" in `vue-devtools` when I disable it.

**Comment by harryhazza77** [comment]
just wanted to add that i also get this problem too

**Comment by rafaesc** [comment]
Hi @lionel-bijaoui,

you can close this issue, I fixed on 0.0.6 version of vue-perf-devtool.
if the problem persists, you can continue in this thread.

https://github.com/vue-perf-devtool/vue-perf-devtool/issues/7

Regards!

**Comment by lionel-bijaoui** [comment]
@rafaesc thanks !
