### ISSUE TITLE
"Store as global variable" button for components

### ISSUE THREAD

**Issue by Kelin2025** [vuejs/vue-devtools#613]
### What problem does this feature solve?
It's a nice feature to edit data right in vue-devtools  
But I also want to test components in console by calling their methods etc during development  
For now, I just write `window.a = this` in created hook  
It would be nice to have "Store as global variable" button in components section that will just put the component instance in some global variable

### What does the proposed API look like?
Just a button near "Scroll to view" ([**here**](http://i.imgur.com/FSkEW6D.png)) that will copy component instance to a global variable

**Comment by LinusBorg** [comment]
You can already do that.

When you select a component in the component inspector's tree, you will see a short note beside it, like this:
```
<App> = $vm0
```
<img width="437" alt="bildschirmfoto 2018-02-09 um 22 50 10" src="https://user-images.githubusercontent.com/1444526/36051834-b81786da-0deb-11e8-8e2a-c97648f35c4a.png">


That means that this component is now accessible as a variable named `$vm0` in the console.

**Comment by Kelin2025** [comment]
But...  
![image](https://user-images.githubusercontent.com/4208480/36052008-0ef5666e-0dfd-11e8-98b4-d87ef319c125.png)  
![image](https://user-images.githubusercontent.com/4208480/36052014-148e275a-0dfd-11e8-8fc8-f650ca3083a5.png)

**Comment by LinusBorg** [comment]
But....

<img width="701" alt="bildschirmfoto 2018-02-09 um 22 57 09" src="https://user-images.githubusercontent.com/1444526/36052094-9835d596-0dec-11e8-967a-c42ac0c3bc72.png">

Can you provide a little more information about the scenario in which this doesn't work? any (i)frames involved, for example?

**Comment by Kelin2025** [comment]
I've just installed `webpack` template from `vue-cli`, no iframes on the page (even from extensions) :thinking:

**Comment by crswll** [comment]
I just opened up a PR which might make this a little more obvious: #614

**Comment by Akryum** [comment]
Fix in #614
