### ISSUE TITLE
Every component is $vm0 in vue-devtools

### ISSUE THREAD

**Issue by tillyboy** [vuejs/vue-devtools#615]
### Version
4.1.3

### Browser and OS info
Chrome 64.0.3282.140 (Official Build) (64-bit) / Manjaro Linux 4.15.0-1

### Steps to reproduce
Follow [this tutorial](https://laracasts.com/series/learn-vue-2-step-by-step/episodes/11?autoplay=true) until 5:35.

### What is expected?
`$vm0` should reference the `tabs` component.

### What is actually happening?
`$vm0` instead references the containing `div#root` component.

---
Everything inside the `div#root` is referenced as `$vm0`. I am actually unsure if this is a bug or if `$vm0` intends the Vue instance or if every subcomponent should get its custom `$vmX`. Inferring from the linked tutorial however, it seems that something went wrong here.

**Comment by Gerche** [comment]
Did you click on the tabs component inside the vue pane like they did in the video?
If you did you will see " \<Tabs\> == $vm0" as the component title here.
This means $vm0 references the tabs component now, $vm0 will always reference the component you selected in the vue pane.
If \<Root\> was the last component you've clicked $vm0 will be equal to this.

**Comment by tillyboy** [comment]
Nope I didn't. Found out shortly after and thought that I already closed the issue.
