### ISSUE TITLE
Documentation on how to run on port != :8080

### ISSUE THREAD

**Issue by FEA5T** [vuejs/vue-devtools#617]
### What problem does this feature solve?
8080 is used by a lot of services.  I need a way to run the dev-tools build on a port other than 8080.

### What does the proposed API look like?
Unsure

**Comment by michalsnik** [comment]
Hey @FEA5T. Devtools use webpack-dev-server, so it's as simple as passing another parameter:
```
npm run dev -- --port 4000
```
More info here: https://webpack.js.org/configuration/dev-server/#devserver-port 

If you still think it would be of use, don't hesitate to create a PR with updated documentation :)

**Comment by FEA5T** [comment]
@michalsnik Thanks, I noticed that it was running webpack-dev-server however when I did some Ctrl-F'ing I noticed :8080 hardcoded into a lot of tests and other places so I assumed that there had to be something more to it.

Thanks!
