### ISSUE TITLE
Installing as project dependency asks for Ionic version

### ISSUE THREAD

**Issue by gabrielboliveira** [vuejs/vue-devtools#623]
### Version
4.1.3

### Browser and OS info
Any / macOS 10.13.3

### Steps to reproduce
Install @vue/devtools as devDependency with yarn (`yarn add --dev @vue/devtools`)

### What is expected?
@vue/devtools should be installed with no issues

### What is actually happening?
Yarn shows a warning message: `Couldn't find any versions for "ionic" that matches "beta". Please choose a version of "ionic" from this list:`
Then it just don't install at all, stuck at `Building fresh packages. waiting...`

![yarn install error](https://user-images.githubusercontent.com/11093090/36484262-6ff23480-16f7-11e8-9cdb-854496383db2.png)

---
Following the Electron installation docs: https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md

**Comment by Akryum** [comment]
I think we don't have `ionic` declared as a dependency anywhere in the devtools.

**Comment by gabrielboliveira** [comment]
@Akryum Yep.. That's the weird thing. I did a fresh yarn install before testing this, and running `yarn add --dev @vue/devtools` asks for the Ionic version. Perhaps a sub-dependency of a direct dependecy?

**Comment by gabrielboliveira** [comment]
@Akryum Sorry to bother you guys with this, but I managed to solve this removing ionic from my globally installed packages. It looks like ionic installation broke for some reason. Removing it solved the issue.
