### ISSUE TITLE
Devtools fail in onActivated: 'Cannot find menu item with id vue-inspect-instance'

### ISSUE THREAD

**Issue by henrik-muehe** [vuejs/vue-devtools#629]
### Version
4.1.3

### Browser and OS info
Chrome 64, Mac OS

### Steps to reproduce
Install plugin, open background tab, open console, watch error message.

### What is expected?
No error message.

### What is actually happening?
Error message shows.

---
This may be benign, the tools do seem to work (although showing this message) on vuejs.org.

**Comment by Akryum** [comment]
This is benign but would be nice to fix.
