### ISSUE TITLE
Safari DevTools active on production site when disabled in main.js

### ISSUE THREAD

**Issue by bigsee** [vuejs/vue-devtools#632]
### Version
4.1.3

### Browser and OS info
Safari 11.0.2, Mac OS 10.13.2

### Steps to reproduce
Specify in the main.js file that vue-devtools should be disabled in production mode:

```(javascript)
if (process.env.NODE_ENV === 'production') {
  Vue.config.devtools = false;
}
```

2. Open a URL in Chrome where there is a production build and confirm that dev tools have been disabled
3. Open the same URL in Safari and click on the devtools button

### What is expected?
1. A message, similar to the one in Chrome, which states: "Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author."
2. No components or other data to be visible

### What is actually happening?
The dev tools are still available and I can see all the components and state, even in production.

**Comment by bigsee** [comment]
@jaredhobbs kindly confirmed that this is a known bug here: https://github.com/vuejs/vue-devtools/pull/352

When a user visits a site in development mode then then later visits the production version in the same browser session, the devtools will appears. However, the data that appears is not actually data from the production version, but persistent data from the earlier visit to the development version.

I think this is probably still confusing and therefore worth fixing so I won't close this, but the contributor may disagree. Perhaps something in the docs to highlight this bug would save others some debug time? 😀

**Comment by Akryum** [comment]
Hi thanks for your bug report, but we no longer support Safari. Please use the [standalone electron app](https://github.com/vuejs/vue-devtools/blob/master/shells/electron/README.md) instead.
