### ISSUE TITLE
Properties prefixed with $ are not editable

### ISSUE THREAD

**Issue by frlinw** [vuejs/vue-devtools#636]
### Version
4.1.3

### Browser and OS info
Windows 10 / Chrome 64

### Steps to reproduce
- Open vue devtool
- go on a component
- Add a property prefixed with $ in data (called $value)
-> you can't edit the property

### What is expected?
$value should be editable (except properties added by official plugin maybe)

### What is actually happening?
It is not possible to edit $value

---
$ is not a reserved sign though it can mean `private` or `readonly` (underscore can mean private too, but you can edit underscore prefixed value), dev should be able to edit every properties.

**Comment by Akryum** [comment]
Properties starting this a `$` sign are meant to be internal to Vue. You shouldn't name yours with it.

**Comment by frlinw** [comment]
I agree and it is true at the very "root" of a component (this.$vueRelated), not inside an object (this.myCustomObj.$dataRelated)

Anyway, if you want to enforce `readonly` (and `$` or `_` prefixed values don't mean `read-only` at all), and be consistent with the style guide:
- `_` prefixed property should be readonly too
- `$_` properties should be editable

Reference: https://vuejs.org/v2/style-guide/#Private-property-names-essential

> Vue uses the _ prefix to define its own private properties, so using the same prefix (e.g. _update) risks overwriting an instance property. Even if you check and Vue is not currently using a particular property name, there is no guarantee a conflict won’t arise in a later version.

As for the $ prefix, it’s purpose within the Vue ecosystem is special instance properties that are exposed to the user, so using it for private properties would not be appropriate.

Instead, we recommend combining the two prefixes into $_, as a convention for user-defined private properties that guarantee no conflicts with Vue
