### ISSUE TITLE
Dynamically created Vue instances

### ISSUE THREAD

**Issue by hkan** [vuejs/vue-devtools#64]
Thanks for such an awesome devtool, it's really helpful. The problem I'm having is when I create a `new Vue({ ... })` instance in a place such as `$.ajax(...).done(function () { /* here */ })` this devtool doesn't show it. Is that something I'm doing wrong? Do you need a full example to reproduce the issue?

**Comment by hkan** [comment]
I took a look through the source code. If only there's a way to call `scan` function in `backend/index.js`, I could do that manually every time, until somebody patches the devtool.

**Comment by sirlancelot** [comment]
Is this still an issue for you? I create Vue instances on the fly using a similar mechanism and I can inspect them within DevTools.

**Comment by hkan** [comment]
@sirlancelot just tried `new Vue({ el: '#footer' });` on console and it's not visible in Vue DevTools tab.

**Comment by simplesmiler** [comment]
@hkan this use case with multiple separated roots belongs to https://github.com/vuejs/vue-devtools/issues/98.
Try specifying parent:
``` js
var vm = new Vue({ el: '#root' }); // main root
var header = new Vue({ el: '#footer', parent: vm });
```
If this works, then I consider the issue resolved.

**Comment by hkan** [comment]
@simplesmiler yeah, if I specify a parent, Vue DevTools tab shows the new component.
