### ISSUE TITLE
Tab shortcut interference 

### ISSUE THREAD

**Issue by jq-87** [vuejs/vue-devtools#640]
### Version
4.1.3

### Browser and OS info
Chrome 64 / OSX 10.12.6

### Steps to reproduce
* Open multiple browser tabs and in one of those tabs engage Vue Dev Tools.
* Try using the shortcut for switching browser tabs (⌘   1 through ⌘   8)

### What is expected?
I should be able to use the standard browser shortcut to switch browser tabs

### What is actually happening?
Vue dev tools uses this shortcut (⌘   1 through ⌘   8) and prevents me from switching browser tabs

**Comment by Akryum** [comment]
If you are not focusing the devtools, you should be able to switch to another tab (tested in Firefox and Chrome on MacOS).
