### ISSUE TITLE
Vue Devtools do not capture events emitted from the `main.js`

### ISSUE THREAD

**Issue by AyushG3112** [vuejs/vue-devtools#651]
### Version
4.1.4

### Browser and OS info
Chrome 65 / Ubuntu 16.04

### Steps to reproduce
1. Create a central Event Bus.
2. Emit any event from that event bus in `main.js`

### What is expected?
Event Tab in Vue Devtools should capture the event

### What is actually happening?
The event is not captured.

**Comment by Akryum** [comment]
The bus isn't rendered on the page, so the devtools can't detect it.
