### ISSUE TITLE
Devtools lags when value is a long string

### ISSUE THREAD

**Issue by donnysim** [vuejs/vue-devtools#652]
### Version
4.1.4

### Browser and OS info
Windows 10

### Steps to reproduce
Have a base64 image string or something big in data or vuex store.

### What is expected?
Opening component details or vuex mutation is fast.

### What is actually happening?
It takes a long time until it displays the data.

---
Maybe for very long strings it could shorten them to some max length and provide a button to display the whole thing?

**Comment by jakob-fuchs** [comment]
I'm having the exact same problem. If you save a base64 encoded image that's larger than one or two megabytes then the devtools basically become unusable. Vuex itself doesn't seem to have any kind of problems with large strings, although there might be better places to store them.

I rarely have the need to see the actual value, so it could be hidden and only be shown after clicking on it.

I haven't tried it but here's a possible solution for other people that run into that problem: https://medium.com/@gabriele.cimato/on-how-to-store-an-image-in-redux-d623bcc06ca7
