### ISSUE TITLE
Can be used in Chrome://inspect? 

### ISSUE THREAD

**Issue by snoopy83101** [vuejs/vue-devtools#654]
### Version
4.1.4

### Browser and OS info
mac OS

### Steps to reproduce
1 chrome://inspect
2 check inspect

### What is expected?
![image](https://user-images.githubusercontent.com/24613784/38044020-29cbbf2a-32eb-11e8-8238-3022c6cca5ca.png)
in chrome://inspect/#devices , just can't find ...

### What is actually happening?

I hope it can be used.

**Comment by palpich** [comment]
Perhaps this would help you [link](https://github.com/vuejs/vue-devtools/tree/master/shells/electron)

**Comment by Akryum** [comment]
Use the standalone electron app.
