### ISSUE TITLE
Would love editable props

### ISSUE THREAD

**Issue by ericcirone** [vuejs/vue-devtools#669]
### What problem does this feature solve?
Lot's of times I would like to see quick changes when a prop is changed, but most of the time the props getting sent in are hard coded. I would love to be able to change props on the fly as well as data.

### What does the proposed API look like?
Make props editable the same way that data is editable.

**Comment by lehos** [comment]
уоu can edit data (which is passed to your component as prop) in parent controller.

**Comment by emanuelmutschlechner** [comment]
I think editing `props` shouldn't be added as a feature to devtools because following warning will be thrown every time:
```
[Vue warn]: Avoid mutating a prop directly since the value will be 
overwritten whenever the parent component re-renders. Instead, 
use a data or computed property based on the prop's value.
```

But feel free to test it yourself
[chrome.zip](https://github.com/vuejs/vue-devtools/files/1933805/chrome.zip)
1. Download and extract `chrome.zip` to `chrome`
2. Open Chrome extension page
3. Check "developer mode"
4. Click "load unpacked extension", and choose `chrome`.

**Comment by cannap** [comment]
maybe as an option? :D 
"Enable Prop manipulation*" 
or something

**Comment by emanuelmutschlechner** [comment]
@cannap We'll have to wait until we have the settings tab #547

**Comment by gabrielstuff** [comment]
@emanuelmutschlechner what are the plan for #547, it actually looks pretty dead.

**Comment by geocine** [comment]
This is an interesting feature so we could directly test an individual component is behaving correctly when a prop is changed just like how we could manipulate an attribute of a web component.

**Comment by jamyspencer** [comment]
This is a great feature, I just used it for testing a component I'm making. Thanks for adding it :)

**Comment by noalbalint** [comment]
is it possible there's been regression on this feature? I'm unable to edit props in 2022

https://user-images.githubusercontent.com/45208632/180294718-65ae37ba-1fc0-4cab-b222-ad2a7db344d3.mov

**Comment by cannap** [comment]
> is it possible there's been regression on this feature? I'm unable to edit props in 2022
> 
>  Screen.Recording.2022-07-21.at.11.56.25.AM.mov

<img width="314" alt="image" src="https://user-images.githubusercontent.com/1394151/180303041-494d5280-4e4d-4d50-87e2-44d27dc4b9fe.png">
