### ISSUE TITLE
Object editing without quotes on keys

### ISSUE THREAD

**Issue by beyersito** [vuejs/vue-devtools#671]
### What problem does this feature solve?
When you type in data-field-edit it has to be valid JSON. This confused me and a co-worker since we were trying to insert the object inside an array as regular js object: ( { foo: "bar" } instead of { "foo": "bar" } ). Only after trying to solve this issue I realized that in order to edit or add an object It had to be valid JSON.

### What does the proposed API look like?
I found two possible solutions:
* https://www.quora.com/How-can-I-parse-unquoted-JSON-with-JavaScript
* https://www.npmjs.com/package/jsonic

The first would be to:
```
 value.replace(/(['"])?([a-zA-Z0-9_] )(['"])?:/g, '"$2": ');
```
before checking if valid and also before saving

The second involves changing the parser library.

Another possible solution is to detect when an object or collection is being entered without quouted keys and give a warning.

I would like to implement this myself as a first contribution.

**Comment by Akryum** [comment]
There should already be a warning displayed if the input is not valid JSON.

**Comment by beyersito** [comment]
The warning is shown, but the reason for the warning is not clear, it says invalid value, leading to think that objects can not be input
