### ISSUE TITLE
vue ssr online DevTools icon is not active

### ISSUE THREAD

**Issue by 132yse** [vuejs/vue-devtools#672]
### Version
4.1.4

### Browser and OS info
chrome、filefox

### Steps to reproduce
1.turn to www.idanmu.cc   the icon is not active
2.change url to www.google.com , and then click the back button , back to prev page(www.idanmu.cc) , the icon is active

### What is expected?
1.SSR caused
2.brower caused

### What is actually happening?
the DevTools online is not actived , but when turn to another page , and come back , the icon is actived

and……if it runs on localhost , the icon is active , too

**Comment by XanderLuciano** [comment]
Unable to reproduce.
