### ISSUE TITLE
chrome 66 vue dev tools bug? body empty

### ISSUE THREAD

**Issue by d3bgger** [vuejs/vue-devtools#677]
### Version
4.1.4

### Browser and OS info
Chrome 66 / windows 10

### Steps to reproduce
Just have vue dev tools enabled (developer tools open) and reload a page containing a vue app. 

### What is expected?
DOM correctly shown in elements tab.

### What is actually happening?
body element is empty, inspection doesn't work

---
Most of the time, the body element is shown empty (elements tab), and can't inspect any element inside it.
When vue dev tools extension is disabled, body always shows its contents, and inspection works.

**Comment by alexdevero** [comment]
This may not be a bug in Vue dev tools. I might be experiencing the same issue in "default" Chrome dev tools:
![chrome epmty body](https://user-images.githubusercontent.com/4237724/39284150-2cc3640c-4912-11e8-8801-6f3bf0eea7c1.png)

**Comment by simplyynot** [comment]
I have this exact same issue and its driving me nuts. I found that if you keep the inspector closed and open after refreshing the page, it works. If you refresh the page with inspector open, the body blanks out.

**Comment by alexdevero** [comment]
@simplyynot I can confirm your observation. Refreshing the page with inspector open will cause the body to be empty, and dev tools unusable.

**Comment by d3bgger** [comment]
It just happened to me again, with vue dev tools extension disabled. 
So i guess @alexdevero you're right, this might be a chrome bug, and not a vue dev tools bug...

**Comment by alexdevero** [comment]
@d3bgger I forgot to mention that I don't even have vue dev tools. I found this issue through search. So, it is bug in Chrome.

**Comment by jayyarbsy** [comment]
Same here. Began occurring after I upgraded to 66 -- MacOS High Sierra 10.13.4
Page loads, but the <body> element is empty and elements on the page cannot be inspected.
Closing and re-opening dev tools fixes the problem until the next page reload, however, this is still extremely annoying
