### ISSUE TITLE
no component/store detection when using Vue or Vuex from CDN

### ISSUE THREAD

**Issue by laurentpayot** [vuejs/vue-devtools#683]
### Version
4.1.4

### Browser and OS info
Chrome 67, Ubuntu 18.04

### Steps to reproduce
* create a project with vue-cli 3 beta 9
* comment the line `import Vue from 'vue'` in **main.js**
* add `<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>` in the *body* section of **index.html**

### What is expected?
Components detection (Root, App…).

### What is actually happening?
No component displayed.

When using the select tool on a component, we get the following error in the console:
```
backend.js:1 Uncaught TypeError: Cannot read property '__VUE_DEVTOOLS_UID__' of undefined
    at backend.js:1
    at t.a.v.on.e (backend.js:1)
    at t.a.n.emit (backend.js:1)
    at e.listen.e (backend.js:1)
    at n (backend.js:1)
(anonymous) @ backend.js:1
v.on.e @ backend.js:1
n.emit @ backend.js:1
e.listen.e @ backend.js:1
n @ backend.js:1
postMessage (async)
o @ proxy.js:1
```

---
Same with Vue runtime from CDN.

Same issue when importing Vuex from a CDN: the store is not detected/displayed.

**Comment by Akryum** [comment]
You are using a production version of those, so devtools are disabled by default. See https://vuejs.org/v2/api/#devtools

**Comment by laurentpayot** [comment]
D'oh! Thanks @Akryum
