### ISSUE TITLE
Perform scan when children are destroyed and re-attached 

### ISSUE THREAD

**Issue by jonagoldman** [vuejs/vue-devtools#70]
It seems that autorefresh doesn't work in some cases. Would like to see if there is a solutions, please look at this issue: https://github.com/inca/voie/issues/8

Thanks.

**Comment by blake-newman** [comment]
@yyx990803 Whats the status on this.... Seems like it works okay for me now, may be wrong though.

**Comment by michalsnik** [comment]
I think it works well now. I you still experience this issue in Vue@2 and current devtools please reopen this issue and provide a working example that we could quickly jump into and inspect :)
