### ISSUE TITLE
Vuex mutations not showing in dev tools

### ISSUE THREAD

**Issue by nick-stanley** [vuejs/vue-devtools#710]
### Version
4.1.4

### Browser and OS info
Chrome 68.0.3440.75, Windows 10 1803

### Steps to reproduce
Created a new project using the Vue CLI (webpack).
Installed Vuex.
Created a basic store. Added one property (array) and a mutation to alter it.
Committed a mutation, store does update (when logged), but the mutation doesn't show in dev tools.

I took screenshots of each step, which can be viewed here: 
https://imgur.com/a/66ZCeSp

### What is expected?
The mutation should show in dev tools. I know it used to, seems to have been a very recent update somewhere that has stopped this from working.

### What is actually happening?
The mutation isn't showing in dev tools.

---
Be sure to check my screenshots here: https://imgur.com/a/66ZCeSp

**Comment by Ben52** [comment]
You need to record the mutations: 

<img width="1291" alt="screenshot 2018-07-26 13 30 52" src="https://user-images.githubusercontent.com/5143458/43278140-2e854130-90d8-11e8-850e-a5c1f9eb74cc.png">

**Comment by nick-stanley** [comment]
Oh man, I didn't even think of this because it had always just been on. Thanks, I must have turned it off by accident somehow.

**Comment by htasha** [comment]
Jesus christ, I almost go crazy because of this

**Comment by bennyty** [comment]
Another common thing I run into is something throwing an error. Sometimes I will have my vue devtools open without the console and wonder why my mutations aren't showing up. Check your console!

**Comment by aislanmaia** [comment]
For me, not is showing when changing the route. My devtools doesn't can to show up anything, like it had lost the state completely, or get the state unregistered.
