### ISSUE TITLE
Edit State Properties in Tree View

### ISSUE THREAD

**Issue by srhise** [vuejs/vue-devtools#74]
Do you plan to have a feature to edit the state right there in the app / tree view, right now it just displays the values but you can't edit them.

**Comment by dansullivan86** [comment]
I have started playing about with implementing this:
https://github.com/dansullivan86/vue-devtools/tree/editable

The basics work, however I am having issues with the flush event.  Essentially I have created a loop, by updating the app data the app triggers a flush event, this then triggers an update-data event which updates the app data again.   Currently I have an ultra hacky settimeout which breaks the loop but we still trigger an error:
`[Vue warn]: Duplicate value found in v-for="field in target.state": {"type":"computed","key":"awww","value":{"a":{"b":{"c":123}}}}. Use track-by="$index" if you are expecting duplicate values.`

Is anyone else with more experience able to chime in here?

**Comment by yyx990803** [comment]
Hey @dansullivan86 - really appreciate the effort! I'll take a look when I get a chance.

**Comment by jbruni** [comment]
:+1: Great. I am also eager to see vue-devtools + vuex integration... :smiley:

**Comment by blake-newman** [comment]
@yyx990803  can this issue be closed?

**Comment by Christilut** [comment]
The ability to change VueX data (or component data) would be a great addition. Would make testing multiple states much easier.

**Comment by yazfield** [comment]
that's interesting

**Comment by markadrake** [comment]
Ran into some bugs today that being able to edit the data from the dev tools would have been much quicker for testing and resolution.

**Comment by serkandemirelnmq** [comment]
What is the current **state**?
