### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined backend.js

### ISSUE THREAD

**Issue by zhuman1993** [vuejs/vue-devtools#741]
### Version
4.1.5

### Browser and OS info
Chrome 67

### Steps to reproduce
1. git clone https://github.com/vuejs/vue-devtools.git
2. npm install
3. npm run build
4. add shells/chrome to the Chrome extension
5. open vue-devtools/vue 1-test.html in Chrome, then open Chrome developer tool and choose the vue section, finally console the error 'Uncaught TypeError: Cannot read property 'children' of undefined backend.js, and the components can not show.

node v 10.8.0

### What is expected?
i want the component show in the vue-devtools, and do not console error. thx!

### What is actually happening?
The tool console the error 'Uncaught TypeError: Cannot read property 'children' of undefined backend.js', and the components can not show

**Comment by zhuman1993** [comment]
i clone v4.1.4 release, and everything is ok.
i don't no why.

**Comment by KeithScheiwiller** [comment]
Is this still being investigated? I have no issue in v4.1.5 but the v5.0.0 betas all throw this error when opening the Vue tab.

For reference, here's the whole stack from master on Chrome 69 and Vue 1.0.28 (ugly format, sorry):
```
15:40:56.212 backend.js:10619  vue-devtools  Detected Vue v1.0.28 
15:40:56.218 backend.js:10889 Uncaught TypeError: Cannot read property 'children' of undefined
    at capture (VM2551 backend.js:10889)
    at Array.map (<anonymous>)
    at capture (VM2551 backend.js:10885)
    at Array.map (<anonymous>)
    at capture (VM2551 backend.js:10885)
    at Array.map (<anonymous>)
    at capture (VM2551 backend.js:10885)
    at Array.map (<anonymous>)
    at capture (VM2551 backend.js:10885)
    at Array.map (<anonymous>)
capture @ backend.js:10889
capture @ backend.js:10885
capture @ backend.js:10885
capture @ backend.js:10885
capture @ backend.js:10885
findQualifiedChildrenFromList @ backend.js:10760
flush @ backend.js:10740
scan @ backend.js:10699
setTimeout @ backend.js:10627
setTimeout (async)
connect @ backend.js:10626
initBackend @ backend.js:10504
handshake @ backend.js:1343
postMessage (async)
o @ proxy.js:1
124 @ proxy.js:1
t @ proxy.js:1
124 @ proxy.js:1
(anonymous) @ proxy.js:1
```
