### ISSUE TITLE
Cannot inspect Map in vue-devtools

### ISSUE THREAD

**Issue by awacode21** [vuejs/vue-devtools#744]
### Version
4.1.5

### Browser and OS info
Google Chrome Version 68.0.3440.106 (Official Build) (64-Bit) on Windows 10

### Steps to reproduce
Here is a little code sandbox:
Code:
https://codesandbox.io/s/m9qr69jmkp
Preview:
https://m9qr69jmkp.codesandbox.io/

Using the inputs you can add values to the map.
The console.log shows you all the map content, but using vue-devtools it is not possible to inspect the map.
You can only see "myMap: Map" .. so you can see that it is a map, but cannot see what it contains.

### What is expected?
that i can see the Maps content by inspecting the map using the vue-devtools

### What is actually happening?
Its only displayed that the data is from type Map, but you cannot interact with it, you cannot inspect its content

---
Reproducable with vue version 2.5.17 in latest nuxt version

**Comment by awacode21** [comment]
![map-inspect](https://user-images.githubusercontent.com/30939926/44257393-26428100-a20c-11e8-95a1-4aedaa28dd2a.PNG)

**Comment by awacode21** [comment]
Anything new on this?

**Comment by Akryum** [comment]
Could you post the reproduction again? The links in the OP are dead. Anyway I can't reproduce it on the dev app:

![Screenshot from 2019-03-20 17-18-52](https://user-images.githubusercontent.com/2798204/54700978-4769a800-4b34-11e9-9b27-4e75c2d0529b.png)

**Comment by awacode21** [comment]
@Akryum thank you for your reply. I restored the example links.
I still only see myMap: Map in the vue-devtools but maybe i'm handling the map wrong?

<img width="702" alt="Bildschirmfoto 2019-03-21 um 13 58 22" src="https://user-images.githubusercontent.com/30939926/54753625-c79a1700-4be1-11e9-90d1-f2ef21624263.png">

**Comment by Akryum** [comment]
I guess it's happening because you are using a polyfilled `Map` which is then technically not the same as the native `Map` and causes `myMap instanceof Map` to return `false`.

**Comment by awacode21** [comment]
Thank you
