### ISSUE TITLE
Vue tab missing in Chrome 69 on mac

### ISSUE THREAD

**Issue by jemminger** [vuejs/vue-devtools#763]
### Version
4.1.5-beta.1

### Browser and OS info
Version 69.0.3497.81 (Official Build) (64-bit), macOS 10.13.6 (17G65)

### Steps to reproduce
Open devtools on a page with Vue in dev mode.  

### What is expected?
The vue tab will be present

### What is actually happening?
The vue tab is missing

---
I see this error when trying to inspect the "background page" on the extension's info page in chrome: 

```
_generated_background_page.html:1 Unchecked runtime.lastError while running contextMenus.remove: Cannot find menu item with id vue-inspect-instance
    at s (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/background.js:1:640)
    at chrome.tabs.onActivated.addListener (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/background.js:1:2085)
```

**Comment by jemminger** [comment]
Looks like it's gone in Firefox too 62.0 (64-bit)

**Comment by jemminger** [comment]
Ugh, nevermind, pretty sure another script (Olark plugin) was silently crashing and somehow preventing the Vue devtools from starting.

**Comment by auntlucy** [comment]
Looks like the bug still exists on Chrome 69.

**Comment by jemminger** [comment]
In my case, some other script was running through and killing all timeouts on the page, I'm assuming killing the one that Vue devtools uses to set up.

**Comment by DanielRivers** [comment]
I have no plugins installed other than vue devtools and I am getting this issue.  Started randomly this morning ... Rebooted etc and no luck
