### ISSUE TITLE
Installation-suggestion

### ISSUE THREAD

**Issue by desunire** [vuejs/vue-devtools#767]
Manual Installation
Make sure you are using Node 6+ and NPM 3+

Clone this repo to your computer and remember the download path x
Then cd x 
npm install (Or yarn install if you are using yarn as the package manager)
npm run build
Open Chrome extension page
Check "developer mode"
Click "load unpacked extension", and choose shells/chrome.

**Comment by desunire** [comment]
installation suggest

**Comment by kewlniss** [comment]
After npm run build, I'd add: 
cd /shells/chrome
npx webpack
