### ISSUE TITLE
Vuex tab not showing up

### ISSUE THREAD

**Issue by nblackburn** [vuejs/vue-devtools#77]
Awesome job on the improvements but the `vuex` tab is not showing for me despite having access to it.

**Comment by dansullivan86** [comment]
@nblackburn not sure on your settings, but I have found you need to disable the logger.  It would be great if this wasn't the case as I work with people not using Chrome so could do with both. 

It also conflicts with strict mode, thinking it would be nice to have it drop to read only mode when in strict mode

**Comment by yyx990803** [comment]
Did you upgrade to vuex 0.5.0?

**Comment by nblackburn** [comment]
@yyx990803 Nope, but that did the trick, thanks!

**Comment by yyx990803** [comment]
@dansullivan86 vuex@0.5.1 should've fixed the strict mode issue

**Comment by dansullivan86** [comment]
@yyx990803 Thanks, working well now
