### ISSUE TITLE
Uncaught ReferenceError: t is not defined

### ISSUE THREAD

**Issue by sduduzog** [vuejs/vue-devtools#771]
### Version
5.0.0-beta.2

### Browser and OS info
Chrome 69 / Ubuntu 18.04

### Steps to reproduce
Basically running npm run serve. https://github.com/sduduzog/tover/tree/development link to the public repo where this occured

### What is expected?
Rendering of the app with hot reload as usual

### What is actually happening?
The app is not rendered probably because the error interrupts the process, leaving me with a black screen.

---
There were no issues whatsoever with the stable devtools. After disabling the stable one and installing the beta version I started running into this issue. Hopefully links from the screenshots will provide more context.
https://www.dropbox.com/s/60n2vzlycek0nwg/screenshot1.png?dl=0

https://www.dropbox.com/s/5x40glsed6qar3g/screensho2.png?dl=0

https://www.dropbox.com/s/kagaq0dix6h652j/screenshot3.png?dl=0

**Comment by studnitz** [comment]
Got the same error with a vanilly vue-cli typescript install. 

Also `vue ui` stops working with the same error in the console. This happens only in Chrome 69 though and not in Firefox. I'm on Windows.

**Comment by nathanchase** [comment]
Same error here in Chrome 69.0.3497.92 64-bit in Windows 10. Had to disable Vue Dev Tools in order to get my app to run, as the error prevented the Vue app from executing.

**Comment by acidjazz** [comment]
Same here, latest Chrome on OSX

**Comment by wangxuepeng** [comment]
Same issue, latest Chrome on OSX.

**Comment by laSinteZ** [comment]
Same here, MacOS, Google Chrome `Version 68.0.3440.106 (Official Build) (64-bit)`, Vue devtools `5.0.0 beta 2`.

**Comment by larsmars** [comment]
Same here, Chrome 69/Win 10
![devtool_crash](https://user-images.githubusercontent.com/5154589/45609213-317d0c80-ba57-11e8-8975-d85e4f515c93.PNG)

**Comment by dkuzmenchuk** [comment]
Same here. Ubuntu 18.04, Chrome 6, Vue devtools 5.0.0beta2

**Comment by intermundos** [comment]
Same here. Mac, Chrome, devtools 5.0.0-beta-2

**Comment by mekhami** [comment]
@Akryum this problem is still happening in 5.0.0 beta 3.
