### ISSUE TITLE
Devtools tab not showing in Firefox Nightly

### ISSUE THREAD

**Issue by entepe85** [vuejs/vue-devtools#786]
### Version
4.1.5

### Browser and OS info
Firefox Nightly 64.0a1 (2018-09-27) / macOS 10.13.4

### Steps to reproduce
Access development Vue project on localhost:8080, open Firefox Dev Tools after the toolbar button confirms that Vue was detected.

### What is expected?
vuejs-devtools should be injected into the Firefox developer tools

### What is actually happening?
No vuejs-devtools tab is to be found

---
Addon debugging console reports this error:

10:25:45.439 Unchecked lastError value: Error: An unexpected error occurred 11 devtools-background.js:1
	i moz-extension://cddcbf0c-11b9-9d48-9f6e-f9c2b200d64c/build/devtools-background.js:1:620

**Comment by xemoka** [comment]
Had this problem as well, looks like it's fixed in 64.0a1 2018-10-04, can this be closed?

**Comment by entepe85** [comment]
Yep, I can report it as fixed as well. Closing.
