### ISSUE TITLE
The line code was not deleted console.log

### ISSUE THREAD

**Issue by DrugsZ** [vuejs/vue-devtools#789]
### Version
5.0.0-beta.3

### Browser and OS info
chrome 69/windows7

### Steps to reproduce
Using the latest version of vue-devtool, the refs of the current instance will be continuously printed when the input is triggered on the subcomponent `vue-devtools/src/backend/index.js`

### What is expected?
The console has no extra information

### What is actually happening?
Print is triggered each time the refs data changes

**Comment by Akryum** [comment]
Closing in favor of #801
