### ISSUE TITLE
"Vue.js devtools" is not allowed to access about:newtab

### ISSUE THREAD

**Issue by clintonyeb** [vuejs/vue-devtools#790]
### Version
4.1.5

### Browser and OS info
FireFox Quantum (62.0), 64 Bit, Linux - Debian 9

### Steps to reproduce
1. Have VueJS Devtools installed on Firefox
2. Open  a new tab 
3. Open Console
4. Error shows up in console.
5. Error: `The extension "Vue.js devtools" is not allowed to access about:newtab                                              manifest.json `

### What is expected?
VueJS DevTools does not care about opening a new tab. (about:newtab)

### What is actually happening?
VueJS DevTools tried to access `about:newtab` and it seems Firefox does not allow addons to access this page. So there is a permission error.

---
No additional comments...

**Comment by Akryum** [comment]
I don't think this is effectively causing any issue.

**Comment by RodrigoCC-dev** [comment]
I have the same message when init Firefox: 'The extension "Vue.js devtools" is not allowed to access about:home'. In my case, Vue.js devtool don't recongnize my Vue.js apps in develop mode. I don't know if this message is relevant for my case, but may be. 
My Vue.js version is 4.5.8
