### ISSUE TITLE
Time travel passes state instead of payload

### ISSUE THREAD

**Issue by alex88** [vuejs/vue-devtools#792]
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 69 / OSX 10.13.6

### Steps to reproduce
 - open https://new-issue.vuejs.org/?repo=vuejs/vue-devtools
 - click the button twice
 - time travel to first mutation
 - time travel to second mutation
 - check console

### What is expected?
State changes as per the mutation code

### What is actually happening?
Mutation is called with state as payload

**Comment by alex88** [comment]
Sandbox link to check the code etc: https://codesandbox.io/s/jnkp169869

**Comment by eunjae-lee** [comment]
I'm having the same issue.
