### ISSUE TITLE
Bug submenu routing tooltip

### ISSUE THREAD

**Issue by Kolobok12309** [vuejs/vue-devtools#795]
### Browser and OS info
Chrome 69 / Windows 10 x64

### Steps to reproduce
Open vue-devtools,  hover on menu item routing, and on the first item in this menu
 

### What is expected?
see tooltip menu item mouse

### What is actually happening?
tooltip was shown under my mouse, after this hover leave menu and menu closing

---
Change position of this tooltip on hover
Vue devtools 5.0.0 beta 3

**Comment by richardhuf84** [comment]
+1 for this one. 

Just to explain it in more detail (I think this is the same issue as described above), when you hover over the routing dropdown, 2 menu items appear in the dropdown. If you hover over the first item, after a moment, a tooltip appears below the cursor, which in turn, causes the dropdown to disappear. 

See gif attached of the issue.

![vue-dev-tools-menu-bug](https://user-images.githubusercontent.com/5269874/58302613-77347500-7e2f-11e9-98a3-f05712990ed6.gif)

**Comment by Kolobok12309** [comment]
Now fixed
![image](https://user-images.githubusercontent.com/32272181/88164474-d866fc80-cc1c-11ea-8196-11b14d2d8e91.png)
