### ISSUE TITLE
Console.log left in code

### ISSUE THREAD

**Issue by arpowers** [vuejs/vue-devtools#801]
### Version
5.0.0-beta.3

### Browser and OS info
chrome osx

### Steps to reproduce
found in src/backend/index.js ~ line 680

### What is expected?
no logging from dev tools 

### What is actually happening?
the erroneous logging cost me about 30 minutes trying to figure out why it was getting output

**Comment by louim** [comment]
There is a PR pending for this: https://github.com/vuejs/vue-devtools/pull/791
