### ISSUE TITLE
Unit tests within single file component

### ISSUE THREAD

**Issue by eiva** [vuejs/vue-devtools#807]
### What problem does this feature solve?
I was so excited by single file components, and have a naive question about the same approach with tests:

What do you think if single file component has the tag "tests", and js code inside used to perform unit tests for this particular component?

### What does the proposed API look like?
```
<template>
</template>
<script>
</script>
<tests>
import { mount } from '@vue/test-utils'
describe('Some name', () => {
  const wrapper = mount() // import default componet

  it('renders the correct markup', () => {
    expect(wrapper.html())....
  })
})
</tests>
```

**Comment by Akryum** [comment]
I'm not sure this is related to vue-devtools which is the extension you put in your browser to debug your Vue app.
