### ISSUE TITLE
vue-remote-devtools's window always on top

### ISSUE THREAD

**Issue by heihachi88** [vuejs/vue-devtools#809]
### What problem does this feature solve?
I'm using safari with vue-remote-devtools, would be handy, if I could make the devtool's window always on top of my safari window, so it would feel just like chrome's native version.

### What does the proposed API look like?
I explained my use case in the form above.

**Comment by Elizabethclove** [comment]
#809

**Comment by heihachi88** [comment]
@Elizabethclove ?

**Comment by emanuelmutschlechner** [comment]
As I'm not a Mac user, I can't help you very much. Here's a [Stack Exchange](https://apple.stackexchange.com/a/327849) link with some third party applications which should do the job.

I think it's impossible to solve this in devtools directly.

**Comment by Akryum** [comment]
This feature is out-of-scope for the moment.
