### ISSUE TITLE
Vue devtools doesn't work with chrome v 48

### ISSUE THREAD

**Issue by ahmedash95** [vuejs/vue-devtools#81]
after updating my chrome i found vue devtools appear in address bar but i can't found it in debug window in chrome .. don't know why

**Comment by yyx990803** [comment]
Hmm it's working fine for me (Chrome stable is at 49 now btw) - try re-installing the extension.

**Comment by ahmedash95** [comment]
actually i do this , but nothing happen .

have a look  http://i.imgur.com/4dIqXCY.png

**Comment by yyx990803** [comment]
The button doesn't do anything. The panel is next to "Resources", you need to hit the dropdown to see it.

**Comment by ahmedash95** [comment]
it's empty too. i used it for long time , but suddenly after updating chrome it disappeared

**Comment by ahmedash95** [comment]
it's working now . i didn't do any thing !!
