### ISSUE TITLE
Version 1.1.5 don't work with Vue.js v1.0.17

### ISSUE THREAD

**Issue by lincolnbrito** [vuejs/vue-devtools#82]
With the last update 2016-03-08 the tab content don't appear. I'm using Windows 7 and Chrome 49.0.2623.75

![capturar](https://cloud.githubusercontent.com/assets/310896/13601163/b74a502a-e50c-11e5-8a80-80a37044ea74.PNG)

**Comment by jbruni** [comment]
This is also happening with me.

**Comment by jbruni** [comment]
I am using Windows 10, and in an attempt to solve the issue I've updated Chrome from version 48 (not sure of the minor version) to 49.0.2623.75. It didn't resolve the issue. I hope there is an easy and fast fix, as I'm using the tool a lot... Thank you.

**Comment by jbruni** [comment]
More news: if I follow the "Manual Installation" instructions from [the README](https://github.com/vuejs/vue-devtools/blob/master/README.md), the extension works.

I can see the new "vuex getter" and "router-view" features. :+1: I'm happy I can use vue-devtools again.

I wonder why the installation from Chrome Web Store is failing...

**Comment by wdmtech** [comment]
This is also happening for me on Win7 with vue v1.0.16, on Chrome 9.0.2623.75 m.

**Comment by einice** [comment]
+1 
This is also happening with me

**Comment by lincolnbrito** [comment]
@jbruni @wdmtech @einice I followed "The manual installation". The extension is working now. 
But the installation from Web Store don't work

**Comment by einice** [comment]
@lincolnbrito All right

**Comment by wdmtech** [comment]
Manual installation fixed it for me too :) Cheers for the suggestion, @jbruni and @lincolnbrito :)

**Comment by agc93** [comment]
Just another +1 for broken devtools after 1.1.5 update. Just following the manual steps from @jbruni now. Hopefully @yyx990803 can shed some light on this soon..

**Comment by nblackburn** [comment]
Manual installation works fine but it's broken otherwise for me.

**Comment by Lovatt** [comment]
Same issue here on OSX / Chrome 40.0.2564.109

**Comment by nblackburn** [comment]
Packing the extension works too, so here is a packed version to tide everyone over until it's fixed.

[vue-devtools.zip](https://github.com/vuejs/vue-devtools/files/163419/vue-devtools.zip)

**Comment by yyx990803** [comment]
Oops, fixed in 1.1.6.
