### ISSUE TITLE
latest beta breaks vue-cli pwa app

### ISSUE THREAD

**Issue by vesper8** [vuejs/vue-devtools#825]
### Version
5.0.0-beta.3

### Browser and OS info
osx chrome 70

### Steps to reproduce
visit https://beta.nomadsoulmates.com

### What is expected?
cannot click on login button if extension is enabled, there are console errors. If extension disabled then no problem

### What is actually happening?
having the extension enabled breaks the page

**Comment by Sp1ker** [comment]
Do you import lodash into `Navigation.js`? I do not see it.
You are using lodash in `unreadNotificationsCount` getter.

**Comment by Sp1ker** [comment]
Try to move `window._ = require('lodash');` before `import store from './vuex/store';` in main.js
Devtools run all getters when vuex will be inited. Lodash in your code will setup later. `window._ = _` - is bad practice. Use webpack aliases for lodash instead.

**Comment by Akryum** [comment]
> `window._ = _` is bad practice.

This.
