### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by npelto** [vuejs/vue-devtools#826]
### Version
5.0.0-beta.3

### Browser and OS info
Chrome 70.0.3538.102 / Windows 10

### Steps to reproduce
Enable dev tools on a site that has lodash set to window._

### What is expected?
Site is expected to load normally

### What is actually happening?
I get the error: Uncaught ReferenceError: _ is not defined
And page fails to load.

**Comment by lwiml** [comment]
same issue

**Comment by Sp1ker** [comment]
Duplication of #825

**Comment by Akryum** [comment]
Duplicate of #825
