### ISSUE TITLE
Getting strange errors in latest version

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-devtools#83]
When I click a certain component, I get errors and warnings in the console that are non-sensical.

E.g. the following error and warning show up:
```
Uncaught TypeError: Cannot read property 'validation' of null
[Vue warn]: Error when evaluating expression "function isValid() {
      var type = this.validation;
      var value = this.value;

      return (0, _helpers.validate)(type, value);
    }". 
```

That code is in a component called formInput.vue and has nothing to do with what I select in the devtools. It's not even part of the tree I'm inspecting.

**Comment by yyx990803** [comment]
But what does that component look like?

**Comment by TheDutchCoder** [comment]
Here you go (I left out the styling):

```js
<template>
  <div class="input" :class="{ 'is-active': active || hasValue, 'is-valid': hasValue && isValid, 'is-invalid': hasValue && !isValid }">
    <label for="{{ id }}" class="input__label" @click="activate">{{ label }}</label>
    <input id="{{ id }}" type="{{ type }}" class="input__input" required="{{ required }}" v-model="value" @focus="activate" @blur="deactivate"></input>
    <div class="input__error" v-if="hasValue && !isValid" transition="input-error">{{ error }}</div>
    <a href="#" class="input__helper" v-if="helper">This is a helper</a>
  </div>
</template>

<script>
import { validate } from '../helpers'

export default {

  props: {
    id: {
      type: String,
      required: true
    },
    label: {
      type: String,
      required: true,
      default: 'Label'
    },
    type: {
      type: String,
      default: 'text'
    },
    required: {
      type: Boolean,
      default: false
    },
    validation: {
      type: String,
      default: 'text'
    },
    error: {
      type: String,
      default: 'Please fill out this field correctly.'
    }
  },

  methods: {

    activate() {
      this.active = true
    },

    deactivate() {
      this.active = false
    }

  },

  computed: {

    hasValue() {
      return this.value.length
    },

    isValid() {
      let type = this.validation
      let value = this.value

      return validate(type, value)
    }

  },

  data() {
    return {
      active: false,
      value: '',
      helper: false
    }
  }

}
</script>
```

**Comment by yyx990803** [comment]
Hmm, kinda weird... it'd be best to have a repo that I can run actual code with. Need error stack info etc.

**Comment by TheDutchCoder** [comment]
Unfortunately I'm under an NDA, so I can't share the repo.
Is there anything I can do on my end to help?

It's almost as if a certain listener is not removed correctly, as the formInput component was used in some previous state.

I basically have a <modal> component that takes other ones like <form-input> and <checkbox>.

My <configure-location> component uses <modal> and <form-input>. <configure-location> is called initially and when done, a different component (<configurator>) is called, which also uses <modal>, but not <formInput>.

Maybe something goes wrong when <modal> is torn down?

Let me know if you want me to post the full error stack from the console.

**Comment by blake-newman** [comment]
Closing issue, if you have any more information on this issue please reopen. Is this still occuring for you?
