### ISSUE TITLE
Add support for Dynamic Components

### ISSUE THREAD

**Issue by josx** [vuejs/vue-devtools#834]
### What problem does this feature solve?
There are plenty of complex webapps and libraries using dynamic components.
It seems that vue-devtools has not support for that vue feature.

### What does the proposed API look like?
To be clear this is the feature that vue has that I think would be necessary on Vuetools.

https://vuejs.org/v2/guide/components.html#Dynamic-Components

**Comment by Akryum** [comment]
I'm sorry but your proposal isn't describing a feature request. What does dynamic component support means to you? What do you expect to be displayed in the devtools? What doesn't work currently? etc.

**Comment by josx** [comment]
Sorry but it already support it (my mistake, i was wondering to show components dynamicly created)
