### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by marcosrjjunior** [vuejs/vue-devtools#84]
Maybe we could create a dark theme

![vuedtools1](https://cloud.githubusercontent.com/assets/5287262/13644769/47dc52ce-e606-11e5-8e1a-1c4abd174381.png)
![vuedtools2](https://cloud.githubusercontent.com/assets/5287262/13644768/47d68aec-e606-11e5-88a7-28e479974e90.png)
![vuedtools3](https://cloud.githubusercontent.com/assets/5287262/13645431/c36b60f8-e609-11e5-9dd0-f43904313ce5.png)

**Comment by blake-newman** [comment]
Feel free to provide a PR, for this. Currently this is not on the roadmap.
