### ISSUE TITLE
Display Error

### ISSUE THREAD

**Issue by fakaka** [vuejs/vue-devtools#844]
### Version
4.1.5

### Browser and OS info
Chrome 70/Windows 10

### Steps to reproduce
1. change the console to black theme
2. events button display error

### What is expected?
the button num is black and banckground-color is white

### What is actually happening?
button  banckground-color is white

---
修改控制台为黑色主题，在 vue 面板 events 的数字看不到

**Comment by Akryum** [comment]
I believe it's fixed in 5.x beta.
