### ISSUE TITLE
EventBus in Devtools

### ISSUE THREAD

**Issue by pxwee5** [vuejs/vue-devtools#854]
### What problem does this feature solve?
Need to be able to debug EventBus in devtools.

### What does the proposed API look like?
Create a separate tree for EventBus or something ?

**Comment by LinusBorg** [comment]
Eventbus is not a recommended pattern to use in your applications broadly.

Adding an section for it to devtools (ignoring the problems of implementing one for a second) would make it seem as if we recommend using them intensly. We generally don't.

**Comment by pxwee5** [comment]
Yes I agree overusing EventBus is a bad practise. 
However, there are specific cases where EventBus is the perfect use case in an app. For example, making native params reactive, such as variables from `windows` or `document` or browser specific information. 

These information are not considered as application data but needed to be used globally is perfect use case for EventBus.

**Comment by Akryum** [comment]
I doubt of the technical reasonable feasibility and ratio between effort required vs. actual usage of this feature.
