### ISSUE TITLE
Vuex Store change not displayed on electron when state is in a shared context

### ISSUE THREAD

**Issue by Hammster** [vuejs/vue-devtools#856]
### Version
5.0.0-beta.3

### Browser and OS info
Electron 3.0.13 / Windows 10 (Chrome 66.0.3359.181)

### Steps to reproduce
- Create a window with the `webPreferences` setting `nativeWindowOpen: true`
- Give that first window a `sharedStore` variable in to global scope with the property `count` set to 1
- Create a new window with `window.open` and load Vue & Vuex in that second window
- Create a Vuex Instance that uses the `window.opener.sharedStore` variable as state
- Create a third window that does the same.
- Increase the `count` value of the state from the first window

The second one will have that state too, so it works from the Vue/Vuex side but the vue-devtools if already opened will not react to the variable change instead it will remain at 1.

### What is expected?
That the display state values in the vue-devtools Vuex tab, change with the value of the actual state.

### What is actually happening?
The Value changes in the context, it can be seen correct in the Chrome REPL. But then the display in the Vuex tab will stay at the value that was set when you opened the chrome dev-tools

---
This is not a general use case, I encountered that bug while researching ways to use electron with multiple windows. And the premise is to have one controlling V8 Isolate with shared and local V8 contexts. To eliminate IPC madness.

I recorded this footage for a better understanding of the visual issue.
![htmybm8crg](https://user-images.githubusercontent.com/1093709/50691801-13511180-1032-11e9-8a95-5a9c3c379396.gif)

**Comment by Akryum** [comment]
Committing mutations in one application won't commit them in others. Also since in normal usage (not editing values via the devtools), vuex state doesn't change outside of mutations so what you see under the `state` section is a snapshot of the store after each mutation.
