### ISSUE TITLE
Unable to see commits triggered from the created method

### ISSUE THREAD

**Issue by EmmanuelDemey** [vuejs/vue-devtools#868]
### Version
4.1.5-beta.2

### Browser and OS info
Chrome 71 on Mac OSx

### Steps to reproduce
I have a very very basic VueJS application with VueX. When I open the Devtools, most of the time I can see VueX mutations in the dedicated panel. 

But If I commit something in the `created` method of the main component (`App.vue`), this commit is not displayed. Is it normal ? 

```javascript
export default {
  name: 'app',
  created() {
     this.$store.commit('initData', data);
  }
};
```

For example, in the previous example, the `initData` commit is triggered and my store is well initialized. But I can not see this commit in the history of the VueX panel of the Devtools. 
If I move the same code in a function executed after clicking on a button, the commit will be displayed.

### What is expected?
We should see the VueX commit in the Vuex panel of the Devtools

### What is actually happening?
We cannot see the commit triggered from from the created method of the main component

---
Thanks a lot

**Comment by Akryum** [comment]
Maybe it's related to #491

**Comment by EmmanuelDemey** [comment]
Thanks @Akryum . I think you are correct. 
I close this issue.
