### ISSUE TITLE
Feature: Expand all, Auto expand all

### ISSUE THREAD

**Issue by phromo** [vuejs/vue-devtools#87]
It would be very helpful if I could auto expand all components and all state variables. I would save a lot of time and energy not being forced to touch the mouse every time I switch component :)

**Comment by yyx990803** [comment]
Auto expanding everything can also be quite messy when the app is large. The data inspector also needs to deal with possible circular references. I have made it expand 2 levels deep by default - this should save a good amount of clicks for simpler components.

**Comment by jonnywilliamson** [comment]
Would it be hard to allow us to choose if we want auto expand or not?

At the moment I have an object as one of my data variables. It has a lot of properties and is being expanded automatically. This means I have to scroll down a lot (or collapse the object) before I can get to see the next data variable easily.

In the grand scheme of things, it's just a little bit of a nuisance!

**Comment by kaleb** [comment]
In other parts of the chrome dev tools, alt-clicking (ctrl+alt click for me on Unity desktop) performs an expand-all:

https://umaar.com/dev-tips/18-alt-click-expand-node/

**Comment by titusdecali** [comment]
I'm not seeing that 2 layers are expanded by default, and I'm really tired of clicking open my data every time I reload the app.

I would love a button in settings that lets me choose how many layers are open by default. This little UI feature would save developer lifetimes.

**Comment by aubreypwd** [comment]
+!

**Comment by samb1999** [comment]
+1
