### ISSUE TITLE
Vue Tools does not show changes for Vuex (or routes, or state)

### ISSUE THREAD

**Issue by jtsom** [vuejs/vue-devtools#872]
### Version
5.0.0-beta.3

### Browser and OS info
Chrome Release and Dev / WIndows 10

### Steps to reproduce
Open any Vue app that uses Vuex. Navigate around so that mutations are hit.

### What is expected?
Mutations should be listed in the Vuex tab as they occur.
Also, routes should be listed in the Routes tab.

### What is actually happening?
Mutations are not listed when they occur. State changes do not reflect in the state list. Routes do not list in the Route History tab.

**Comment by Akryum** [comment]
We need a minimal runnable repdocution that demonstrates your issue.

**Comment by fbrbovic** [comment]
I am also experiencing the same exact issue,  using 5.0.0-beta.4 Chrome plugin on Windows 10. 
Hitting refresh also doesn't update state. 

Sorry don't have time to setup reproduction repo.

**Comment by huxaiphaer** [comment]
I am experiencing the same issue, it takes time to change state, getters etc.
