### ISSUE TITLE
Browser plugin fails loading with t.isBuffer is not a function

### ISSUE THREAD

**Issue by juliushaertl** [vuejs/vue-devtools#874]
### Version
5.0.0-beta.4

### Browser and OS info
Chromium 72, Firefox 65

### Steps to reproduce
Create a simple vue app that uses a vuex store

```
const debug = process.env.NODE_ENV !== 'production'

export default new Vuex.Store({
	modules: {
		myModule
	},
	strict: debug
})
```

### What is expected?
vue-devtools work as expected

### What is actually happening?
The javascript console shows the following error:

```
TypeError: t.isBuffer is not a function[Learn More] eval:1:1695

    y (index):1 u (index):1 <anonymous> (index):1 r (index):1 emit (index):1 devtoolPlugin vuex.esm.js:51 Store vuex.esm.js:347 js index.js:30 Bootstrap27Webpack
```
![image](https://user-images.githubusercontent.com/3404133/52205317-fb5def00-2876-11e9-9551-bf2388dbee8d.png)

---
The culprit line from vue-devtools seems to be https://github.com/vuejs/vue-devtools/blob/cf74ad3ce66534ea028e953ca4ccf85835114f7f/src/backend/hook.js#L186

**Comment by jaketoolson** [comment]
Happening to me now suddenly too.

**Comment by Akryum** [comment]
This seems related to https://github.com/pvorb/clone/issues/104

**Comment by TheDutchCoder** [comment]
Yes this is a breaking change for me too. I can't actually work currently because I can't debug my app anymore.

Can you please roll back this version in the meantime?

**Comment by gotexis** [comment]
My situation is a bit different, I got this

```js
Property or method "_isBuffer" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

x 100 times

**Comment by JFonsecaSpot** [comment]
>x 100 times

Same error message.
Having thousands really, and halting the browser for massive periods. Unusable atm.

My bet: **might it be related to using arrow functions on array callbacks**. Maybe something related to a polyfil? If that's the case, arrow function context spec cannot be subverted by the used poli and this should to be changed, (but who am I)

Looking to downgrade the extension while this is not fixed.

**Comment by Akryum** [comment]
@gotexis @JFonsecaSpot Your issue is different, please comment and provide more info **and** runnable minimal reproduction in the actual issue: #955

**Comment by JFonsecaSpot** [comment]
@Akryum couldn't reproduce with CLI3 generated app. Maybe an interaction with our main app configuration. Looking at the error stack instead. If I have time later will try to reproduce on a minimal repo with the same configuration.

**Comment by JFonsecaSpot** [comment]
@Akryum Can you tell if [this b4e19c3](https://github.com/vuejs/vue-devtools/commit/b3207e743ea992bd3a4420f7f61397db2b4e19c3) reached the production build / chrome extension store?

I am not able to reproduce the issue anymore and that coomit seams to be a good candidate for the fix.

**Comment by Akryum** [comment]
@JFonsecaSpot If you look at the [commits](https://github.com/vuejs/vue-devtools/commits/dev), it's after the last release (5.0.7).
