### ISSUE TITLE
Release beta.4 on NPM

### ISSUE THREAD

**Issue by cyoharry** [vuejs/vue-devtools#877]
### Version
5.0.0-beta.4

### Browser and OS info
n/a

### Steps to reproduce
See: https://www.npmjs.com/package/@vue/devtools versions.

### What is expected?
run `npm i -D @vue/devtools@5.0.0-beta.4`

this should install

### What is actually happening?
`No matching version found for @vue/devtools@5.0.0-beta.4`

---
Thanks for all the great work on this!

**Comment by Akryum** [comment]
I release 5.0.0-beta.5
