### ISSUE TITLE
Editable Props only works when loading page with it off, then toggling on.

### ISSUE THREAD

**Issue by Roballen** [vuejs/vue-devtools#878]
### Version
5.0.0-beta.4

### Browser and OS info
Chrome 71.0.3578.98 (Official Build) (64-bit), Mojave 10.14.2 (18C54) 

### Steps to reproduce
1) Turn on editable props.
2) Reload the page
3) Try to edit a prop, I can't
4) Toggle editable props off
5) Reload page
6) Toggle editable props on
7) Try to edit a prop, I can now

8) Repeat steps 1-3, with the prop not editable, close chrome dev tools, re-open chrome dev tools and notice props are again editable.

### What is expected?
When loading a page with editable props settings on, props should be editable.

### What is actually happening?
When loading a page with editable props settings on, props are not editable.

---
I am using inline-templates, not sure if that matters.

**Comment by Akryum** [comment]
Fixed in https://github.com/vuejs/vue-devtools/commit/f46c608120ce9dea01c92ff7fc23673e14d42ceb

**Comment by cmygray** [comment]
Is this fixed in v5.0.9?

Props still not editable after reloading, until toggle switch again(but additional reloading is not required).

**Comment by MKorostoff** [comment]
Still experiencing this issue as of 5.1.1
