### ISSUE TITLE
Child components are sometimes not in DOM order

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/vue-devtools#88]
I can't pinpoint where or how to reproduce but if you check out [Players World of Warships](http://worldofwarships.com/en/community/accounts/teams/) and expand down in to the list of "VueTeamRow" components, you will see that the Components are not in DOM order.

![image](https://cloud.githubusercontent.com/assets/71916/13825667/e2190886-eb70-11e5-9515-bdc70d332f8b.png)

The "VueTeamRow" components with arrows next to them indicate the first three rows with icons. They don't seem to be in any order.

**Comment by yyx990803** [comment]
Fixed in 1.2.0.

**Comment by kaleb** [comment]
I still on occasion see some out of order, but not in any reliably reproducible way.

**Comment by posva** [comment]
@kaleb There's an issue open for that. I think it happens when nodes are reused

**Comment by digitalle** [comment]
Was this ever fixed? I've just encountered it, i.e. a v-for loop of rendered components derived from an array object, and whilst they are rendering in the correct order in the dom, the Vue dev tools are showing the items in the correct order. Have tried adding a :key from the item.ID but still no joy. I have multiple other component lists on the same page and they are showing in the correct order.
