### ISSUE TITLE
Can't edit component data if no props

### ISSUE THREAD

**Issue by kevinmarrec** [vuejs/vue-devtools#882]
### Version
5.0.0-beta.4

### Browser and OS info
Chrome 72 / Windows 10

### Steps to reproduce
1. Define a minimal component with an array of any type in `data` (array of numbers for example)
```js
export default {
  data () {
    return {
      someArray: [1, 2]
    }
  }
}
```
2. Try do edit the array in Vue DevTools

### What is expected?
Edit or deleting an item works

### What is actually happening?
Edit, deleting (and also increment/decrement) throws an error :
`Cannot read property 'someArray' of undefined`

### Stack Trace
![screenshot_6](https://user-images.githubusercontent.com/25272043/52712986-7e2d2b00-2f96-11e9-88c2-33adee9976e7.png)

---
Editing the array manually from root edit button works (JSON edit)

**Comment by Akryum** [comment]
I don't reproduce this on dev branch.

**Comment by davidwaterston** [comment]
> I don't reproduce this on dev branch.

By 'dev branch' do you mean Beta 5?
I've just updated to B5 via https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg and this is still broken i.e. it is not possible to edit the data within an object or array, as described by @kevinmarrec.

**Version**
5.0.0-beta.5

**Browser and OS info**
Chrome 72.0.3626.121 (Official Build) (64-bit) / MacOS Mojave 10.14.3.

**Comment by kevinmarrec** [comment]
@Akryum Issue is still present and reproducible on Beta 5.

The issue happens almost for each feature when the variable is an array :
- Adding a value in an array
- Remove an item from an array
- Editing an item in an array
- Incrementing an item (if it's numeric) in an array

Error: `Cannot read property 'NAME_OF_THE_ARRAY' of undefined` (with `NAME_OF_THE_ARRAY` being the name of your array variable).

**Comment by Sp1ker** [comment]
Editing and deleting in devtools instead in vue app.
I fixed bug.

**Comment by kevinmarrec** [comment]
@Sp1ker Great !

What do you mean by component `without props` ?
If the component has no props, it makes devTools buggy for all other datas of the component ?

**Comment by Sp1ker** [comment]
> If the component has no props, it makes devTools buggy for all other datas of the component ?

Yes

**Comment by kevinmarrec** [comment]
Oh alright, need to wait @Akryum for further information and see if it's the right fix :)

**Comment by Akryum** [comment]
Closed in https://github.com/vuejs/vue-devtools/pull/907
