### ISSUE TITLE
Uncaught TypeError: seen.get is not a function

### ISSUE THREAD

**Issue by pavgra** [vuejs/vue-devtools#89]
Chrome 51.0.2679.0 dev-m (64-bit)

![2016-03-18 11_24_44-developer tools](https://cloud.githubusercontent.com/assets/10010071/13872529/52b02958-ecfc-11e5-8de8-3d2278163075.png)

**Comment by yyx990803** [comment]
Hmmmm not quite sure how this is possible, do you have something that overwrites `Map` globally?

**Comment by pavgra** [comment]
Yes, I found source overwriting Map. Now everything works fine. Thaks!
