### ISSUE TITLE
Message length exceeded maximum allowed length

### ISSUE THREAD

**Issue by moonjoungyoung** [vuejs/vue-devtools#896]
### Version
4.1.5-beta.1

### Browser and OS info
Chrome 62 / Windows 10

### Steps to reproduce
From https://github.com/vuejs/vue-devtools/issues/515

```
<!DOCTYPE html>
<body>
    <div id="app"></div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.js"></script>
<script>
new Vue({
    el: '#app',
    mounted () {
        for (let i = 0; i < 10000000; i  )
            this.largeArray.push(i)
    },
    data: {
        largeArray: []
    }
})
</script>
```

### What is expected?
Have a loading, and view data

### What is actually happening?
proxy.js:1 Uncaught Error: Message length exceeded maximum allowed length.
    at r (proxy.js:1)

**Comment by vinhhungle** [comment]
I've also got this error in Dev Console even thought the component doesn't have a large dataset. I could not inspect the component in the DevTools. Every time I click the component, I got this error:

```
proxy.js:1 Uncaught Error: Message length exceeded maximum allowed length.
    at r (proxy.js:1)
r @ proxy.js:1
postMessage (async)
send @ backend.js:1
send @ backend.js:1
O @ backend.js:1
v.on.e @ backend.js:1
n.emit @ backend.js:1
e.listen.e @ backend.js:1
n @ backend.js:1
postMessage (async)
o @ proxy.js:1
```

Is there a workaround?

**Comment by Akryum** [comment]
Fixed in https://github.com/vuejs/vue-devtools/commit/a9b658b37ce3cd77b4615775f4686df7ab2456c8

**Comment by walmon** [comment]
I'm experiencing this still with vue devtools 6.2.1  with an application we are migrating from vue 2 (where devtools works just fine) to vue 3 with compat build on.

**Comment by miyakoj** [comment]
I also have it with devtools 6.5 and Vue 2 when trying to load components that use a lot of data.

**Comment by moonjoungyoung** [comment]
@Akryum 

Thank you.

However, there seems to be some parts that have not been solved yet, such as those who wrote down comments.
Could you check it out?

**Comment by Altenrion** [comment]
Uncaught Error: Message length exceeded maximum allowed length.
![CleanShot 2024-01-13 at 17 17 58](https://github.com/vuejs/devtools/assets/5549987/6e67a111-1390-4f99-959d-ecba0e8ea7bb)
