### ISSUE TITLE
Latency with state in dev tools

### ISSUE THREAD

**Issue by shortdiv** [vuejs/vue-devtools#899]
### Version
4.1.5-beta.1

### Browser and OS info
Chrome 72

### Steps to reproduce
- Create a button that increments a counter data property 
- Click on the counter to increment and watch the dev tools
- Dev Tools doesn't update the counter value as expected if the property is not used

### What is expected?
The data property should update as an event happens in real time.

### What is actually happening?
The data property does not update in time and only updates when you navigate away from the component and click back in to the component. 

---
Here is a gif of the current interaction -> https://gph.is/g/Evn8YgE

**Comment by Sp1ker** [comment]
It is `vue` problem, not `vue-devtools`. Vue dont send message on update unused property.

**Comment by Akryum** [comment]
Vue reactivity system is optimized to not recompute data which isn't used in the app.
