### ISSUE TITLE
Loading Vue-Devtools throws exception "Error: Extension context invalidated"

### ISSUE THREAD

**Issue by NTTAKR** [vuejs/vue-devtools#901]
### Version
5.0.0-beta.4

### Browser and OS info
Chrome 72, Windows 10Pro

### Steps to reproduce
Just press F12 to open devtools. 

### What is expected?
Devtools working

### What is actually happening?
Exception "Error: Extension context invalidated"

Resume keeps throwing this error

---
//inspect page for node count changes and if change then capture state on devtools.js

nodeCounter = function () {
    //FIX FOR TIME TRAVEL - MAKE SOME SORT OF CHECK SO NEW STATE ISN'T ADDED
    chrome.storage.sync.get('traveledThroughTime', function (result) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ EXCEPTION HERE
        if (!result.traveledThroughTime) {
            count = document.querySelectorAll('*').length - document.querySelectorAll('div.highlighter').length - document.querySelectorAll('div.timeTravel').length;
            chrome.storage.sync.get('count', function () {
                check = count;
            });
            if (count !== check) {
                chrome.storage.sync.set({
                    'count': count
                }, function () {
                    return
                });
            }
        }
    })
}

**Comment by Akryum** [comment]
Please provide an actual runnable reproduction.

**Comment by vanholler** [comment]
Yes, I also have the same problem. I open the project, open the console, open vue devtools and it starts to give errors recursively and points to the same code as shown here.
I have a big project, and yesterday there was no such mistake. it happens. when I move from components to child components and come back.

This is a recursive error. while I am writing to you, it is still duplicated.))
`VM16 content-script.js:42 Uncaught Error: Extension context invalidated.
    at nodeCounter (VM16 content-script.js:42)`


and it gives out right at the beginning.
`DevTools failed to parse SourceMap: http://localhost:3000/service-worker-ext.js.map`

**Comment by vanholler** [comment]
And it also gives thousands of such errors.
`vue.runtime.esm.js:587 [Vue warn]: Property or method "_isBuffer" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
`

**Comment by vanholler** [comment]
Hooray. I found a solution. After the updates in the section vuex / events / and in the new section of the router, the flag "start recording" was turned on. We did not have a "record".Because of the recording of all these sections - devtools could not stand
**To fix this problem, you need to do the following.**

> 1. In the vuex section - turn off the "record" flag and click "Restore All"
> 2. do step 1 in the section of the router and events.
> 2. Click Forced Update for all Vue Devtools.

PS I hope this helps someone.

**Comment by vchapple17** [comment]
Turning off the record is an okay work around, like @vanholler mentioned, but by no means ideal. 

Is there a way to revert changes in Chrome Extensions?

**Comment by Akryum** [comment]
`Error: Extension context invalidated` seems to be an error thrown by Chrome extensions when they are updated and the script injected on the user page is orphaned. Simply reloading the page should fix this.

Also, the code in the OP is not part of vue-devtools, maybe you are having an issue with another extension?
