### ISSUE TITLE
Update state automatically if last mutation is active

### ISSUE THREAD

**Issue by Sp1ker** [vuejs/vue-devtools#909]
### What problem does this feature solve?
When adding each new mutation we have to click on the `load state` button. It is not comfortable. Especially when mutations are triggered by time interval.
![](https://i.imgur.com/M8lVhTs.gif)
### What does the proposed API look like?
Update state automatically only If last mutation is active and vuex tab is selected.

Example:
![](https://i.imgur.com/PxUDVS8.gif)

**Comment by Akryum** [comment]
This is by design to prevent performance issues or even crashes in bigger applications.

**Comment by Akryum** [comment]
I added this behind a setting with a warning message.
