### ISSUE TITLE
Vue Dev Tools not showing in Remote Debugging Dev Tools

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-devtools#91]
When I test my app on my android device, I use the Chrome Remote Dev Tools as described in [this article](https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging#remote-debugging-on-android-with-chrome-devtools), but the Vue Dev Tools isn't there.
It shows up only on a normal webpage on my desktop.

Also, `window.__VUE_DEVTOOLS_GLOBAL_HOOK__` isn't defined.

**Comment by amirrustam** [comment]
This is also the case when using something like [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy), which is currently the only way to inspect iOS Safari within Chrome DevTools.

**Comment by githoniel** [comment]
this is still a problem

**Comment by lmfresneda** [comment]
Any solution or tip?

**Comment by michalsnik** [comment]
I don't think we can add vue devtools there, remote shell doesn't support addons.

We also don't support remote debugging yat - but we might, as it's possible.
We could create electron standalone shell, that could be installed globally with `npm install -g vue-devtools`, it would open standalone devtools window in which we'd communicate with page that we want to debug by using websockets. Users will need to add one script on their pages though.

React devtools did just that in here: https://github.com/facebook/react-devtools/tree/master/packages/react-devtools and it seems like we should do something similar here :)

**Comment by Akryum** [comment]
I think we can close this as a remote Electron shell would fix this. Discussion on the Electron shell: #451, related PR: #452.
