### ISSUE TITLE
can I see the info about the getter/setter of the data?

### ISSUE THREAD

**Issue by qaz2810714** [vuejs/vue-devtools#915]
### What problem does this feature solve?
my project can't work well always  because of I forget the getter/setter of data,Every time it happend,I can only use console.log() to print the object for debug,Can the Vue devtools show the getter/setter method about It? thanks

### What does the proposed API look like?
check the getter/setter data if they are binded.

**Comment by Akryum** [comment]
I'm not sure to understand what your feature request is really about. Please provide some example.

**Comment by gerasimvol** [comment]
http://prntscr.com/n34e94
Vuex tab is broken

**Comment by Akryum** [comment]
@gerasimvol How is it related?

**Comment by gerasimvol** [comment]
@Akryum i though it is same bug. After enabling "Autoload VUEX state" in setting have infinite loading http://prntscr.com/n35rdn

**Comment by Akryum** [comment]
@gerasimvol Please open an issue if you have a problem other than the one described here. Closing
