### ISSUE TITLE
 Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by taoche** [vuejs/vue-devtools#916]
### Version
5.0.1

### Browser and OS info
Chrome 73

### Steps to reproduce
Vue.js version is  v1.0.24
Vuex version is v0.6.2

open the app, chrome throw a error is `"Uncaught TypeError: Cannot read property 'bind' of undefined"`

```
u.storeModules = [];
var e = t.registerModule.bind(t);
```
t without `registerModule` method

### What is expected?
Do not block the application from opening properly

### What is actually happening?
throw a error

---
could you please add disable button for devtools?

**Comment by arjenzwerver** [comment]
I got the same problem for Chrome: Version 72.0.3626.81 (Official Build) (64-bit)
Operating System: Ubuntu 16.04.5 LTS

**Comment by bajzarpa** [comment]
It looks like there is no backward compatibility for older Vuex versions

**Comment by nblackburn** [comment]
Disable the extension, it doesn't look to be compatible with Vue 1.x as @bajzarpa points out.

**Comment by taoche** [comment]
> Disable the extension, it doesn't look to be compatible with Vue 1.x as @bajzarpa points out.

I certainly know that disabling devTools can get around this, but I have multiple applications, and I just hope it doesn't block my application from working properly

**Comment by nblackburn** [comment]
> > Disable the extension, it doesn't look to be compatible with Vue 1.x as @bajzarpa points out.
> 
> I certainly know that disabling devTools can get around this, but I have multiple applications, I just hope it doesn't block my application from working properly

Oh i agree, i was just proposing a solution to get the application working again. By no means did i suggest this is the right solution but for now it works.

**Comment by c0bra** [comment]
@Akryum this error still appears to be happening in v5.0.5 with a v1 app.

**Comment by Akryum** [comment]
Please provide a runnable reproduction.

**Comment by c0bra** [comment]
You can check here: https://app.seniorvu.com/

If I have vue devtools uninstalled the site loads. If I have them installed it's just white screened with that error in the console.

**Comment by taoche** [comment]
> Please provide a runnable reproduction.

![image](https://user-images.githubusercontent.com/5573059/55202829-05132b80-5204-11e9-8327-590c44d632b6.png)

`VM87750:formatted:73 Uncaught TypeError: Cannot read property 'bind' of undefined`

`t.replaceState.bind(t)`

t without replaceState method

**Comment by Tinoooo** [comment]
Same here. Visit https://my.qbrx.com with dev tools enabled and check the console.

**Comment by liamgomez** [comment]
This is still an issue in 5.0.6, even with `Vue.config.devtools = false`.

vue@1.0.28
vuex@0.8.2
Chrome: 73.0.3683.86

**Comment by taoche** [comment]
[chrome.zip](https://github.com/vuejs/vue-devtools/files/3061724/chrome.zip)
I packaged a version 5.0.3 that worked

**Comment by fuchengjx** [comment]
Has the vue team given up on solving the vueDevtools vue1.x compatibility issue? I still have this problem
