### ISSUE TITLE
Uncaught TypeError: path.split is not a function

### ISSUE THREAD

**Issue by little-yao** [vuejs/vue-devtools#919]
### Version
5.0.1

### Browser and OS info
Chrome 73

### Steps to reproduce
on the chrome, throw a error is "Uncaught TypeError: path.split is not a function" when I use "registerModule" to register a nested module. Here is my code:
`this.$store.registerModule(['activity', 'detail'], module);`
The position of error code and stack is here:
![image](https://user-images.githubusercontent.com/37481369/54984918-d2421b00-4fea-11e9-9de5-071db361b896.png)
I think the reason of this error is because of setting "path" param with a error type, 
it want to get a string, but set array with slice
![image](https://user-images.githubusercontent.com/37481369/54984680-59db5a00-4fea-11e9-9ce4-9e4dfb3409ec.png)

### What is expected?
set path with a correct type

### What is actually happening?
set "path" param with array, but it want to get string

**Comment by G-Bro** [comment]
I have also encountered the same error on Firefox after registering a module dialogs.snackbars in the Vuex state like this

````js
    globalStore.registerModule(['dialogs', 'snackbars'], store);
````

**Comment by DanEvans485** [comment]
I am also having the same issue only component tree is working in the dev tools.
When a nested vuex module is registered.

**Comment by flutterq** [comment]
[[Solved] Getting Uncaught TypeError: path.split is not a function in react
](https://exerror.com/getting-uncaught-typeerror-path-split-is-not-a-function-in-react/)
