### ISSUE TITLE
Vuex: keep inspected mutation selected if there is a new mutation

### ISSUE THREAD

**Issue by robodude** [vuejs/vue-devtools#925]
### Version
5.0.3

### Browser and OS info
Chrome / Windows 10

### Steps to reproduce
1. Create a Vuex enabled App
2. In a created component, create an `setInterval` that updates the state via a mutation at a regular interval
3. Try to inspect the Vuex state

### What is expected?
If an entry in the vuex log is explicitly clicked on to be inspected, it shouldn't be changed due to a mutation.

### What is actually happening?
When a mutation occurs the 'inspected' Vuex item is updated to the latest value

---
I added a screen capture of what is occurring here: https://imgur.com/a/QfKAI9N

**Comment by robodude** [comment]
![vuex-bug](https://user-images.githubusercontent.com/1719221/55035234-9a2fdd80-4fd4-11e9-9a25-199268bfa99b.gif)

The screen capture

**Comment by jacobg** [comment]
IMHO Seems more like a bug than an enhancement, since viewing state is pretty much unusable, and it’s also a regression of behaviorfrom prior dev tools version.

**Comment by robodude** [comment]
I have to agree with @jacobg 
Our only solution at the moment is to disable the time based features of our app in order to get any use out of the Vuex tab.

**Comment by Akryum** [comment]
@jacobg Git agrees with me that the inspected mutation was always reset to the last one when a mutation was received, even 2 years ago 😸️

![Screenshot from 2019-04-05 13-39-46](https://user-images.githubusercontent.com/2798204/55625240-73c62b00-57a8-11e9-86b7-393993a840ba.png)

**Comment by jacobg** [comment]
@Akryum Thanks for resolving. I thought I remember in the old version I could look at state even when new mutations come in. Perhaps the state was getting updated with new mutations. The current version changes to Loading State spinner when new mutation comes in.

**Comment by Akryum** [comment]
@jacobg I think your are talking about something different, OP was about selecting a mutation other than the last one and keeping it selected when a new mutation is received.
