### ISSUE TITLE
What did you do to the Vuex state in the new update? Where is the way to see it?

### ISSUE THREAD

**Issue by SilencerWeb** [vuejs/vue-devtools#928]
### Version
5.0.3

### Browser and OS info
Version 0.61.52 Chromium: 73.0.3683.86 / MacOS 10.14.2

### Steps to reproduce
Open Vue devtools, change tab to "Vuex" and try to see the current state

### What is expected?
There was a way to see the current Vuex state but now there is the only way to see it by mutation

### What is actually happening?
I can see the state only by mutation

**Comment by Sp1ker** [comment]
Select last mutation to see actual state. Last mutation is selected by default.

**Comment by filippolcr** [comment]
After selecting last mutation, loading state... loader indicator enter in an infinite loop.

![image](https://user-images.githubusercontent.com/13961934/55066994-31516f80-507f-11e9-955d-2f8fb012e5eb.png)

**Comment by Sp1ker** [comment]
Oh.. possible bug :)

**Comment by filippolcr** [comment]
Yeah, I'm developing with nuxt.js, I notice that without "@nuxtjs/auth": "^4.5.3" module, vue dev tools load state correctly and it's really fast.

**Comment by G-Bro** [comment]
Sounds similar to the issues I was facing in #922 I have posted some workarounds in my latest comment there

**Comment by filippolcr** [comment]
Thanks G-Bro, following #922

**Comment by jDrysdale** [comment]
Temporary workaround: did a manual install of [vue-devtools@4.1.5](https://github.com/vuejs/vue-devtools/releases/tag/v4.1.5) and I don't see this issue using that release.

I see the infinite loop loading Vuex state too. When I click the new button in the last mutation to load the Vuex state, it loads very slowly, sometimes doesn't load at all unless I reopen devtools. Eventually I see a 100% CPU process for Google Chrome Helper and have to force quit the tab. Only see this issue in version 5.x.

**Comment by denisinvader** [comment]
We have an issue with dynamic vuex modules. 

We register/unregister them in route components. 

When I click "load state" in dev tools it tries to register these  modules again (I guess) and fails with errors like `vuex.esm.js:729 [vuex] duplicate getter key:`

**Comment by GeniaT** [comment]
@filippolcr I have the same issue by using version 4.1.5, click "Load state" a few times and the state may eventually display

**Comment by Akryum** [comment]
Please open separate issues for each problem.
