### ISSUE TITLE
Wrong isLegacy checking

### ISSUE THREAD

**Issue by bajzarpa** [vuejs/vue-devtools#932]
### Version
5.0.3

### Browser and OS info
Chrome 73, macOS 10.14.3

### Steps to reproduce
Start the Vue Devtools with a 2.x version Vue and 1.x version of Vuex

### What is expected?
It can map the mutations properly

### What is actually happening?
Throws console errors 

---
It looks like when you deciding is that the current Vuex is an old version you only rely on the version of Vue. In our case where the Vue is 2.x and Vuex is 1.x, it's not the best solution because when the app tries to replay the mutations it tries to use a Vuex 1.x handler.

**Comment by zfeher** [comment]
Checked this in 5.0.3: 
```Javascript 
isLegacy = hook.Vue.version && hook.Vue.version.split('.')[0] === '1'
```

And in `initVuexBackend`:
```Javascript
if (isLegacy) {
  // Vuex 1
  mutation.handlers(store.state, mutation.payload)
} else {
  mutation.handlers(mutation.payload)
}
```

Unfortunatelly this won't work with Vue 2 + Vuex < 2.x setup which some may have.

The legacy check of Vuex may need to be separated from Vue legacy checking to make this setup work.
