### ISSUE TITLE
Vuex duplicate getter key

### ISSUE THREAD

**Issue by dantanie** [vuejs/vue-devtools#937]
### Version
5.0.3

### Browser and OS info
Firefox 68, MacOs Mojav

### Steps to reproduce
After updating to the latest vue devtools version 5.0.3 version, the Vuex store keeps report duplicate getter key.

This is how am registering store modules dynamically

const pluginAuth = {
    install(Vue, options) {
    if (!(options.store && options.store.state && options.store.state['organizations'])) {
            options.store.registerModule("organizations", StoreOrganization);
          }
}

### What is expected?
This is suppose to register the module once.

### What is actually happening?
Seems the store modules are being registered on every single component update.

---
This wasn't happening from the previous version.

**Comment by Akryum** [comment]
Should be fixed in the upcoming release.
