### ISSUE TITLE
Legacy mode setting not working properly

### ISSUE THREAD

**Issue by bajzarpa** [vuejs/vue-devtools#939]
### Version
5.0.5

### Browser and OS info
MacOs, Chrome 73

### Steps to reproduce
- Start an application with Vue 2.x and Vuex 1.x
- Start the Vue Devtools 
- Try to load mutations

### What is expected?
Map the mutations properly 

### What is actually happening?
Throws an error

---
It looks like the `backend/vuex.js` cannot read properly the `SharedData` values. 

I've checked and the `vuex1` flag is present in the storage with true value, and also looks good on the settings page, but when the `backend/vuex.js` tries to read it, it's always false. 

Screenshots:

https://ibb.co/0DmhLyg
https://ibb.co/CmGJXxv

**Comment by Akryum** [comment]
I'm sorry I can't reproduce this.

**Comment by Akryum** [comment]
@vuejs/vue-devtools Could someone try to reproduce with a Mac?

**Comment by bajzarpa** [comment]
Hi @Akryum, 

I've created a [sandbox](https://codesandbox.io/s/oj09971376) where I was able to reproduce this even on windows and mac.
