### ISSUE TITLE
Have "pinned" Vuex state property

### ISSUE THREAD

**Issue by koresar** [vuejs/vue-devtools#941]
### What problem does this feature solve?
The new DevTools is awesome and fast as hell! :) That's a relief. However, I still have to scroll through my 100 getters and 20 substores (Vuex modules) 100 times a day.

Every day I open Vue DevTools about 100 times. When I'm developing a feature I typically go to the same property (or Vuex module) again and again. This is annoying in mid size stores. And 10 times more annoying when a website (or a PWA in our case) gets big.

### What does the proposed API look like?
There is this new three-dot dropdown menu in front of each store property/getter/value. Currently it has only one menu item - `Copy Value`. I propose to add one more item there - `Auto Show` (or `Pin`, or `Auto Scroll to Here`). When clicked it should:

* Memorise (aka "pin") the property for the whole website (value should be stored in a localStorage or something), so that it works cross tabs.
* Forget the previously "pinned" property.
* When the state tree is shown for the first time the DevTools should **auto scroll to and expand that property**. (Or do nothing if property is not found.)

**Comment by jiggy1com** [comment]
Is it me or didn't the state always stay in view (Vue dev tools)? And when the state changed dev tools saw the change w/o any type of reload. 

I think I received an update, and now when the state changes it says "Recording state..." (w/o the state present), then the updated state appears, but all the nodes are collapsed. 

WTF
