### ISSUE TITLE
Handle third-party cookies being blocked

### ISSUE THREAD

**Issue by aeyachts99** [vuejs/vue-devtools#942]
### Version
5.0.6

### Browser and OS info
Chrome Version 73.0.3683.86 (Official Build) (64-bit) macOS Mojave

### Steps to reproduce
Click Settings and set Theme to Dark. Theme goes dark.
Reload page that is being inspected.
Theme reverts to light.

### What is expected?
Theme remains dark once chosen.

### What is actually happening?
Theme reverts to light.

**Comment by tm-3** [comment]
This was happening to me as well. I had third party cookies blocked and it wasn't writing settings to local storage.

https://github.com/vuejs/vue-devtools/blob/dev/src/storage.js

Enabling 3rd party cookies keeps my settings saved when I refresh now.

**Comment by Akryum** [comment]
Maybe we could try to detect when `localStorage` is blocked for the extension and display a message. Or try [chrome.store API](https://developers.chrome.com/extensions/storage).

**Comment by Akryum** [comment]
Fixed in 5.1.1
