### ISSUE TITLE
Vue-devtools breaks Vuepress's different layouts

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vue-devtools#943]
### Version
5.0.6

### Browser and OS info
Chrome 74 / Windows 10

### Steps to reproduce

https://github.com/meteorlxy/vue-devtools-breaks-vuepress

```sh
yarn
yarn dev
```

- Navigate the pages - works well

- Open vue-devtools

- Refresh the page

- Try to navigate the pages - breaks

### What is expected?
Works well

### What is actually happening?
Breaks

![image](https://user-images.githubusercontent.com/18205362/55228991-aaef8600-5256-11e9-97ab-43ba583890c2.png)

### Other info

Vuepress regesiters layout components in `beforeEnter` hook of `vue-router`, which might be related to this bug.

https://github.com/vuejs/vuepress/blob/cc193d5cc1c29a0ff802ca6bf13fdf6887047604/packages/%40vuepress/core/lib/node/internal-plugins/routes.js#L42-L49

https://github.com/vuejs/vuepress/blob/cc193d5cc1c29a0ff802ca6bf13fdf6887047604/packages/%40vuepress/core/lib/client/util.js#L84-L91

**Comment by Akryum** [comment]
Maybe related to #944

**Comment by meteorlxy** [comment]
I think's it's duplicated of #944 .

Closing this as #944 is more specific
