### ISSUE TITLE
Vuex - Object method is not visible in inspector

### ISSUE THREAD

**Issue by h07mng** [vuejs/vue-devtools#945]
### Version
5.0.6

### Browser and OS info
Chrome 73.0.3683.86 (64-bit)/ Windows 10

### Steps to reproduce
Create a Vuex state that contains an object that has a method. 
Example:

```
const state = {
   items: {
      doodle: function(){
          return true;
       } 
   }
}
```

### What is expected?
The method should be visible in the inspector when viewing the Vuex state.

### What is actually happening?
The method is not visible.

---
When I look at the props of the template receiving the state the method is visible. It is not visible in vuex state.

**Comment by tomexx** [comment]
same here

**Comment by JFGHT** [comment]
Last updates brang some new bugs regarding the reading of the state by Vuex like stated here: https://github.com/vuejs/vue-devtools/issues/935

What is surprising to me is that, this didn't have too much attention from @Akryum yet and it's something affecting in big numbers.

**Comment by Akryum** [comment]
I can't reproduce on my own, please provide a runnable minimal reproduction.

**Comment by h07mng** [comment]
Hello.

I've been away for a while. I just tried it again, now however I have v5.1.0 and in this version it's working as expected. So consider it fixed.
