### ISSUE TITLE
Vuex devtools plays mutations with nested objects wrong when loading state

### ISSUE THREAD

**Issue by sploders101** [vuejs/vue-devtools#946]
### Version
5.0.6

### Browser and OS info
Chrome 72.0.3626.119

### Steps to reproduce
Create a vue project that passes nested object structures or non-primitive data types as payloads into a mutation, and tell vue-devtools to "load state" in the vuex tab.

### What is expected?
The state is retrieved from the page and displayed in the devtools window

### What is actually happening?
vue-devtools appears to re-play all mutations, but converts any values within an object payload to primitive types, causing nested objects, Blobs, etc. to be wrongly converted to strings. Ex. "[object Blob]".

---
This did not happen before 5.0.0 (if that helps at all)

**Comment by Akryum** [comment]
Should be fixed in https://github.com/vuejs/vue-devtools/commit/6f947cbd7b81af828a5c6daeaa5f31441b83b524
