### ISSUE TITLE
Performance tab does not show any components, and no error is given

### ISSUE THREAD

**Issue by robaxelsen** [vuejs/vue-devtools#947]
### Version
5.0.6

### Browser and OS info
Chrome 73 / Ubuntu 18.04

### Steps to reproduce
Unfortunately our (company project) front-end relies on a back-end environment, so not possible to reproduce in it's entirety for external devs. Out code is open source though, and available here:
https://github.com/sipwise/ngcp-csc-ui

When I load our loading view in the browser, I can see correctly two components listed in the "Performance" tab with "Component render" selected. When I log in and the entire layout is rendered, no components are listed anymore. I get no error messages.

### What is expected?
To list the components in the "Performance" tab, or at the very least give an error message that can help me troubleshoot.

### What is actually happening?
No components listed in the "Performance" tab with "Component render" selected.

---
Have tried setting "Vue.config.performance = true", but does not help.

Components are listed successfully in the "Components" tab.

**Comment by Akryum** [comment]
I'm afraid we need a more minimal reproduction that we can actually run, otherwise it's near impossible to find the source of your problem with the provided information.

**Comment by robaxelsen** [comment]
@Akryum fully understand. Will post a new issue if I am able to reproduce on a smaller scale project. Closing this for now as I am not sure if/when I can reproduce.
