### ISSUE TITLE
Vuex Registering Nested Modules before devtools init

### ISSUE THREAD

**Issue by robertmoura** [vuejs/vue-devtools#950]
### Version
5.0.6

### Browser and OS info
Chrome 73 / Windows 10

### Steps to reproduce
Register a Vuex module with nothing but nested modules. 

### What is expected?
The nested modules are registered to state on the dev tools.

### What is actually happening?
The nested module aren't recognized by the dev tools.

---
I've created a sandbox for this issue: https://codesandbox.io/s/q8qw1vxp96

To reproduce the errors I'm encountering with this bug:
1. Go to https://q8qw1vxp96.codesandbox.io
2. Click `Load Module`
3. and open the devtools onto the Vuex tab

**Comment by martynchamberlin** [comment]
There's a whole team of us that are in the throes right now because of this issue. Having to resort to `console.log` statements to b able to see what's going on in our store. Would love to get this fixed!
