### ISSUE TITLE
Tabs visual lag error

### ISSUE THREAD

**Issue by lennoximus** [vuejs/vue-devtools#951]
### Version
5.0.6

### Browser and OS info
Chrome 73 / Windows 7 (64-bit)

### Steps to reproduce
1. Open Chrome DevTools.
2. Forward to Vue DevTools Tab.

### What is expected?
DevTools to properly display Vue DevTools tab.

### What is actually happening?
Window with Chrome DevTools is glitched out and contains a "snapshot" of previously opened tab's content and Vue tab.

---
Not sure either this is a bug related to the Vue DevTools itself or Chrome in general. Attaching a screenshot for further understanding: https://imgur.com/a/yFHR2Zx

**Comment by Akryum** [comment]
I'm not sure to understand what's going on here.
