### ISSUE TITLE
Property or method "_isBuffer" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by ProBun** [vuejs/vue-devtools#955]
### Version
5.0.7

### Browser and OS info
Chrome 73.0.3683.86

### Steps to reproduce
Open vue-devtools on vue app and switch route

### What is expected?
No errors in console

### What is actually happening?
Throwing error  Property or method "_isBuffer" is not defined on the instance but referenced during render.

**Comment by ashishov** [comment]
I have the same issue, but not on all vuejs projects.

**Comment by Landen13** [comment]
Same issue

**Comment by Akryum** [comment]
Please provide a runnable minimal reproduction.

**Comment by ProBun** [comment]
https://github.com/ProBun/vuedevtools-issue

**Comment by Akryum** [comment]
@ProBun The repository only contains hello world components.

**Comment by ProBun** [comment]
Sorry forgot to add them to git repo

**Comment by YESENE** [comment]
Some handy guides and reference ,,When you...?

**Comment by ProBun** [comment]
@YESENE Just switch route using one of the links on homepage

**Comment by YESENE** [comment]
Of these API endpoints based on developer feedback. If we do, we will announce the changes here on the developer...!!

**Comment by YESENE** [comment]
application/vnd.github.switcheroo-preview+json
&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;During the preview period, we may change aspects of these APIs based on developer feedback.
If we do, we will announce the changes here on the developer blog, but we will not provide any advance notice.&lt;/p&gt;

&lt;p&gt;If you have any questions or feedback, please &lt;a href="https://github.com/contact?form%5Bsubject%5D=Pages+toggle+API"&gt;let us know&lt;/a&gt;!&lt;/p&gt;</content>
  </entry>
  <entry>
    <id>tag:developer.github.com,2019-02-14:/changes/2019-02-14-draft-pull-requests/</id>
    <title type="html">Preview the new Draft Pull Requests API</title>

**Comment by YESENE** [comment]
$ ssh-keygen -p
# Start the SSH key creation process
> Enter file in which the key is (/Users/you/.ssh/id_rsa): [Hit enter]
> Key has comment '/Users/you/.ssh/id_rsa'
> Enter new passphrase (empty for no passphrase): [Type new passphrase]
> Enter same passphrase again: [One more time for luck]
> Your identification has been saved with the new passphrase.?

**Comment by YESENE** [comment]
With GitHub Team, organizations include:

Unlimited public and private repositories
Unlimited collaborators
Two-factor authentication enforcement
Team discussions
Team access controls for managing groups
Advanced tools and insights:

GitHub Pages
Wikis
Protected branches
Code owners
Repository insights graphs: Pulse, contributors, traffic, commits, code frequency, network, and forks
Draft pull requests??

**Comment by YESENE** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item,,

**Comment by YESENE** [comment]
The point of reference-style links is not that they’re easier to write. The point is that with reference-style links, your document source is vastly more readable. Compare the above examples: using reference-style links, the paragraph itself is only 81 characters long; with inline-style links, it’s 176 characters; and as raw HTML, it’s 234 characters. In the raw HTML, there’s more markup than there is text.?

**Comment by wizbit** [comment]
I've had this, but only when 'vuex-router-sync' is setup and changing routes.

**Comment by jgmcelwain** [comment]
For what it's worth, I do _not_ have `vuex-router-sync` in my project but am experiencing the same bug.

**Comment by YESENE** [comment]
A code block continues until it reaches a line that is not indented (or the end of the article).

Within a code block, ampersands (&) and angle brackets (< and >) are automatically converted into HTML entities. This makes it very easy to include example HTML source code using Markdown — just paste it and indent it, and Markdown will handle the hassle of encoding the ampersands and angle brackets. For example, this     ? ,,

**Comment by mbranicky** [comment]
The same problem here, when changing route, on almost all components. Not using `vuex-router-sync`

**Comment by JFonsecaSpot** [comment]
@jgmcelwain and @mbranicky can you tell if you have arrays stored on vuex and if those route changes render components using those arrays? My issue seams to be triggered when using array functions (forEach, filter, sort... etc) on computed values.

**Comment by jgmcelwain** [comment]
@JFonsecaSpot Yes, I have store arrays and have computed props based on those stored arrays that use those Array methods.

**Comment by mbranicky** [comment]
@JFonsecaSpot  Yes I do. Arrays in VUEX and components rendered based on these arrays.

**Comment by vchapple17** [comment]
I also have this issue. I reverted to 5.0.0 in Chrome Extensions. 

https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg.

I look forward to a fix, or someone explaining what else I can try if its not an issue with vue devtools.

**Comment by jgmcelwain** [comment]
> I look forward to a fix, or someone explaining what else I can try if its not an issue with vue devtools.

@vchapple17 the issue is labelled as fixed in 2ff9785 and should be working when a new release is pushed.

**Comment by gapnav** [comment]
> I also have this issue. I reverted to 5.0.0 in Chrome Extensions.
> 
> https://chrome.google.com/webstore/detail/vuejs-devtools/ljjemllljcmogpfapbkkighbhhppjdbg.
> 
> I look forward to a fix, or someone explaining what else I can try if its not an issue with vue devtools.

How did you get this link? I see that this link is to chrome webstore (not third-party service), but I can't find way to see old versions.

**Comment by vchapple17** [comment]
> How did you get this link? I see that this link is to chrome webstore (not third-party service), but I can't find way to see old versions.

This particular link is to the beta channel with is for 5.0.0, which for me was far enough back to help with the issue.

There are currently two vuejs-devtools extensions, one for the 5.0.0 and one for the current release 5.0.7 (https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)

**Comment by carlosgbp00027** [comment]
The solution is uninstall and install extension chrome of Vue

**Comment by DespertaWeb** [comment]
@carlosgbp00027 is right. There's already an update:
### **uninstall and reinstall**
https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd/related
