### ISSUE TITLE
VueJs tab in devtools doesn't working

### ISSUE THREAD

**Issue by ahmedash95** [vuejs/vue-devtools#96]
i don't know what's the problem .. but vuejs doesn't display in tabs and i'm sure the vue.js works fine in my website . sometimes it working and sometimes not .. any explanation about that ?

**Comment by probil** [comment]
https://github.com/vuejs/vue-devtools/issues/100
The same issue

**Comment by probil** [comment]
1) Try to re-open chrome dev tools. 
2) Check you are using vue.js and not vue.min.js
3) Check is page with vue not inside `iframe`

Also, check this comment
https://github.com/vuejs/vue-devtools/issues/100#issuecomment-218264327

**Comment by ahmedash95** [comment]
@probil thanks for your reply , actually i was using vue.min.js instead of uncompressed file
