### ISSUE TITLE
"Send to console" Shortcut

### ISSUE THREAD

**Issue by kfriend** [vuejs/vue-devtools#97]
It would be handy to have a shortcut for sending an instance to the console. Possibly super + clicking the tree item?

Another thought would be a checkbox that you can click, which would send any selected tree item to the console, e.g. "Automatically send selected tree item to console"

**Comment by blake-newman** [comment]
This is currently available #106 is an enhancement. Thus closing this ticket, please refer to #106 for further improvements on this feature.

**Comment by kfriend** [comment]
thanks for the update @blake-newman 👍
