### ISSUE TITLE
Crash if third party cookies are blocked

### ISSUE THREAD

**Issue by GarrettGeorge** [vuejs/vue-devtools#979]
### Version
5.1.0

### Browser and OS info
Chrome  73.0.3683.103 / Windows 10

### Steps to reproduce
1. Open Chrome Dev Tools
2. Click on `Vue` tab
3. Click on settings, `vuex` state, or other tabs

### What is expected?
Anything to happen.

### What is actually happening?
Nothing happens.

**Comment by GarrettGeorge** [comment]
Would like an update on this, `vue-dev-tools` is completely broken and unusable for me.

**Comment by GarrettGeorge** [comment]
After trying again, it works _**initially**_ but breaks the moment I click on the settings button.

**Comment by index23** [comment]
I have similar situation.

**Extension version**: 5.1.0
**Browser**: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
**OS**: macOS Mojave Version 10.14.3

**Steps to reproduce**
1. Open Chrome Dev Tools
2. Click on Vue tab

**What is expected?**
Everything to work fine and fluently.

**What is actually happening?**
Entire browser tab and devtool is frozen and broken.

My solution is to install previous version ( 5.0.0) where almost everything works as expected.

**Comment by DespertaWeb** [comment]
where can I get the 5.0.0 v ? @index23

**Comment by nickdex** [comment]
Can confirm happens with Vivaldi (Chromium 73.0.3683.105) on Linux and MacOS Mojave. Everything works fine until settings icon is clicked.
@DespertaWeb You can get releases from [releases tab](https://github.com/vuejs/vue-devtools/releases) and follow steps for [manual installation](https://github.com/vuejs/vue-devtools#manual-installation)

**Comment by Akryum** [comment]
I can't reproduce on Chrome 73.0.3683.103 / Win 10.

**Comment by benediktvolke** [comment]
Same problem here:

**Extension version:** 5.1.0
**Browser:** Chrome 74.0.3729.108
**OS:** Windows 10 Pro (1809)

### Steps to reproduce

1. Open Chrome Dev Tools
2. Click on Vue Tab
3. Click on Settings inside Vue Tab

### What is expected?
Settings tab opens

### What is actually happening?
Browser Tab and Chrome Dev Tools freeze.

Version 5.0.5 is working just fine.

**Comment by Akryum** [comment]
Could you right-click on the devtools, select Inspect (or similar) and share the content of the console in the opened chrome devtools window?

**Comment by benediktvolke** [comment]
```
shell.js:7997 Main._createAppUI: 76.946044921875ms
shell.js:7997 Main._showAppUI: 84.51611328125ms
shell.js:7997 Main._initializeTarget: 26.43798828125ms
shell.js:7997 Main._lateInitialization: 11.224853515625ms
devtools.js:7 TypeError: Cannot read property '$options' of undefined
    at ow.c.r.a.config.errorHandler (devtools.js:51)
    at ie (devtools.js:7)
    at ne (devtools.js:7)
    at Array.<anonymous> (devtools.js:7)
    at le (devtools.js:7)
devtools.js:7 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at a.provide (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:51:13275)
    at Le (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:15082)
    at a.t._init (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:34428)
    at new a (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:35694)
    at an (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:21615)
    at init (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:20481)
    at p (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:44114)
    at h (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:43743)
    at H (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:46346)
    at L (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/devtools.js:7:47135)
```

**Comment by Akryum** [comment]
Are you blocking third-party cookies?

**Comment by DKhalil** [comment]
Same issue here, and yes I'm blocking third-party cookies

**Comment by Akryum** [comment]
That's the reason then. We may need to refactor the extension to use `chrome.storage` instead of `localStorage`.

**Comment by nickdex** [comment]
@Akryum I unchecked "Block 3rd Party" Cookies and now its working.
It was on by default, and I imagine it would be same for more browsers in future.

**Comment by DespertaWeb** [comment]
Back to v5 and up & running! 
great! thanx @nickdex

**Comment by hailwood** [comment]
@Akryum Appreciate you putting in the work to fix this.

When do you think this might be released (week, month, 3 month?)? 
I'd really like to turn third party cookies back off!

**Comment by hay** [comment]
What worked for me is to add an exception for the Extension URL.

Go to Settings --> Advanced --> Site settings --> Cookies.
With 'Block third-party cookies' enabled press the 'Add' button next to allow and enter `chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/`. Click add. 

You should now see a 'Vue devtools' icon in the list of allowed cookies. Reload Devtools and you should be able to go to the settings tab.
