### ISSUE TITLE
Multiple roots

### ISSUE THREAD

**Issue by aemadrid** [vuejs/vue-devtools#98]
It stops working when I have two roots (two separate apps) running on the same page. The left sidebar might show the right information (multiple roots) but clicking on any of the roots or its children (if shown) will not update the data on the right sidebar.

**Comment by afkatja** [comment]
We seem to have this issue, too.

**Comment by guidobouman** [comment]
@yyx990803 Any news on this? Can we support this, or is it just not an option in the current devtools setup?

**Comment by guidobouman** [comment]
Ping @simplesmiler ?

**Comment by spaceemotion** [comment]
Not sure if this is the right issue for this, but I got a minor issue with multiple vue roots on my page.

I built a small modal system that attaches itself as a new vue instance at the end of the body. The devtools only seem to pick it up once I hit its "Refresh" button.

Just something minor, but would be great if there's a way to pick this up automagically.

**Comment by michalsnik** [comment]
I think we can close this issue now @posva 

And if you still experience following problem @spaceemotion it would be great if you create separate issue with an example codebase to reproduce the problem :)
