### ISSUE TITLE
Failure to pass validation applicable to firefox ^66.03

### ISSUE THREAD

**Issue by SilverLeaves** [vuejs/vue-devtools#989]
### Version
5.1.0

### Browser and OS info
 firefox 66.03

### Steps to reproduce
update firefox to ^66.03

### What is expected?
normal use

### What is actually happening?
Failure to pass validation applicable to firefox
![图片](https://user-images.githubusercontent.com/31165554/57173510-8db86380-6e63-11e9-98d7-99c6ddb03eb7.png)

**Comment by hekmatinasser** [comment]
I have this problem

**Comment by nika-d** [comment]
me too :( and also, i cannot download vuejs webtools from mozillas addons, see [screenshot](
https://user-images.githubusercontent.com/46905562/57176972-4e881380-6e5f-11e9-8b7f-701e77d6e08a.png
).
same firefox version (on macOS Mojave 10.14.4).

**Comment by gassius** [comment]
As now, signing add-ons is required as per
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-can-i-do-if-firefox-disables-an-installed-add-on

Workaround in the meantime. Use Firefox Developer Edition and set 
`extensions.langpacks.signatures.required` to false

**Comment by fnicastri** [comment]
Same problem, workaround didn't works for me.
![image](https://user-images.githubusercontent.com/5978520/57178495-26a1ab80-6e71-11e9-88c2-6eba1d5c726c.png)
![image](https://user-images.githubusercontent.com/5978520/57178496-29040580-6e71-11e9-96a5-276e85b3c374.png)

**Comment by Akryum** [comment]
It's an upstream issue in Firefox itself:
https://twitter.com/mozamo/status/1124484255159971840

A hotfix should be available to you soon:
https://twitter.com/mozamo/status/1124627930301255680

**Comment by SilverLeaves** [comment]
thanks very much, now it works, I will close this issue.
