### ISSUE TITLE
Too big information bars

### ISSUE THREAD

**Issue by vedmant** [vuejs/vue-devtools#99]
Hi, if it's possible I'd like to ask to make information bars http://screencast.com/t/EHWxEsjQo46L little smaller, they take too much space and to see actual frames with data I need to resize dev tools window to make it bigger, but then it takes too much main window space. Just something that bothers me each time I use vue dev tools.

Thanks! Sorry if it's not relevant.

**Comment by yyx990803** [comment]
Reducing a few pixels won't make it fundamentally better - you can dock the devtools to the side instead, or even have it in a separate window.

**Comment by vedmant** [comment]
It's not a few pixels it's more than twice bigger than other bars in chrome devs tools. It would be better to make it match other dev tools elements sizes and styles. Also filter bar takes whole line. This might look good when you have big screen, but for MacBooks it's really not convenient to use. Having it in sidebar is not an option, it will reduce window width so site responsive queries will change design to mobile, having it on side is only good when working with mobile version.
