### ISSUE TITLE
Debug tools doesn't show the components in both Chrome and FireFox

### ISSUE THREAD

**Issue by jakelumetta** [vuejs/vue-devtools#998]
### Version
5.1.0

### Browser and OS info
Mac OS 10.10.5 / Chrome Version 74.0.3729.131 / Firefox 66.0.5

### Steps to reproduce
Full details here: https://cl.ly/667b6b7e3295

### What is expected?
Vue debug toolbar loads and shows the components on the Page.

### What is actually happening?
Components on the Page do not show up in the toolbar. They are selectable when I hover over them but clicking on a component still does not load it.

---
Full details here: https://cl.ly/667b6b7e3295

**Comment by jonathantizard** [comment]
I can confirm I have had the same issue for the last week - I was using it in electron though, full issue here

https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/268#issue-441661896

**Comment by jakelumetta** [comment]
Looks like I have multiple versions of Vue running so that could be the issue. Going to debug some more locally and close this issue.
